Repository vmware-tanzu/tanzu-framework, pull requests merged in 2021-10, with the labels that each got.

#324 Instruction on clarifying where to find built cli binaries
  docs/cli/getting-started.md
Labels: kind/documentation, ok-to-merge

#755 Remove "latest" from GCP reference and update installation instructions
  docs/cli/getting-started.md
Labels: kind/documentation, ok-to-merge, cla-not-required

#757 Add pkg.go.dev badge to README
  README.md
Labels: area/repo maintenance, kind/documentation, ok-to-merge, cla-not-required

#635 Refactor CRD wait for addons controller to its own package
  addons/controllers/addon_controller.go
  addons/controllers/suite_test.go
  addons/go.mod
  addons/go.sum
  addons/main.go
  addons/pkg/crdwait/crd_wait.go
  addons/pkg/crdwait/crd_wait_test.go
  addons/pkg/crdwait/suite_test.go
  go.mod
  go.sum
Labels: kind/refactor, area/addons, kind/bug, ok-to-merge

#763 Remove GOPRIVATE references
  Makefile
  addons/Dockerfile
  addons/Makefile
  common.mk
  pkg/v1/builder/template/plugintemplates/Makefile.tmpl
  pkg/v1/builder/template/plugintemplates/plugin_readme.md.tmpl
  pkg/v1/sdk/capabilities/Dockerfile
  pkg/v1/sdk/capabilities/Makefile
  pkg/v1/sdk/features/Dockerfile
  pkg/v1/sdk/features/Makefile
  pkg/v1/tkr/Dockerfile
  pkg/v1/tkr/Makefile
Labels: area/repo maintenance, kind/other, ok-to-merge, cla-not-required

#765 Fix docker build in capabilities and features packages
  pkg/v1/sdk/capabilities/Dockerfile
  pkg/v1/sdk/features/Dockerfile
Labels: area/repo maintenance, kind/bug, ok-to-merge, cla-not-required

#778 Fixing windows node overlay template apply
  pkg/v1/providers/infrastructure-vsphere/v0.7.10/ytt/overlay-windows.yaml
Labels: kind/bug, ok-to-merge, cla-not-required

#779 Fix package install typo
  cmd/cli/plugin/package/package_install.go
  docs/cli/commands/tanzu_package_install.md
Labels: area/plugin, area/addons, ok-to-merge, cla-not-required

#787 IAM CODEOWNERS should be able to review their own code
  CODEOWNERS
Labels: area/repo maintenance, ok-to-merge, cla-not-required

#782 Update version for BOM retrieval to v0.6.0
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#783 Update version for BOM retrieval to v0.7.0-dev
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge

#799 Update CODEOWNERS with new teams
  CODEOWNERS
Labels: area/repo maintenance, area/release, ok-to-merge, cla-not-required

#805 remove triage/accepted from support process flow
  docs/community/support-process.md
Labels: area/repo maintenance, ok-to-merge, cla-not-required

#830 Package repository URL should be able to use sha256 digest
  pkg/v1/tkg/tkgpackageclient/image_utils.go
  pkg/v1/tkg/tkgpackageclient/image_utils_test.go
Labels: bug, priority/important-soon, area/plugin, ok-to-merge, cla-not-required

#708 Enable kapp-controller port in workload cluster for calico cni
  pkg/v1/providers/ytt/02_addons/cni/add_cni.yaml
Labels: ok-to-merge, cla-not-required, area/networking

#818 addons/pinniped/post-deploy: trigger test with addons
  addons/Makefile
  addons/pinniped/post-deploy/Makefile
Labels: ok-to-merge, cla-not-required

#875 Updating version used for BOM retrieval to v0.8.0-dev
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#870 Codeowners update: Use github group @vmware-tanzu/tkg-addons-owners for addons code owners
  CODEOWNERS
Labels: area/repo maintenance, ok-to-merge, cla-not-required

#881 addons/pinniped/post-deploy: publish pinniped API info (to be discovered by the CLI)
  addons/pinniped/post-deploy/pkg/configure/configure.go
  addons/pinniped/post-deploy/pkg/configure/configure_test.go
  addons/pinniped/post-deploy/pkg/configure/supervisor/supervisor.go
  addons/pinniped/post-deploy/pkg/configure/supervisor/supervisor_test.go
Labels: ok-to-merge, cla-not-required

#897 Fix path to "Contribution Ladder" in contribution docs
  CONTRIBUTING.md
Labels: ok-to-merge, cla-not-required

#759 Support cluster lifecycle operations on v1alpha2 based TKGS clusters
  apis/run/v1alpha1/tanzukubernetescluster_types.go
  apis/run/v1alpha1/zz_generated.deepcopy.go
  apis/run/v1alpha2/groupversion_info.go
  apis/run/v1alpha2/tanzukubernetescluster_types.go
  apis/run/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/run.tanzu.vmware.com_tanzukubernetesclusters.yaml
  pkg/v1/providers/config.yaml
  pkg/v1/providers/config_default.yaml
  pkg/v1/providers/infrastructure-tkg-service-vsphere/v1.0.0/ytt/overlay.yaml
  pkg/v1/providers/infrastructure-tkg-service-vsphere/v1.1.0/cluster-template-definition-dev.yaml
  pkg/v1/providers/infrastructure-tkg-service-vsphere/v1.1.0/cluster-template-definition-prod.yaml
  pkg/v1/providers/infrastructure-tkg-service-vsphere/v1.1.0/ytt/base-template.yaml
  pkg/v1/providers/infrastructure-tkg-service-vsphere/v1.1.0/ytt/overlay.yaml
  pkg/v1/providers/tests/clustergen/param_models/cluster_tkgs.model
  pkg/v1/providers/ytt/01_plans/dev.yaml
  pkg/v1/providers/ytt/01_plans/prod.yaml
  pkg/v1/providers/ytt/lib/config_variable_association.star
  pkg/v1/providers/ytt/lib/helpers.star
  pkg/v1/providers/ytt/lib/validate.star
  pkg/v1/tkg/client/client_suite_test.go
  pkg/v1/tkg/client/cluster.go
  pkg/v1/tkg/client/get_cluster.go
  pkg/v1/tkg/client/get_cluster_helper.go
  pkg/v1/tkg/client/get_kubernetes_versions.go
  pkg/v1/tkg/client/get_kubernetes_versions_test.go
  pkg/v1/tkg/client/scale.go
  pkg/v1/tkg/client/upgrade_cluster.go
  pkg/v1/tkg/client/validate.go
  pkg/v1/tkg/client/workload_cluster.go
  pkg/v1/tkg/clusterclient/clusterclient.go
  pkg/v1/tkg/clusterclient/clusterclient_test.go
  pkg/v1/tkg/clusterclient/resource.go
  pkg/v1/tkg/constants/cluster_internal.go
  pkg/v1/tkg/fakes/clusterclient.go
  pkg/v1/tkg/fakes/clusterclientfactory.go
  pkg/v1/tkg/fakes/crtclientfactory.go
  pkg/v1/tkg/fakes/crtclusterclient.go
  pkg/v1/tkg/fakes/discoveryclientfactory.go
  pkg/v1/tkg/fakes/discoveryclusterclient.go
  pkg/v1/tkg/fakes/helper/fakeobjectcreater.go
  pkg/v1/tkg/fakes/poller.go
Labels: area/cli, kind/enhancement, ok-to-merge, cla-not-required

#832 Add changes for adding secret for secretgen controller to be deployed by addons manager
  pkg/v1/providers/config_default.yaml
  pkg/v1/providers/ytt/02_addons/secretgen-controller/add_secretgen-controller.yaml
  pkg/v1/providers/ytt/02_addons/secretgen-controller/secretgen-controller_addon_data.lib.yaml
Labels: area/addons, ok-to-merge, cla-not-required

#914 Update CLI docs for imagepullsecret deprecation
  docs/cli/getting-started.md
Labels: area/release, area/docs, ok-to-merge, cla-not-required

#922 Update install docs for new artifacts packaging format
  docs/cli/getting-started.md
Labels: area/release, area/docs, ok-to-merge

#918 Allow adding custom root CA certificate for Proxy
  pkg/v1/providers/config_default.yaml
  pkg/v1/providers/tests/clustergen/param_models/cluster_optional.model
  pkg/v1/providers/tests/clustergen/param_models/cluster_vsphere.model
  pkg/v1/providers/ytt/lib/config_variable_association.star
  pkg/v1/providers/ytt/lib/helpers.star
  pkg/v1/tkg/constants/config_variables.go
  pkg/v1/tkg/constants/env_variables.go
  pkg/v1/tkg/fakes/awsclient.go
  pkg/v1/tkg/fakes/clusterclient.go
  pkg/v1/tkg/fakes/clusterclientfactory.go
  pkg/v1/tkg/fakes/crtclientfactory.go
  pkg/v1/tkg/fakes/crtclusterclient.go
  pkg/v1/tkg/fakes/discoveryclientfactory.go
  pkg/v1/tkg/fakes/discoveryclusterclient.go
  pkg/v1/tkg/fakes/poller.go
  pkg/v1/tkg/fakes/tkgconfigbomclient.go
  pkg/v1/tkg/kind/client.go
  pkg/v1/tkg/tkgconfigbom/bom.go
  pkg/v1/tkg/tkgconfigbom/bom_test.go
  pkg/v1/tkg/tkgconfigbom/client.go
  pkg/v1/tkg/tkgconfigupdater/provider.go
Labels: area/plugin, kind/bug, ok-to-merge, cla-not-required

#944 addons/pinniped/post-deploy: use stable cert-manager v1 APIs
  addons/pinniped/post-deploy/pkg/configure/configure.go
  addons/pinniped/post-deploy/pkg/configure/configure_test.go
  addons/pinniped/post-deploy/pkg/utils/utils.go
Labels: ok-to-merge, cla-not-required

#905 Add nodepool operations for TKGS providers
  cmd/cli/plugin/cluster/get_node_pools.go
  pkg/v1/tkg/client/client.go
  pkg/v1/tkg/client/machine_deployment.go
  pkg/v1/tkg/client/machine_deployment_test.go
  pkg/v1/tkg/client/pacific_cluster.go
  pkg/v1/tkg/clusterclient/clusterclient.go
  pkg/v1/tkg/fakes/client.go
  pkg/v1/tkg/fakes/clusterclient.go
  pkg/v1/tkg/tkgctl/interface.go
  pkg/v1/tkg/tkgctl/machine_deployment.go
  pkg/v1/tkg/tkgctl/pacific_cluster.go
Labels: area/cli, kind/enhancement, ok-to-merge, cla-not-required

#934 addons/pinniped/post-deploy: Publish Pinniped API info in workload cluster
  addons/pinniped/post-deploy/pkg/configure/configure.go
  addons/pinniped/post-deploy/pkg/configure/configure_test.go
  addons/pinniped/post-deploy/pkg/configure/helper.go
  addons/pinniped/post-deploy/pkg/configure/helper_test.go
  addons/pinniped/post-deploy/pkg/configure/supervisor/supervisor.go
  addons/pinniped/post-deploy/pkg/configure/supervisor/supervisor_test.go
Labels: ok-to-merge, cla-not-required

#935 Adds default feature flags (when missing) to config file
  config/crd/bases/config.tanzu.vmware.com_clientconfigs.yaml
  pkg/v1/config/clientconfig.go
  pkg/v1/config/clientconfig_test.go
Labels: kind/feature, ok-to-merge, area/ux, area/ui, cla-not-required

#821 Deploy ako in bootstrap cluster with tanzu-framework
  pkg/v1/providers/ytt/03_customizations/02_avi/add-ako.yaml
  pkg/v1/providers/ytt/03_customizations/02_avi/add_akoo.yaml
  pkg/v1/providers/ytt/03_customizations/02_avi/ako-deployment.lib.yaml
  pkg/v1/providers/ytt/03_customizations/02_avi/ako-operator-deployment.lib.yaml
  pkg/v1/providers/ytt/03_customizations/02_avi/static.lib.yaml
Labels: ok-to-merge, cla-not-required

#951 Tweaks ContextAwareDiscovery to allow more generic feature flags to u…
  pkg/v1/cli/catalog/catalog_test.go
  pkg/v1/cli/command/core/plugin_manager.go
  pkg/v1/config/clientconfig.go
Labels: kind/cleanup, ok-to-merge, area/ux, cla-not-required

#986 Service cidr size validation
  pkg/v1/tkg/client/validate.go
  pkg/v1/tkg/client/validate_test.go
Labels: kind/enhancement, ok-to-merge, cla-not-required, area/networking

#1019 Fix validate_test.go unit test
  pkg/v1/tkg/client/validate_test.go
Labels: ok-to-merge, cla-not-required
