Repository vmware-tanzu/tanzu-framework, pull requests merged in 2021-11, with the labels that each got.

#1011 Implement `tanzu plugin sync` command for auto download plugins
  cmd/cli/plugin/login/main.go
  pkg/v1/cli/command/core/plugin_manager.go
  pkg/v1/cli/pluginmanager/manager.go
  pkg/v1/cli/pluginmanager/manager_test.go
Labels: area/cli, area/plugin, kind/feature, ok-to-merge, cla-not-required

#1020 increase default poll timeout value
  pkg/v1/tkg/tkgpackagedatamodel/constants.go
Labels: ok-to-merge, cla-not-required

#819 Provision dual-stack bootstrap cluster when TKG_IP_FAMILY is `ipv4,ipv6`
  pkg/v1/providers/infrastructure-vsphere/v0.7.10/ytt/overlay.yaml
  pkg/v1/providers/tests/unit/ip_family_test.go
  pkg/v1/tkg/client/upgrade_addon.go
  pkg/v1/tkg/client/upgrade_addon_test.go
  pkg/v1/tkg/fakes/config/config_ipv4_ipv6.yaml
  pkg/v1/tkg/kind/client.go
  pkg/v1/tkg/kind/client_test.go
Labels: area/cli, kind/enhancement, ok-to-merge, cla-not-required

#948 Display the latest package version as part of "tanzu package available list" command
  cmd/cli/plugin/package/package_available_list.go
  go.mod
  go.sum
Labels: ok-to-merge, cla-not-required

#1033 Update nameserver test for ytt error
  pkg/v1/providers/tests/unit/custom_nameservers_test.go
Labels: kind/failing-test, ok-to-merge, cla-not-required

#915 check values file exist before package install & update
  pkg/v1/tkg/tkgpackageclient/package_install.go
  pkg/v1/tkg/tkgpackageclient/package_update.go
  pkg/v1/tkg/tkgpackageclient/package_update_test.go
Labels: ok-to-merge, cla-not-required

#1030 Fixes feature flag typo (export from confirm)
  pkg/v1/config/clientconfig.go
  pkg/v1/tkg/fakes/client.go
Labels: ok-to-merge, area/ui

#1040 Updating version tag used for BOM retrieval to v0.10.0
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#1038 Node pool redux
  pkg/v1/tkg/client/machine_deployment.go
  pkg/v1/tkg/client/machine_deployment_test.go
  pkg/v1/tkg/client/scale.go
  pkg/v1/tkg/client/scale_test.go
Labels: ok-to-merge, cla-not-required

#1022 Removed command to register and deregister the management cluster from TMC
  cmd/cli/plugin/managementcluster/README.md
  cmd/cli/plugin/managementcluster/create.go
  cmd/cli/plugin/managementcluster/doc.go
  cmd/cli/plugin/managementcluster/main.go
  cmd/cli/plugin/managementcluster/register.go
  config/crd/bases/run.tanzu.vmware.com_tanzukubernetesclusters.yaml
  docs/cli/commands/tanzu_management-cluster.md
  docs/cli/commands/tanzu_management-cluster_register.md
  go.mod
  go.sum
  pkg/v1/cli/command/plugin/lint/cli-wordlist.yml
  pkg/v1/providers/config_default.yaml
  pkg/v1/providers/ytt/lib/config_variable_association.star
  pkg/v1/tkg/client/client.go
  pkg/v1/tkg/client/deregister.go
  pkg/v1/tkg/client/init.go
  pkg/v1/tkg/client/register.go
  pkg/v1/tkg/client/register_test.go
  pkg/v1/tkg/cmd/deregister.go
  pkg/v1/tkg/cmd/deregister_region.go
  pkg/v1/tkg/cmd/init.go
  pkg/v1/tkg/cmd/register.go
  pkg/v1/tkg/cmd/register_region.go
  pkg/v1/tkg/constants/config_variables.go
  pkg/v1/tkg/fakes/client.go
  pkg/v1/tkg/tkgctl/api_sig_enforce_test.go
  pkg/v1/tkg/tkgctl/deregister_region.go
  pkg/v1/tkg/tkgctl/init.go
  pkg/v1/tkg/tkgctl/interface.go
  pkg/v1/tkg/tkgctl/region_test.go
  pkg/v1/tkg/tkgctl/register_region.go
Labels: area/cli, ok-to-merge, area/ux

#1044 Fix incorrect import in add_akoo.yaml.
  pkg/v1/providers/ytt/03_customizations/02_avi/add_akoo.yaml
Labels: kind/bug, ok-to-merge, cla-not-required

#1041 update the BOM retrieval version to v0.11.0-dev
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#1025 Enable accelerated networking on Azure VMs by default where available
  pkg/v1/providers/config_default.yaml
Labels: area/plugin, ok-to-merge, cla-not-required

#1018 Update pinniped-auth login command to adjust concierge credentials cache path
  cmd/cli/plugin/pinniped-auth/login.go
  cmd/cli/plugin/pinniped-auth/login_test.go
  docs/cli/commands/tanzu_pinniped-auth_login.md
Labels: area/auth, kind/cleanup, ok-to-merge, cla-not-required

#1053 add a way to create a single management package bundle
  Makefile
  hack/packages/scripts/package-utils.sh
Labels: kind/feature, ok-to-merge, cla-not-required, area/lcm

#1012 Bump kapp controller to version 0.28.0
  pkg/v1/providers/vendir.lock.yml
  pkg/v1/providers/vendir.yml
  pkg/v1/providers/ytt/02_addons/kapp-controller/kapp-controller_addon_data.lib.yaml
  pkg/v1/providers/ytt/vendir/cni/_ytt_lib/LICENSE
  pkg/v1/providers/ytt/vendir/cni/_ytt_lib/NOTICE
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/LICENSE
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/LICENSE.md
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.28.0/bundle/config/overlays/change-namespace.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.28.0/bundle/config/overlays/update-configmap.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.28.0/bundle/config/overlays/update-crds.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.28.0/bundle/config/overlays/update-deployment.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.28.0/bundle/config/upstream/kapp-controller.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.28.0/bundle/config/values.star
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.28.0/bundle/config/values.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/kapp-controller.lib.yaml
Labels: area/addons, ok-to-merge, cla-not-required

#1023 Add support to configure cluster API server port
  pkg/v1/providers/config_default.yaml
  pkg/v1/providers/infrastructure-aws/v0.6.6/ytt/overlay.yaml
  pkg/v1/providers/infrastructure-azure/v0.4.15/ytt/overlay.yaml
  pkg/v1/providers/infrastructure-vsphere/v0.7.10/ytt/overlay-windows.yaml
  pkg/v1/providers/infrastructure-vsphere/v0.7.10/ytt/overlay.yaml
  pkg/v1/providers/tests/clustergen/param_models/cluster_aws.model
  pkg/v1/providers/tests/clustergen/param_models/cluster_azure.model
  pkg/v1/providers/tests/clustergen/param_models/cluster_vsphere.model
  pkg/v1/providers/tests/unit/windows_test.go
Labels: area/cli, kind/enhancement, ok-to-merge, cla-not-required

#1055 Make provider unit tests pass linter checks
  .github/workflows/main.yaml
  pkg/v1/providers/tests/go.mod
  pkg/v1/providers/tests/go.sum
  pkg/v1/providers/tests/unit/ip_family_test.go
  pkg/v1/providers/tests/unit/windows_test.go
Labels: ok-to-merge, cla-not-required

#1034 update secret registry readme
  cmd/cli/plugin/secret/README.md
Labels: ok-to-merge, cla-not-required

#1060 Fixes error in custom resource group usecase
  pkg/v1/tkg/web/src/app/views/landing/azure-wizard/provider-step/azure-provider-step.component.ts
Labels: kind/bug, ok-to-merge, area/ux, area/ui

#901 Design doc for bring-your-own-host
  docs/design/bringyourownhost-design.md
Labels: kind/design, area/docs, ok-to-merge

#1065 Don't override image version during docker builds
  Makefile
Labels: area/repo maintenance, area/release, kind/other, ok-to-merge, cla-not-required

#1043 Add support for OCI based plugin discovery and distribution
  Makefile
  addons/go.mod
  addons/go.sum
  go.mod
  go.sum
  pkg/v1/builder/command/publish.go
  pkg/v1/builder/command/publish/local.go
  pkg/v1/builder/command/publish/oci.go
  pkg/v1/builder/command/publish/publisher.go
  pkg/v1/cli/artifact/oci.go
  pkg/v1/cli/carvelhelpers/kbld.go
  pkg/v1/cli/carvelhelpers/kbld_test.go
  pkg/v1/cli/carvelhelpers/package.go
  pkg/v1/cli/carvelhelpers/registry.go
  pkg/v1/cli/carvelhelpers/ytt.go
  pkg/v1/cli/carvelhelpers/ytt_test.go
  pkg/v1/cli/clientconfighelpers/helpers.go
  pkg/v1/cli/clientconfighelpers/windows_trusted_ca.go
  pkg/v1/cli/discovery/local.go
  pkg/v1/cli/discovery/oci.go
  pkg/v1/cli/discovery/oci_test.go
  pkg/v1/tkg/client/client_suite_test.go
  pkg/v1/tkg/fakes/client.go
  pkg/v1/tkg/fakes/clusterclient.go
  pkg/v1/tkg/fakes/kappclient.go
  pkg/v1/tkg/fakes/kindprovider.go
  pkg/v1/tkg/fakes/providersupgradeclient.go
  pkg/v1/tkg/fakes/readerwriter.go
  pkg/v1/tkg/fakes/regionmanager.go
  pkg/v1/tkg/fakes/tkgconfigbomclient.go
  pkg/v1/tkg/fakes/tkgconfigupdaterclient.go
  pkg/v1/tkg/fakes/vcclient.go
  pkg/v1/tkg/kind/client.go
  pkg/v1/tkg/tkgconfigbom/bom.go
  pkg/v1/tkg/tkgconfigbom/bom_test.go
  pkg/v1/tkg/tkgconfigbom/client.go
  pkg/v1/tkg/tkgconfigupdater/ensure.go
  pkg/v1/tkg/tkgconfigupdater/provider.go
  pkg/v1/tkg/utils/files.go
  pkg/v1/tkg/yamlprocessor/ytt.go
  pkg/v1/tkr/controllers/source/tkr_source_controller.go
  pkg/v1/tkr/fakes/registy.go
  pkg/v1/tkr/pkg/registry/client.go
  pkg/v1/tkr/pkg/registry/client_integ_test.go
  pkg/v1/tkr/pkg/registry/interface.go
Labels: area/cli, area/release, area/plugin, kind/feature, ok-to-merge, cla-not-required

#1061 Refactor package tooling to support building individual package bundles and multiple repositories
  .gitignore
  Makefile
  cliplugins/Makefile
  hack/packages/kbld-image-replace/Makefile
  hack/packages/kbld-image-replace/main.go
  hack/packages/scripts/create-package.sh
  hack/packages/scripts/package-utils.sh
  hack/packages/templates/repo-utils/package-helpers.lib.yaml
  packages/kbld-config.yaml
  packages/management/featuregates/README.md
  packages/management/featuregates/bundle/config/upstream/certificates.yaml
  packages/management/featuregates/bundle/config/upstream/feature-crd.yaml
  packages/management/featuregates/bundle/config/upstream/featuregate-crd.yaml
  packages/management/featuregates/bundle/config/upstream/rbac.yaml
  packages/management/featuregates/bundle/config/upstream/service.yaml
  packages/management/featuregates/bundle/config/upstream/tanzu-featuregates-manager.yaml
  packages/management/featuregates/bundle/config/upstream/webhook.yaml
  packages/management/featuregates/bundle/config/values.yaml
  packages/management/featuregates/bundle/vendir.lock.yml
  packages/management/featuregates/bundle/vendir.yml
  packages/management/featuregates/metadata.yaml
  packages/management/featuregates/package.yaml
  packages/package-values.yaml
  pkg/v1/sdk/features/Makefile
Labels: kind/feature, ok-to-merge, cla-not-required, area/lcm

#932 improve warning message when values schema is empty
  cmd/cli/plugin/package/package_available_get.go
  pkg/v1/tkg/tkgpackageclient/utils.go
Labels: ok-to-merge, cla-not-required

#1051 Add core-management-cliplugins and standalone-cliplugins packages
  hack/packages/kbld-image-replace/main.go
  hack/packages/scripts/create-package.sh
  hack/packages/scripts/package-utils.sh
  hack/packages/templates/new-package/Makefile
  packages/kbld-config.yaml
  packages/management/core-management-cliplugins/Makefile
  packages/management/core-management-cliplugins/README.md
  packages/management/core-management-cliplugins/bundle/config/01_cliplugin-crd.yaml
  packages/management/core-management-cliplugins/bundle/config/02_cluster.yaml
  packages/management/core-management-cliplugins/bundle/config/03_kubernetes-release.yaml
  packages/management/core-management-cliplugins/metadata.yaml
  packages/management/core-management-cliplugins/package.yaml
  packages/management/core-management-cliplugins/values.template.yaml
  packages/management/featuregates/Makefile
  packages/package-values.yaml
  packages/standalone/standalone-cliplugins/Makefile
  packages/standalone/standalone-cliplugins/README.md
  packages/standalone/standalone-cliplugins/bundle/config/overlay/login.yaml
  packages/standalone/standalone-cliplugins/bundle/config/overlay/management-cluster.yaml
  packages/standalone/standalone-cliplugins/bundle/config/overlay/package.yaml
  packages/standalone/standalone-cliplugins/bundle/config/overlay/pinniped-auth.yaml
  packages/standalone/standalone-cliplugins/bundle/config/overlay/secret.yaml
  packages/standalone/standalone-cliplugins/metadata.yaml
  packages/standalone/standalone-cliplugins/package.yaml
  packages/standalone/standalone-cliplugins/values.template.yaml
Labels: area/plugin, kind/feature, ok-to-merge, cla-not-required

#1013 add dualstack feature flags
  pkg/v1/config/clientconfig.go
  pkg/v1/tkg/client/client.go
  pkg/v1/tkg/client/cluster.go
  pkg/v1/tkg/client/test_utils.go
  pkg/v1/tkg/client/validate.go
  pkg/v1/tkg/client/validate_test.go
  pkg/v1/tkg/clientcreator/creator.go
  pkg/v1/tkg/fakes/client.go
  pkg/v1/tkg/fakes/featureflagclient.go
  pkg/v1/tkg/features/interface.go
  pkg/v1/tkg/tkgctl/client.go
  pkg/v1/tkg/web/server/handlers/docker.go
  pkg/v1/tkg/web/server/handlers/init.go
Labels: ok-to-merge, cla-not-required, area/networking

#1076 Do not remove `v` prefix from package repo version
  hack/packages/scripts/package-utils.sh
Labels: priority/critical-urgent, area/repo maintenance, area/release, kind/bug, ok-to-merge, cla-not-required

#1091 Fixes 'you Azure account'
  pkg/v1/tkg/web/src/app/views/landing/azure-wizard/provider-step/azure-provider-step.component.html
Labels: kind/cleanup, ok-to-merge, area/ux, area/ui

#1073 Fix clustergen tests
  pkg/v1/providers/tests/clustergen/param_models/cluster_optional.model
Labels: kind/bug, ok-to-merge, cla-not-required

#1096 Rename CLI plugin packages
  packages/kbld-config.yaml
  packages/management/core-management-plugins/Makefile
  packages/management/core-management-plugins/README.md
  packages/management/core-management-plugins/bundle/config/01_cliplugin-crd.yaml
  packages/management/core-management-plugins/bundle/config/02_cluster.yaml
  packages/management/core-management-plugins/bundle/config/03_kubernetes-release.yaml
  packages/management/core-management-plugins/metadata.yaml
  packages/management/core-management-plugins/package.yaml
  packages/management/core-management-plugins/values.template.yaml
  packages/package-values.yaml
  packages/standalone/standalone-plugins/Makefile
  packages/standalone/standalone-plugins/README.md
  packages/standalone/standalone-plugins/bundle/config/overlay/login.yaml
  packages/standalone/standalone-plugins/bundle/config/overlay/management-cluster.yaml
  packages/standalone/standalone-plugins/bundle/config/overlay/package.yaml
  packages/standalone/standalone-plugins/bundle/config/overlay/pinniped-auth.yaml
  packages/standalone/standalone-plugins/bundle/config/overlay/secret.yaml
  packages/standalone/standalone-plugins/metadata.yaml
  packages/standalone/standalone-plugins/package.yaml
  packages/standalone/standalone-plugins/values.template.yaml
  pkg/v1/cli/carvelhelpers/kbld_test.go
Labels: priority/critical-urgent, kind/bug, ok-to-merge, cla-not-required, area/lcm

#1089 bump carvel tool versions
  hack/tools/Makefile
Labels: area/repo maintenance, kind/other, ok-to-merge

#1093 Fixes Kickstart UI's control plane subnet CIDR issue
  pkg/v1/tkg/web/src/app/views/landing/azure-wizard/azure-wizard.component.ts
  pkg/v1/tkg/web/src/app/views/landing/azure-wizard/vnet-step/vnet-step.component.html
  pkg/v1/tkg/web/src/app/views/landing/azure-wizard/vnet-step/vnet-step.component.ts
Labels: kind/bug, ok-to-merge, area/ux, area/ui

#1095 clustergen: update provider and image versions
  pkg/v1/providers/tests/clustergen/param_models/cluster_aws.model
  pkg/v1/providers/tests/clustergen/param_models/cluster_azure.model
  pkg/v1/providers/tests/clustergen/param_models/cluster_optional.model
  pkg/v1/providers/tests/clustergen/param_models/cluster_vsphere.model
Labels: CI, kind/failing-test, ok-to-merge, cla-not-required

#1072 Link standalone discovery image information during build time
  Makefile
  pkg/v1/cli/discovery/gcp.go
  pkg/v1/cli/discovery/interface.go
  pkg/v1/cli/discovery/interface_test.go
  pkg/v1/cli/discovery/kubernetes.go
  pkg/v1/cli/discovery/local.go
  pkg/v1/cli/discovery/oci.go
  pkg/v1/cli/pluginmanager/manager.go
  pkg/v1/cli/pluginmanager/manager_test.go
  pkg/v1/cli/pluginmanager/test/config.yaml
  pkg/v1/cli/pluginmanager/test/local/discovery/default/management-cluster.yaml
  pkg/v1/cli/pluginmanager/test/local/distribution/v0.2.0/tanzu-management-cluster-darwin_amd64
  pkg/v1/cli/pluginmanager/test/local/distribution/v0.2.0/tanzu-management-cluster-linux_amd64
  pkg/v1/cli/pluginmanager/test/local/distribution/v0.2.0/tanzu-management-cluster-windows_amd64
  pkg/v1/config/clientconfig.go
  pkg/v1/config/clientconfig_test.go
  pkg/v1/config/defaults.go
  pkg/v1/tkg/clusterclient/clusterclient.go
  pkg/v1/tkg/constants/config_variables.go
  pkg/v1/tkg/fakes/clusterclient.go
Labels: ok-to-merge, cla-not-required

#1101 Update CLIPlugin to use v1 CRD
  packages/management/core-management-plugins/bundle/config/01_cliplugin-crd.yaml
Labels: area/api, ok-to-merge, cla-not-required

#1074 Add MachineDeployment specifier to node pool
  cmd/cli/plugin/cluster/set_node_pool.go
  pkg/v1/tkg/client/machine_deployment.go
  pkg/v1/tkg/client/machine_deployment_test.go
Labels: ok-to-merge, cla-not-required

#1086 Support set/unset environment variables through tanzu config file
  apis/config/v1alpha1/clientconfig.go
  apis/config/v1alpha1/clientconfig_types.go
  pkg/v1/cli/command/core/config.go
  pkg/v1/cli/command/core/config_test.go
  pkg/v1/cli/command/core/root.go
  pkg/v1/cli/runner.go
  pkg/v1/config/clientconfig.go
Labels: area/cli, kind/feature, ok-to-merge, cla-not-required

#1054 Extend AWS CloudFormation commands
  addons/go.sum
  cmd/cli/plugin/managementcluster/permissions_aws_generate.go
  cmd/cli/plugin/managementcluster/permissions_aws_set.go
  go.mod
  pkg/v1/providers/config_default.yaml
  pkg/v1/tkg/aws/client.go
  pkg/v1/tkg/aws/client_test.go
  pkg/v1/tkg/aws/fixtures/cloudformation-default.yaml
  pkg/v1/tkg/aws/fixtures/cloudformation-with-tmc.yaml
  pkg/v1/tkg/aws/interface.go
  pkg/v1/tkg/client/client.go
  pkg/v1/tkg/client/config_permission.go
  pkg/v1/tkg/constants/config_variables.go
  pkg/v1/tkg/fakes/awsclient.go
  pkg/v1/tkg/fakes/client.go
  pkg/v1/tkg/fakes/featuresclient.go
  pkg/v1/tkg/tkgctl/config_permission_aws.go
  pkg/v1/tkg/tkgctl/interface.go
Labels: kind/feature, ok-to-merge, cla-not-required, area/lcm

#1083 Prevent Windows Updates by disabling the service
  pkg/v1/providers/ytt/03_customizations/03_windows/prevent_windows_updates.yaml
Labels: ok-to-merge, cla-not-required

#1080 apply ordering to RBAC resources in FeatureGates package
  packages/kbld-config.yaml
  packages/management/featuregates/bundle/config/upstream/rbac.yaml
Labels: area/addons, kind/bug, ok-to-merge, cla-not-required

#1107 Remove erroneous -f flag from delete command, use --force instead
  pkg/v1/tkg/client/delete_region.go
Labels: ok-to-merge, area/ux, cla-not-required

#1119 Fix panic on node-pool set with no cluster name
  cmd/cli/plugin/cluster/set_node_pool.go
Labels: ok-to-merge, cla-not-required

#1104 introduce feature flags for custom nameservers
  pkg/v1/config/clientconfig.go
  pkg/v1/tkg/client/cluster.go
  pkg/v1/tkg/client/validate.go
  pkg/v1/tkg/client/validate_test.go
Labels: ok-to-merge, area/ux, cla-not-required, area/networking

#1108 Deploy clusters on multiple-azs in vSphere.
  pkg/v1/providers/config_default.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.0.1/ytt/overlay.yaml
  pkg/v1/providers/infrastructure-vsphere/ytt/vsphere-overlay.yaml
  pkg/v1/tkg/client/client_suite_test.go
  pkg/v1/tkg/client/validate.go
Labels: ok-to-merge, area/ux, cla-not-required

#1124 Fix plugin download from OCI registry if bundle includes test directory
  pkg/v1/cli/artifact/oci.go
Labels: kind/bug, ok-to-merge, cla-not-required

#1128 Fix table of contents in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: ok-to-merge, cla-not-required

#788 Separate avi vip network
  pkg/v1/providers/config_default.yaml
  pkg/v1/providers/tests/clustergen/param_models/cluster_vsphere.model
  pkg/v1/providers/ytt/02_addons/avi/ako_operator_secret.yaml
  pkg/v1/providers/ytt/03_customizations/02_avi/add-ako.yaml
  pkg/v1/providers/ytt/03_customizations/02_avi/ako-deployment.lib.yaml
  pkg/v1/providers/ytt/03_customizations/02_avi/ako-operator-deployment.lib.yaml
Labels: ok-to-merge, cla-not-required, area/networking

#1118 bump CPI to version 1.22.3
  pkg/v1/providers/vendir.lock.yml
  pkg/v1/providers/vendir.yml
  pkg/v1/providers/ytt/02_addons/cpi/cpi_overlay.lib.yaml
  pkg/v1/providers/ytt/02_addons/cpi/cpi_secret_crs.yaml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/LICENSE
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/NOTICE
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.3/bundle/config/overlays/add-secret.yaml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.3/bundle/config/overlays/update-config.yaml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.3/bundle/config/overlays/update-daemonset.yaml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.3/bundle/config/overlays/update-secret.yaml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.3/bundle/config/upstream/vsphere-cpi/01-rbac.yaml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.3/bundle/config/upstream/vsphere-cpi/02-config.yaml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.3/bundle/config/upstream/vsphere-cpi/03-secret.yaml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.3/bundle/config/upstream/vsphere-cpi/04-service.yaml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.3/bundle/config/upstream/vsphere-cpi/05-daemonset.yaml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.3/bundle/config/values.star
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.3/bundle/config/values.yaml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.3/bundle/config/vsphereconf.lib.txt
  pkg/v1/providers/ytt/vendir/vsphere_cpi/vsphere_cpi.lib.yaml
Labels: ok-to-merge, cla-not-required

#1088 Add logic for asking user content if secret export exists before adding secret of the same name
  cmd/cli/plugin/secret/registry_secret_add.go
  pkg/v1/tkg/fakes/kappclient.go
  pkg/v1/tkg/kappclient/client.go
  pkg/v1/tkg/kappclient/interface.go
  pkg/v1/tkg/test/tkgpackageclient/package_plugin_integration_test.go
  pkg/v1/tkg/tkgpackageclient/interface.go
  pkg/v1/tkg/tkgpackageclient/registry_secret_list.go
Labels: area/plugin, ok-to-merge, cla-not-required

#1140 Remove nameservers and dualstack settings from clustergen models
  pkg/v1/providers/tests/clustergen/param_models/cluster_optional.model
Labels: area/testing, ok-to-merge, cla-not-required

#1153 Disable autoscaler integration tests
  pkg/v1/tkg/test/tkgctl/shared/autoscaler.go
Labels: kind/bug, kind/failing-test, ok-to-merge, cla-not-required

#1149 set priorityClassName: system-node-critical in CPI daemonset
  pkg/v1/providers/vendir.lock.yml
  pkg/v1/providers/vendir.yml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.3/bundle/config/upstream/vsphere-cpi/05-daemonset.yaml
Labels: ok-to-merge, cla-not-required

#1165 Update tkg-telemetry collector url for 1.5.0
  pkg/v1/tkg/clusterclient/clusterclient.go
Labels: ok-to-merge, cla-not-required

#1162 Add cert-manager templates to providers
  pkg/v1/providers/cert-manager/v1.5.3/cert-manager.yaml
  pkg/v1/providers/config.yaml
  pkg/v1/tkg/constants/config_keys.go
  pkg/v1/tkg/fakes/providers/providers.zip
  pkg/v1/tkg/tkgconfigupdater/provider.go
  pkg/v1/tkg/tkgconfigupdater/tkgconfigupdater_test.go
  pkg/v1/tkg/tkgctl/client_test.go
Labels: kind/bug, ok-to-merge, cla-not-required

#979 Bump Antrea to Dragonfish.1 (1.2.3)
  pkg/v1/providers/infrastructure-vsphere/v1.0.1/ytt/overlay-windows.yaml
  pkg/v1/providers/vendir.lock.yml
  pkg/v1/providers/vendir.yml
  pkg/v1/providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/0.13.3/bundle/config/upstream/antrea.yaml
  pkg/v1/providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.2.3/bundle/config/kapp-config.yaml
  pkg/v1/providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.2.3/bundle/config/overlay/antrea_overlay.yaml
  pkg/v1/providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.2.3/bundle/config/upstream/antrea.yaml
  pkg/v1/providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.2.3/bundle/config/values.star
  pkg/v1/providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.2.3/bundle/config/values.yaml
  pkg/v1/providers/ytt/vendir/cni/cni.lib.yaml
Labels: ok-to-merge, cla-not-required

#1159 adapt ako's fix for avi resource deletion in k8s 1.22
  pkg/v1/tkg/clusterclient/resource.go
  pkg/v1/tkg/constants/cluster_internal.go
Labels: area/cli, kind/bug, ok-to-merge, cla-not-required, area/networking

#1182 Fix issue where azure management cluster identity secret is not moved…
  pkg/v1/providers/infrastructure-azure/v1.0.0/ytt/overlay.yaml
Labels: area/cli, kind/bug, ok-to-merge, cla-not-required

#1170 Configure outbound load balancers for azure private clusters
  pkg/v1/providers/config_default.yaml
  pkg/v1/providers/infrastructure-azure/v1.0.0/ytt/overlay.yaml
  pkg/v1/providers/tests/clustergen/param_models/cluster_azure.model
Labels: ok-to-merge, area/ux, cla-not-required, area/networking, docs-triage-needed

#1144 Enable feature flag for API driven CLIPlugin Discovery
  .github/workflows/plugin_tests.yaml
  Makefile
  cmd/cli/plugin/login/main.go
  cmd/cli/plugin/managementcluster/create.go
  cmd/cli/plugin/managementcluster/get.go
  cmd/cli/plugin/managementcluster/upgrade.go
  common.mk
  docs/dev/build.md
  pkg/v1/cli/catalog/catalog.go
  pkg/v1/cli/catalog/catalog_test.go
  pkg/v1/cli/command/core/discovery_source.go
  pkg/v1/cli/command/core/plugin_manager.go
  pkg/v1/cli/command/core/root.go
  pkg/v1/cli/common/defaults.go
  pkg/v1/cli/discovery/utils.go
  pkg/v1/cli/discovery/utils_test.go
  pkg/v1/cli/pluginmanager/manager.go
  pkg/v1/cli/pluginmanager/manager_test.go
  pkg/v1/config/clientconfig.go
  pkg/v1/config/clientconfig_test.go
  pkg/v1/config/defaults.go
  pkg/v1/config/discovery.go
  pkg/v1/providers/ytt/02_addons/management-packages/core-management-plugins/add_core_management_plugins_package.yaml
  pkg/v1/tkg/client/cluster.go
  pkg/v1/tkg/client/init.go
  pkg/v1/tkg/client/upgrade_cluster.go
  pkg/v1/tkg/client/upgrade_region.go
  pkg/v1/tkg/constants/cluster_internal.go
  pkg/v1/tkg/constants/config_variables.go
Labels: area/cli, area/plugin, kind/feature, ok-to-merge, cla-not-required

#990 MAJOR windows fixes for secretgen and antrea-cleanup
  pkg/v1/providers/infrastructure-vsphere/ytt/vsphere-overlay.yaml
  pkg/v1/providers/tests/unit/windows_test.go
  pkg/v1/providers/ytt/02_addons/secretgen-controller/add_secretgen-controller.yaml
  pkg/v1/providers/ytt/03_customizations/03_windows/prevent_windows_updates.yaml
  pkg/v1/providers/ytt/03_customizations/03_windows/register_antrea_cleanup.yaml
  pkg/v1/tkg/client/client.go
  pkg/v1/tkg/client/client_suite_test.go
  pkg/v1/tkg/client/cluster.go
  pkg/v1/tkg/client/config.go
  pkg/v1/tkg/client/init.go
  pkg/v1/tkg/client/validate.go
  pkg/v1/tkg/tkgctl/create_cluster.go
Labels: kind/bug, ok-to-merge, cla-not-required

#1117 Update node-pool API to handle vpshere ipv6
  pkg/v1/tkg/client/machine_deployment.go
  pkg/v1/tkg/client/machine_deployment_test.go
Labels: ok-to-merge, cla-not-required

#1135 Update BoM retrieval version to v0.11.0
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#1136 Update BoM retrieval version to v0.12.0-dev
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#1210 Set cluster plan info in CSI addon secret
  pkg/v1/providers/ytt/02_addons/csi/csi_addon_data.lib.yaml
Labels: priority/critical-urgent, ok-to-merge, cla-not-required

#1211 Update k8s version support matrix with management-cluster version
  pkg/v1/tkg/tkgconfighelper/tkgconfighelper_test.go
  pkg/v1/tkg/tkgconfighelper/validate.go
Labels: area/release, ok-to-merge, cla-not-required

#1197 Bump kapp-controller version to 0.30.0
  pkg/v1/providers/vendir.lock.yml
  pkg/v1/providers/vendir.yml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.30.0/bundle/config/overlays/change-namespace.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.30.0/bundle/config/overlays/update-configmap.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.30.0/bundle/config/overlays/update-crds.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.30.0/bundle/config/overlays/update-deployment.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.30.0/bundle/config/upstream/kapp-controller.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.30.0/bundle/config/values.star
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.30.0/bundle/config/values.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/kapp-controller.lib.yaml
Labels: area/addons, ok-to-merge, cla-not-required

#1188 Add documentation regarding API-driven plugin discovery
  .markdownlintrc
  docs/cli/cli-architecture.md
  docs/cli/getting-started.md
  docs/cli/plugin_implementation_guide.md
  docs/design/context-aware-plugin-discovery-design.md
  docs/design/images/context-aware-plugin-discovery-design.png
Labels: area/docs, ok-to-merge, cla-not-required

#1215 Support set/unset environment variables through tanzu config file
  apis/config/v1alpha1/clientconfig.go
  apis/config/v1alpha1/clientconfig_types.go
  pkg/v1/cli/command/core/config.go
  pkg/v1/cli/command/core/config_test.go
  pkg/v1/cli/command/core/root.go
  pkg/v1/cli/runner.go
  pkg/v1/config/clientconfig.go
Labels: ok-to-merge, cla-not-required

#1221 Cherry-pick #1205 in release-0.11 for patch release v0.11.1
  pkg/v1/cli/runner.go
Labels: area/release, ok-to-merge, cla-not-required

#1222 Update BoM retrieval version to v0.11.1
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#1216 Setup proxy configuration to infrastructure controllers
  pkg/v1/providers/infrastructure-aws/v1.0.0/infrastructure-components.yaml
  pkg/v1/providers/infrastructure-azure/v1.0.0/infrastructure-components.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.0.1/infrastructure-components.yaml
Labels: area/cli, kind/bug, ok-to-merge, cla-not-required

#1227 Update version for BOM retrieval to v0.12.0
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#1225 Docs: Update README node-server run command
  pkg/v1/tkg/web/README.md
Labels: ok-to-merge, area/ux

#1218 Fix vsphere cluster ytt template multi cluster issue
  pkg/v1/providers/infrastructure-vsphere/ytt/vsphere-overlay.yaml
Labels: area/cli, kind/bug, ok-to-merge, cla-not-required

#1229 Fix the issue where cluster upgrade doesn't timeout and stuck indefin…
  pkg/v1/tkg/clusterclient/clusterclient.go
Labels: area/cli, kind/bug, ok-to-merge, cla-not-required

#1232 Update BoM retrieval version to v0.13.0-dev
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#1228 Kickstart UI: enum refactor vsphere fields
  pkg/v1/tkg/web/src/app/shared/constants/app.constants.ts
  pkg/v1/tkg/web/src/app/views/landing/vsphere-wizard/node-setting-step/node-setting-step.component.ts
  pkg/v1/tkg/web/src/app/views/landing/vsphere-wizard/provider-step/vsphere-provider-step.component.ts
  pkg/v1/tkg/web/src/app/views/landing/vsphere-wizard/resource-step/resource-step.component.ts
  pkg/v1/tkg/web/src/app/views/landing/vsphere-wizard/vsphere-wizard.constants.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/constants/wizard.constants.ts
Labels: ok-to-merge, area/ux, area/ui

#1181 fix severity 1 link in support process document
  docs/community/support-process.md
Labels: area/repo maintenance, ok-to-merge, cla-not-required

#1255 Makes the bootstrap token ttl configurable
  pkg/v1/providers/bootstrap-kubeadm/v1.0.0/bootstrap-components.yaml
Labels: ok-to-merge, cla-not-required, area/lcm

#1139 version prefix matching changed to exact match when updating TKR compatibility condition
  pkg/v1/tkr/controllers/source/suite_test.go
  pkg/v1/tkr/controllers/source/tkr_source_controller.go
  pkg/v1/tkr/fakes/boms/bom-v1.20.5+vmware.1.yaml
  pkg/v1/tkr/fakes/boms/metadata.yaml
Labels: area/cli, kind/bug, ok-to-merge, cla-not-required

#1146 UI - cleanup unused code (azure worker node settings, disabled unit tests)
  pkg/v1/tkg/web/src/app/shared/abstracts/basic-subscriber.ts
  pkg/v1/tkg/web/src/app/shared/service/Messenger.ts
  pkg/v1/tkg/web/src/app/views/landing/aws-wizard/aws-wizard.component.ts
  pkg/v1/tkg/web/src/app/views/landing/aws-wizard/vpc-step/vpc-step.component.ts
  pkg/v1/tkg/web/src/app/views/landing/azure-wizard/azure-wizard.component.spec.ts
  pkg/v1/tkg/web/src/app/views/landing/azure-wizard/azure-wizard.module.ts
  pkg/v1/tkg/web/src/app/views/landing/azure-wizard/provider-step/azure-provider-step.component.spec.ts
  pkg/v1/tkg/web/src/app/views/landing/azure-wizard/vnet-step/vnet-step.component.ts
  pkg/v1/tkg/web/src/app/views/landing/azure-wizard/worker-node-setting-step/worker-node-setting-step.component.html
  pkg/v1/tkg/web/src/app/views/landing/azure-wizard/worker-node-setting-step/worker-node-setting-step.component.scss
  pkg/v1/tkg/web/src/app/views/landing/azure-wizard/worker-node-setting-step/worker-node-setting-step.component.spec.ts
  pkg/v1/tkg/web/src/app/views/landing/azure-wizard/worker-node-setting-step/worker-node-setting-step.component.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/components/steps/network-step/network-step.component.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/wizard-base/wizard-base.ts
Labels: kind/cleanup, ok-to-merge, area/ui

#1245 Update references to old config directory
  docs/cli/commands/tanzu_completion.md
  pkg/v1/cli/command/core/completion.go
Labels: area/docs, ok-to-merge, cla-not-required

#1257 Fix issue with applying ceip yaml to the management cluster
  pkg/v1/tkg/clusterclient/clusterclient.go
Labels: kind/bug, ok-to-merge, cla-not-required

#1158 update ClusterAPI version to v1.0.1
  addons/go.mod
  addons/go.sum
  addons/pinniped/post-deploy/go.sum
  go.mod
  go.sum
  pkg/v1/providers/bootstrap-kubeadm/v1.0.1/bootstrap-components.yaml
  pkg/v1/providers/bootstrap-kubeadm/v1.0.1/metadata.yaml
  pkg/v1/providers/cluster-api/v1.0.1/core-components.yaml
  pkg/v1/providers/cluster-api/v1.0.1/metadata.yaml
  pkg/v1/providers/config.yaml
  pkg/v1/providers/control-plane-kubeadm/v1.0.1/control-plane-components.yaml
  pkg/v1/providers/control-plane-kubeadm/v1.0.1/metadata.yaml
  pkg/v1/providers/infrastructure-docker/v1.0.1/cluster-template-definition-dev.yaml
  pkg/v1/providers/infrastructure-docker/v1.0.1/cluster-template-definition-prod.yaml
  pkg/v1/providers/infrastructure-docker/v1.0.1/infrastructure-components.yaml
  pkg/v1/providers/infrastructure-docker/v1.0.1/metadata.yaml
  pkg/v1/providers/infrastructure-docker/v1.0.1/ytt/base-template.yaml
  pkg/v1/providers/infrastructure-docker/v1.0.1/ytt/overlay.yaml
  pkg/v1/providers/tests/go.mod
  pkg/v1/providers/tests/go.sum
Labels: ok-to-merge, cla-not-required, area/lcm
