Repository vmware-tanzu/tanzu-framework, pull requests merged in 2021-12, with the labels that each got.

#1267 Updating version tag used for BOM retrieval to v0.13.0
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#1268 Updating version tag used for BOM retrieval to v0.14.0-dev
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#1263 create namespace prior to metadata check
  pkg/v1/tkg/fakes/kappclient.go
  pkg/v1/tkg/test/tkgpackageclient/package_plugin_integration_test.go
  pkg/v1/tkg/tkgpackageclient/package_install.go
  pkg/v1/tkg/tkgpackageclient/package_update_test.go
Labels: ok-to-merge, cla-not-required

#1260 Kickstart UI: store labels and annotations in config file
  pkg/v1/tkg/tkgconfigproviders/aws.go
  pkg/v1/tkg/tkgconfigproviders/azure.go
  pkg/v1/tkg/tkgconfigproviders/docker.go
  pkg/v1/tkg/tkgconfigproviders/helper.go
  pkg/v1/tkg/tkgconfigproviders/helper_test.go
  pkg/v1/tkg/tkgconfigproviders/tkgconfig_test.go
  pkg/v1/tkg/tkgconfigproviders/vsphere.go
Labels: ok-to-merge, area/ux, area/ui

#1042 Add templating to support dualstack ipv6 primary
  pkg/v1/providers/infrastructure-vsphere/v1.0.1/ytt/overlay.yaml
  pkg/v1/providers/tests/unit/ip_family_test.go
  pkg/v1/providers/ytt/03_customizations/ip_family.yaml
Labels: area/cli, kind/enhancement, ok-to-merge, cla-not-required

#1272 Fix vsphere ssh key for multi AZ MDs
  pkg/v1/providers/infrastructure-vsphere/ytt/vsphere-overlay.yaml
Labels: area/cli, kind/bug, ok-to-merge, cla-not-required

#1271 Ignore changes to TKGDefaultCompatibilityImagePath in verify script
  hack/verify-dirty.sh
Labels: priority/critical-urgent, area/repo maintenance, area/testing, kind/bug, ok-to-merge, cla-not-required

#883 Make Capability GVR query's group field optional
  apis/run/v1alpha1/capability_types.go
  config/crd/bases/run.tanzu.vmware.com_capabilities.yaml
Labels: area/sdk, kind/bug, ok-to-merge, cla-not-required

#1231 Adds functionality to update kube-vip parameters
  pkg/v1/tkg/client/kubevip_update_helper.go
  pkg/v1/tkg/client/upgrade_cluster.go
  pkg/v1/tkg/client/upgrade_cluster_test.go
  pkg/v1/tkg/clusterclient/clusterclient.go
  pkg/v1/tkg/clusterclient/resource.go
  pkg/v1/tkg/fakes/clusterclient.go
  pkg/v1/tkg/fakes/clusterclientfactory.go
  pkg/v1/tkg/fakes/crtclientfactory.go
  pkg/v1/tkg/fakes/crtclusterclient.go
  pkg/v1/tkg/fakes/discoveryclientfactory.go
  pkg/v1/tkg/fakes/discoveryclusterclient.go
  pkg/v1/tkg/fakes/poller.go
Labels: area/cli, ok-to-merge, cla-not-required

#1179 codeowners update: add codeowners for api machinery related files
  CODEOWNERS
Labels: area/repo maintenance, ok-to-merge, cla-not-required

#1279 Adds missing github actions for setting Node version in Release and Release Staging
  .github/workflows/release.yaml
  .github/workflows/release_staging.yaml
Labels: CI, ok-to-merge, cla-not-required

#1283 Fix upgrade exits prematurely when upgrade does not involve a change in Kubernetes version
  pkg/v1/tkg/clusterclient/clusterclient.go
  pkg/v1/tkg/clusterclient/clusterclient_test.go
Labels: kind/bug, ok-to-merge, cla-not-required, area/lcm

#1291 add nilness check for secret export
  cmd/cli/plugin/secret/registry_secret_add.go
Labels: ok-to-merge, cla-not-required

#1111 Suppress output of CLI spinner if not connected to terminal
  .github/workflows/tkgpackage_integration_test.yaml
  cmd/cli/plugin/package/display_utils.go
  go.mod
  go.sum
Labels: ok-to-merge, cla-not-required

#1157 Add install scripts
  hack/install.bat
  hack/install.sh
Labels: area/release, ok-to-merge, cla-not-required

#1147 improve readability of nameserver flag validation
  pkg/v1/tkg/client/validate.go
Labels: kind/cleanup, ok-to-merge, cla-not-required

#962 Improve help for Makefile
  Makefile
Labels: ok-to-merge, cla-not-required

#1049 CODEOWNERS cleanup
  CODEOWNERS
Labels: area/repo maintenance, ok-to-merge, cla-not-required

#865 Fix broken URL
  docs/cli/style_guide.md
Labels: ok-to-merge, cla-not-required

#1295 Add CodeQL scan github action
  .github/workflows/security_codeql.yaml
Labels: area/testing, ok-to-merge, cla-not-required

#1050 Update golangci-lint to 1.43.0
  .github/workflows/main.yaml
  .golangci.yaml
  cmd/cli/plugin-admin/codegen/test/main.go
  cmd/cli/plugin/package/package_installed_get.go
  cmd/cli/plugin/secret/registry_secret_add.go
  hack/tools/go.mod
  hack/tools/go.sum
  pkg/v1/cli/command/core/root.go
  pkg/v1/cli/runner.go
  pkg/v1/tkg/aws/client_test.go
  pkg/v1/tkg/client/delete_region.go
  pkg/v1/tkg/client/init.go
  pkg/v1/tkg/client/machine_deployment_test.go
  pkg/v1/tkg/client/validate.go
  pkg/v1/tkg/clusterclient/clusterclient_test.go
  pkg/v1/tkg/constants/config_variables.go
  pkg/v1/tkg/kappclient/client.go
  pkg/v1/tkg/log/writer.go
  pkg/v1/tkg/tkgpackageclient/package_install.go
  pkg/v1/tkg/tkgpackageclient/package_update.go
  pkg/v1/tkg/utils/common.go
  pkg/v1/tkg/utils/kubeconfig.go
  pkg/v1/tkg/web/server/handlers/error.go
  pkg/v1/tkg/yamlprocessor/ytt.go
Labels: ok-to-merge, cla-not-required

#1242 add packaging API check for non-tanzu cluster
  cmd/cli/plugin/package/main.go
  cmd/cli/plugin/package/package_available.go
  cmd/cli/plugin/package/package_install.go
  cmd/cli/plugin/package/package_installed.go
  cmd/cli/plugin/package/repository.go
  cmd/cli/plugin/secret/main.go
  cmd/cli/plugin/secret/registry.go
  pkg/v1/tkg/test/tkgpackageclient/package_plugin_integration_test.go
  pkg/v1/tkg/tkgpackagedatamodel/constants.go
Labels: ok-to-merge, cla-not-required

#1302 Fix panic on creating nodepools
  pkg/v1/tkg/client/machine_deployment.go
Labels: ok-to-merge, cla-not-required

#1301 Update defaults for Azure private cluster configs
  pkg/v1/providers/config_default.yaml
Labels: ok-to-merge, cla-not-required

#1308 Add retry with polling when patching Cluster resource after successfu…
  pkg/v1/tkg/client/upgrade_cluster.go
  pkg/v1/tkg/clusterclient/clusterclient.go
  pkg/v1/tkg/fakes/clusterclient.go
Labels: area/cli, kind/bug, ok-to-merge, cla-not-required, area/lcm

#1241 Sync calico package updates to the ClusterResourceSet
  pkg/v1/providers/vendir.lock.yml
  pkg/v1/providers/vendir.yml
  pkg/v1/providers/ytt/vendir/cni/_ytt_lib/addons/packages/calico/3.19.1/bundle/config/overlay/calico_overlay.yaml
  pkg/v1/providers/ytt/vendir/cni/_ytt_lib/addons/packages/calico/3.19.1/bundle/config/values.yaml
Labels: area/addons, ok-to-merge, cla-not-required

#1318 Antrea offload capability
  pkg/v1/providers/vendir.lock.yml
  pkg/v1/providers/vendir.yml
  pkg/v1/providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.2.3/bundle/config/overlay/antrea_overlay.yaml
  pkg/v1/providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.2.3/bundle/config/upstream/antrea.yaml
  pkg/v1/providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.2.3/bundle/config/values.yaml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/NOTICE
Labels: ok-to-merge, cla-not-required, area/networking

#1335 Revert "Antrea offload capability"
  pkg/v1/providers/vendir.lock.yml
  pkg/v1/providers/vendir.yml
  pkg/v1/providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.2.3/bundle/config/overlay/antrea_overlay.yaml
  pkg/v1/providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.2.3/bundle/config/upstream/antrea.yaml
  pkg/v1/providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.2.3/bundle/config/values.yaml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/NOTICE
Labels: kind/bug, ok-to-merge, cla-not-required, area/networking

#1312 Fixes potential issue where contents get unzipped outside current directory
  pkg/v1/tkg/tkgconfigupdater/helper.go
  pkg/v1/tkg/tkgconfigupdater/helper_test.go
Labels: area/cli, area/security, ok-to-merge, cla-not-required

#1353 Expand tkg-iam team ownership
  CODEOWNERS
Labels: ok-to-merge, cla-not-required

#1354 Bump CAPA version to v1.2.0
  pkg/v1/providers/config.yaml
  pkg/v1/providers/infrastructure-aws/v1.2.0/cluster-template-definition-dev.yaml
  pkg/v1/providers/infrastructure-aws/v1.2.0/cluster-template-definition-prod.yaml
  pkg/v1/providers/infrastructure-aws/v1.2.0/infrastructure-components.yaml
  pkg/v1/providers/infrastructure-aws/v1.2.0/metadata.yaml
  pkg/v1/providers/infrastructure-aws/v1.2.0/ytt/base-template.yaml
  pkg/v1/providers/infrastructure-aws/v1.2.0/ytt/overlay.yaml
  pkg/v1/providers/tests/clustergen/param_models/cluster_aws.model
  pkg/v1/providers/tests/clustergen/param_models/cluster_optional.model
Labels: area/cli, ok-to-merge, cla-not-required, area/lcm

#1343 Add extra read only IAM permissions to support Tanzu Mission Control
  pkg/v1/tkg/aws/client.go
  pkg/v1/tkg/aws/client_test.go
  pkg/v1/tkg/aws/fixtures/cloudformation-with-tmc.yaml
Labels: ok-to-merge, cla-not-required

#1330 Add network separation feature gate
  pkg/v1/config/clientconfig.go
  pkg/v1/providers/config_default.yaml
  pkg/v1/tkg/client/validate.go
  pkg/v1/tkg/client/validate_test.go
  pkg/v1/tkg/constants/config_variables.go
Labels: kind/enhancement, ok-to-merge, cla-not-required

#1367 air-gap script should support customized tkg-bom tag
  hack/gen-publish-images.sh
Labels: area/docs, ok-to-merge

#1298 Exit install script on error
  hack/install.sh
Labels: CI, ok-to-merge, cla-not-required

#1310 UI - Resolve Github code scanning alerts
  pkg/v1/tkg/web/e2e/src/vsphere-flow/vsphere-enable-opt-common.ts
  pkg/v1/tkg/web/e2e/src/vsphere-flow/wizard-common.ts
  pkg/v1/tkg/web/e2e/src/vsphere-flow/wizard.e2e-spec.ts
  pkg/v1/tkg/web/node-server/package-lock.json
  pkg/v1/tkg/web/node-server/package.json
  pkg/v1/tkg/web/node-server/src/app.js
Labels: ok-to-merge, area/ui

#1362 Fix the upgrade issue when the clusters are configured with non-defau…
  pkg/v1/providers/infrastructure-azure/v1.0.0/ytt/overlay.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.0.1/ytt/overlay-windows.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.0.1/ytt/overlay.yaml
  pkg/v1/providers/tests/unit/ip_family_test.go
Labels: area/cli, kind/bug, ok-to-merge, cla-not-required

#1336 Fix `tanzu config set` command help-text
  pkg/v1/cli/command/core/config.go
Labels: area/cli, kind/bug, ok-to-merge, cla-not-required

#1380 [release-0.13] Cherry-pick #1354: Bump CAPA version to v1.2.0
  pkg/v1/providers/config.yaml
  pkg/v1/providers/infrastructure-aws/v1.0.0/infrastructure-components.yaml
  pkg/v1/providers/infrastructure-aws/v1.2.0/cluster-template-definition-dev.yaml
  pkg/v1/providers/infrastructure-aws/v1.2.0/cluster-template-definition-prod.yaml
  pkg/v1/providers/infrastructure-aws/v1.2.0/infrastructure-components.yaml
  pkg/v1/providers/infrastructure-aws/v1.2.0/metadata.yaml
  pkg/v1/providers/infrastructure-aws/v1.2.0/ytt/base-template.yaml
  pkg/v1/providers/infrastructure-aws/v1.2.0/ytt/overlay.yaml
  pkg/v1/providers/tests/clustergen/param_models/cluster_aws.model
  pkg/v1/providers/tests/clustergen/param_models/cluster_optional.model
Labels: ok-to-merge, cla-not-required, area/lcm

#1317 Add unit tests for AVI related providers.
  pkg/v1/providers/tests/unit/avi_test.go
Labels: ok-to-merge, cla-not-required

#1389 add missing ordering annotation to cliplugins CRD in core-management-plugins package
  packages/management/core-management-plugins/bundle/config/01_cliplugin-crd.yaml
Labels: kind/bug, ok-to-merge, cla-not-required

#1390 Remove v1beta1 references from autoscaler deployment yaml
  pkg/v1/providers/ytt/03_customizations/autoscaler/enable_autoscaler.yaml
  pkg/v1/tkg/test/tkgctl/shared/autoscaler.go
Labels: ok-to-merge, cla-not-required

#1374 Antrea disable UDP workload setting
  pkg/v1/providers/config_default.yaml
  pkg/v1/providers/tests/clustergen/param_models/cluster_optional.model
  pkg/v1/providers/vendir.lock.yml
  pkg/v1/providers/vendir.yml
  pkg/v1/providers/ytt/02_addons/cni/antrea/antrea_addon_data.lib.yaml
  pkg/v1/providers/ytt/lib/config_variable_association.star
  pkg/v1/providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.2.3/bundle/config/overlay/antrea_overlay.yaml
  pkg/v1/providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.2.3/bundle/config/values.yaml
Labels: ok-to-merge, cla-not-required, area/networking

#1328 Configure cluster DNS in kapp controller package
  pkg/v1/providers/config_default.yaml
  pkg/v1/providers/tests/unit/windows_test.go
  pkg/v1/providers/vendir.lock.yml
  pkg/v1/providers/vendir.yml
  pkg/v1/providers/ytt/02_addons/kapp-controller/kapp-controller_addon_data.lib.yaml
  pkg/v1/providers/ytt/02_addons/kapp-controller/kapp-controller_overlay.lib.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.30.0/bundle/config/overlays/update-deployment.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.30.0/bundle/config/values.star
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.30.0/bundle/config/values.yaml
  pkg/v1/tkg/client/cluster.go
  pkg/v1/tkg/client/validate.go
  pkg/v1/tkg/client/validate_test.go
  pkg/v1/tkg/constants/config_variables.go
Labels: area/addons, kind/feature, ok-to-merge, cla-not-required

#1383 [release-0.13] Updating version tag used for BOM retrieval to v0.13.1
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#1202 Registry CA cert will be used when copying images
  hack/gen-publish-images-fromtar.sh
Labels: area/cli, kind/bug, ok-to-merge, cla-not-required, tkg-sre

#1326 Add unit test for kubeadm template panic
  pkg/v1/tkg/client/machine_deployment_test.go
Labels: ok-to-merge, cla-not-required

#1363 Update Makefile for plugin template and plugin implementation guide
  docs/cli/plugin_implementation_guide.md
  docs/design/context-aware-plugin-discovery-design.md
  pkg/v1/builder/template/plugintemplates/Makefile.tmpl
Labels: kind/documentation, ok-to-merge, cla-not-required

#1373 Updates the CAPV version to v1.0.2
  addons/go.sum
  go.mod
  go.sum
  pkg/v1/providers/config.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.0.2/cluster-template-definition-dev-windows.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.0.2/cluster-template-definition-dev.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.0.2/cluster-template-definition-prod.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.0.2/infrastructure-components.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.0.2/metadata.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.0.2/ytt/base-template.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.0.2/ytt/overlay-windows.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.0.2/ytt/overlay.yaml
  pkg/v1/providers/tests/clustergen/param_models/cluster_optional.model
  pkg/v1/providers/tests/clustergen/param_models/cluster_vsphere.model
  pkg/v1/providers/tests/unit/custom_nameservers_test.go
  pkg/v1/providers/tests/unit/ip_family_test.go
  pkg/v1/providers/tests/unit/windows_test.go
Labels: area/cli, ok-to-merge, cla-not-required, area/lcm

#1329 Replace deprecated linters
  .golangci.yaml
  Makefile
  apis/run/v1alpha2/tanzukubernetescluster_types.go
  cmd/cli/plugin/cluster/set_node_pool.go
  cmd/cli/plugin/package/package_available.go
  cmd/cli/plugin/secret/registry.go
  pkg/v1/builder/command/publish/publisher.go
  pkg/v1/builder/template/plugintemplates/dotgolangci.txt.tmpl
  pkg/v1/cli/command/core/config.go
  pkg/v1/tkg/client/delete_region.go
  pkg/v1/tkg/client/get_cluster_helper.go
  pkg/v1/tkg/client/init.go
  pkg/v1/tkg/client/validate.go
  pkg/v1/tkg/clusterclient/clusterclient.go
  pkg/v1/tkg/kind/client.go
  pkg/v1/tkg/region/interface.go
  pkg/v1/tkg/test/framework/cluster_proxy.go
  pkg/v1/tkg/test/framework/e2e_config.go
  pkg/v1/tkg/test/framework/exec/kubectl.go
  pkg/v1/tkg/test/framework/utils.go
  pkg/v1/tkg/test/tkgctl/shared/addons.go
  pkg/v1/tkg/test/tkgctl/shared/autoscaler.go
  pkg/v1/tkg/test/tkgctl/shared/ceip.go
  pkg/v1/tkg/test/tkgctl/shared/e2e_common.go
  pkg/v1/tkg/test/tkgctl/shared/mhc.go
  pkg/v1/tkg/test/tkgctl/shared/scale.go
  pkg/v1/tkg/test/tkgctl/shared/upgrade.go
  pkg/v1/tkg/tkgconfigbom/bom.go
  pkg/v1/tkg/tkgconfighelper/validate.go
  pkg/v1/tkg/tkgctl/constants.go
  pkg/v1/tkg/tkgpackageclient/package_install.go
  pkg/v1/tkg/tkgpackageclient/package_update.go
  pkg/v1/tkg/tkgpackageclient/registry_secret_update.go
  pkg/v1/tkg/tkgpackageclient/repository_add.go
  pkg/v1/tkg/tkgpackagedatamodel/constants.go
  pkg/v1/tkg/tkgpackagedatamodel/types.go
  pkg/v1/tkg/utils/common.go
Labels: ok-to-merge, cla-not-required

#1402 Fix the ip_family unit tests failed due to capv version bump
  pkg/v1/providers/tests/unit/ip_family_test.go
Labels: area/cli, kind/failing-test, ok-to-merge

#1384 Don't skip cert validation on `tanzu [management-]cluster kubeconfig get`
  cmd/cli/plugin/managementcluster/kubeconfig_get.go
  pkg/v1/tkg/client/get_cluster_pinniped_info.go
  pkg/v1/tkg/client/get_cluster_pinniped_info_test.go
Labels: area/auth, kind/bug, ok-to-merge, cla-not-required, area/iam

#1375 Change TMC IAM permissions config var to `DISABLE_TMC_CLOUD_PERMISSIONS`
  pkg/v1/providers/config_default.yaml
  pkg/v1/tkg/aws/client.go
  pkg/v1/tkg/aws/client_test.go
  pkg/v1/tkg/aws/fixtures/cloudformation-default.yaml
  pkg/v1/tkg/aws/fixtures/cloudformation-tmc-disabled.yaml
  pkg/v1/tkg/client/config_permission.go
  pkg/v1/tkg/constants/config_variables.go
Labels: ok-to-merge, cla-not-required

#1404 Updating version tag used for BOM retrieval to v0.14.0
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#1405 Updating version tag used for BOM retrieval to v0.15.0-dev
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#1393 Fix error/warning displayed when CLIPlugin CRD is not installed with `tanzu plugin` commands
  pkg/v1/cli/discovery/kubernetes.go
  pkg/v1/cli/discovery/kubernetes_test.go
  pkg/v1/tkg/clusterclient/clusterclient.go
  pkg/v1/tkg/fakes/clusterclient.go
  pkg/v1/tkg/fakes/helper/fakeobjectcreater.go
  pkg/v1/tkg/fakes/helper/types.go
Labels: kind/bug, ok-to-merge, cla-not-required

#1378 clustergen model updates
  pkg/v1/providers/tests/clustergen/param_models/cluster_aws.model
  pkg/v1/providers/tests/clustergen/param_models/cluster_azure.model
  pkg/v1/providers/tests/clustergen/param_models/cluster_optional.model
Labels: CI, ok-to-merge, cla-not-required, area/dx

#1293 Adding management cluster upgrade version compatibility validation
  pkg/v1/tkg/client/upgrade_region.go
  pkg/v1/tkg/client/upgrade_region_test.go
  pkg/v1/tkg/clusterclient/clusterclient.go
Labels: area/cli, kind/bug, ok-to-merge, cla-not-required

#1417 Temporarily exclude UI generated bindata from Git diff on verify step
  hack/verify-dirty.sh
Labels: ok-to-merge, area/ui

#1398 Fix validation for autoscaler deployment
  pkg/v1/tkg/client/cluster.go
  pkg/v1/tkg/client/create_test.go
Labels: ok-to-merge, cla-not-required

#1409 add CAPD integration tests for telemetry
  pkg/v1/tkg/test/tkgctl/docker/docker_ceip_test.go
  pkg/v1/tkg/test/tkgctl/shared/ceip.go
Labels: ok-to-merge, cla-not-required

#1368 GH workflow for misspell
  .github/workflows/misspell.yaml
  Makefile
  docs/api-machinery/guide/README.md
  docs/cli/design_stage_styleguide_checklist.md
  docs/cli/plugin_implementation_guide.md
  docs/cli/style_guide.md
  docs/cli/tkgctl/upgrade.md
  hack/check/.misspellignore
  hack/check/misspell.sh
  pkg/v1/providers/config_default.yaml
  pkg/v1/providers/tests/clustergen/diffcluster/example/original.yaml
  pkg/v1/tkg/web/src/app/views/landing/aws-wizard/provider-step/aws-provider-step.component.html
  pkg/v1/tkg/web/src/app/views/landing/azure-wizard/provider-step/azure-provider-step.component.ts
  pkg/v1/tkg/web/src/app/views/landing/vsphere-wizard/provider-step/vsphere-provider-step.component.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/components/steps/network-step/network-step.component.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/components/steps/os-image-step/os-image-step.component.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/constants/validation.constants.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/validation/validation.service.ts
Labels: area/testing, kind/cleanup, ok-to-merge

#1427 Kickstart UI: refactors OsImageComponent to use generics. Also fixes a few tests.
  pkg/v1/tkg/web/src/app/views/landing/aws-wizard/os-image-step/aws-os-image-step.component.ts
  pkg/v1/tkg/web/src/app/views/landing/aws-wizard/provider-step/aws-provider-step.component.spec.ts
  pkg/v1/tkg/web/src/app/views/landing/azure-wizard/os-image-step/azure-os-image-step.component.ts
  pkg/v1/tkg/web/src/app/views/landing/vsphere-wizard/os-image-step/vsphere-os-image-step.component.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/components/steps/os-image-step/os-image-step.component.html
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/components/steps/os-image-step/os-image-step.component.spec.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/components/steps/os-image-step/os-image-step.component.ts
Labels: kind/cleanup, ok-to-merge, area/ux, area/ui

#1412 Handle `context-aware-cli-for-plugin` feature flag with `tanzu init` …
  pkg/v1/cli/command/core/init.go
  pkg/v1/cli/command/core/update.go
Labels: area/cli, kind/bug, ok-to-merge, cla-not-required
