Repository vmware-tanzu/tanzu-framework, pull requests merged in 2022-03, with the labels that each got.

#1733 Bump kapp-controller's package to 0.30.1
  pkg/v1/providers/vendir.lock.yml
  pkg/v1/providers/vendir.yml
  pkg/v1/providers/ytt/02_addons/kapp-controller/kapp-controller_addon_data.lib.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.30.1/bundle/config/overlays/change-namespace.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.30.1/bundle/config/overlays/update-configmap.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.30.1/bundle/config/overlays/update-crds.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.30.1/bundle/config/overlays/update-deployment.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.30.1/bundle/config/upstream/kapp-controller.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.30.1/bundle/config/values.star
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.30.1/bundle/config/values.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/kapp-controller.lib.yaml
Labels: area/addons, ok-to-merge, cla-not-required

#1751 Update BOM retrieval version to v0.18.0
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#1752 Update BOM retrieval version to v0.19.0-dev
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#1703 Add tkr-infra-machine-webhook packages for all providers in management package repository
  packages/kbld-config.yaml
  packages/management/tkr-aws-machine-webhook/Makefile
  packages/management/tkr-aws-machine-webhook/README.md
  packages/management/tkr-aws-machine-webhook/bundle/config/overlays/overlay-infra-machine-webhook.yaml
  packages/management/tkr-aws-machine-webhook/bundle/config/upstream/certificates.yaml
  packages/management/tkr-aws-machine-webhook/bundle/config/upstream/service.yaml
  packages/management/tkr-aws-machine-webhook/bundle/config/upstream/tkr-infra-machine-webhook-deployment.yaml
  packages/management/tkr-aws-machine-webhook/bundle/config/upstream/webhook.yaml
  packages/management/tkr-aws-machine-webhook/bundle/config/values.yaml
  packages/management/tkr-aws-machine-webhook/bundle/vendir.lock.yml
  packages/management/tkr-aws-machine-webhook/bundle/vendir.yml
  packages/management/tkr-aws-machine-webhook/metadata.yaml
  packages/management/tkr-aws-machine-webhook/package.yaml
  packages/management/tkr-azure-machine-webhook/Makefile
  packages/management/tkr-azure-machine-webhook/README.md
  packages/management/tkr-azure-machine-webhook/bundle/config/overlays/overlay-infra-machine-webhook.yaml
  packages/management/tkr-azure-machine-webhook/bundle/config/upstream/certificates.yaml
  packages/management/tkr-azure-machine-webhook/bundle/config/upstream/service.yaml
  packages/management/tkr-azure-machine-webhook/bundle/config/upstream/tkr-infra-machine-webhook-deployment.yaml
  packages/management/tkr-azure-machine-webhook/bundle/config/upstream/webhook.yaml
  packages/management/tkr-azure-machine-webhook/bundle/config/values.yaml
  packages/management/tkr-azure-machine-webhook/bundle/vendir.lock.yml
  packages/management/tkr-azure-machine-webhook/bundle/vendir.yml
  packages/management/tkr-azure-machine-webhook/metadata.yaml
  packages/management/tkr-azure-machine-webhook/package.yaml
  packages/management/tkr-docker-machine-webhook/Makefile
  packages/management/tkr-docker-machine-webhook/README.md
  packages/management/tkr-docker-machine-webhook/bundle/config/overlays/overlay-infra-machine-webhook.yaml
  packages/management/tkr-docker-machine-webhook/bundle/config/upstream/certificates.yaml
  packages/management/tkr-docker-machine-webhook/bundle/config/upstream/service.yaml
  packages/management/tkr-docker-machine-webhook/bundle/config/upstream/tkr-infra-machine-webhook-deployment.yaml
  packages/management/tkr-docker-machine-webhook/bundle/config/upstream/webhook.yaml
  packages/management/tkr-docker-machine-webhook/bundle/config/values.yaml
  packages/management/tkr-docker-machine-webhook/bundle/vendir.lock.yml
  packages/management/tkr-docker-machine-webhook/bundle/vendir.yml
  packages/management/tkr-docker-machine-webhook/metadata.yaml
  packages/management/tkr-docker-machine-webhook/package.yaml
  packages/management/tkr-vsphere-machine-webhook/Makefile
  packages/management/tkr-vsphere-machine-webhook/README.md
  packages/management/tkr-vsphere-machine-webhook/bundle/config/overlays/overlay-infra-machine-webhook.yaml
  packages/management/tkr-vsphere-machine-webhook/bundle/config/upstream/certificates.yaml
  packages/management/tkr-vsphere-machine-webhook/bundle/config/upstream/service.yaml
  packages/management/tkr-vsphere-machine-webhook/bundle/config/upstream/tkr-infra-machine-webhook-deployment.yaml
  packages/management/tkr-vsphere-machine-webhook/bundle/config/upstream/webhook.yaml
  packages/management/tkr-vsphere-machine-webhook/bundle/config/values.yaml
  packages/management/tkr-vsphere-machine-webhook/bundle/vendir.lock.yml
  packages/management/tkr-vsphere-machine-webhook/bundle/vendir.yml
  packages/management/tkr-vsphere-machine-webhook/metadata.yaml
  packages/management/tkr-vsphere-machine-webhook/package.yaml
  packages/package-values.yaml
Labels: kind/feature, ok-to-merge, cla-not-required, area/tkr, area/packages

#1728 change addons-manager package name to v2
  packages/kbld-config.yaml
  packages/management/addons-manager-v2/Makefile
  packages/management/addons-manager-v2/README.md
  packages/management/addons-manager-v2/bundle/config/overlays/overlay-addons-manager.yaml
  packages/management/addons-manager-v2/bundle/config/upstream/addons-manager.yaml
  packages/management/addons-manager-v2/bundle/config/upstream/antreaconfigs.yaml
  packages/management/addons-manager-v2/bundle/config/upstream/calicoconfigs.yaml
  packages/management/addons-manager-v2/bundle/config/upstream/clusterbootstraps.yaml
  packages/management/addons-manager-v2/bundle/config/upstream/clusterbootstraptemplates.yaml
  packages/management/addons-manager-v2/bundle/config/upstream/kappcontrollerconfigs.yaml
  packages/management/addons-manager-v2/bundle/config/values.yaml
  packages/management/addons-manager-v2/bundle/vendir.lock.yml
  packages/management/addons-manager-v2/bundle/vendir.yml
  packages/management/addons-manager-v2/metadata.yaml
  packages/management/addons-manager-v2/package.yaml
  packages/package-values.yaml
Labels: area/addons, ok-to-merge, cla-not-required

#1760 postNodeUpgrade won't upgrade standard-package-repo on tce
  pkg/v1/tkg/client/upgrade_cluster.go
Labels: ok-to-merge, cla-not-required

#1554 Add CPIConfig spec and CRD for vsphere-cpi package.
  PROJECT
  addons/controllers/cpi/cpiconfig_const.go
  addons/controllers/cpi/cpiconfig_controller.go
  addons/controllers/cpi/cpiconfig_datavalues.go
  addons/controllers/cpi/cpiconfig_utils.go
  addons/controllers/cpiconfig_controller_test.go
  addons/controllers/suite_test.go
  addons/controllers/testdata/test-cpi-non-paravirtual.yaml
  addons/controllers/testdata/test-cpi-paravirtual.yaml
  addons/go.mod
  addons/go.sum
  addons/pkg/constants/constants.go
  addons/pkg/util/cluster_variable_util.go
  addons/pkg/util/cluster_variable_util_test.go
  apis/cpi/v1alpha1/cpiconfig_types.go
  apis/cpi/v1alpha1/groupversion_info.go
  apis/cpi/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/cpi.tanzu.vmware.com_cpiconfigs.yaml
  config/crd/kustomization.yaml
  config/rbac/cpiconfig_editor_role.yaml
  config/rbac/cpiconfig_viewer_role.yaml
  config/samples/cpi_v1alpha1_cpiconfig.yaml
Labels: ok-to-merge, cla-not-required

#1759 Remove double compile of core from builder
  pkg/v1/builder/command/cli.go
Labels: ok-to-merge, cla-not-required

#1679 Add more reconciliation logic to clusterbootstrap controller for cluster creation
  addons/controllers/antrea/antreaconfig_controller.go
  addons/controllers/clusterbootstrap_controller.go
  addons/controllers/clusterbootstrap_controller_test.go
  addons/controllers/kapp-controller/kappcontrollerconfig_controller.go
  addons/controllers/kappcontrollerconfig_controller_test.go
  addons/controllers/suite_test.go
  addons/controllers/testdata/fake_package_crd.yaml
  addons/controllers/testdata/test-cluster-bootstrap-1.yaml
  addons/controllers/testdata/test-cluster-bootstrap-2.yaml
  addons/pkg/config/config.go
  addons/pkg/constants/constants.go
  addons/pkg/util/addon_util.go
Labels: area/addons, ok-to-merge, cla-not-required

#1687 Adds support for webhooks using self generated certificates
  addons/controllers/certificates_test.go
  addons/controllers/suite_test.go
  addons/controllers/testdata/test-webhook-manifests.yaml
  addons/go.mod
  addons/go.sum
  go.mod
  go.sum
  pkg/v1/webhooks/certificates.go
  pkg/v1/webhooks/certificates_test.go
  pkg/v1/webhooks/doc.go
Labels: ok-to-merge, cla-not-required

#1784 Reduce cyclomatic complexity in clusterbootstrap_controller.go
  addons/controllers/clusterbootstrap_controller.go
Labels: ok-to-merge, cla-not-required

#1788 [v0.11.2] Update version for BOM retrieval to v0.11.2
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge

#1790 Remove unused field from cpi addon data
  pkg/v1/providers/ytt/02_addons/cpi/cpi_addon_data.lib.yaml
Labels: ok-to-merge, cla-not-required, area/lcm

#1783 Add the watch for ClusterBootstrap CR which was dropped erroneously
  addons/controllers/clusterbootstrap_controller.go
Labels: ok-to-merge, cla-not-required

#1525 Add cluster audit logging
  pkg/v1/tkg/constants/files.go
  pkg/v1/tkg/log/interface.go
  pkg/v1/tkg/log/writer.go
  pkg/v1/tkg/tkgconfigpaths/client.go
  pkg/v1/tkg/tkgconfigpaths/filepaths.go
  pkg/v1/tkg/tkgctl/create_cluster.go
  pkg/v1/tkg/tkgctl/delete_cluster.go
  pkg/v1/tkg/tkgctl/delete_region.go
  pkg/v1/tkg/tkgctl/helpers.go
  pkg/v1/tkg/tkgctl/init.go
  pkg/v1/tkg/tkgctl/upgrade_cluster.go
  pkg/v1/tkg/tkgctl/upgrade_region.go
Labels: ok-to-merge, cla-not-required, area/lcm

#1741 Expose NSX-T T1 router configuration for NSX ALB
  pkg/v1/providers/config_default.yaml
  pkg/v1/providers/tests/clustergen/param_models/cluster_vsphere.model
  pkg/v1/providers/ytt/02_addons/avi/ako_operator_secret.yaml
  pkg/v1/providers/ytt/03_customizations/02_avi/ako-deployment.lib.yaml
Labels: ok-to-merge, cla-not-required, area/networking

#1800 move back to build flag edition specification
  apis/cli/v1alpha1/zz_generated.deepcopy.go
  apis/config/v1alpha1/clientconfig_types.go
  apis/config/v1alpha1/zz_generated.deepcopy.go
  apis/run/v1alpha1/zz_generated.deepcopy.go
  apis/run/v1alpha2/zz_generated.deepcopy.go
  common.mk
  pkg/v1/buildinfo/buildvar.go
  pkg/v1/config/clientconfig.go
  pkg/v1/providers/client/manifest/providers_embeded.go
  pkg/v1/providers/client/manifest/providers_skipped.go
  pkg/v1/sdk/capabilities/controllers/suite_test.go
  pkg/v1/sdk/features/controllers/suite_test.go
  pkg/v1/tkg/aws/ini/fuzz.go
Labels: area/release, kind/bug, ok-to-merge, cla-not-required

#1802 UI: remove node server mock certificate and key
  pkg/v1/tkg/web/node-server/main.js
  pkg/v1/tkg/web/node-server/package.json
  pkg/v1/tkg/web/node-server/src/conf/appConfig.js
  pkg/v1/tkg/web/node-server/src/conf/paths.js
  pkg/v1/tkg/web/node-server/src/www.js
  pkg/v1/tkg/web/node-server/support/cert.pem
  pkg/v1/tkg/web/node-server/support/key.pem
Labels: ok-to-merge, area/ui, cla-not-required

#1742 fix local docker registry port
  Makefile
  hack/packages/scripts/package-utils.sh
Labels: ok-to-merge, cla-not-required

#1780 Add pause mechanism to ClusterBootstrap
  addons/controllers/clusterbootstrap_controller.go
  addons/controllers/clusterbootstrap_controller_test.go
  addons/controllers/testdata/test-cluster-bootstrap-3.yaml
  apis/run/v1alpha3/clusterbootstraptemplate_types.go
  config/crd/bases/run.tanzu.vmware.com_clusterbootstraps.yaml
  config/crd/bases/run.tanzu.vmware.com_clusterbootstraptemplates.yaml
Labels: area/addons, ok-to-merge

#1736 update TKG CAPV version to v1.1.0
  addons/controllers/cpi/cpiconfig_utils.go
  addons/controllers/cpiconfig_controller_test.go
  addons/controllers/suite_test.go
  addons/go.mod
  addons/go.sum
  go.mod
  go.sum
  pkg/v1/providers/config.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/cluster-template-definition-dev-windows.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/cluster-template-definition-dev.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/cluster-template-definition-prod.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/infrastructure-components-supervisor.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/infrastructure-components.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/metadata.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/ytt/base-template.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/ytt/overlay-windows.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/ytt/overlay.yaml
  pkg/v1/providers/tests/clustergen/param_models/cluster_optional.model
  pkg/v1/providers/tests/clustergen/param_models/cluster_vsphere.model
  pkg/v1/providers/tests/unit/ip_family_test.go
  pkg/v1/tkg/client/client_suite_test.go
  pkg/v1/tkg/client/machine_deployment.go
  pkg/v1/tkg/client/machine_deployment_test.go
  pkg/v1/tkg/client/upgrade_cluster.go
  pkg/v1/tkg/client/upgrade_cluster_test.go
  pkg/v1/tkg/client/validate.go
  pkg/v1/tkg/clusterclient/clusterclient.go
  pkg/v1/tkg/clusterclient/credentials.go
  pkg/v1/tkg/clusterclient/templates.go
  pkg/v1/tkg/fakes/helper/fakeobjectcreater.go
Labels: ok-to-merge, cla-not-required

#1705 Add script to download and install Tanzu Framework CLI
  docs/cli/getting-started.md
  hack/fetch-install-tf.sh
Labels: ok-to-merge, cla-not-required

#1804 Fix the imgpkg registy custom certificate validation and validation skipping issue
  pkg/v1/tkr/controllers/source/tkr_source_controller.go
  pkg/v1/tkr/pkg/registry/client.go
Labels: area/cli, kind/bug, ok-to-merge, cla-not-required

#1818 fix addons-manager-v2 RBAC
  packages/management/addons-manager-v2/bundle/config/upstream/addons-manager.yaml
Labels: ok-to-merge, cla-not-required

#1815 Cherry pick alb fixes for 0.11
  pkg/v1/providers/config_default.yaml
  pkg/v1/providers/tests/clustergen/param_models/cluster_vsphere.model
  pkg/v1/providers/ytt/02_addons/avi/ako_operator_secret.yaml
  pkg/v1/providers/ytt/03_customizations/02_avi/ako-deployment.lib.yaml
  pkg/v1/providers/ytt/03_customizations/02_avi/ako-operator-deployment.lib.yaml
Labels: ok-to-merge, cla-not-required

#1822 [release-0.11]: Cherry-pick 1302: Fix panic on creating nodepools
  pkg/v1/tkg/client/machine_deployment.go
Labels: area/release, ok-to-merge, cla-not-required

#1819 Fix node pool delete logic
  pkg/v1/tkg/client/machine_deployment.go
  pkg/v1/tkg/client/machine_deployment_test.go
Labels: ok-to-merge, cla-not-required

#1823 Bumps cobra from `v1.3.0` to `v1.4.0`
  go.mod
  go.sum
Labels: ok-to-merge, cla-not-required

#1826 Update DoSetMachineDeployment to fix np name issue
  pkg/v1/tkg/client/machine_deployment.go
  pkg/v1/tkg/client/machine_deployment_test.go
Labels: ok-to-merge, cla-not-required, area/lcm

#1829 addons/pinniped/post-deploy: bump dependencies for Kube v0.23.0
  addons/pinniped/post-deploy/go.mod
  addons/pinniped/post-deploy/go.sum
  addons/pinniped/post-deploy/main.go
  addons/pinniped/post-deploy/pkg/configure/concierge/concierge.go
  addons/pinniped/post-deploy/pkg/configure/concierge/concierge_test.go
  addons/pinniped/post-deploy/pkg/configure/configure.go
  addons/pinniped/post-deploy/pkg/configure/configure_test.go
  addons/pinniped/post-deploy/pkg/configure/supervisor/supervisor.go
  addons/pinniped/post-deploy/pkg/configure/supervisor/supervisor_test.go
Labels: ok-to-merge, cla-not-required

#1813 Bump Cluster API to v1.1.3
  addons/go.mod
  addons/go.sum
  go.mod
  go.sum
  pkg/v1/providers/bootstrap-kubeadm/v1.1.3/bootstrap-components.yaml
  pkg/v1/providers/bootstrap-kubeadm/v1.1.3/metadata.yaml
  pkg/v1/providers/cluster-api/v1.1.3/core-components.yaml
  pkg/v1/providers/cluster-api/v1.1.3/metadata.yaml
  pkg/v1/providers/config.yaml
  pkg/v1/providers/control-plane-kubeadm/v1.1.3/control-plane-components.yaml
  pkg/v1/providers/control-plane-kubeadm/v1.1.3/metadata.yaml
  pkg/v1/providers/infrastructure-docker/v1.1.3/cluster-template-definition-dev.yaml
  pkg/v1/providers/infrastructure-docker/v1.1.3/cluster-template-definition-prod.yaml
  pkg/v1/providers/infrastructure-docker/v1.1.3/infrastructure-components.yaml
  pkg/v1/providers/infrastructure-docker/v1.1.3/metadata.yaml
  pkg/v1/providers/infrastructure-docker/v1.1.3/ytt/base-template.yaml
  pkg/v1/providers/infrastructure-docker/v1.1.3/ytt/overlay.yaml
  pkg/v1/providers/tests/go.mod
  pkg/v1/providers/tests/go.sum
Labels: ok-to-merge, cla-not-required, area/lcm

#1834 Remove CNI selection using cluster variable
  addons/controllers/clusterbootstrap_controller.go
  addons/controllers/clusterbootstrap_controller_test.go
  addons/controllers/suite_test.go
  addons/controllers/testdata/test-cluster-bootstrap-1.yaml
  addons/controllers/testdata/test-cluster-bootstrap-3.yaml
  addons/main.go
  addons/pkg/config/config.go
  addons/pkg/constants/constants.go
  apis/run/v1alpha3/clusterbootstraptemplate_types.go
  apis/run/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/run.tanzu.vmware.com_clusterbootstraps.yaml
  config/crd/bases/run.tanzu.vmware.com_clusterbootstraptemplates.yaml
Labels: ok-to-merge, cla-not-required

#1809 Feature gate ClusterBootstrap and AddonConfig controllers
  addons/controllers/clusterbootstrap_controller_test.go
  addons/controllers/suite_test.go
  addons/main.go
  addons/pkg/constants/constants.go
  packages/management/addons-manager-v2/bundle/config/overlays/feature-gate-clusterbootstrap.yaml
  packages/management/addons-manager-v2/bundle/config/overlays/overlay-addons-manager.yaml
  packages/management/addons-manager-v2/bundle/config/upstream/addons-manager.yaml
  packages/management/addons-manager-v2/bundle/config/upstream/cni.tanzu.vmware.com_antreaconfigs.yaml
  packages/management/addons-manager-v2/bundle/config/upstream/cni.tanzu.vmware.com_calicoconfigs.yaml
  packages/management/addons-manager-v2/bundle/config/upstream/cpi.tanzu.vmware.com_cpiconfigs.yaml
  packages/management/addons-manager-v2/bundle/config/upstream/run.tanzu.vmware.com_clusterbootstraps.yaml
  packages/management/addons-manager-v2/bundle/config/upstream/run.tanzu.vmware.com_clusterbootstraptemplates.yaml
  packages/management/addons-manager-v2/bundle/config/upstream/run.tanzu.vmware.com_kappcontrollerconfigs.yaml
  packages/management/addons-manager-v2/bundle/config/values.yaml
  packages/management/addons-manager-v2/bundle/vendir.lock.yml
  packages/management/addons-manager-v2/bundle/vendir.yml
  pkg/v1/providers/ytt/02_addons/tanzu-addons-manager/tanzu-addons-manager_addon_data.lib.yaml
Labels: ok-to-merge, cla-not-required

#1723 Fix the issue where upgrade operation fails for vSphere cluster if vSphere password contains single quote(')
  pkg/v1/tkg/client/validate.go
  pkg/v1/tkg/clusterclient/clusterclient.go
  pkg/v1/tkg/clusterclient/clusterclient_test.go
  pkg/v1/tkg/clusterclient/credentials.go
  pkg/v1/tkg/clusterclient/templates.go
  pkg/v1/tkg/fakes/clusterclient.go
Labels: area/cli, kind/bug, ok-to-merge, cla-not-required

#1838 Rename CPIConfig to VSphereCPIConfig.
  addons/controllers/cpi/vspherecpiconfig_const.go
  addons/controllers/cpi/vspherecpiconfig_controller.go
  addons/controllers/cpi/vspherecpiconfig_datavalues.go
  addons/controllers/cpi/vspherecpiconfig_utils.go
  addons/controllers/suite_test.go
  addons/controllers/testdata/test-vsphere-cpi-non-paravirtual.yaml
  addons/controllers/testdata/test-vsphere-cpi-paravirtual.yaml
  addons/controllers/vspherecpiconfig_controller_test.go
  addons/main.go
  apis/cpi/v1alpha1/vspherecpiconfig_types.go
  apis/cpi/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/cpi.tanzu.vmware.com_vspherecpiconfigs.yaml
  config/rbac/vspherecpiconfig_editor_role.yaml
  config/rbac/vspherecpiconfig_viewer_role.yaml
  config/samples/cpi_v1alpha1_vspherecpiconfig.yaml
Labels: ok-to-merge, cla-not-required

#1843 Update BOM retrieval version to v0.19.0
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#1844 Update BOM retrieval version to v0.20.0-dev
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#1847 Run make modules.
  pkg/v1/providers/tests/go.mod
  pkg/v1/providers/tests/go.sum
Labels: ok-to-merge, cla-not-required

#1775 Fix issues while deploying management packages into bootstrap and management cluster
  pkg/v1/providers/config_default.yaml
  pkg/v1/providers/ytt/02_addons/management-packages/add_management_package_repo.yaml
  pkg/v1/tkg/client/config.go
  pkg/v1/tkg/client/management_components.go
  pkg/v1/tkg/constants/cluster_internal.go
  pkg/v1/tkg/constants/config_variables.go
  pkg/v1/tkg/managementcomponents/management_component_install.go
Labels: ok-to-merge, cla-not-required, area/lcm

#1842 Register CPI schema and update addons-manager-v2 package
  addons/main.go
  packages/management/addons-manager-v2/bundle/config/overlays/feature-gate-clusterbootstrap.yaml
  packages/management/addons-manager-v2/bundle/config/upstream/cpi.tanzu.vmware.com_vspherecpiconfigs.yaml
  packages/management/addons-manager-v2/bundle/vendir.lock.yml
  packages/management/addons-manager-v2/bundle/vendir.yml
Labels: ok-to-merge, cla-not-required

#1840 Patch kube-vip for tkg 1.6
  pkg/v1/tkg/client/kubevip_update_helper.go
  pkg/v1/tkg/client/upgrade_cluster_test.go
Labels: ok-to-merge, cla-not-required

#1713 Handle TKR upgrade in ClusterBootstrap controller
  addons/controllers/clusterbootstrap_controller.go
  addons/controllers/clusterbootstrap_controller_test.go
  addons/controllers/testdata/test-cluster-bootstrap-1.yaml
Labels: area/addons, ok-to-merge, cla-not-required

#1836 Set caching location for golangci-lint
  .github/workflows/main.yaml
Labels: ok-to-merge, cla-not-required

#1853 Fix upgrade issue when latest TKR is passed on already upgrade cluster
  cmd/cli/plugin/cluster/upgrade.go
  cmd/cli/plugin/cluster/upgrade_test.go
Labels: ok-to-merge, cla-not-required

#1841 Added validation to set Azure Client Secret
  pkg/v1/tkg/client/upgrade_region.go
  pkg/v1/tkg/client/utils.go
  pkg/v1/tkg/client/validate_upgrade.go
  pkg/v1/tkg/client/validate_upgrade_test.go
Labels: ok-to-merge, cla-not-required

#1873 [release-0.11] Cherry-pick #1819 #1826: Fix node pool delete logic, Update DoSetMachineDeployment to fix np name issue
  pkg/v1/tkg/client/machine_deployment.go
  pkg/v1/tkg/client/machine_deployment_test.go
Labels: area/release, ok-to-merge, cla-not-required

#1875 [release-0.11] Update version for BOM retrieval to v0.11.3
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#1803 Adds function to continuously manage webhook TLS certificates
  addons/controllers/suite_test.go
  addons/controllers/webhooks_test.go
  pkg/v1/webhooks/certificates.go
  pkg/v1/webhooks/certificates_test.go
  pkg/v1/webhooks/webhooks.go
Labels: ok-to-merge

#1878 Ensure no_proxy entries are sorted
  pkg/v1/providers/ytt/lib/helpers.star
Labels: CI, area/testing, ok-to-merge, cla-not-required

#1868 Reconcile ProviderServiceAccount for VSphereCPIConfig paravirtual mode.
  addons/controllers/cpi/vspherecpiconfig_const.go
  addons/controllers/cpi/vspherecpiconfig_controller.go
  addons/controllers/cpi/vspherecpiconfig_utils.go
  addons/controllers/vspherecpiconfig_controller_test.go
  apis/cpi/v1alpha1/vspherecpiconfig_types.go
  config/crd/bases/cpi.tanzu.vmware.com_vspherecpiconfigs.yaml
  packages/management/addons-manager-v2/bundle/config/upstream/addons-manager.yaml
Labels: ok-to-merge, cla-not-required

#1870 fix addons-manager-v2 sha
  packages/package-values.yaml
Labels: ok-to-merge, cla-not-required

#1874 Add kube-vip field to TKR.spec.kubernetes
  apis/run/v1alpha1/conversion.go
  apis/run/v1alpha1/conversion_test.go
  apis/run/v1alpha3/tanzukubernetesrelease_types.go
  apis/run/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/run.tanzu.vmware.com_tanzukubernetesreleases.yaml
Labels: ok-to-merge, cla-not-required, area/tkr, area/lcm

#1884 Initial pinniped config controller commit
  addons/pinniped/config-controller/Dockerfile
  addons/pinniped/config-controller/README.md
  addons/pinniped/config-controller/constants/constants.go
  addons/pinniped/config-controller/controllers/controller_test.go
  addons/pinniped/config-controller/controllers/controllers.go
  addons/pinniped/config-controller/controllers/handlers.go
  addons/pinniped/config-controller/controllers/suite_test.go
  addons/pinniped/config-controller/deployment.yaml
  addons/pinniped/config-controller/go.mod
  addons/pinniped/config-controller/go.sum
  addons/pinniped/config-controller/hack/check.sh
  addons/pinniped/config-controller/hack/lint.sh
  addons/pinniped/config-controller/hack/run.sh
  addons/pinniped/config-controller/hack/test.sh
  addons/pinniped/config-controller/main.go
  addons/pinniped/config-controller/utils/utils.go
  addons/pinniped/hack/test.sh
Labels: area/addons, ok-to-merge, cla-not-required

#1860 [release-0.11] Fix upgrade when latest TKR is passed on already upgrade cluster
  cmd/cli/plugin/cluster/upgrade.go
  cmd/cli/plugin/cluster/upgrade_test.go
Labels: ok-to-merge, cla-not-required, area/lcm

#1480 Configure vSphere cpi to exclude kube-vip ip
  pkg/v1/providers/tests/unit/avi_test.go
  pkg/v1/providers/tests/unit/ip_family_test.go
  pkg/v1/providers/tests/unit/windows_test.go
  pkg/v1/providers/vendir.lock.yml
  pkg/v1/providers/vendir.yml
  pkg/v1/providers/ytt/02_addons/cpi/cpi_addon_data.lib.yaml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.5/bundle/config/overlays/add-secret.yaml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.5/bundle/config/overlays/update-config.yaml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.5/bundle/config/overlays/update-daemonset.yaml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.5/bundle/config/overlays/update-secret.yaml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.5/bundle/config/schema.yaml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.5/bundle/config/upstream/vsphere-cpi/01-rbac.yaml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.5/bundle/config/upstream/vsphere-cpi/02-config.yaml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.5/bundle/config/upstream/vsphere-cpi/03-secret.yaml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.5/bundle/config/upstream/vsphere-cpi/04-daemonset.yaml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.5/bundle/config/values.star
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.5/bundle/config/values.yaml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.5/bundle/config/vsphereconf.lib.txt
  pkg/v1/providers/ytt/vendir/vsphere_cpi/vsphere_cpi.lib.yaml
Labels: area/plugin, ok-to-merge, cla-not-required, orange

#1883 [release-0.11 cherrypick] Fixes for airgap custom certificate issues
  pkg/v1/providers/vendir.lock.yml
  pkg/v1/providers/vendir.yml
  pkg/v1/providers/ytt/02_addons/kapp-controller/kapp-controller_addon_data.lib.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.30.1/bundle/config/overlays/change-namespace.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.30.1/bundle/config/overlays/update-configmap.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.30.1/bundle/config/overlays/update-crds.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.30.1/bundle/config/overlays/update-deployment.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.30.1/bundle/config/upstream/kapp-controller.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.30.1/bundle/config/values.star
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.30.1/bundle/config/values.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/kapp-controller.lib.yaml
  pkg/v1/tkr/controllers/source/tkr_source_controller.go
  pkg/v1/tkr/pkg/registry/client.go
Labels: ok-to-merge, cla-not-required

#1892 Add Makefile target to generate the default pinniped addon secret
  Makefile
  addons/pinniped/config-controller/README.md
  addons/pinniped/config-controller/hack/check.sh
  addons/pinniped/config-controller/hack/generate-package-secret.sh
  addons/pinniped/config-controller/hack/generate-package-secret.test.sh
  addons/pinniped/config-controller/hack/ytt/default-package-secret.yaml
  addons/pinniped/config-controller/hack/ytt/schema.yaml
  addons/pinniped/config-controller/hack/ytt/values.yaml
Labels: area/addons, ok-to-merge, cla-not-required

#1911 [release-0.11] Cherry-pick: Added validation to set Azure Client Secret (#1841)
  pkg/v1/tkg/client/upgrade_region.go
  pkg/v1/tkg/client/utils.go
  pkg/v1/tkg/client/validate_upgrade.go
  pkg/v1/tkg/client/validate_upgrade_test.go
Labels: ok-to-merge, cla-not-required

#1909 [release-0.11 cherry-pick]Fix the issue where upgrade operation fails for vSphere cluster if vSphere password contains single quote(')
  pkg/v1/tkg/client/validate.go
  pkg/v1/tkg/clusterclient/clusterclient.go
  pkg/v1/tkg/clusterclient/clusterclient_test.go
  pkg/v1/tkg/clusterclient/credentials.go
  pkg/v1/tkg/clusterclient/templates.go
  pkg/v1/tkg/fakes/clusterclient.go
Labels: area/cli, kind/bug, ok-to-merge, cla-not-required

#1918 Makefile/additions/controller-gen and kustomize
  Makefile
  common.mk
  config/crd/bases/cli.tanzu.vmware.com_catalogs.yaml
  config/crd/bases/cli.tanzu.vmware.com_cliplugins.yaml
  config/crd/bases/cni.tanzu.vmware.com_antreaconfigs.yaml
  config/crd/bases/cni.tanzu.vmware.com_calicoconfigs.yaml
  config/crd/bases/config.tanzu.vmware.com_clientconfigs.yaml
  config/crd/bases/config.tanzu.vmware.com_featuregates.yaml
  config/crd/bases/config.tanzu.vmware.com_features.yaml
  config/crd/bases/cpi.tanzu.vmware.com_vspherecpiconfigs.yaml
  config/crd/bases/providers.tanzu.vmware.com_templatedefinitions.yaml
  config/crd/bases/run.tanzu.vmware.com_capabilities.yaml
  config/crd/bases/run.tanzu.vmware.com_clusterbootstraps.yaml
  config/crd/bases/run.tanzu.vmware.com_clusterbootstraptemplates.yaml
  config/crd/bases/run.tanzu.vmware.com_kappcontrollerconfigs.yaml
  config/crd/bases/run.tanzu.vmware.com_osimages.yaml
  config/crd/bases/run.tanzu.vmware.com_tanzukubernetesclusters.yaml
  config/crd/bases/run.tanzu.vmware.com_tanzukubernetesreleases.yaml
  hack/tools/Makefile
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: ok-to-merge, cla-not-required

#1908 addons/pinniped/config-controller: Watch clusterbootstrap secrets
  addons/pinniped/config-controller/constants/constants.go
  addons/pinniped/config-controller/controllers/controller_test.go
  addons/pinniped/config-controller/controllers/controllers.go
  addons/pinniped/config-controller/controllers/handlers.go
  addons/pinniped/config-controller/deployment.yaml
  addons/pinniped/config-controller/go.mod
  addons/pinniped/config-controller/go.sum
  addons/pinniped/config-controller/utils/utils.go
Labels: ok-to-merge, cla-not-required

#1922 Removed slash from the custom image repo being read in as hostname
  pkg/v1/tkg/kind/client.go
  pkg/v1/tkg/kind/utils.go
  pkg/v1/tkg/kind/utils_test.go
Labels: area/cli, kind/bug, ok-to-merge, cla-not-required

#1839 Plugin description wraps if its column exceeds 80 characters
  pkg/v1/cli/component/output.go
Labels: ok-to-merge, cla-not-required

#1724 Not using WithVersion no longer causes error and allows searching for any version
  pkg/v1/sdk/capabilities/discovery/cluster_gvr.go
  pkg/v1/sdk/capabilities/discovery/cluster_test.go
  pkg/v1/sdk/capabilities/discovery/fake.go
  pkg/v1/sdk/capabilities/discovery/generate.go
  pkg/v1/sdk/capabilities/discovery/tkg/resource_test.go
Labels: ok-to-merge, cla-not-required

#1869 add antrea Egress and FlowExporter params
  pkg/v1/providers/config_default.yaml
  pkg/v1/providers/tests/clustergen/param_models/cluster_optional.model
  pkg/v1/providers/ytt/02_addons/cni/antrea/antrea_addon_data.lib.yaml
  pkg/v1/providers/ytt/lib/config_variable_association.star
Labels: kind/enhancement, ok-to-merge, cla-not-required, area/networking

#1816 Load all credential helpers
  addons/go.mod
  addons/go.sum
  addons/main.go
  cmd/cli/plugin/package/main.go
  cmd/cli/plugin/secret/main.go
  pkg/v1/tkr/main.go
Labels: ok-to-merge, cla-not-required

#1935 Use controller-gen to generate pinniped controller RBAC
  addons/pinniped/config-controller/controllers/controllers.go
  addons/pinniped/config-controller/hack/generate.sh
  addons/pinniped/config-controller/hack/run.sh
  addons/pinniped/config-controller/manifests/deployment.yaml
  addons/pinniped/config-controller/manifests/role.yaml
Labels: area/addons, ok-to-merge, cla-not-required

#1934 [release-0.11] Cherry-pick removed slash from the custom image repo being read in as hostname (#1922)
  pkg/v1/tkg/kind/client.go
  pkg/v1/tkg/kind/utils.go
  pkg/v1/tkg/kind/utils_test.go
Labels: area/cli, ok-to-merge, cla-not-required

#1941 [release-0.11 cherry-pick] Load all credential helpers (#1816)
  addons/go.sum
  addons/main.go
  cmd/cli/plugin/package/main.go
  cmd/cli/plugin/secret/main.go
  pkg/v1/tkr/main.go
Labels: area/auth, ok-to-merge, cla-not-required

#1951 Updating version tag used for BOM retrieval to v0.20.0
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#1896 Fix avi vip network auto propagate logic to
  pkg/v1/providers/ytt/02_addons/avi/ako_operator_secret.yaml
Labels: ok-to-merge, cla-not-required

#1960 [release-0.11] fix avi vip network auto propagate logic to ensure backward compatibility
  pkg/v1/providers/ytt/02_addons/avi/ako_operator_secret.yaml
Labels: ok-to-merge, cla-not-required

#1962 Kickstart UI: Resolve node-forge dependabot alerts
  pkg/v1/tkg/web/package-lock.json
  pkg/v1/tkg/web/package.json
Labels: ok-to-merge, area/ui, cla-not-required

#1949 Add edition to `tkg-metadata` configmap
  pkg/v1/providers/ytt/02_addons/metadata/add_cluster_metadata.yaml
Labels: ok-to-merge, cla-not-required

#1781 Add PackageInstallStatus controller & remote watch
  addons/controllers/addon_controller.go
  addons/controllers/clusterbootstrap_controller.go
  addons/controllers/clusterbootstrap_controller_test.go
  addons/controllers/packageinstallstatus_controller.go
  addons/controllers/packageinstallstatus_controller_test.go
  addons/controllers/packageinstallstatus_handler.go
  addons/controllers/suite_test.go
  addons/controllers/testdata/test-packageinstallstatus.yaml
  addons/go.mod
  addons/go.sum
  addons/main.go
  addons/pkg/config/config.go
  addons/pkg/constants/constants.go
  addons/pkg/types/addons.go
  addons/pkg/util/cluster_util.go
  addons/pkg/util/cluster_variable_util_test.go
  addons/pkg/util/condition_util.go
  addons/pkg/util/condition_util_test.go
  addons/pkg/util/util_suite_test.go
  apis/run/v1alpha3/clusterbootstrap_types.go
  apis/run/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/run.tanzu.vmware.com_clusterbootstraps.yaml
  pkg/v1/tkg/clusterclient/clusterclient.go
  pkg/v1/tkr/controllers/source/helper.go
  pkg/v1/tkr/controllers/source/suite_test.go
  pkg/v1/tkr/controllers/source/tkr_source_controller.go
  pkg/v1/tkr/pkg/constants/constants.go
Labels: area/addons, ok-to-merge, cla-not-required

#1937 [release-0.11] Backport capv-secret-deletion-fix-to.0.11
  addons/go.mod
  addons/go.sum
  go.mod
  go.sum
  pkg/v1/providers/config.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.0.3/cluster-template-definition-dev-windows.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.0.3/cluster-template-definition-dev.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.0.3/cluster-template-definition-prod.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.0.3/infrastructure-components.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.0.3/metadata.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.0.3/ytt/base-template.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.0.3/ytt/overlay-windows.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.0.3/ytt/overlay.yaml
  pkg/v1/providers/tests/clustergen/param_models/cluster_optional.model
  pkg/v1/providers/tests/clustergen/param_models/cluster_vsphere.model
  pkg/v1/providers/tests/unit/ip_family_test.go
Labels: ok-to-merge, cla-not-required
