Repository vmware-tanzu/tanzu-framework, pull requests merged in 2022-07, with the labels that each got.

#1737 add overide of tkr-bom with DOWNLOAD_TKRS
  hack/gen-publish-images-fromtar.sh
  hack/gen-publish-images-totar.sh
  hack/gen-publish-images.sh
Labels: ok-to-merge, cla-not-required

#2813 Make the TKR Resolver webhook to always set Cluster topology version
  pkg/v2/tkr/webhook/cluster/tkr-resolver/cluster/cluster.go
  pkg/v2/tkr/webhook/cluster/tkr-resolver/cluster/cluster_test.go
Labels: kind/bug, ok-to-merge, cla-not-required, area/tkr

#2809 Updating version tag used for BOM retrieval to v0.24.0
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: ok-to-merge, cla-not-required

#2819 Revert "Updating version tag used for BOM retrieval to v0.24.0 (#2809)"
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#2784 Pin release-notes to v0.13.0 to work with go v1.17
  .github/workflows/release.yaml
  docs/release/release-notes-gathering-process.md
Labels: area/release, ok-to-merge, cla-not-required

#2760 TKGS integration test cases
  pkg/v1/tkg/constants/cluster_internal.go
  pkg/v1/tkg/test/config/config.yaml
  pkg/v1/tkg/test/config/tkgs.yaml
  pkg/v1/tkg/test/framework/e2e_config.go
  pkg/v1/tkg/test/framework/exec/kubectl.go
  pkg/v1/tkg/test/framework/utils.go
  pkg/v1/tkg/test/tkgctl/tkgs/tkgs_suite_test.go
  pkg/v1/tkg/test/tkgctl/tkgs/tkgs_workload_cluster_test.go
  pkg/v1/tkg/tkgctl/create_cluster.go
  pkg/v1/tkg/tkgctl/create_cluster_test.go
  pkg/v1/tkg/tkgctl/helpers.go
Labels: area/testing, ok-to-merge, cla-not-required

#2649 Bump kapp-controller cli
  addons/go.mod
  addons/go.sum
  go.mod
  go.sum
Labels: ok-to-merge, cla-not-required

#2807 Object Propagation: detect and replace source namespace
  pkg/v2/object-propagation/README.md
  pkg/v2/object-propagation/config/config.go
  pkg/v2/object-propagation/propagation/config.go
  pkg/v2/object-propagation/propagation/reconciler.go
  pkg/v2/object-propagation/propagation/reconciler_test.go
  pkg/v2/object-propagation/propagation/replacer_test.go
Labels: priority/critical-urgent, ok-to-merge, cla-not-required, go, area/cc

#2816 fix bug in kapp controller data values secret generation
  addons/controllers/antrea/antreaconfig_controller.go
  addons/controllers/calico/calicoconfig_controller.go
  addons/controllers/clusterbootstrap_controller.go
  addons/controllers/clusterbootstrap_controller_test.go
  addons/controllers/cpi/vspherecpiconfig_controller.go
  addons/controllers/csi/vspherecsiconfig_controller.go
  addons/controllers/kapp-controller/kappcontrollerconfig_controller.go
  addons/pkg/util/clusterbootstrapclone/clusterbootstrapclone.go
Labels: ok-to-merge, cla-not-required

#2667 UI/CLI: Set AviControlPlaneEndpointProvider false by default
  pkg/v1/tkg/tkgconfigproviders/vsphere.go
Labels: ok-to-merge, cla-not-required

#2811 Add telemetry plugin to standalone plugins kbld config
  packages/standalone-plugins/kbld-config.yaml
Labels: ok-to-merge, cla-not-required

#2832 Allow ConfigMap get,list permission to the telemetry service account
  pkg/v1/tkg/manifest/telemetry/config-aws.yaml
  pkg/v1/tkg/manifest/telemetry/config-azure.yaml
  pkg/v1/tkg/manifest/telemetry/config-docker.yaml
  pkg/v1/tkg/manifest/telemetry/config-vsphere.yaml
  pkg/v1/tkg/manifest/telemetry/zz_generated.bindata.go
  pkg/v1/tkg/test/tkgctl/shared/ceip.go
Labels: area/cli, kind/bug, kind/failing-test, ok-to-merge, cla-not-required

#2842 Add support to delete clusterclass based clusters on TKGs
  pkg/v1/tkg/clusterclient/clusterclient.go
  pkg/v1/tkg/clusterclient/clusterclient_test.go
Labels: area/cli, kind/enhancement, kind/bug, ok-to-merge, cla-not-required

#2833 Cluster UpdatesAvailable condition message should list TKR versions
  pkg/v2/tkr/controller/tkr-status/clusterstatus/clusterstatus.go
  pkg/v2/tkr/controller/tkr-status/clusterstatus/clusterstatus_test.go
Labels: ok-to-merge, cla-not-required

#2834 Handle nil secret for KappControllerConfig
  addons/controllers/clusterbootstrap_controller.go
  addons/controllers/clusterbootstrap_controller_test.go
  addons/controllers/testdata/test-cluster-bootstrap-4.yaml
Labels: ok-to-merge, cla-not-required

#2821 Update BOM retrieval version to v0.24.0
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#2818 Updating version tag used for BOM retrieval to v0.25.0-dev
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#2781 Enable PackageInstallStatus feature in AddonsManager
  pkg/v1/tkg/managementcomponents/helper.go
  pkg/v1/tkg/managementcomponents/test/output_aws.yaml
  pkg/v1/tkg/managementcomponents/test/output_azure.yaml
  pkg/v1/tkg/managementcomponents/test/output_vsphere.yaml
  pkg/v1/tkg/managementcomponents/types.go
Labels: ok-to-merge, cla-not-required

#2845 TKGS integration test cases for dry-run use cases
  pkg/v1/tkg/test/tkgctl/tkgs/tkgs_workload_cluster_test.go
Labels: area/testing, ok-to-merge, cla-not-required

#2859 Fix management-cluster not found error during upgrade
  pkg/v1/tkg/client/upgrade_cluster.go
Labels: ok-to-merge, cla-not-required

#2745 Update cluster upgrade and available-upgrades commands to support clu…
  cmd/cli/plugin/cluster/available_upgrade.go
  cmd/cli/plugin/cluster/available_upgrade_test.go
  cmd/cli/plugin/cluster/upgrade.go
  cmd/cli/plugin/cluster/upgrade_test.go
  pkg/v2/tkr/util/sets/strings.go
  pkg/v2/tkr/util/topology/cluster.go
Labels: area/cli, kind/enhancement, ok-to-merge, cla-not-required

#2839 Fix missing tkr annotation on AWS prod cluster package based lcm
  pkg/v1/providers/infrastructure-aws/v1.2.0/yttcc/overlay.yaml
Labels: ok-to-merge, cla-not-required

#2804 Add ClusterClass based cluster creation validation check at runtime
  pkg/v1/tkg/test/tkgctl/tkgs/tkgs_workload_cluster_test.go
  pkg/v1/tkg/tkgctl/client.go
  pkg/v1/tkg/tkgctl/create_cluster.go
  pkg/v1/tkg/tkgctl/create_cluster_test.go
  pkg/v1/tkg/tkgctl/interface.go
Labels: ok-to-merge, cla-not-required

#2844 Add integration test to verify management-cluster is CC based and all packages are reconciled successfully
  pkg/v1/tkg/clusterclient/clusterclient.go
  pkg/v1/tkg/fakes/clusterclient.go
  pkg/v1/tkg/fakes/dynamicclientfactory.go
  pkg/v1/tkg/test/tkgctl/aws_cc/aws_cc_suite_test.go
Labels: area/testing, ok-to-merge, cla-not-required

#2743 add common functions to test Addon config APIs
  addons/go.sum
  go.mod
  go.sum
  pkg/v1/tkg/test/tkgctl/shared/e2e_common.go
  pkg/v1/tkg/test/tkgctl/shared/package.go
Labels: ok-to-merge, cla-not-required

#2864 add node role selector to kapp controller
  addons/controllers/kapp-controller/kappcontrollerconfig_types.go
  pkg/v1/providers/kapp-controller-values/kapp-controller_data.lib.yaml
  pkg/v1/tkg/client/test/kapp-controller-values/testcase1/output.yaml
  pkg/v1/tkg/client/test/kapp-controller-values/testcase2/output.yaml
  pkg/v1/tkg/client/test/kapp-controller-values/testcase3/output.yaml
Labels: ok-to-merge, cla-not-required

#2883 Concurrency guard addons/pkg/util.gvrHelper
  addons/pkg/util/gvr_helper.go
  addons/pkg/util/gvr_helper_test.go
Labels: ok-to-merge, cla-not-required

#2827 Clean up NSX Advanced Load Balancer(avi) related configurations
  pkg/v1/providers/config_default.yaml
Labels: kind/enhancement, area/addons, ok-to-merge

#2861 kapp controller 0.38.3 sh file update
  hack/kind/deploy_kind_with_capi_and_kapp.sh
Labels: ok-to-merge, cla-not-required

#2880 Bump kapp-controller to version 0.38.4
  pkg/v1/providers/vendir.lock.yml
  pkg/v1/providers/vendir.yml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.38.4/bundle/config/overlays/change-namespace.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.38.4/bundle/config/overlays/update-configmap.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.38.4/bundle/config/overlays/update-crds.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.38.4/bundle/config/overlays/update-deployment.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.38.4/bundle/config/overlays/update-strategy-overlay.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.38.4/bundle/config/upstream/kapp-controller.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.38.4/bundle/config/values.star
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.38.4/bundle/config/values.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/kapp-controller.lib.yaml
Labels: ok-to-merge, cla-not-required

#2886 Add support to list clusterclass based clusters on TKGs
  pkg/v1/tkg/client/get_cluster.go
  pkg/v1/tkg/tkgctl/get_cluster.go
  pkg/v1/tkg/tkgctl/get_cluster_test.go
Labels: area/cli, kind/bug, ok-to-merge, cla-not-required

#2901 kapp controller 0.38.4 sh file update
  hack/kind/deploy_kind_with_capi_and_kapp.sh
Labels: area/addons, ok-to-merge

#2910 Make: Fix builds of controller code when using separate go modules
  .gitignore
  Makefile
  addons/Makefile
  apis/cni/Makefile
  apis/cni/v1alpha1/zz_generated.deepcopy.go
  apis/cpi/Makefile
  apis/cpi/v1alpha1/zz_generated.deepcopy.go
  common.mk
Labels: ok-to-merge, cla-not-required

#2915 Skip legacy fallback creation test
  pkg/v1/tkg/test/tkgctl/shared/legacy_fallback.go
Labels: area/testing, ok-to-merge, cla-not-required

#2914 Rewrite GetExternalCRDPaths test helper to use go tools package
  .gitignore
  addons/Makefile
  addons/controllers/suite_test.go
  addons/controllers/suite_test_crd_dependencies.go
  addons/go.mod
  addons/pinniped/post-deploy/go.sum
  addons/pinniped/tanzu-auth-controller-manager/controllers/suite_test.go
  addons/pinniped/tanzu-auth-controller-manager/controllers/suite_test_crd_dependencies.go
  addons/pinniped/tanzu-auth-controller-manager/go.mod
  addons/pinniped/tanzu-auth-controller-manager/go.sum
  addons/test/testutil/test_helpers.go
Labels: ok-to-merge, cla-not-required

#2913 Verify addons installation and deletion as part of tkg clusterclass tests
  addons/go.mod
  addons/go.sum
  go.mod
  go.sum
  pkg/v1/tkg/test/tkgctl/aws_cc/aws_cc_antrea_test.go
  pkg/v1/tkg/test/tkgctl/shared/e2e_common.go
  pkg/v1/tkg/test/tkgctl/shared/package.go
Labels: ok-to-merge, cla-not-required

#2882 Use fslock to acquire lock when reading/writing the tanzu config file for update
  cmd/cli/plugin/login/main.go
  pkg/v1/auth/csp/grpc.go
  pkg/v1/cli/command/core/config.go
  pkg/v1/cli/command/core/discovery_source.go
  pkg/v1/cli/command/core/repo.go
  pkg/v1/cli/pluginmanager/manager_test.go
  pkg/v1/cli/pluginmanager/test/config.yaml
  pkg/v1/config/clientconfig.go
  pkg/v1/config/clientconfig_test.go
  pkg/v1/config/lock.go
  pkg/v1/tkg/test/framework/utils.go
Labels: area/plugin, ok-to-merge, area/ux, cla-not-required

#2903 Show plugin version as installed version and status based on discovered plugin version
  apis/cli/v1alpha1/catalog_types.go
  docs/design/context-aware-plugin-discovery-design.md
  pkg/v1/cli/command/core/plugin_manager.go
  pkg/v1/cli/command/core/plugin_manager_test.go
  pkg/v1/cli/plugin/types.go
  pkg/v1/cli/pluginmanager/manager.go
  pkg/v1/cli/pluginmanager/manager_test.go
Labels: area/cli, ok-to-merge, cla-not-required

#2885 TKGS integration test cases - feature flag and featuregate specific
  pkg/v1/tkg/test/README.md
  pkg/v1/tkg/test/config/config.yaml
  pkg/v1/tkg/test/config/tkgs.yaml
  pkg/v1/tkg/test/framework/e2e_config.go
  pkg/v1/tkg/test/tkgctl/tkgs/tkgs_suite_test.go
  pkg/v1/tkg/test/tkgctl/tkgs/tkgs_workload_cluster_test.go
  pkg/v1/tkg/tkgctl/client.go
  pkg/v1/tkg/tkgctl/interface.go
Labels: area/testing, ok-to-merge, cla-not-required

#2929 Update vendir of cpi CRD to include the change of antreaNSXPodRouting…
  packages/addons-manager/bundle/config/upstream/cpi.tanzu.vmware.com_vspherecpiconfigs.yaml
  packages/addons-manager/vendir.lock.yml
  packages/addons-manager/vendir.yml
Labels: ok-to-merge, cla-not-required

#2931 Change default AVI_CONTROLLER_VERSION to 20.1.3.
  pkg/v1/providers/config_default.yaml
Labels: ok-to-merge, cla-not-required

#2928 Add envvar option to exclude CC-related files during build
  pkg/v1/providers/Makefile
Labels: ok-to-merge, cla-not-required, area/cc

#2935 change cluster pause webhook behavior to no pause for legacy tkr
  addons/controllers/cluster_pause_webhook_test.go
  addons/controllers/clusterbootstrap_controller.go
  addons/controllers/testdata/webhooks/cluster-pause-webhook-manifest-with-legacy-tkr-label.yaml
  addons/controllers/testdata/webhooks/cluster-pause-webhook-manifest.yaml
  addons/pkg/constants/constants.go
  addons/webhooks/cluster_pause_webhook.go
  addons/webhooks/cluster_pause_webhook_test.go
Labels: area/addons, ok-to-merge

#2445 Update node pool API for new clusters
  docs/design/node-pool/package-based-lcm-node-pools.md
  packages/tkg-clusterclass-aws/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-azure/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  pkg/v1/providers/infrastructure-aws/v1.2.0/cconly/base.yaml
  pkg/v1/providers/infrastructure-azure/v1.2.1/cconly/base.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/cconly/base.yaml
  pkg/v1/tkg/client/machine_deployment.go
  pkg/v1/tkg/client/machine_deployment_cc.go
  pkg/v1/tkg/client/machine_deployment_cc_test.go
Labels: ok-to-merge, cla-not-required, area/lcm, area/cc

#2846 remove tanzu-framework prefix in repo bundle tarball name
  hack/packages/package-tools/cmd/repo-bundle-generate.go
  hack/packages/package-tools/cmd/repo-bundle-push.go
Labels: ok-to-merge, cla-not-required

#2875 Add AWS EBS and AzureDisk CSI Drivers
  pkg/v1/providers/ytt/02_addons/public-cloud-csi/add_aws_csi_driver.yaml
  pkg/v1/providers/ytt/02_addons/public-cloud-csi/add_azure_csi_driver.yaml
  pkg/v1/providers/ytt/02_addons/public-cloud-csi/disk/azuredisk-csi-driver_data.lib.yaml
  pkg/v1/providers/ytt/02_addons/public-cloud-csi/ebs/aws-ebs-csi-driver_data.lib.yaml
  pkg/v1/providers/ytt/03_customizations/add_sc.yaml
  pkg/v1/providers/ytt/lib/helpers.star
  pkg/v1/tkg/aws/client.go
  pkg/v1/tkg/aws/fixtures/cloudformation-default.yaml
  pkg/v1/tkg/aws/fixtures/cloudformation-tmc-disabled.yaml
Labels: ok-to-merge, cla-not-required

#2948 Add support for PCI Passthrough for vSphere w/o Supervisor
  pkg/v1/providers/config_default.yaml
  pkg/v1/providers/infrastructure-aws/v1.2.0/ytt/base-template.yaml
  pkg/v1/providers/infrastructure-aws/v1.2.0/ytt/overlay.yaml
  pkg/v1/providers/infrastructure-azure/v1.2.1/ytt/base-template.yaml
  pkg/v1/providers/infrastructure-azure/v1.2.1/ytt/overlay.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/ytt/base-template.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/ytt/overlay.yaml
  pkg/v1/providers/tests/clustergen/param_models/cluster_optional.model
  pkg/v1/providers/tests/clustergen/param_models/cluster_vsphere.model
  pkg/v1/providers/tests/unit/fixtures/yttmocks/lib/helpers.star
  pkg/v1/providers/tests/unit/pci_passthrough_test.go
  pkg/v1/providers/ytt/lib/helpers.star
  pkg/v1/tkg/constants/config_variables.go
  pkg/v1/tkg/tkgconfigproviders/vsphere.go
Labels: ok-to-merge, cla-not-required

#2900 Update clusterclass node pool support for TKGS
  cmd/cli/plugin/cluster/delete_node_pool.go
  cmd/cli/plugin/cluster/get_node_pools.go
  cmd/cli/plugin/cluster/set_node_pool.go
  pkg/v1/tkg/client/machine_deployment.go
  pkg/v1/tkg/client/machine_deployment_cc.go
  pkg/v1/tkg/client/machine_deployment_cc_test.go
Labels: ok-to-merge, cla-not-required

#2954 Fixes TKC based cluster template generation issue when `TKG_CUSTOM_IMAGE_REPOSITORY` is set
  pkg/v1/providers/ytt/03_customizations/registry_skip_tls_verify.yaml
Labels: area/cli, kind/bug, ok-to-merge, cla-not-required

#2956 Add docs regarding allowing registry override for context scoped plugins
  docs/design/context-aware-plugin-discovery-design.md
Labels: kind/documentation, ok-to-merge, cla-not-required

#2792 Antrea 1.5.3 package bump
  addons/controllers/antrea/antreaconfig_util.go
  addons/controllers/testdata/antrea-test-1.yaml
  apis/cni/v1alpha1/antreaconfig_types.go
  apis/cni/v1alpha1/zz_generated.deepcopy.go
  pkg/v1/providers/config_default.yaml
  pkg/v1/providers/tests/clustergen/param_models/cluster_optional.model
  pkg/v1/providers/vendir.lock.yml
  pkg/v1/providers/vendir.yml
  pkg/v1/providers/ytt/02_addons/cni/antrea/antrea_addon_data.lib.yaml
  pkg/v1/providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.5.3/bundle/config/kapp-config.yaml
  pkg/v1/providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.5.3/bundle/config/overlay/antrea-overlay.yaml
  pkg/v1/providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.5.3/bundle/config/overlay/update-strategy-overlay.yaml
  pkg/v1/providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.5.3/bundle/config/schema.yaml
  pkg/v1/providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.5.3/bundle/config/upstream/antrea.yaml
  pkg/v1/providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.5.3/bundle/config/values.star
  pkg/v1/providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.5.3/bundle/config/values.yaml
  pkg/v1/providers/ytt/vendir/cni/cni.lib.yaml
Labels: ok-to-merge, cla-not-required, area/networking, codefreeze

#2938 Change AKO default service type to npl when cni is antrea
  pkg/v1/providers/ytt/02_addons/avi/ako_operator_secret.yaml
  pkg/v1/providers/ytt/03_customizations/02_avi/ako-deployment.lib.yaml
Labels: ok-to-merge, cla-not-required

#2926 Update CSI controller in tanzu-framework to set Zone for Paravirtual CSI
  addons/controllers/addon_controller.go
  addons/controllers/csi/vspherecsiconfig_constants.go
  addons/controllers/csi/vspherecsiconfig_controller.go
  addons/controllers/csi/vspherecsiconfig_datavalues.go
  addons/controllers/csi/vspherecsiconfig_utils.go
  addons/controllers/suite_test.go
  addons/controllers/testdata/dependency/crd/topology.tanzu.vmware.com_availabilityzones.yaml
  addons/controllers/vspherecsiconfig_controller_test.go
  addons/go.mod
  addons/go.sum
  addons/main.go
  addons/test/testutil/test_helpers.go
Labels: ok-to-merge, cla-not-required

#2962 set maxUnavailable to 1 in addons-manager deployment
  packages/addons-manager/bundle/config/upstream/addons-manager.yaml
Labels: ok-to-merge, cla-not-required

#2969 Update issue and PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: area/repo maintenance, ok-to-merge, area/dx

#2974 Addons-controller init should not wait on availabilityzones resource
  addons/controllers/addon_controller.go
  addons/controllers/csi/vspherecsiconfig_controller.go
  addons/controllers/vspherecsiconfig_controller_test.go
  addons/test/testutil/test_helpers.go
Labels: area/addons, ok-to-merge, cla-not-required

#2981 Kickstart UI: Adds support for new NSX fields
  pkg/v1/tkg/tkgconfigproviders/tkgconfig_test.go
  pkg/v1/tkg/tkgconfigproviders/vsphere.go
  pkg/v1/tkg/web/api/spec.yaml
  pkg/v1/tkg/web/server/models/avi_config.go
  pkg/v1/tkg/web/server/restapi/embedded_spec.go
  pkg/v1/tkg/web/src/app/views/landing/vsphere-wizard/vsphere-wizard.component.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/components/steps/load-balancer/load-balancer-step.component.html
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/components/steps/load-balancer/load-balancer-step.component.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/components/steps/load-balancer/load-balancer-step.fieldmapping.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/wizard-base/wizard-base.ts
Labels: ok-to-merge, cla-not-required

#2823 Add NSX ALB(Avi) related fields validation & remove vip network separation feature gate
  addons/go.mod
  addons/go.sum
  pkg/v1/config/clientconfig.go
  pkg/v1/tkg/avi/client.go
  pkg/v1/tkg/avi/interface.go
  pkg/v1/tkg/avi/mocks/mock_client.go
  pkg/v1/tkg/avi/mocks/mock_mini_cloud_client.go
  pkg/v1/tkg/avi/mocks/mock_mini_network_client.go
  pkg/v1/tkg/avi/mocks/mock_mini_service_engine_client.go
  pkg/v1/tkg/client/validate.go
  pkg/v1/tkg/client/validate_test.go
  pkg/v1/tkg/constants/cluster_internal.go
  pkg/v1/tkg/constants/config_variables.go
Labels: area/cli, kind/enhancement, area/addons, ok-to-merge, cla-not-required, area/networking, codefreeze

#2987 validate workload cluster existence
  pkg/v1/tkg/client/cluster.go
  pkg/v1/tkg/constants/cluster_internal.go
  pkg/v1/tkg/tkgctl/create_cluster.go
  pkg/v1/tkg/tkgctl/create_cluster_test.go
  pkg/v1/tkg/tkgctl/get_cluster.go
  pkg/v1/tkg/tkgctl/get_cluster_test.go
Labels: area/cli, kind/bug, ok-to-merge, cla-not-required

#2977 Support configuring multiple default trusted registry for plugin downloads during build-time
  Makefile
  pkg/v1/cli/pluginmanager/manager_test.go
  pkg/v1/config/defaults.go
Labels: ok-to-merge, cla-not-required

#2637 Add codeowners for cmd/cli/plugin/package/kctrl
  CODEOWNERS
Labels: ok-to-merge, cla-not-required

#2752 Add single quote to ca cert related preKubeadmCommands to make sure w…
  packages/tkg-clusterclass-aws/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-azure/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  pkg/v1/providers/infrastructure-aws/v1.2.0/cconly/base.yaml
  pkg/v1/providers/infrastructure-azure/v1.4.0/cconly/base.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.1/cconly/base.yaml
  pkg/v1/providers/ytt/03_customizations/http_proxy_ca_cert.yaml
Labels: ok-to-merge, cla-not-required

#2994 Set CAPI ClusterTopology feature accordingly during management cluster creation
  pkg/v1/tkg/client/init.go
  pkg/v1/tkg/client/utils.go
  pkg/v1/tkg/client/utils_test.go
  pkg/v1/tkg/constants/config_variables.go
Labels: ok-to-merge, cla-not-required

#2996 Exposes addons-manager cluster-delete-timeout as template parameter
  packages/addons-manager/bundle/config/upstream/addons-manager.yaml
  packages/addons-manager/bundle/config/values.yaml
  packages/framework/bundle/config/values.yaml
  packages/tkg/bundle/config/values.yaml
Labels: ok-to-merge, cla-not-required

#3002 Fix: object-Propagation controller failing to copy resources
  pkg/v2/object-propagation/propagation/reconciler.go
  pkg/v2/object-propagation/propagation/reconciler_test.go
Labels: ok-to-merge, cla-not-required

#3006 OPC should remove ownerReferences from propagated objects
  pkg/v2/object-propagation/propagation/reconciler.go
  pkg/v2/object-propagation/propagation/reconciler_test.go
Labels: ok-to-merge, cla-not-required

#2999 Update Scale API to support ClusterClass clusters
  pkg/v1/tkg/client/scale.go
  pkg/v1/tkg/client/scale_test.go
  pkg/v1/tkg/test/tkgctl/aws_cc/aws_cc_scale_test.go
Labels: ok-to-merge, cla-not-required

#2986 Remove feature-gate validation for TKGS cluster and make it based on vSphere version
  pkg/v1/tkg/clusterclient/clusterclient.go
  pkg/v1/tkg/fakes/clusterclient.go
  pkg/v1/tkg/tkgctl/featuregate_helper.go
Labels: ok-to-merge, cla-not-required

#3013 TKR Resolver: Custom imageRepository
  pkg/v2/tkr/util/testdata/gendata.go
  pkg/v2/tkr/util/topology/cluster_test.go
  pkg/v2/tkr/webhook/cluster/tkr-resolver/cluster/cluster.go
  pkg/v2/tkr/webhook/cluster/tkr-resolver/cluster/cluster_test.go
  pkg/v2/tkr/webhook/cluster/tkr-resolver/main.go
Labels: ok-to-merge, cla-not-required, area/tkr

#3004 Address OOM kills in addons-manager
  addons/controllers/csi/vspherecsiconfig_controller.go
  addons/controllers/packageinstallstatus_controller.go
  addons/controllers/packageinstallstatus_controller_test.go
  addons/controllers/packageinstallstatus_handler.go
  addons/main.go
  addons/pkg/constants/constants.go
Labels: ok-to-merge, cla-not-required

#2803 Add integration tests for TKR resolution for clusterclass based clusters creation and upgrade
  .github/workflows/tkg_integration_tests_clusterclass.yaml
  pkg/v1/tkg/client/validate.go
  pkg/v1/tkg/test/framework/cluster_proxy.go
  pkg/v1/tkg/test/framework/schemes.go
  pkg/v1/tkg/test/tkgctl/aws_cc/aws_cc_tkrresolver_test.go
  pkg/v1/tkg/test/tkgctl/shared/e2e_tkrresolver.go
Labels: area/testing, ok-to-merge, cla-not-required, area/tkr

#3007 Propagate only clusterclass related resources to other namespaces based on label
  packages/tkg-clusterclass/bundle/config/object-propagation/deployment.yaml
Labels: ok-to-merge, cla-not-required

#2984 Adding namespace watch to Namespace controller
  pkg/v1/sdk/features/controllers/featuregate_controller.go
Labels: ok-to-merge, cla-not-required

#3016 Ability to generate default capabilities secret with user-specified PSPs
  Makefile
  pkg/v1/sdk/capabilities/hack/generate-package-secret.test.sh
Labels: ok-to-merge, cla-not-required

#3021 Modify logic to determine stretch supervisor
  addons/controllers/csi/vspherecsiconfig_utils.go
  addons/controllers/vspherecsiconfig_controller_test.go
Labels: ok-to-merge, cla-not-required

#2997 UpdatesAvailable condition for legacy-style Clusters in uTKG
  apis/run/v1alpha3/tanzukubernetesrelease_types.go
  pkg/v2/tkr/controller/tkr-status/clusterstatus/clusterstatus.go
  pkg/v2/tkr/controller/tkr-status/clusterstatus/clusterstatus_test.go
  pkg/v2/tkr/util/version/version.go
Labels: area/api, ok-to-merge, cla-not-required, area/tkr

#3003 Add e2e test for TKR compatibility status condition
  pkg/v1/tkg/test/framework/cluster_proxy.go
  pkg/v1/tkg/test/tkgctl/aws_cc/aws_cc_tkr_test.go
  pkg/v1/tkg/test/tkgctl/shared/tkr_cc_misc.go
Labels: ok-to-merge, cla-not-required

#3020 Update BOM retrieval version to v0.25.0
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#3025 Updating version tag used for BOM retrieval to v0.26.0-dev
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#2970 Detect TKGS environment for any version of TKC API
  pkg/v1/sdk/capabilities/discovery/tkg/capabilities.go
  pkg/v1/sdk/capabilities/discovery/tkg/capabilities_test.go
  pkg/v1/sdk/capabilities/discovery/tkg/fake.go
Labels: ok-to-merge, cla-not-required

#3030 Update support matrix for v1.7
  pkg/v1/tkg/tkgconfighelper/tkgconfighelper_test.go
  pkg/v1/tkg/tkgconfighelper/validate.go
Labels: ok-to-merge, cla-not-required

#2955 Add E2E tests for Antrea/Calico CNI on tkgs
  pkg/v1/tkg/client/cluster.go
  pkg/v1/tkg/test/tkgctl/tkgs/tkgs_suite_test.go
  pkg/v1/tkg/test/tkgctl/tkgs/tkgs_workload_cluster_test.go
  pkg/v1/tkg/test/tkgctl/tkgs_cc/tkgs_cc_suite_test.go
  pkg/v1/tkg/test/tkgctl/tkgs_cc/tkgs_cc_workload_cluster_test.go
  pkg/v1/tkg/test/tkgctl/tkgs_cc/utils.go
Labels: ok-to-merge, cla-not-required

#3037 PCI variable name mismatch issue in vendorId/deviceId variable name
  pkg/v1/providers/infrastructure-vsphere/v1.3.1/ytt/overlay.yaml
  pkg/v1/providers/tests/unit/pci_passthrough_test.go
Labels: ok-to-merge, cla-not-required

#3033 Validate cluster kubernetes version upgrade check as initial step
  pkg/v1/tkg/client/upgrade_cluster.go
  pkg/v1/tkg/client/upgrade_cluster_test.go
Labels: area/cli, kind/bug, ok-to-merge, cla-not-required

#3009 Run vendir sync for packages concurrently
  hack/packages/package-tools/cmd/vendir-sync.go
  hack/packages/package-tools/go.mod
  hack/packages/package-tools/go.sum
Labels: ok-to-merge, cla-not-required

#3038 [backport-release-0.25]Validate cluster kubernetes version upgrade check as initial step
  pkg/v1/tkg/client/upgrade_cluster.go
  pkg/v1/tkg/client/upgrade_cluster_test.go
Labels: area/cli, kind/bug, ok-to-merge, cla-not-required
