Repository vmware-tanzu/tanzu-framework, pull requests merged in 2022-08, with the labels that each got.

#3041 Use TKR API commands based on feature-gate on the supervisor-cluster
  cmd/cli/plugin/tkr/main.go
  pkg/v1/tkg/tkgctl/client.go
  pkg/v1/tkg/tkgctl/featuregate_helper.go
Labels: area/cli, kind/bug, ok-to-merge, cla-not-required

#3055 Fix data race in cluster pause webhook
  addons/Makefile
  addons/pkg/crdwait/crd_wait_test.go
  addons/webhooks/cluster_pause_webhook.go
  addons/webhooks/cluster_pause_webhook_test.go
  packages/addons-manager/bundle/config/upstream/addons-manager.yaml
Labels: ok-to-merge, cla-not-required

#3028 Add e2e test to validate published TKRs are available on management c…
  pkg/v1/tkg/test/framework/cluster_proxy.go
  pkg/v1/tkg/test/framework/schemes.go
  pkg/v1/tkg/test/tkgctl/shared/tkr_cc_misc.go
Labels: area/testing, ok-to-merge, cla-not-required, area/tkr

#3050 Fixed "tanzu cluster get" command to return Classy cluster details on…
  cmd/cli/plugin/cluster/get.go
  pkg/v1/tkg/tkgctl/describe_cluster.go
  pkg/v1/tkg/tkgctl/describe_cluster_test.go
Labels: area/cli, kind/bug, ok-to-merge, cla-not-required

#3026 Fix the issue of tkg-clusterclass packageinstall reconcile failed after 15 minutes of management-cluster creation
  pkg/v1/tkg/client/init.go
  pkg/v1/tkg/client/machine_deployment.go
  pkg/v1/tkg/client/machine_deployment_test.go
  pkg/v1/tkg/client/upgrade_addon.go
  pkg/v1/tkg/client/upgrade_addon_test.go
  pkg/v1/tkg/client/upgrade_cluster.go
  pkg/v1/tkg/client/upgrade_cluster_test.go
  pkg/v1/tkg/clusterclient/clusterclient.go
  pkg/v1/tkg/clusterclient/clusterclient_test.go
  pkg/v1/tkg/constants/cluster_internal.go
  pkg/v1/tkg/fakes/clusterclient.go
  pkg/v1/tkg/fakes/helper/fakeobjectcreater.go
Labels: area/cli, kind/bug, ok-to-merge, cla-not-required

#3044 Check if aws_vpc_cidr is empty before adding to no_proxy list
  pkg/v1/providers/kapp-controller-values/helpers.star
  pkg/v1/providers/tests/clustergen/param_models/cluster_optional.model
  pkg/v1/providers/ytt/03_customizations/http_proxy.yaml
  pkg/v1/providers/ytt/09_miscellaneous/08_store_data_values.yaml
  pkg/v1/providers/ytt/lib/helpers.star
  pkg/v1/providers/yttcc/lib/helpers.star
  pkg/v1/tkg/client/validate.go
  pkg/v1/tkg/client/validate_test.go
Labels: area/cli, kind/bug, ok-to-merge, cla-not-required

#3059 [Backport]: Fix data race in cluster pause webhook (#3055)
  addons/Makefile
  addons/pkg/crdwait/crd_wait_test.go
  addons/webhooks/cluster_pause_webhook.go
  addons/webhooks/cluster_pause_webhook_test.go
  addons/webhooks/clusterbootstrap_webhook.go
  packages/addons-manager/bundle/config/upstream/addons-manager.yaml
Labels: ok-to-merge, cla-not-required

#3057 [release-0.25] Use TKR API commands based on feature-gate on the management-cluster
  cmd/cli/plugin/tkr/main.go
  pkg/v1/tkg/tkgctl/client.go
  pkg/v1/tkg/tkgctl/featuregate_helper.go
Labels: kind/bug, ok-to-merge, cla-not-required

#3049 [release-0.25] Fixed "tanzu cluster get" command to return Classy cluster details on TKGS
  cmd/cli/plugin/cluster/get.go
  pkg/v1/tkg/tkgctl/describe_cluster.go
  pkg/v1/tkg/tkgctl/describe_cluster_test.go
Labels: area/cli, kind/bug, ok-to-merge, cla-not-required

#3060 [backport release-0.25]Add e2e test to validate published TKRs are available on management c…
  pkg/v1/tkg/test/framework/cluster_proxy.go
  pkg/v1/tkg/test/framework/schemes.go
  pkg/v1/tkg/test/tkgctl/shared/tkr_cc_misc.go
Labels: kind/enhancement, area/testing, ok-to-merge, cla-not-required

#3064 Add mutex for GVR access in clusterbootstrap webhook
  addons/webhooks/clusterbootstrap_webhook.go
Labels: ok-to-merge, cla-not-required

#3053 Display correct error message when passing Cluster based resource without ClusterClass as part of cluster create
  pkg/v1/tkg/constants/clusterclass_mapping.go
  pkg/v1/tkg/tkgctl/create_cluster_test.go
  pkg/v1/tkg/tkgctl/helpers.go
  pkg/v1/tkg/tkgctl/helpers_test.go
Labels: ok-to-merge, cla-not-required

#3073 Automate create/delete CC Guest cluster on supervisor using Custom ClusterBootstrap and verify if all addons are successfully deployed
  pkg/v1/tkg/test/config/tkgs.yaml
  pkg/v1/tkg/test/data/testdata/customClusterBootstrapAntrea.yaml
  pkg/v1/tkg/test/framework/e2e_config.go
  pkg/v1/tkg/test/tkgctl/shared/e2e_common.go
  pkg/v1/tkg/test/tkgctl/shared/package.go
  pkg/v1/tkg/test/tkgctl/shared/tkr_cc_misc.go
  pkg/v1/tkg/test/tkgctl/tkgs_cc/tkgs_cc_suite_test.go
  pkg/v1/tkg/test/tkgctl/tkgs_cc/tkgs_cc_workload_cluster_test.go
Labels: ok-to-merge, cla-not-required

#3019 monitor cluster class based workload cluster core packages installation
  pkg/v1/tkg/client/cluster.go
  pkg/v1/tkg/client/package_helper.go
  pkg/v1/tkg/client/package_helper_test.go
  pkg/v1/tkg/client/upgrade_region.go
  pkg/v1/tkg/client/workload_cluster.go
  pkg/v1/tkg/clusterclient/clusterclient.go
  pkg/v1/tkg/constants/cluster_internal.go
  pkg/v1/tkg/fakes/config/clusterbootstrap.yaml
  pkg/v1/tkg/managementcomponents/management_component_install.go
  pkg/v1/tkg/tkgctl/create_cluster.go
Labels: area/cli, ok-to-merge, cla-not-required

#3063 Add annotation to all cluster class templates
  packages/tkg-clusterclass-aws/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-azure/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  pkg/v1/providers/infrastructure-aws/v1.2.0/cconly/base.yaml
  pkg/v1/providers/infrastructure-azure/v1.4.0/cconly/base.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.1/cconly/base.yaml
Labels: area/cli, ok-to-merge, cla-not-required

#3068 [Cherry pick to 0.25]Check if aws_vpc_cidr is empty before adding to no_proxy list (#3044)
  pkg/v1/providers/kapp-controller-values/helpers.star
  pkg/v1/providers/tests/clustergen/param_models/cluster_optional.model
  pkg/v1/providers/ytt/03_customizations/http_proxy.yaml
  pkg/v1/providers/ytt/09_miscellaneous/08_store_data_values.yaml
  pkg/v1/providers/ytt/lib/helpers.star
  pkg/v1/providers/yttcc/lib/helpers.star
  pkg/v1/tkg/client/validate.go
  pkg/v1/tkg/client/validate_test.go
Labels: ok-to-merge, cla-not-required, area/networking

#3018 cc_cluster lifecycle test - upgrade
  pkg/v1/tkg/test/tkgctl/shared/e2e_common.go
  pkg/v1/tkg/test/tkgctl/tkgs_cc/tkgs_cc_workload_cluster_test.go
Labels: ok-to-merge, cla-not-required

#3036 add addon test for tkgs cluster creation
  pkg/v1/tkg/test/tkgctl/shared/e2e_common.go
  pkg/v1/tkg/test/tkgctl/shared/package.go
  pkg/v1/tkg/test/tkgctl/tkgs/tkgs_workload_cluster_test.go
  pkg/v1/tkg/test/tkgctl/tkgs_cc/tkgs_cc_workload_cluster_test.go
Labels: ok-to-merge, cla-not-required

#2775 package/pinniped: post-deploy job read nodes to obtain cluster-name or accept --jwtauthenticator-audience flag
  addons/pinniped/post-deploy/go.mod
  addons/pinniped/post-deploy/pkg/configure/configure.go
  addons/pinniped/post-deploy/pkg/configure/configure_test.go
  addons/pinniped/post-deploy/pkg/inspect/inspect.go
Labels: ok-to-merge, cla-not-required

#3082 monitor cluster class based workload cluster core packages installation
  pkg/v1/tkg/client/cluster.go
  pkg/v1/tkg/client/package_helper.go
  pkg/v1/tkg/client/package_helper_test.go
  pkg/v1/tkg/client/upgrade_region.go
  pkg/v1/tkg/client/workload_cluster.go
  pkg/v1/tkg/clusterclient/clusterclient.go
  pkg/v1/tkg/constants/cluster_internal.go
  pkg/v1/tkg/fakes/config/clusterbootstrap.yaml
  pkg/v1/tkg/managementcomponents/management_component_install.go
  pkg/v1/tkg/tkgctl/create_cluster.go
Labels: ok-to-merge, cla-not-required

#3086 Add support for "tanzu cluster get" command to show tree view of cluster for …
  cmd/cli/plugin/cluster/get.go
  pkg/v1/tkg/tkgctl/describe_cluster.go
  pkg/v1/tkg/tkgctl/describe_cluster_test.go
Labels: area/cli, kind/enhancement, ok-to-merge, cla-not-required

#3076 [release-0.25] Display correct error message when passing Cluster based resource without ClusterClass as part of cluster create
  pkg/v1/tkg/constants/clusterclass_mapping.go
  pkg/v1/tkg/tkgctl/create_cluster.go
  pkg/v1/tkg/tkgctl/create_cluster_test.go
  pkg/v1/tkg/tkgctl/helpers_test.go
Labels: area/cli, ok-to-merge, cla-not-required

#3096 Fix package plugin tests flakes
  pkg/v1/tkg/test/tkgpackageclient/config/package_plugin_config.yaml
  pkg/v1/tkg/test/tkgpackageclient/package_plugin_integration_test.go
Labels: ok-to-merge, cla-not-required

#3091 Update osInfo annotation on Cluster resource during cluster upgrade
  pkg/v1/tkg/client/upgrade_cluster.go
  pkg/v1/tkg/clusterclient/clusterclient.go
  pkg/v1/tkg/clusterclient/clusterclient_test.go
  pkg/v1/tkg/fakes/clusterclient.go
Labels: ok-to-merge, cla-not-required, area/lcm

#3092 [release-0.25] Update osInfo annotation on Cluster resource during cluster upgrade
  pkg/v1/tkg/client/upgrade_cluster.go
  pkg/v1/tkg/clusterclient/clusterclient.go
  pkg/v1/tkg/clusterclient/clusterclient_test.go
  pkg/v1/tkg/fakes/clusterclient.go
Labels: ok-to-merge, cla-not-required

#3087 [backport release-0.25 branch]Add support for "tanzu cluster get" to show tree view of cluster for …
  cmd/cli/plugin/cluster/get.go
  pkg/v1/tkg/tkgctl/describe_cluster.go
  pkg/v1/tkg/tkgctl/describe_cluster_test.go
Labels: area/cli, kind/enhancement, ok-to-merge, cla-not-required

#3094 update error message while checking management cluster infra provider details
  pkg/v1/tkg/client/cluster.go
  pkg/v1/tkg/constants/cluster_internal.go
  pkg/v1/tkg/tkgctl/create_cluster.go
  pkg/v1/tkg/tkgctl/describe_cluster.go
  pkg/v1/tkg/tkgctl/describe_cluster_test.go
  pkg/v1/tkg/tkgctl/get_cluster.go
  pkg/v1/tkg/tkgctl/get_cluster_test.go
  pkg/v1/tkg/tkgctl/upgrade_cluster.go
Labels: area/cli, ok-to-merge, cla-not-required

#3107 package/pinniped: pinniped-post-deploy symlink for historic binary name
  addons/pinniped/post-deploy/Dockerfile
Labels: ok-to-merge, cla-not-required

#3088 Remove installation of kubeval
  common.mk
  hack/tools/Makefile
Labels: kind/cleanup, ok-to-merge, cla-not-required

#3089 Changed location to get access to SharedGalleryImages
  pkg/v1/tkg/test/config/azure.yaml
Labels: CI, area/testing, ok-to-merge, cla-not-required

#3112 Update broken link to variable mapping doc
  docs/cli/clusterclass/README.md
Labels: kind/documentation, ok-to-merge

#3093 Port Node Pool E2E Test to release-0.25
  packages/tkg-clusterclass-aws/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-azure/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  pkg/v1/providers/infrastructure-aws/v1.2.0/cconly/base.yaml
  pkg/v1/providers/infrastructure-azure/v1.4.0/cconly/base.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.1/cconly/base.yaml
  pkg/v1/tkg/client/machine_deployment_cc.go
  pkg/v1/tkg/test/README.md
  pkg/v1/tkg/test/config/aws.yaml
  pkg/v1/tkg/test/config/cc/aws/aws_cc_wc_config.yaml
  pkg/v1/tkg/test/tkgctl/aws_cc/aws_cc_node_pool_test.go
  pkg/v1/tkg/test/tkgctl/docker/docker_node_pool_test.go
  pkg/v1/tkg/test/tkgctl/shared/node_pools.go
  pkg/v1/tkg/test/tkgctl/tkgs/tkgs_workload_cluster_test.go
  pkg/v1/tkg/test/tkgctl/tkgs_cc/tkgs_cc_node_pool_test.go
  pkg/v1/tkg/test/tkgctl/tkgs_cc/tkgs_cc_suite_test.go
  pkg/v1/tkg/test/tkgctl/tkgs_cc/tkgs_cc_workload_cluster_test.go
Labels: ok-to-merge, cla-not-required

#3113 update correct package name to monitor package installation
  pkg/v1/tkg/client/cluster.go
  pkg/v1/tkg/client/package_helper.go
  pkg/v1/tkg/client/package_helper_test.go
  pkg/v1/tkg/clusterclient/clusterclient.go
  pkg/v1/tkg/fakes/clusterclient.go
Labels: ok-to-merge, cla-not-required

#3084 Adds upgrade integration test for custom CB clusters
  pkg/v1/tkg/test/tkgctl/tkgs_cc/tkgs_cc_workload_cluster_test.go
Labels: ok-to-merge, cla-not-required

#3103 Handle plugin errors properly
  cmd/cli/tanzu/main.go
  pkg/v1/cli/command/core/root.go
Labels: kind/bug, ok-to-merge, cla-not-required, area/core-cli

#3111 Add log messages for tanzu plugin install local all
  pkg/v1/cli/command/core/plugin_manager.go
Labels: kind/bug, ok-to-merge, cla-not-required, area/core-cli

#3101 Implement logr wrapper as part of existing logger and use with clusterctl
  pkg/v1/tkg/log/interface.go
  pkg/v1/tkg/log/logger.go
  pkg/v1/tkg/log/logr.go
  pkg/v1/tkg/tkgctl/client.go
Labels: area/cli, ok-to-merge, cla-not-required

#3031 Add calico e2e test to aws clusterclass suite
  pkg/v1/tkg/test/tkgctl/aws_cc/aws_cc_calico_test.go
  pkg/v1/tkg/test/tkgctl/shared/e2e_common.go
  pkg/v1/tkg/test/tkgctl/shared/package.go
Labels: area/testing, area/addons, ok-to-merge, cla-not-required

#3119 [release-0.25] explictly set the criSocket field in AWS and Azure to avoid race conditions
  packages/tkg-clusterclass-azure/bundle/config/upstream/base.yaml
  pkg/v1/providers/infrastructure-aws/v1.2.0/ytt/base-template.yaml
  pkg/v1/providers/infrastructure-aws/v1.2.0/ytt/overlay.yaml
  pkg/v1/providers/infrastructure-aws/ytt/aws-overlay.yaml
  pkg/v1/providers/infrastructure-azure/v1.4.0/cconly/base.yaml
  pkg/v1/providers/infrastructure-azure/v1.4.0/ytt/base-template.yaml
  pkg/v1/providers/infrastructure-azure/ytt/azure-overlay.yaml
  pkg/v1/providers/infrastructure-azure/yttcc/azure-overlay.yaml
Labels: ok-to-merge, cla-not-required

#3120 explictly set the criSocket field in AWS and Azure to avoid race conditions
  packages/tkg-clusterclass-aws/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-azure/bundle/config/upstream/base.yaml
  pkg/v1/providers/infrastructure-aws/v1.2.0/cconly/base.yaml
  pkg/v1/providers/infrastructure-aws/v1.2.0/ytt/base-template.yaml
  pkg/v1/providers/infrastructure-aws/v1.2.0/ytt/overlay.yaml
  pkg/v1/providers/infrastructure-aws/ytt/aws-overlay.yaml
  pkg/v1/providers/infrastructure-azure/v1.4.0/cconly/base.yaml
  pkg/v1/providers/infrastructure-azure/v1.4.0/ytt/base-template.yaml
  pkg/v1/providers/infrastructure-azure/ytt/azure-overlay.yaml
  pkg/v1/providers/infrastructure-azure/yttcc/azure-overlay.yaml
Labels: ok-to-merge, cla-not-required

#2774 Plumb legacy skipCNIBinaries config to CalicoConfig API
  pkg/v1/providers/yttcb/clusterbootstrap.yaml
Labels: area/addons, ok-to-merge, cla-not-required, needs-triage

#3134 Clarify error when discovery source is invalid
  pkg/v1/cli/command/core/discovery_source.go
  pkg/v1/cli/command/core/discovery_source_test.go
Labels: kind/bug, ok-to-merge, cla-not-required, area/core-cli

#3127 UpdatesAvailable not showing all available TKRs
  pkg/v2/tkr/controller/tkr-status/clusterstatus/clusterstatus.go
Labels: kind/bug, ok-to-merge, cla-not-required, area/tkr

#3124 [release 0.25] update workload cluster create addon's packages monitoring logic
  pkg/v1/tkg/client/cluster.go
  pkg/v1/tkg/client/package_helper.go
  pkg/v1/tkg/client/package_helper_test.go
  pkg/v1/tkg/clusterclient/clusterclient.go
  pkg/v1/tkg/fakes/clusterclient.go
Labels: ok-to-merge, cla-not-required

#3123 update error message as generic to the infrastructure provider (#3094)
  pkg/v1/tkg/client/cluster.go
  pkg/v1/tkg/constants/cluster_internal.go
  pkg/v1/tkg/tkgctl/create_cluster.go
  pkg/v1/tkg/tkgctl/describe_cluster.go
  pkg/v1/tkg/tkgctl/describe_cluster_test.go
  pkg/v1/tkg/tkgctl/get_cluster.go
  pkg/v1/tkg/tkgctl/get_cluster_test.go
  pkg/v1/tkg/tkgctl/upgrade_cluster.go
Labels: ok-to-merge, cla-not-required

#3061 Fix small typos to Contributing documentation
  CONTRIBUTING.md
Labels: kind/documentation, ok-to-merge, cla-not-required

#3137 Cherry-pick #3127 into release-0.25 branch
  pkg/v2/tkr/controller/tkr-status/clusterstatus/clusterstatus.go
Labels: ok-to-merge, cla-not-required

#3147 Relax the memory limit on the TKR Conversion webhook
  packages/tkr-service/bundle/config/upstream/tkr-conversion-webhook-deployment.yaml
Labels: ok-to-merge, cla-not-required

#3148 Fix TKR Conversion webhook being OOM killed
  packages/tkr-service/bundle/config/upstream/tkr-conversion-webhook-deployment.yaml
Labels: ok-to-merge, cla-not-required

#3121 Update node pool test to use alternate namespace
  pkg/v1/tkg/test/tkgctl/aws_cc/aws_cc_node_pool_test.go
Labels: area/testing, ok-to-merge, cla-not-required

#3141 Create separate go modules for `apis/cli` and `apis/config`
  Makefile
  addons/go.mod
  addons/go.sum
  apis/cli/Makefile
  apis/cli/go.mod
  apis/cli/go.sum
  apis/config/Makefile
  apis/config/go.mod
  apis/config/go.sum
  apis/config/v1alpha1/clientconfig.go
  apis/config/v1alpha1/featuregate_webhook.go
  apis/config/v1alpha1/featuregate_webhook_test.go
  cmd/cli/plugin/cluster/create.go
  cmd/cli/plugin/cluster/upgrade.go
  cmd/cli/plugin/managementcluster/create.go
  cmd/cli/plugin/managementcluster/delete.go
  cmd/cli/plugin/managementcluster/upgrade.go
  config/crd/bases/cni.tanzu.vmware.com_antreaconfigs.yaml
  go.mod
  go.sum
  pkg/v1/cli/command/core/config.go
  pkg/v1/sdk/capabilities/Dockerfile
  pkg/v1/sdk/features/Dockerfile
  pkg/v1/tkg/tkgctl/compatibility.go
  pkg/v1/tkg/tkgctl/compatibility_test.go
  pkg/v1/tkr/Dockerfile
  pkg/v2/object-propagation/Dockerfile
  pkg/v2/tkr/controller/tkr-source/Dockerfile
  pkg/v2/tkr/controller/tkr-status/Dockerfile
  pkg/v2/tkr/webhook/cluster/tkr-resolver/Dockerfile
  pkg/v2/tkr/webhook/infra-machine/Dockerfile
  pkg/v2/tkr/webhook/tkr-conversion/Dockerfile
Labels: kind/refactor, ok-to-merge, cla-not-required, area/core-cli

#3135 Ask for Confirmation for Tanzu Plugin Delete
  pkg/v1/cli/command/core/plugin_manager.go
  pkg/v1/cli/pluginmanager/manager.go
  pkg/v1/cli/pluginmanager/manager_test.go
Labels: kind/bug, ok-to-merge, cla-not-required

#2202 CLI: Add context command
  .codecov.yaml
  apis/config/v1alpha1/clientconfig.go
  apis/config/v1alpha1/clientconfig_test.go
  apis/config/v1alpha1/clientconfig_types.go
  apis/config/v1alpha1/zz_generated.deepcopy.go
  cmd/cli/plugin/login/main.go
  config/crd/bases/config.tanzu.vmware.com_clientconfigs.yaml
  docs/cli/cli-architecture.md
  docs/cli/plugin_implementation_guide.md
  pkg/v1/cli/command/core/config.go
  pkg/v1/cli/command/core/context.go
  pkg/v1/cli/command/core/root.go
  pkg/v1/cli/deprecation.go
  pkg/v1/config/clientconfig.go
  pkg/v1/config/clientconfig_test.go
  pkg/v1/config/context.go
  pkg/v1/config/context_test.go
  pkg/v1/config/conversion.go
  pkg/v1/config/conversion_test.go
Labels: ok-to-merge, area/ux, cla-not-required, area/core-cli

#2989 Vendir packages CRDs locally
  hack/verify-dirty.sh
  packages/addons-manager/bundle/config/upstream/crds/cni.tanzu.vmware.com_antreaconfigs.yaml
  packages/addons-manager/bundle/config/upstream/crds/cni.tanzu.vmware.com_calicoconfigs.yaml
  packages/addons-manager/bundle/config/upstream/crds/cpi.tanzu.vmware.com_vspherecpiconfigs.yaml
  packages/addons-manager/bundle/config/upstream/crds/csi.tanzu.vmware.com_vspherecsiconfigs.yaml
  packages/addons-manager/bundle/config/upstream/crds/run.tanzu.vmware.com_clusterbootstraps.yaml
  packages/addons-manager/bundle/config/upstream/crds/run.tanzu.vmware.com_clusterbootstraptemplates.yaml
  packages/addons-manager/bundle/config/upstream/crds/run.tanzu.vmware.com_kappcontrollerconfigs.yaml
  packages/addons-manager/vendir.lock.yml
  packages/addons-manager/vendir.yml
  packages/capabilities/bundle/config/upstream/crds/run.tanzu.vmware.com_capabilities.yaml
  packages/capabilities/vendir.lock.yml
  packages/capabilities/vendir.yml
  packages/featuregates/bundle/config/upstream/crds/config.tanzu.vmware.com_featuregates.yaml
  packages/featuregates/bundle/config/upstream/crds/config.tanzu.vmware.com_features.yaml
  packages/featuregates/bundle/config/upstream/feature-crd.yaml
  packages/featuregates/bundle/config/upstream/featuregate-crd.yaml
  packages/featuregates/vendir.lock.yml
  packages/featuregates/vendir.yml
  packages/tanzu-auth/vendir.lock.yml
  packages/tanzu-auth/vendir.yml
  packages/tkg-storageclass/vendir.lock.yml
  packages/tkg-storageclass/vendir.yml
  packages/tkr-source-controller/vendir.lock.yml
  packages/tkr-source-controller/vendir.yml
Labels: ok-to-merge, cla-not-required

#3168 fix vendir out of sync antreaconfig crd
  packages/addons-manager/bundle/config/upstream/crds/cni.tanzu.vmware.com_antreaconfigs.yaml
Labels: ok-to-merge, cla-not-required

#3146 Automate testcase TC25: Verify if the data value secret is created for a package with inline config
  addons/pkg/util/clusterbootstrapclone/clusterbootstrapclone.go
  pkg/v1/tkg/test/data/testdata/customClusterBootstrapInline.yaml
  pkg/v1/tkg/test/tkgctl/tkgs_cc/tkgs_cc_workload_cluster_test.go
Labels: ok-to-merge, cla-not-required

#3172 [release-0.25] Fix incorrect log message when creating management-cluster
  pkg/v1/tkg/client/init.go
Labels: kind/bug, ok-to-merge, cla-not-required

#3171 Fix incorrect log message when creating management-cluster
  pkg/v1/tkg/client/init.go
Labels: kind/bug, ok-to-merge, cla-not-required

#3177 Acquire lock before reading tanzu config file to avoid possible misconfigured file reads
  pkg/v1/cli/command/core/config.go
  pkg/v1/cli/command/core/discovery_source.go
  pkg/v1/cli/command/core/repo.go
  pkg/v1/config/clientconfig.go
  pkg/v1/config/context.go
  pkg/v1/tkg/test/framework/utils.go
  pkg/v1/tkg/tkgctl/compatibility.go
Labels: CI, kind/bug, ok-to-merge, cla-not-required

#3169 Refactor apis/run to standalone go module
  addons/controllers/suite_test.go
  addons/go.mod
  addons/manifests/samples/README.md
  addons/webhooks/webhooks_suite_test.go
  apis/run/Makefile
  apis/run/config/crd/bases/run.tanzu.vmware.com_capabilities.yaml
  apis/run/config/crd/bases/run.tanzu.vmware.com_clusterbootstraps.yaml
  apis/run/config/crd/bases/run.tanzu.vmware.com_clusterbootstraptemplates.yaml
  apis/run/config/crd/bases/run.tanzu.vmware.com_kappcontrollerconfigs.yaml
  apis/run/config/crd/bases/run.tanzu.vmware.com_osimages.yaml
  apis/run/config/crd/bases/run.tanzu.vmware.com_tanzukubernetesclusters.yaml
  apis/run/config/crd/bases/run.tanzu.vmware.com_tanzukubernetesreleases.yaml
  apis/run/go.mod
  apis/run/go.sum
  apis/run/hack/boilerplate.go.txt
  apis/run/util/conversion/README.md
  apis/run/util/conversion/conversion.go
  apis/run/util/conversion/conversion_test.go
  apis/run/util/sets/strings.go
  apis/run/util/version/compatibility.go
  apis/run/util/version/fuzz.go
  apis/run/util/version/version.go
  apis/run/util/version/version_test.go
  apis/run/v1alpha1/conversion.go
  apis/run/v1alpha1/conversion_test.go
  apis/run/v1alpha2/conversion.go
  apis/run/v1alpha2/conversion_test.go
  apis/run/v1alpha3/fuzz.go
  cmd/cli/plugin/cluster/upgrade.go
  config/crd/kustomization.yaml
  go.mod
  packages/addons-manager/bundle/config/upstream/runcrds/run.tanzu.vmware.com_clusterbootstraps.yaml
  packages/addons-manager/bundle/config/upstream/runcrds/run.tanzu.vmware.com_clusterbootstraptemplates.yaml
  packages/addons-manager/bundle/config/upstream/runcrds/run.tanzu.vmware.com_kappcontrollerconfigs.yaml
  packages/addons-manager/vendir.lock.yml
  packages/addons-manager/vendir.yml
  packages/capabilities/vendir.yml
  pkg/v1/tkg/test/tkgctl/shared/e2e_tkrresolver.go
  pkg/v1/tkg/test/tkgctl/shared/tkr_cc_misc.go
  pkg/v2/object-propagation/propagation/reconciler_test.go
  pkg/v2/tkr/controller/tkr-source/compatibility/reconciler.go
  pkg/v2/tkr/controller/tkr-source/compatibility/reconciler_test.go
  pkg/v2/tkr/controller/tkr-source/fetcher/fetcher.go
  pkg/v2/tkr/controller/tkr-source/pkgcr/reconciler.go
  pkg/v2/tkr/controller/tkr-source/pkgcr/reconciler_test.go
  pkg/v2/tkr/controller/tkr-status/clusterstatus/clusterstatus.go
  pkg/v2/tkr/controller/tkr-status/clusterstatus/clusterstatus_test.go
  pkg/v2/tkr/resolver/internal/resolver_impl.go
  pkg/v2/tkr/resolver/internal/resolver_impl_test.go
  pkg/v2/tkr/util/testdata/gendata.go
  pkg/v2/tkr/util/topology/cluster.go
  pkg/v2/tkr/webhook/cluster/tkr-resolver/cluster/cluster.go
  pkg/v2/tkr/webhook/cluster/tkr-resolver/cluster/cluster_test.go
Labels: ok-to-merge, cla-not-required

#3178 Add automation tests for upgrade aws cluster with custom clusterbootstrap
  pkg/v1/tkg/test/tkgctl/aws_cc/aws_cc_calico_test.go
  pkg/v1/tkg/test/tkgctl/aws_cc/aws_cc_custom_cb_test.go
  pkg/v1/tkg/test/tkgctl/aws_cc/aws_cc_tkrresolver_and_upgrade_test.go
  pkg/v1/tkg/test/tkgctl/aws_cc/aws_cc_tkrresolver_test.go
  pkg/v1/tkg/test/tkgctl/aws_cc/aws_cc_upgrade_calico_test.go
  pkg/v1/tkg/test/tkgctl/shared/e2e_common.go
  pkg/v1/tkg/test/tkgctl/shared/e2e_common_cc.go
  pkg/v1/tkg/test/tkgctl/shared/package.go
  pkg/v1/tkg/test/tkgctl/shared/tkrresolver_cc.go
Labels: ok-to-merge, cla-not-required

#3185 Turns on metadata versioning for addons-manager package
  packages/addons-manager/metadata.yaml
Labels: ok-to-merge, cla-not-required

#3170 Fix Question mark prompt color
  pkg/v1/cli/component/prompt.go
  pkg/v1/cli/component/prompt_test.go
Labels: kind/bug, ok-to-merge, cla-not-required, area/core-cli

#3221 Update codepwners of /cmd/cli/plugin/package/kctrl
  CODEOWNERS
Labels: ok-to-merge, cla-not-required

#3216 Create standalone go module for addon config apis
  Makefile
  addons/README.md
  addons/controllers/antrea/antreaconfig_controller.go
  addons/controllers/antrea/antreaconfig_util.go
  addons/controllers/antreaconfig_controller_test.go
  addons/controllers/calico/calicoconfig_controller.go
  addons/controllers/calico/calicoconfig_utils.go
  addons/controllers/calicoconfig_controller_test.go
  addons/controllers/clusterbootstrap_controller_test.go
  addons/controllers/cpi/vspherecpiconfig_controller.go
  addons/controllers/cpi/vspherecpiconfig_utils.go
  addons/controllers/csi/vspherecsiconfig_controller.go
  addons/controllers/csi/vspherecsiconfig_utils.go
  addons/controllers/suite_test.go
  addons/controllers/vspherecpiconfig_controller_test.go
  addons/controllers/vspherecsiconfig_controller_test.go
  addons/go.mod
  addons/main.go
  addons/pkg/constants/constants.go
  addons/pkg/util/clusterbootstrapclone/clusterbootstrapclone_test.go
  addons/pkg/util/gvr_helper_test.go
  addons/predicates/addon_config_test.go
  addons/webhooks/webhooks_suite_test.go
  apis/addonconfigs/Makefile
  apis/addonconfigs/cni/v1alpha1/antreaconfig_types.go
  apis/addonconfigs/cni/v1alpha1/antreaconfig_webhook.go
  apis/addonconfigs/cni/v1alpha1/calicoconfig_types.go
  apis/addonconfigs/cni/v1alpha1/calicoconfig_webhook.go
  apis/addonconfigs/cni/v1alpha1/groupversion_info.go
  apis/addonconfigs/cni/v1alpha1/zz_generated.deepcopy.go
  apis/addonconfigs/config/crd/bases/cni.tanzu.vmware.com_antreaconfigs.yaml
  apis/addonconfigs/config/crd/bases/cni.tanzu.vmware.com_calicoconfigs.yaml
  apis/addonconfigs/config/crd/bases/cpi.tanzu.vmware.com_vspherecpiconfigs.yaml
  apis/addonconfigs/config/crd/bases/csi.tanzu.vmware.com_vspherecsiconfigs.yaml
  apis/addonconfigs/cpi/v1alpha1/groupversion_info.go
  apis/addonconfigs/cpi/v1alpha1/vspherecpiconfig_types.go
  apis/addonconfigs/cpi/v1alpha1/zz_generated.deepcopy.go
  apis/addonconfigs/csi/v1alpha1/groupversion_info.go
  apis/addonconfigs/csi/v1alpha1/vspherecsiconfig_types.go
  apis/addonconfigs/csi/v1alpha1/zz_generated.deepcopy.go
  apis/addonconfigs/go.mod
  apis/addonconfigs/go.sum
  apis/addonconfigs/hack/boilerplate.go.txt
  apis/cni/Makefile
  apis/cpi/Makefile
  apis/cpi/go.mod
  apis/cpi/go.sum
  go.mod
  packages/addons-manager/bundle/config/upstream/addonconfigscrds/cni.tanzu.vmware.com_antreaconfigs.yaml
  packages/addons-manager/bundle/config/upstream/addonconfigscrds/cni.tanzu.vmware.com_calicoconfigs.yaml
  packages/addons-manager/bundle/config/upstream/addonconfigscrds/cpi.tanzu.vmware.com_vspherecpiconfigs.yaml
  packages/addons-manager/bundle/config/upstream/addonconfigscrds/csi.tanzu.vmware.com_vspherecsiconfigs.yaml
  packages/addons-manager/vendir.lock.yml
  packages/addons-manager/vendir.yml
Labels: ok-to-merge, cla-not-required
