Repository vmware-tanzu/tanzu-framework, pull requests merged in 2022-09, with the labels that each got.

#3240 Add core reviewers as CODEOWNER for package/kctrl as well
  CODEOWNERS
Labels: ok-to-merge, cla-not-required

#3246 Update BOM retrieval version to v0.26.0
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#3249 Update BOM retrieval version to v0.27.0-dev
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#3227 Fix make build-cli-with-oci-discovery
  Makefile
Labels: kind/bug, ok-to-merge, cla-not-required, area/core-cli

#3261 Provide automatic buildinfo for plugins
  cli/runtime/buildinfo/buildinfo.go
  pkg/v1/builder/template/plugintemplates/Makefile.tmpl
  pkg/v1/builder/template/plugintemplates/main.go.tmpl
Labels: ok-to-merge, cla-not-required

#2950 Adding support for TMC-Plugin discovery
  cli/runtime/config/clientconfig.go
  cli/runtime/config/clientconfig_test.go
  config/crd/bases/config.tanzu.vmware.com_clientconfigs.yaml
  hack/embed-pinniped-binary.sh
  pkg/v1/cli/artifact/http.go
  pkg/v1/cli/command/core/discovery_source.go
  pkg/v1/cli/command/core/discovery_source_test.go
  pkg/v1/cli/pluginmanager/manager_test.go
  pkg/v1/config/defaults.go
Labels: kind/feature, ok-to-merge, cla-not-required, area/core-cli

#3259 Update Makefile and add docs to `cli/runtime` module
  cli/runtime/Makefile
  cli/runtime/README.md
  cli/runtime/docs/README.md
  cli/runtime/hack/tools/Makefile
  cli/runtime/hack/tools/go.mod
  cli/runtime/hack/tools/go.sum
  cli/runtime/hack/tools/main.go
  cli/runtime/hack/tools/tools.go
Labels: ok-to-merge, cla-not-required, area/core-cli

#3264 Remove `tkgconfigpaths.DefaultTKGBOMRepo` and `tkgconfigpaths.DefaultTKGCompatibilityPath` dependency from `pkg/v1/config`
  apis/config/v1alpha1/clientconfig_types.go
  cli/runtime/config/clientconfig.go
  pkg/v1/config/bom.go
  pkg/v1/tkg/tkgconfigupdater/ensure.go
Labels: area/plugin, ok-to-merge, cla-not-required, area/core-cli

#3285 Correct go module name in cli/runtime/hack/tools
  cli/runtime/hack/tools/go.mod
Labels: kind/bug, ok-to-merge, cla-not-required

#3254 Adding CAPD CC docker tests to CI workflow
  .github/workflows/tkg_integration_tests_clusterclass.yaml
  packages/tkg-clusterclass-docker/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass/bundle/config/object-propagation/deployment.yaml
  pkg/v1/providers/infrastructure-docker/v1.1.5/cconly/base.yaml
Labels: ok-to-merge, cla-not-required

#3192 Update generate-all-docs command logic to fetch installed plugins
  cli/runtime/plugin/doc.go
  pkg/v1/cli/catalog.go
  pkg/v1/cli/command/core/doc.go
  pkg/v1/cli/pluginmanager/manager.go
  pkg/v1/cli/pluginmanager/manager_test.go
Labels: ok-to-merge, cla-not-required

#3126 CLI: Add target separation
  apis/cli/go.mod
  apis/cli/go.sum
  apis/cli/v1alpha1/catalog_types.go
  apis/cli/v1alpha1/zz_generated.deepcopy.go
  apis/config/v1alpha1/clientconfig.go
  apis/config/v1alpha1/clientconfig_types.go
  cli/runtime/config/conversion.go
  config/crd/bases/cli.tanzu.vmware.com_catalogs.yaml
  config/crd/bases/config.tanzu.vmware.com_clientconfigs.yaml
  docs/cli/cli-architecture.md
  pkg/v1/cli/catalog/catalog.go
  pkg/v1/cli/command/core/init.go
  pkg/v1/cli/command/core/root.go
  pkg/v1/config/discovery.go
Labels: ok-to-merge, area/ux, cla-not-required, area/core-cli

#3313 Skip running cc based pipelines if PR is from a fork
  .github/workflows/tkg_integration_tests_clusterclass.yaml
Labels: kind/failing-test, ok-to-merge, cla-not-required

#3297 Update the BOM retrieval version to v0.25.1
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#3326 Fix lint error
  pkg/v1/providers/tests/clustergen/README_ccgen.md
Labels: ok-to-merge, cla-not-required

#3329 Update support-process.md
  docs/community/support-process.md
Labels: ok-to-merge, cla-not-required

#3280 Decouple addons module from tanzu-framework
  addons/Makefile
  addons/controllers/addon_controller.go
  addons/controllers/addon_reconcilers.go
  addons/controllers/app_reconciler.go
  addons/controllers/certificates_test.go
  addons/controllers/cluster_pause_webhook_test.go
  addons/controllers/clusterbootstrap_controller.go
  addons/controllers/clusterbootstrap_controller_test.go
  addons/controllers/package_reconciler.go
  addons/controllers/packageinstallstatus_controller.go
  addons/controllers/suite_test.go
  addons/controllers/webhooks_test.go
  addons/fakegen/fakegen.go
  addons/go.mod
  addons/go.sum
  addons/hack/tools/go.mod
  addons/hack/tools/go.sum
  addons/hack/tools/main.go
  addons/hack/tools/tools.go
  addons/main.go
  addons/pkg/buildinfo/buildvar.go
  addons/pkg/constants/constants.go
  addons/pkg/fakeclusterclient/crtclusterclient.go
  addons/pkg/util/addon_util.go
  addons/pkg/util/bom_util.go
  addons/pkg/util/cluster_util.go
  addons/pkg/util/tkr_util_test.go
  addons/pkg/webhooks/certificates.go
  addons/pkg/webhooks/certificates_test.go
  addons/pkg/webhooks/doc.go
  addons/pkg/webhooks/webhooks.go
  addons/pkg/webhooks/webhooks_suite_test.go
  addons/test/testutil/test_helpers.go
  addons/webhooks/cluster_pause_webhook.go
  addons/webhooks/cluster_pause_webhook_test.go
  apis/run/go.mod
  apis/run/pkg/tkr/v1/bom.go
  apis/run/pkg/tkr/v1/bommetadata.go
  apis/run/pkg/tkr/v1/doc.go
  cmd/cli/plugin/tkr/v1alpha1/os.go
  go.mod
  go.sum
  pkg/v1/tkr/controllers/source/helper.go
  pkg/v1/tkr/controllers/source/tkr_source_controller.go
  pkg/v1/tkr/pkg/registry/client_integ_test.go
  pkg/v2/tkr/controller/tkr-source/compatibility/reconciler.go
  pkg/v2/tkr/controller/tkr-source/fetcher/fetcher.go
Labels: kind/refactor, ok-to-merge, cla-not-required

#3345 Fill plugin buildinfo variables
  common.mk
Labels: ok-to-merge, cla-not-required

#3291 Added feedback messages for successful execution of commands
  cli/core/pkg/command/discovery_source.go
  cli/core/pkg/command/plugin_manager.go
  cli/core/pkg/command/repo.go
Labels: ok-to-merge, cla-not-required

#3354 Run cli/runtime unit tests as part of `make test` target
  Makefile
  cli/runtime/config/context_test.go
Labels: kind/refactor, area/testing, ok-to-merge, cla-not-required

#3328 Refactor test plugin
  cmd/cli/plugin-admin/test/go.mod
  cmd/cli/plugin-admin/test/go.sum
  cmd/cli/plugin-admin/test/main.go
Labels: kind/refactor, ok-to-merge, cla-not-required

#3356 Fix 'go vet' related issues
  cmd/cli/plugin/login/main.go
  pkg/v1/tkg/test/tkgctl/shared/tkrresolver_cc.go
Labels: ok-to-merge, cla-not-required

#3360 Fix recv_providers github workflow
  .github/workflows/recv_providers.yaml
Labels: CI, area/testing, ok-to-merge, cla-not-required

#3374 Remove go mod tidy from builder
  cmd/cli/plugin-admin/test/go.sum
  cmd/cli/plugin/login/go.sum
  pkg/v1/builder/command/cli_compile.go
Labels: kind/bug, ok-to-merge, cla-not-required

#3382 Update addons doc for customization of configs
  addons/README.md
Labels: ok-to-merge, cla-not-required

#3384 Add README for `packages`
  packages/README.md
Labels: ok-to-merge, cla-not-required

#3428 Setting IsOfficialBuild variable inside tkg module during build time
  Makefile
  cli/core/Makefile
Labels: kind/refactor, ok-to-merge, cla-not-required

#3430 Removing tkrtypes directory by moving in required code to registry package
  tkg/registry/client_integ_test.go
  tkg/registry/util_test.go
  tkg/tkrtypes/bommetadata.go
  tkg/tkrtypes/doc.go
Labels: kind/refactor, ok-to-merge, cla-not-required

#3229 Graceful upgrade of addons-manager
  tkg/managementcomponents/management_component_install.go
  tkg/managementcomponents/management_component_install_test.go
Labels: ok-to-merge, cla-not-required

#2748 VSphere Template Resolver: Cluster Webhook
  go.mod
  pkg/v2/tkr/util/fakes/templateresolver.go
  pkg/v2/tkr/webhook/cluster/vsphere-template-resolver/Dockerfile
  pkg/v2/tkr/webhook/cluster/vsphere-template-resolver/Makefile
  pkg/v2/tkr/webhook/cluster/vsphere-template-resolver/main.go
  pkg/v2/tkr/webhook/cluster/vsphere-template-resolver/template/resolver.go
  pkg/v2/tkr/webhook/cluster/vsphere-template-resolver/template/resolver_test.go
  pkg/v2/tkr/webhook/cluster/vsphere-template-resolver/template/vcenter.go
  pkg/v2/tkr/webhook/cluster/vsphere-template-resolver/templateresolver/interface.go
  pkg/v2/tkr/webhook/cluster/vsphere-template-resolver/templateresolver/resolver_impl.go
  pkg/v2/tkr/webhook/cluster/vsphere-template-resolver/templateresolver/resolver_impl_test.go
  pkg/v2/tkr/webhook/cluster/vsphere-template-resolver/templateresolver/types.go
  pkg/v2/tkr/webhook/cluster/vsphere-template-resolver/templateresolver/types_test.go
Labels: ok-to-merge, cla-not-required

#3323 Fix flaky package plugin tests
  cmd/cli/plugin/package/test/package_plugin_integration_test.go
Labels: ok-to-merge, cla-not-required

#3318 CPIConfigController also Enqueue cluster event
  addons/controllers/cpi/vspherecpiconfig_controller.go
  addons/controllers/cpi/vspherecpiconfig_utils.go
Labels: ok-to-merge, cla-not-required

#3366 update multicastInterface to multicastInterfaces
  addons/controllers/antrea/antreaconfig_util.go
  apis/addonconfigs/cni/v1alpha1/antreaconfig_types.go
  apis/addonconfigs/cni/v1alpha1/groupversion_info.go
  apis/addonconfigs/cni/v1alpha1/zz_generated.deepcopy.go
  apis/addonconfigs/config/crd/bases/cni.tanzu.vmware.com_antreaconfigs.yaml
  apis/addonconfigs/cpi/v1alpha1/groupversion_info.go
  apis/addonconfigs/csi/v1alpha1/groupversion_info.go
  packages/addons-manager/bundle/config/upstream/addonconfigscrds/cni.tanzu.vmware.com_antreaconfigs.yaml
Labels: ok-to-merge, cla-not-required

#3441 fix lint errors in featuregates and package-tools modules
  featuregates/client/pkg/featuregateclient/client.go
  featuregates/client/pkg/featuregateclient/doc.go
  hack/packages/package-tools/cmd/carvelTools.go
  hack/packages/package-tools/cmd/prepare.go
  hack/packages/package-tools/cmd/vendir-sync.go
  packages/cliplugins/vendir.lock.yml
  packages/featuregates/vendir.lock.yml
Labels: ok-to-merge, cla-not-required

#3289 Update the builder plugin to make version flag optional and add new 'build-plugin-local' make target
  Makefile
  cmd/cli/plugin-admin/builder/cli.go
  cmd/cli/plugin-admin/builder/command/cli_compile.go
Labels: ok-to-merge, cla-not-required

#3300 VSphereCPIConfig derives the insecure flags from the TLS thumbprint in cluster variable.
  addons/controllers/cpi/vspherecpiconfig_utils.go
  apis/addonconfigs/config/crd/bases/cpi.tanzu.vmware.com_vspherecpiconfigs.yaml
  apis/addonconfigs/cpi/v1alpha1/vspherecpiconfig_types.go
  packages/addons-manager/bundle/config/upstream/addonconfigscrds/cpi.tanzu.vmware.com_vspherecpiconfigs.yaml
Labels: ok-to-merge, cla-not-required

#3422 Create a separate go module for pinniped-auth plugin
  cmd/cli/plugin/pinniped-auth/go.mod
  cmd/cli/plugin/pinniped-auth/go.sum
  cmd/cli/plugin/pinniped-auth/login.go
  cmd/cli/plugin/pinniped-auth/login_test.go
  cmd/cli/plugin/pinniped-auth/main.go
  go.mod
Labels: kind/refactor, area/plugin, ok-to-merge, cla-not-required, area/iam

#3320 Fix Not Found errors in vSphere CPI/CSI Config reconciliation
  addons/controllers/cpi/vspherecpiconfig_controller.go
  addons/controllers/cpi/vspherecpiconfig_utils.go
  addons/controllers/csi/vspherecsiconfig_controller.go
  addons/controllers/csi/vspherecsiconfig_utils.go
  addons/controllers/testdata/test-vsphere-cpi-non-paravirtual.yaml
  addons/controllers/testdata/test-vsphere-cpi-paravirtual-clusters-same-name.yaml
  addons/controllers/testdata/test-vsphere-csi-non-paravirtual-minimal.yaml
  addons/controllers/testdata/test-vsphere-csi-non-paravirtual.yaml
  addons/controllers/testdata/test-vsphere-csi-paravirtual.yaml
  addons/controllers/utils/utils.go
  addons/controllers/vspherecpiconfig_controller_test.go
  addons/controllers/vspherecsiconfig_controller_test.go
  addons/pkg/constants/constants.go
Labels: ok-to-merge, cla-not-required

#3432 Fix context unit tests
  cli/runtime/config/context_test.go
Labels: area/testing, ok-to-merge, cla-not-required

#3440 Clusterbootstrap_controller should watch providers in core packages
  addons/Makefile
  addons/controllers/clusterbootstrap_controller.go
  addons/controllers/clusterbootstrap_controller_test.go
  addons/controllers/testdata/test-cluster-bootstrap-5.yaml
Labels: ok-to-merge, cla-not-required

#3352 Make secret plugin a separate go module
  cmd/cli/plugin/package/go.mod
  cmd/cli/plugin/secret/go.mod
  cmd/cli/plugin/secret/go.sum
  cmd/cli/plugin/secret/main.go
  go.mod
  tkg/go.mod
Labels: kind/refactor, ok-to-merge, cla-not-required

#3469 Add automation tests for admission webhook
  addons/controllers/certificates_test.go
  addons/controllers/suite_test.go
  addons/controllers/webhooks_test.go
  addons/pkg/webhooks/certificates_test.go
  tkg/test/tkgctl/aws_cc/aws_cc_antrea_test.go
  tkg/test/tkgctl/shared/e2e_common.go
  tkg/test/tkgctl/shared/e2e_common_cc.go
  tkg/test/tkgctl/shared/package.go
  tkg/test/tkgctl/shared/tkrresolver_cc.go
  tkg/test/tkgctl/shared/utils.go
  tkg/test/tkgctl/tkgs_cc/tkgs_cc_workload_cluster_test.go
Labels: ok-to-merge, cla-not-required

#3433 Reverting tools dependency to v0.1.10
  Makefile
  capabilities/client/pkg/discovery/tkg/capabilities_test.go
  cli/core/pkg/auth/tkg/cluster_pinniped_info.go
  cli/core/pkg/auth/tkg/cluster_pinniped_info_test.go
  cli/core/pkg/auth/utils/kubeconfig/kubeconfig.go
  cli/core/pkg/cli/catalog_test.go
  cli/core/pkg/cluster/client.go
  cli/core/pkg/command/config.go
  cli/core/pkg/command/doc.go
  cli/core/pkg/command/plugin_manager.go
  cli/core/pkg/command/root.go
  cli/core/pkg/command/update.go
  cli/core/pkg/config/bom.go
  cli/core/pkg/config/config.go
  cli/core/pkg/configpaths/filepaths.go
  cli/core/pkg/constants/config_variables.go
  cli/core/pkg/pluginmanager/manager.go
  cli/core/pkg/pluginmanager/manager_test.go
  cli/core/pkg/utils/files.go
  cli/runtime/apis/config/v1alpha1/clientconfig.go
  cli/runtime/apis/config/v1alpha1/clientconfig_types.go
  cli/runtime/command/deprecation.go
  cli/runtime/component/prompt.go
  cli/runtime/component/prompt_test.go
  cli/runtime/config/clientconfig.go
  cli/runtime/config/conversion.go
  cli/runtime/config/lock.go
  cli/runtime/test/framework.go
  cmd/cli/plugin/cluster/available_upgrade.go
  cmd/cli/plugin/cluster/available_upgrade_test.go
  cmd/cli/plugin/cluster/get_machinehealthcheck_control_plane.go
  cmd/cli/plugin/cluster/get_machinehealthcheck_node.go
  cmd/cli/plugin/cluster/upgrade_test.go
  hack/tools/go.mod
  hack/tools/go.sum
Labels: ok-to-merge, cla-not-required

#3368 Fix bootstrap packages got deployed without their configuration
  addons/controllers/clusterbootstrap_controller.go
  addons/controllers/clusterbootstrap_controller_test.go
  addons/controllers/testdata/test-cluster-bootstrap-1.yaml
  addons/controllers/testdata/test-cluster-bootstrap-2.yaml
  addons/controllers/testdata/test-cluster-bootstrap-3.yaml
  addons/controllers/testdata/test-cluster-bootstrap-4.yaml
  addons/controllers/testdata/test-cluster-bootstrap-5.yaml
Labels: ok-to-merge, cla-not-required

#3377 Enqueue AddonConfig if Cluster event happens
  addons/controllers/antrea/antreaconfig_controller.go
  addons/controllers/antrea/antreaconfig_util.go
  addons/controllers/calico/calicoconfig_controller.go
  addons/controllers/calico/calicoconfig_utils.go
  addons/controllers/cpi/vspherecpiconfig_controller.go
  addons/controllers/cpi/vspherecpiconfig_utils.go
  addons/controllers/csi/vspherecsiconfig_controller.go
  addons/controllers/csi/vspherecsiconfig_utils.go
  addons/controllers/kapp-controller/kappcontrollerconfig_handlers.go
Labels: ok-to-merge, cla-not-required

#3173 Fix template issues in vsphere clusterclass implementation
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/overlay.yaml
  pkg/v1/providers/config_default.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.1/cconly/base.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.1/cconly/overlay.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.1/yttcc/overlay.yaml
  pkg/v1/providers/yttcb/clusterbootstrap.yaml
Labels: ok-to-merge, cla-not-required

#3276 Support test plugins with `context-aware-cli-for-plugins` feature-flag enabled
  .github/workflows/plugin_tests.yaml
  cli/core/pkg/artifact/http.go
  cli/core/pkg/artifact/interface.go
  cli/core/pkg/artifact/local.go
  cli/core/pkg/artifact/local_test.go
  cli/core/pkg/artifact/oci.go
  cli/core/pkg/artifact/test/local/v0.0.1/tanzu-plugin-darwin_amd64
  cli/core/pkg/artifact/test/local/v0.0.1/test/tanzu-test-plugin-darwin_amd64
  cli/core/pkg/artifact/test/local/v0.0.2/tanzu-plugin-darwin_amd64
  cli/core/pkg/artifact/test/local/v0.0.2/test/extra_file
  cli/core/pkg/artifact/test/local/v0.0.2/test/tanzu-test-plugin-darwin_amd64
  cli/core/pkg/cli/runner.go
  cli/core/pkg/command/plugin_manager.go
  cli/core/pkg/distribution/artifact.go
  cli/core/pkg/distribution/interface.go
  cli/core/pkg/pluginmanager/manager.go
  cli/core/pkg/pluginmanager/manager_test.go
  cmd/cli/plugin-admin/test/go.sum
  cmd/cli/plugin-admin/test/main.go
Labels: ok-to-merge, cla-not-required, area/dx, area/core-cli

#3480 Bump kapp-controller package to version 0.41.2
  pkg/v1/providers/vendir.lock.yml
  pkg/v1/providers/vendir.yml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.41.2/bundle/config/overlays/change-namespace.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.41.2/bundle/config/overlays/update-configmap.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.41.2/bundle/config/overlays/update-crds.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.41.2/bundle/config/overlays/update-deployment.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.41.2/bundle/config/overlays/update-strategy-overlay.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.41.2/bundle/config/upstream/kapp-controller.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.41.2/bundle/config/values.star
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.41.2/bundle/config/values.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/kapp-controller.lib.yaml
Labels: ok-to-merge, cla-not-required

#3502 replace dummy capabilities client with actual one
  cli/core/go.mod
  cli/core/go.sum
  cli/core/pkg/cluster/client.go
  cli/core/pkg/cluster/discovery/cluster_gvr.go
  cli/core/pkg/cluster/discovery/discovery.go
  cmd/cli/plugin-admin/builder/go.mod
  cmd/cli/plugin-admin/builder/go.sum
  cmd/cli/plugin-admin/test/go.mod
  cmd/cli/plugin-admin/test/go.sum
  cmd/cli/plugin/login/go.mod
  cmd/cli/plugin/login/go.sum
Labels: kind/refactor, ok-to-merge, cla-not-required

#3450 Fix linter issues
  cmd/cli/plugin-admin/test/test/main.go
  cmd/cli/plugin/login/main.go
  tkg/azure/client.go
  tkg/azure/client_test.go
  tkg/client/delete_region.go
  tkg/client/get_cluster_pinniped_info.go
  tkg/client/init.go
  tkg/client/machine_deployment_cc.go
  tkg/client/machine_deployment_cc_test.go
  tkg/client/package_helper.go
  tkg/client/package_helper_test.go
  tkg/client/upgrade_cluster.go
  tkg/client/upgrade_cluster_test.go
  tkg/client/upgrade_region.go
  tkg/client/utils.go
  tkg/client/utils_test.go
  tkg/client/validate.go
  tkg/clusterclient/clusterclient.go
  tkg/constants/cluster_internal.go
  tkg/managementcomponents/helper_test.go
  tkg/managementcomponents/management_component_install.go
  tkg/managementcomponents/management_component_install_test.go
  tkg/tkgctl/compatibility.go
  tkg/tkgctl/compatibility_test.go
  tkg/tkgctl/create_cluster.go
  tkg/tkgctl/create_cluster_test.go
  tkg/tkgctl/featuregate_helper.go
  tkg/tkgctl/get_cluster.go
  tkg/tkr/pkg/constants/constants.go
Labels: ok-to-merge, cla-not-required

#3501 Fixing the ClusterClass CI
  pkg/v1/providers/yttcb/clusterbootstrap.yaml
  tkg/test/tkgctl/shared/package.go
Labels: CI, area/testing, ok-to-merge, cla-not-required

#3395 Read config variable from mgmt cluster into cleanup cluster when deleting mgmt cluster
  tkg/client/delete_region.go
  tkg/client/management_components.go
Labels: ok-to-merge, cla-not-required

#3507 Fix to create CC cluster on vSphere
  pkg/v1/providers/yttcb/clusterbootstrap.yaml
Labels: ok-to-merge, cla-not-required

#3515 Remove pkg/v1/grpc pkg/v1/encoding packages
  go.mod
  go.sum
  pkg/v1/encoding/proto/conversion.go
  pkg/v1/encoding/proto/doc.go
  pkg/v1/grpc/dial.go
  pkg/v1/grpc/doc.go
Labels: kind/cleanup, ok-to-merge, cla-not-required
