Repository vmware-tanzu/tanzu-framework, pull requests merged in 2022-11, with the labels that each got.

#3207 Use kctrl command tree by default in package plugin
  cli/runtime/config/featureflags.go
  cmd/cli/plugin/package/test/lib/package_plugin_kctrl.go
  cmd/cli/plugin/package/test/package_plugin_integration_test.go
Labels: ok-to-merge, cla-not-required

#3764 Remove extra space in no_proxy definition
  packages/tkg-clusterclass-azure/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  providers/infrastructure-azure/v1.5.3/cconly/base.yaml
  providers/infrastructure-vsphere/v1.4.1/cconly/base.yaml
Labels: ok-to-merge, cla-not-required

#3282 Azure cc test
  packages/tkg-clusterclass-azure/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-azure/bundle/config/upstream/overlay.yaml
  packages/tkg-clusterclass-azure/bundle/config/values.yaml
  providers/infrastructure-azure/v1.5.3/cconly/base.yaml
  providers/infrastructure-azure/v1.5.3/cconly/overlay.yaml
  providers/infrastructure-azure/v1.5.3/yttcc/overlay.yaml
Labels: ok-to-merge, cla-not-required

#3648 Adding cert-manager v1.9.1 maifest in providers
  providers/cert-manager/v1.9.1/cert-manager.yaml
  providers/config.yaml
Labels: ok-to-merge, cla-not-required, area/packages

#3808 set tls min version only when utkg is enabled
  addons/main.go
Labels: ok-to-merge, cla-not-required

#3811 set tls-min-version only when clusterbootstrap is enabled (#3808)
  addons/main.go
Labels: ok-to-merge, cla-not-required

#3380 Add --all-namespaces to tanzu cluster list command
  cmd/cli/plugin/cluster/list.go
  tkg/tkgctl/get_cluster.go
  tkg/tkgctl/get_cluster_test.go
Labels: ok-to-merge, cla-not-required

#3796 Use -b for imgpkg command when copying package bundles
  hack/gen-publish-images-totar.sh
Labels: ok-to-merge, cla-not-required

#3780 Remove controlPlaneEndpoint and identityRef in VSphereClusterTemplate
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  providers/infrastructure-vsphere/v1.4.1/cconly/base.yaml
Labels: ok-to-merge, cla-not-required

#3765 remove ipv6 workaround from post kubeadm
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  providers/infrastructure-vsphere/v1.4.1/cconly/base.yaml
  providers/infrastructure-vsphere/v1.4.1/ytt/overlay-windows.yaml
  providers/infrastructure-vsphere/v1.4.1/ytt/overlay.yaml
Labels: ok-to-merge, cla-not-required

#3829 Updates CAPV version to v1.3.5
  addons/go.mod
  addons/go.sum
  go.mod
  go.sum
  packages/cluster-api-provider-vsphere/bundle/config/upstream/infrastructure-components-supervisor.yaml
  packages/cluster-api-provider-vsphere/bundle/config/upstream/infrastructure-components.yaml
  packages/cluster-api-provider-vsphere/vendir.yml
  pkg/v1/providers/config.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.5/cconly/base.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.5/cconly/overlay.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.5/cluster-template-definition-dev.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.5/cluster-template-definition-devcc.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.5/cluster-template-definition-prod.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.5/cluster-template-definition-prodcc.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.5/clusterclass-tkg-vsphere-default.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.5/infrastructure-components-supervisor.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.5/infrastructure-components.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.5/metadata.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.5/ytt/base-template.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.5/ytt/overlay-windows.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.5/ytt/overlay.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.5/yttcc/base-template.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.5/yttcc/overlay.yaml
  pkg/v1/providers/tests/clustergen/param_models/cluster_optional.model
  pkg/v1/providers/tests/clustergen/param_models/cluster_vsphere.model
  pkg/v1/providers/tests/unit/ip_family_test.go
Labels: ok-to-merge, cla-not-required

#3828 Change the version string 20.04 to 2004 returned from the ova metadata
  tkg/vsphere-template-resolver/templateresolver/resolver_impl.go
Labels: ok-to-merge, cla-not-required

#3549 Migrate feature gate resources from ClusterResourceSet
  packages/featuregates/bundle/config/upstream/crds/config.tanzu.vmware.com_featuregates.yaml
  packages/featuregates/bundle/config/upstream/crds/config.tanzu.vmware.com_features.yaml
  packages/featuregates/bundle/config/upstream/default-featuregate-cr.yaml
  packages/featuregates/bundle/config/upstream/tanzu-featuregates-manager.yaml
  packages/featuregates/vendir.lock.yml
  packages/featuregates/vendir.yml
  providers/ytt/02_addons/management-packages/featuregates/add_default_featuregate_cr.yaml
  providers/ytt/02_addons/management-packages/featuregates/add_featuregates_package.yaml
Labels: ok-to-merge, cla-not-required

#3665 Decouple Feature-Flags from cli/runtime library and move to it to plugin specific code
  Makefile
  cli/core/Makefile
  cli/core/docs/cli/config-features.md
  cli/core/pkg/catalog/catalog_test.go
  cli/core/pkg/command/config.go
  cli/core/pkg/command/context.go
  cli/core/pkg/command/doc.go
  cli/core/pkg/command/init.go
  cli/core/pkg/command/plugin_manager.go
  cli/core/pkg/command/root.go
  cli/core/pkg/command/update.go
  cli/core/pkg/config/featureflags.go
  cli/core/pkg/config/features.go
  cli/core/pkg/config/features_test.go
  cli/core/pkg/config/init.go
  cli/core/pkg/pluginmanager/manager.go
  cli/runtime/apis/cli/v1alpha1/catalog_types.go
  cli/runtime/apis/cli/v1alpha1/zz_generated.deepcopy.go
  cli/runtime/config/featureflags.go
  cmd/cli/plugin/cluster/featureflags.go
  cmd/cli/plugin/cluster/main.go
  cmd/cli/plugin/login/main.go
  cmd/cli/plugin/managementcluster/create.go
  cmd/cli/plugin/managementcluster/featureflags.go
  cmd/cli/plugin/managementcluster/main.go
  cmd/cli/plugin/managementcluster/post_install_hook.go
  cmd/cli/plugin/managementcluster/upgrade.go
  cmd/cli/plugin/package/featureflags.go
  cmd/cli/plugin/package/main.go
  cmd/cli/plugin/tkr/featureflags.go
  cmd/cli/plugin/tkr/main.go
  tkg/aws/client.go
  tkg/client/cluster.go
  tkg/client/common.go
  tkg/client/config.go
  tkg/client/delete_region.go
  tkg/client/init.go
  tkg/client/upgrade_cluster.go
  tkg/client/upgrade_region.go
  tkg/client/utils.go
  tkg/client/utils_test.go
  tkg/client/validate.go
  tkg/constants/featureflags.go
  tkg/tkgctl/create_cluster.go
  tkg/tkgctl/create_cluster_test.go
Labels: ok-to-merge, cla-not-required, docs-triage-needed

#3812 Change the proxy format in CC.
  addons/controllers/clusterbootstrap_controller.go
  addons/controllers/clusterbootstrap_controller_test.go
  addons/controllers/testdata/test-cluster-bootstrap-1.yaml
  addons/controllers/testdata/test-cluster-bootstrap-6.yaml
  addons/controllers/testdata/test-cluster-legacy.yaml
  addons/pkg/util/cluster_variable_util.go
  addons/pkg/util/cluster_variable_util_test.go
  packages/tkg-clusterclass-aws/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-azure/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  providers/infrastructure-aws/v2.0.0-beta.1/cconly/base.yaml
  providers/infrastructure-aws/v2.0.0-beta.1/yttcc/overlay.yaml
  providers/infrastructure-azure/v1.5.3/cconly/base.yaml
  providers/infrastructure-azure/v1.5.3/yttcc/overlay.yaml
  providers/infrastructure-vsphere/v1.4.1/cconly/base.yaml
  providers/infrastructure-vsphere/v1.4.1/yttcc/overlay.yaml
  providers/yttcb/clusterbootstrap.yaml
  providers/yttcc/lib/config_variable_association.star
  tkg/constants/clusterclass_mapping.go
  tkg/fakes/config/cluster_aws.yaml
  tkg/fakes/config/cluster_aws_multipleObjects.yaml
  tkg/fakes/config/cluster_azure.yaml
  tkg/fakes/config/cluster_vsphere.yaml
  tkg/tkgctl/create_cluster_test.go
  tkg/tkgctl/helpers.go
Labels: ok-to-merge, cla-not-required

#3833 Fix vCenter connection validation error on classy cluster manifest
  tkg/fakes/config/cluster_vsphere.yaml
  tkg/tkgctl/create_cluster.go
  tkg/tkgctl/helpers.go
  tkg/tkgctl/helpers_test.go
Labels: ok-to-merge, cla-not-required

#3834 Azure prodcc fix
  providers/infrastructure-azure/v1.5.3/yttcc/overlay.yaml
Labels: ok-to-merge, cla-not-required

#3749 Adding missing fields in the AntreaConfig
  addons/controllers/antrea/antreaconfig_util.go
  apis/addonconfigs/cni/v1alpha1/antreaconfig_types.go
  apis/addonconfigs/cni/v1alpha1/zz_generated.deepcopy.go
  apis/addonconfigs/config/crd/bases/cni.tanzu.vmware.com_antreaconfigs.yaml
  packages/addons-manager/bundle/config/upstream/addonconfigscrds/cni.tanzu.vmware.com_antreaconfigs.yaml
Labels: ok-to-merge, cla-not-required

#3598 Topic/pxiao/add azurefile csi component
  PROJECT
  addons/config/expected/csi.tanzu.vmware.com/v1alpha1/azurefilecsiconfig/default.yaml
  addons/config/templates/csi.tanzu.vmware.com/v1alpha1/azurefilecsiconfig.yaml
  addons/config/testcases/csi.tanzu.vmware.com/v1alpha1/azurefilecsiconfig/default.yaml
  addons/controllers/azurefilecsi/azurefilecsiconfig_controller.go
  addons/controllers/azurefilecsi/azurefilecsiconfig_datavalues.go
  addons/controllers/azurefilecsi/azurefilecsiconfig_utils.go
  addons/controllers/suite_test.go
  addons/main.go
  addons/pkg/config/config.go
  addons/pkg/constants/constants.go
  apis/addonconfigs/config/crd/bases/csi.tanzu.vmware.com_azurefilecsiconfigs.yaml
  apis/addonconfigs/csi/v1alpha1/azurefilecsiconfig_types.go
  apis/addonconfigs/csi/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/config.tanzu.vmware.com_azurefilecsiconfigs.yaml
  config/crd/bases/csi.tanzu.vmware.com_azurefilecsiconfigs.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_azurefilecsiconfigs.yaml
  config/crd/patches/webhook_in_azurefilecsiconfigs.yaml
  config/rbac/azurefilecsiconfig_editor_role.yaml
  config/rbac/azurefilecsiconfig_viewer_role.yaml
  config/samples/csi_v1alpha1_azurefilecsiconfig.yaml
  packages/addons-manager/bundle/config/upstream/addonconfigscrds/csi.tanzu.vmware.com_azurefilecsiconfigs.yaml
  packages/addons-manager/vendir.yml
  providers/ytt/02_addons/public-cloud-csi/add_azurefile_csi_driver.yaml
  providers/ytt/02_addons/public-cloud-csi/file/azurefile-csi-driver_data.lib.yaml
  providers/ytt/03_customizations/add_sc.yaml
  providers/yttcb/clusterbootstrap.yaml
Labels: ok-to-merge, cla-not-required

#3848 Update BOM retrieval version to v0.25.2
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, cla-not-required

#3858 Label legacy TKRs as such
  apis/run/v1alpha3/tanzukubernetesrelease_types.go
  tkr/controller/tkr-source/main.go
  tkr/controller/tkr-source/tkr/tkr.go
  tkr/controller/tkr-source/tkr/tkr_test.go
Labels: area/api, ok-to-merge, cla-not-required, area/tkr

#3855 Adjust aws-ebs-csi-driver default namespace to kube-system
  addons/config/expected/csi.tanzu.vmware.com/v1alpha1/awsebscsiconfig/default.yaml
  addons/config/templates/csi.tanzu.vmware.com/v1alpha1/awsebscsiconfig.yaml
  addons/controllers/awsebscsi/awsescsiconfig_utils.go
  tkg/test/tkgctl/shared/e2e_common_cc.go
Labels: ok-to-merge, cla-not-required

#3674 Enable Single Node Cluster deployment via tanzu CLI
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  providers/infrastructure-vsphere/v1.4.1/cconly/base.yaml
  tkg/client/client.go
  tkg/client/cluster.go
  tkg/client/cluster_test.go
  tkg/client/get_cluster_helper.go
  tkg/client/get_cluster_test.go
  tkg/client/machine_deployment.go
  tkg/client/machine_deployment_cc.go
  tkg/client/machine_deployment_cc_test.go
  tkg/client/test_utils.go
  tkg/client/upgrade_cluster.go
  tkg/client/validate.go
  tkg/clusterclient/clusterclient.go
  tkg/clusterclient/clusterclient_test.go
  tkg/clusterclient/templates.go
  tkg/constants/featureflags.go
  tkg/fakes/clusterclient.go
  tkg/fakes/config/cluster_vsphere_snc.yaml
  tkg/fakes/config/cluster_vsphere_snc_cp_taint_true.yaml
  tkg/fakes/config/cluster_vsphere_snc_invalid_cp_taint.yaml
  tkg/fakes/config/cluster_vsphere_snc_omit_workers.yaml
  tkg/fakes/tkgconfigreaderwriterclient.go
  tkg/fakes/vcclientfactory.go
  tkg/tkgconfigreaderwriter/client.go
  tkg/tkgctl/client.go
  tkg/tkgctl/create_cluster.go
  tkg/vc/client.go
  tkg/vc/interface.go
  util/topology/cluster.go
  util/topology/cluster_test.go
Labels: ok-to-merge, cla-not-required

#3854 Oracle Support - Fix Oracle OSImage populate command.
  cmd/cli/plugin/cluster/go.mod
  cmd/cli/plugin/cluster/osimage.go
  cmd/cli/plugin/cluster/osimage_oracle.go
Labels: ok-to-merge, cla-not-required

#3870 Fix the rendering of proxy cert in CC variables
  providers/yttcc/lib/config_variable_association.star
Labels: ok-to-merge, cla-not-required

#3823 Correct the label selector of MachineDeployment in CLI to support backup/restore management cluster with Velero
  providers/infrastructure-vsphere/v1.4.1/ytt/base-template.yaml
  providers/infrastructure-vsphere/v1.4.1/ytt/overlay-windows.yaml
  providers/infrastructure-vsphere/v1.4.1/ytt/overlay.yaml
  providers/infrastructure-vsphere/ytt/vsphere-overlay.yaml
Labels: ok-to-merge, cla-not-required

#3867 Splitting jsonpatches on a conditional antrea installation for windows
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-vsphere/bundle/config/values.yaml
  providers/infrastructure-vsphere/v1.4.1/cconly/base.yaml
Labels: ok-to-merge, cla-not-required

#3637 Add Debian package build script
  cli/core/.gitignore
  cli/core/Makefile
  cli/core/hack/apt/README.md
  cli/core/hack/apt/build_package.sh
Labels: ok-to-merge, cla-not-required

#3857 add default ServiceAccount needed by capabilities controller to the package
  packages/capabilities/bundle/config/upstream/default-serviceaccount.yaml
  packages/capabilities/bundle/config/upstream/rbac.yaml
  packages/capabilities/vendir.lock.yml
  packages/capabilities/vendir.yml
Labels: ok-to-merge, cla-not-required

#3886 Oracle Support - Management cluster plugin: Add support for extra manifests
  cmd/cli/plugin/managementcluster/create.go
  tkg/client/client.go
  tkg/client/init.go
  tkg/clusterclient/clusterclient.go
  tkg/fakes/clusterclient.go
  tkg/tkgctl/init.go
Labels: ok-to-merge, cla-not-required

#3896 Fix clusterboostrap webhook to include additional packages in CB but not present in CBT
  addons/pkg/util/clusterbootstrapclone/clusterbootstrapclone.go
  addons/pkg/util/clusterbootstrapclone/clusterbootstrapclone_test.go
Labels: ok-to-merge, cla-not-required

#3906 [release-0.25] Cherry-pick: Clean up runner space for release workflows
  .github/workflows/release.yaml
  .github/workflows/release_staging.yaml
Labels: area/release, ok-to-merge, cla-not-required

#3909 fix: build plugin incorrectly combines stdout&stderr
  cmd/cli/plugin-admin/builder/command/cli_compile.go
Labels: ok-to-merge, cla-not-required

#3792 Add RPM package build script
  cli/core/Makefile
  cli/core/hack/rpm/README.md
  cli/core/hack/rpm/build_package.sh
  cli/core/hack/rpm/tanzu-cli.spec
Labels: ok-to-merge, cla-not-required

#3883 Add ipv6 localhost to /etc/hosts on ipv6 nodes
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  providers/infrastructure-vsphere/v1.4.1/cconly/base.yaml
  providers/infrastructure-vsphere/v1.4.1/ytt/overlay.yaml
  providers/tests/unit/ip_family_test.go
Labels: ok-to-merge, cla-not-required, area/networking, area/lcm

#3819 add ytt overlay customization warning message
  tkg/client/cluster.go
  tkg/client/upgrade_cluster.go
  tkg/constants/messages.go
Labels: ok-to-merge, cla-not-required

#3893 Fix missing variable count on overlay for Windows
  providers/infrastructure-vsphere/v1.4.1/yttcc/overlay.yaml
Labels: ok-to-merge, cla-not-required

#3897 Oracle Support - Add Cluster API Provider Oracle and initial ClusterClass
  apis/addonconfigs/config/crd/bases/cpi.tanzu.vmware.com_oraclecpiconfigs.yaml
  go.mod
  go.sum
  hack/providers-sync-tools/cluster-api-provider-oci/overlay/add-proxy-environment-variables.yaml
  packages/addons-manager/bundle/config/upstream/addonconfigscrds/cpi.tanzu.vmware.com_oraclecpiconfigs.yaml
  packages/addons-manager/vendir.yml
  packages/cluster-api-provider-oci/Makefile
  packages/cluster-api-provider-oci/README.md
  packages/cluster-api-provider-oci/bundle/config/overlay/add-proxy-environment-variables.yaml
  packages/cluster-api-provider-oci/bundle/config/upstream/infrastructure-components.yaml
  packages/cluster-api-provider-oci/bundle/config/upstream/metadata.yaml
  packages/cluster-api-provider-oci/bundle/config/values.yaml
  packages/cluster-api-provider-oci/metadata.yaml
  packages/cluster-api-provider-oci/package.yaml
  packages/cluster-api-provider-oci/test/unit/overlay_test.go
  packages/cluster-api-provider-oci/test/unit/unit_suite_test.go
  packages/cluster-api-provider-oci/vendir.lock.yml
  packages/cluster-api-provider-oci/vendir.yml
  packages/package-values.yaml
  packages/tkg-clusterclass-oci/Makefile
  packages/tkg-clusterclass-oci/README.md
  packages/tkg-clusterclass-oci/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-oci/bundle/config/upstream/overlay.yaml
  packages/tkg-clusterclass-oci/bundle/config/values.yaml
  packages/tkg-clusterclass-oci/metadata.yaml
  packages/tkg-clusterclass-oci/package.yaml
  packages/tkg-clusterclass-oci/vendir.lock.yml
  packages/tkg-clusterclass-oci/vendir.yml
  packages/tkg-clusterclass/bundle/config/object-propagation/deployment.yaml
  packages/tkg-clusterclass/bundle/config/packageinstalls/tkg-infra-clusterclass-pi.yaml
  packages/tkg-clusterclass/bundle/config/packageinstalls/tkg-infra-clusterclass-service-account.yaml
  packages/tkg-clusterclass/hack/sync-cc.sh
  providers/config.yaml
  providers/config_default.yaml
  providers/infrastructure-oci/v0.4.0/cconly/base.yaml
  providers/infrastructure-oci/v0.4.0/cconly/overlay.yaml
  providers/infrastructure-oci/v0.4.0/cluster-template-definition-devcc.yaml
  providers/infrastructure-oci/v0.4.0/cluster-template-definition-prodcc.yaml
  providers/infrastructure-oci/v0.4.0/clusterclass-tkg-oci-default.yaml
  providers/infrastructure-oci/v0.4.0/infrastructure-components.yaml
  providers/infrastructure-oci/v0.4.0/metadata.yaml
  providers/infrastructure-oci/v0.4.0/yttcc/base-template.yaml
  providers/infrastructure-oci/v0.4.0/yttcc/overlay.yaml
  providers/infrastructure-oci/ytt/oci-overlay.yaml
  providers/infrastructure-oci/yttcc/oci-overlay.yaml
  providers/ytt/lib/validate.star
  providers/yttcc/lib/config_variable_association.star
  tkg/client/init.go
  tkg/constants/cluster_internal.go
  tkg/constants/config_variables.go
  tkg/test/config/oracle.yaml
  tkg/tkgconfigbom/bom_types.go
Labels: ok-to-merge, cla-not-required

#3651 Add Chocolatey package build script
  cli/core/Makefile
  cli/core/hack/choco/README.md
  cli/core/hack/choco/build_package.sh
  cli/core/hack/choco/chocolateyInstall.ps1.tmpl
  cli/core/hack/choco/tanzu-cli-release.nuspec
Labels: area/release, ok-to-merge, cla-not-required, area/core-cli

#3596 prevents metric-server from taking ownership of kube-system namespace.
  providers/ytt/02_addons/metrics-server/metrics_server_secret.yaml
Labels: ok-to-merge, cla-not-required

#3910 Cleanup the core package repo when upgrading from legacy to cc capable
  addons/controllers/addon_controller.go
  addons/controllers/addon_controller_test.go
  addons/main.go
  addons/pkg/config/config.go
  tkg/client/cleanup_core_repo.go
  tkg/client/cleanup_core_repo_test.go
  tkg/client/upgrade_region.go
Labels: area/cli, area/addons, ok-to-merge, cla-not-required, area/lcm, area/cc

#3895 Ensures version suffix for addons manager
  tkg/client/management_components.go
  tkg/client/management_components_test.go
  tkg/managementcomponents/helper.go
  tkg/managementcomponents/helper_test.go
Labels: ok-to-merge, cla-not-required

#3685 Tanzu CLI Config API
  .github/workflows/plugin_tests.yaml
  cli/core/pkg/command/config.go
  cli/core/pkg/command/config_test.go
  cli/runtime/apis/config/v1alpha1/clientconfig.go
  cli/runtime/apis/config/v1alpha1/clientconfig_types.go
  cli/runtime/config/cli_discovery_sources.go
  cli/runtime/config/cli_discovery_sources_it_test.go
  cli/runtime/config/cli_discovery_sources_test.go
  cli/runtime/config/cli_options.go
  cli/runtime/config/cli_options_test.go
  cli/runtime/config/cli_repositories.go
  cli/runtime/config/cli_repositories_it_test.go
  cli/runtime/config/cli_repositories_test.go
  cli/runtime/config/clientconfig.go
  cli/runtime/config/clientconfig_factory.go
  cli/runtime/config/clientconfig_factory_test.go
  cli/runtime/config/clientconfig_test.go
  cli/runtime/config/clientconfig_typemeta.go
  cli/runtime/config/collectionutils.go
  cli/runtime/config/collectionutils_test.go
  cli/runtime/config/config_filesystem.go
  cli/runtime/config/config_keys.go
  cli/runtime/config/context.go
  cli/runtime/config/context_test.go
  cli/runtime/config/contexts.go
  cli/runtime/config/contexts_it_test.go
  cli/runtime/config/contexts_test.go
  cli/runtime/config/conversion.go
  cli/runtime/config/conversion_test.go
  cli/runtime/config/discovery_sources_node.go
  cli/runtime/config/discovery_sources_node_test.go
  cli/runtime/config/envs.go
  cli/runtime/config/envs_test.go
  cli/runtime/config/features.go
  cli/runtime/config/features_test.go
  cli/runtime/config/legacy_clientconfig.go
  cli/runtime/config/legacy_clientconfig_factory.go
  cli/runtime/config/legacy_clientconfig_factory_test.go
  cli/runtime/config/nodeutils/compare_nodes.go
  cli/runtime/config/nodeutils/compare_nodes_test.go
  cli/runtime/config/nodeutils/converters.go
  cli/runtime/config/nodeutils/create_node.go
  cli/runtime/config/nodeutils/create_node_test.go
  cli/runtime/config/nodeutils/find_node.go
  cli/runtime/config/nodeutils/find_node_test.go
  cli/runtime/config/nodeutils/merge_nodes.go
  cli/runtime/config/nodeutils/merge_nodes_test.go
  cli/runtime/config/nodeutils/node_types.go
  cli/runtime/config/servers.go
  cli/runtime/config/servers_it_test.go
  cli/runtime/go.mod
  cli/runtime/go.sum
  cli/runtime/test/framework.go
  cmd/cli/plugin/pinniped-auth/go.mod
  cmd/cli/plugin/pinniped-auth/go.sum
Labels: ok-to-merge, cla-not-required, area/core-cli

#3900 Remove obsolete management components
  tkg/client/delete_region.go
  tkg/client/init.go
  tkg/client/management_components.go
  tkg/client/management_components_test.go
  tkg/client/upgrade_region.go
  tkg/managementcomponents/management_component_install.go
Labels: ok-to-merge, cla-not-required, area/tkr, not-core-cli

#3888 Hide the default completion command of plugins
  cli/runtime/plugin/root.go
Labels: ok-to-merge, cla-not-required

#3932 Add logic for clusterboostrap webhook to handle deleting cluster
  addons/webhooks/clusterbootstrap_webhook.go
  addons/webhooks/clusterbootstrap_webhook_test.go
Labels: ok-to-merge, cla-not-required

#3938 Temporarily disable CAPD integration tests from CI workflow
  .github/workflows/tkg_integration_tests_clusterclass.yaml
Labels: ok-to-merge, cla-not-required

#3786 Implement Azure credential update
  cmd/cli/plugin/cluster/credentials_update.go
  cmd/cli/plugin/managementcluster/credentials_update.go
  tkg/client/update_credentials.go
  tkg/client/update_credentials_test.go
  tkg/clusterclient/clusterclient.go
  tkg/clusterclient/clusterclient_test.go
  tkg/clusterclient/credentials.go
  tkg/fakes/clusterclient.go
  tkg/tkgctl/update_credentials.go
  tkg/tkgctl/update_credentials_region.go
  tkg/tkgctl/update_credentials_test.go
Labels: ok-to-merge, cla-not-required

#3936 Enable AWS Garbage Collection by default
  packages/cluster-api-provider-aws/bundle/config/overlay/set-features-gates.yaml
  providers/infrastructure-aws/v2.0.0-beta.1/infrastructure-components.yaml
Labels: ok-to-merge, cla-not-required

#3891 Add antrea 1.7.1 package
  addons/controllers/antrea/antreaconfig_util.go
  addons/controllers/antreaconfig_controller_test.go
  addons/controllers/testdata/antrea-test-1.yaml
  apis/addonconfigs/cni/v1alpha1/antreaconfig_types.go
  apis/addonconfigs/cni/v1alpha1/zz_generated.deepcopy.go
  apis/addonconfigs/config/crd/bases/cni.tanzu.vmware.com_antreaconfigs.yaml
  packages/addons-manager/bundle/config/upstream/addonconfigscrds/cni.tanzu.vmware.com_antreaconfigs.yaml
  providers/config_default.yaml
  providers/tests/clustergen/param_models/cluster_optional.model
  providers/vendir.lock.yml
  providers/vendir.yml
  providers/ytt/02_addons/cni/antrea/antrea_addon_data.lib.yaml
  providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.5.3/bundle/config/upstream/antrea.yaml
  providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.7.1/bundle/config/kapp-config.yaml
  providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.7.1/bundle/config/overlay/antrea-overlay.yaml
  providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.7.1/bundle/config/overlay/update-strategy-overlay.yaml
  providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.7.1/bundle/config/schema.yaml
  providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.7.1/bundle/config/upstream/antrea.yaml
  providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.7.1/bundle/config/values.star
  providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.7.1/bundle/config/values.yaml
  providers/ytt/vendir/cni/cni.lib.yaml
  providers/yttcb/clusterbootstrap.yaml
Labels: ok-to-merge, cla-not-required

#3884 Add tkg-windows package in package-values.yaml
  packages/package-values.yaml
Labels: ok-to-merge, cla-not-required

#3940 Update Cluster Toplogy utils to populate empty arr
  tkg/client/machine_deployment_cc_test.go
  util/topology/cluster.go
  util/topology/cluster_test.go
Labels: ok-to-merge, cla-not-required

#3875 Allow using VSphereClusterIdentity based identityRef
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass/bundle/config/packageinstalls/tkg-infra-clusterclass-service-account.yaml
  packages/tkr-vsphere-resolver/bundle/config/upstream/rbac.yaml
  providers/infrastructure-vsphere/v1.4.1/cconly/base.yaml
  tkg/vsphere-template-resolver/main.go
  tkg/vsphere-template-resolver/template/resolver.go
  tkg/vsphere-template-resolver/template/resolver_test.go
Labels: ok-to-merge, cla-not-required

#3950 Xport Update Cluster Toplogy utils to populate empty arr
  pkg/v1/tkg/client/machine_deployment_cc_test.go
  pkg/v2/tkr/util/topology/cluster.go
  pkg/v2/tkr/util/topology/cluster_test.go
Labels: ok-to-merge, cla-not-required

#3952 add azuredisk cc support
  PROJECT
  addons/config/expected/csi.tanzu.vmware.com/v1alpha1/azurediskcsiconfig/default.yaml
  addons/config/templates/csi.tanzu.vmware.com/v1alpha1/azurediskcsiconfig.yaml
  addons/config/testcases/csi.tanzu.vmware.com/v1alpha1/azurediskcsiconfig/default.yaml
  addons/controllers/azurediskcsi/azurediskconfig_datavalues.go
  addons/controllers/azurediskcsi/azurediskconfig_utils.go
  addons/controllers/azurediskcsi/azurediskcsiconfig_controller.go
  addons/controllers/suite_test.go
  addons/main.go
  addons/pkg/config/config.go
  addons/pkg/constants/constants.go
  apis/addonconfigs/config/crd/bases/csi.tanzu.vmware.com_azurediskcsiconfigs.yaml
  apis/addonconfigs/csi/v1alpha1/azurediskcsiconfig_types.go
  apis/addonconfigs/csi/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/csi.tanzu.vmware.com_azurediskcsiconfigs.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_azurediskcsiconfigs.yaml
  config/crd/patches/webhook_in_azurediskcsiconfigs.yaml
  config/rbac/azurediskcsiconfig_editor_role.yaml
  config/rbac/azurediskcsiconfig_viewer_role.yaml
  config/samples/csi_v1alpha1_azurediskcsiconfig.yaml
  packages/addons-manager/bundle/config/upstream/addonconfigscrds/csi.tanzu.vmware.com_azurediskcsiconfigs.yaml
  packages/addons-manager/vendir.yml
  providers/yttcb/clusterbootstrap.yaml
Labels: area/testing, ok-to-merge, cla-not-required

#3939 Update unit tests to fix config file corruption issue
  cli/core/pkg/auth/csp/grpc.go
  cli/core/pkg/auth/csp/grpc_test.go
  cli/core/pkg/config/config.go
  cli/core/pkg/config/config_test.go
  cli/core/pkg/fakes/config_client_fake.go
  cli/core/pkg/fakes/fake_config_client_wrapper.go
  cli/core/pkg/interfaces/config_client_interface.go
Labels: area/testing, ok-to-merge, cla-not-required

#3959 Update BOM retrieval version to v0.25.3
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, cla-not-required

#3865 Fix cluster upgrade from legacy to package based lcm
  addons/pkg/constants/constants.go
  addons/pkg/util/bom_util.go
  packages/core-management-plugins/package.yaml
  packages/tkg/bundle/config/packageinstalls/core-management-plugins-pi.yaml
  tkg/client/management_components.go
  tkg/client/upgrade_cluster.go
  tkg/client/upgrade_region.go
  tkg/constants/files.go
Labels: area/cli, area/addons, ok-to-merge, cla-not-required, area/lcm, area/cc, area/core-cli

#3947 add tolerations to aad pod identity
  hack/providers-sync-tools/cluster-api-provider-azure/overlay/add-tolerations.yaml
  providers/infrastructure-azure/v1.5.3/infrastructure-components.yaml
Labels: ok-to-merge, cla-not-required

#3818 Support adding node labels for control plane nodes when cluster creation for vsphere/aws/azure
  packages/tkg-clusterclass-aws/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-azure/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  providers/config_default.yaml
  providers/infrastructure-aws/v2.0.0-beta.1/cconly/base.yaml
  providers/infrastructure-azure/v1.5.3/cconly/base.yaml
  providers/infrastructure-vsphere/v1.4.1/cconly/base.yaml
  providers/yttcc/lib/config_variable_association.star
  providers/yttcc/lib/helpers.star
Labels: ok-to-merge, cla-not-required

#3879 Make manifest to azurecc, adjust default namespace, adjust format for the bootstraps yaml
  addons/config/expected/csi.tanzu.vmware.com/v1alpha1/azurefilecsiconfig/default.yaml
  addons/config/templates/csi.tanzu.vmware.com/v1alpha1/azurefilecsiconfig.yaml
  addons/controllers/azurefilecsi/azurefilecsiconfig_utils.go
  apis/addonconfigs/config/crd/bases/csi.tanzu.vmware.com_azurefilecsiconfigs.yaml
  apis/addonconfigs/csi/v1alpha1/azurefilecsiconfig_types.go
  config/crd/bases/csi.tanzu.vmware.com_azurefilecsiconfigs.yaml
  packages/addons-manager/bundle/config/upstream/addonconfigscrds/csi.tanzu.vmware.com_azurefilecsiconfigs.yaml
  providers/yttcb/clusterbootstrap.yaml
Labels: ok-to-merge, cla-not-required

#3971 add legacy namespace for tkr source controller
  packages/tkr-source-controller/bundle/config/upstream/tkr-source-controller-deployment.yaml
Labels: ok-to-merge, cla-not-required

#3976 Adding Antrea fixes and 1.24 secret for serviceaccount
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  packages/tkg-windows/bundle/config/upstream/rbac.yaml
  providers/infrastructure-vsphere/v1.4.1/cconly/base.yaml
Labels: cla-not-required

#3977 Fix permissions duplicate entries in tanzu config file
  cli/runtime/config/contexts_test.go
  cli/runtime/config/nodeutils/helpers.go
  cli/runtime/config/nodeutils/helpers_test.go
  cli/runtime/config/nodeutils/merge_nodes.go
Labels: ok-to-merge, cla-not-required

#3983 [Workaround]Schedule featuregate pod on controlplane nodes
  packages/featuregates/bundle/config/values.yaml
  packages/framework/bundle/config/values.yaml
  packages/tkg/bundle/config/values.yaml
Labels: ok-to-merge, cla-not-required

#3871 Upgrade CAPV version and introduce h/w version in templates
  addons/go.mod
  addons/go.sum
  packages/cluster-api-provider-vsphere/bundle/config/upstream/infrastructure-components-supervisor.yaml
  packages/cluster-api-provider-vsphere/bundle/config/upstream/infrastructure-components.yaml
  packages/cluster-api-provider-vsphere/bundle/config/upstream/metadata.yaml
  packages/cluster-api-provider-vsphere/vendir.lock.yml
  packages/cluster-api-provider-vsphere/vendir.yml
  providers/config.yaml
  providers/config_default.yaml
  providers/infrastructure-vsphere/v1.5.0/cconly/base.yaml
  providers/infrastructure-vsphere/v1.5.0/cconly/overlay.yaml
  providers/infrastructure-vsphere/v1.5.0/cluster-template-definition-dev.yaml
  providers/infrastructure-vsphere/v1.5.0/cluster-template-definition-devcc.yaml
  providers/infrastructure-vsphere/v1.5.0/cluster-template-definition-prod.yaml
  providers/infrastructure-vsphere/v1.5.0/cluster-template-definition-prodcc.yaml
  providers/infrastructure-vsphere/v1.5.0/clusterclass-tkg-vsphere-default.yaml
  providers/infrastructure-vsphere/v1.5.0/infrastructure-components-supervisor.yaml
  providers/infrastructure-vsphere/v1.5.0/infrastructure-components.yaml
  providers/infrastructure-vsphere/v1.5.0/metadata.yaml
  providers/infrastructure-vsphere/v1.5.0/ytt/base-template.yaml
  providers/infrastructure-vsphere/v1.5.0/ytt/overlay-windows.yaml
  providers/infrastructure-vsphere/v1.5.0/ytt/overlay.yaml
  providers/infrastructure-vsphere/v1.5.0/yttcc/base-template.yaml
  providers/infrastructure-vsphere/v1.5.0/yttcc/overlay.yaml
  providers/tests/clustergen/param_models/cluster_optional.model
  providers/tests/clustergen/param_models/cluster_vsphere.model
  providers/tests/unit/hardware_version_upgrade_test.go
  providers/tests/unit/ip_family_test.go
  tkg/constants/config_variables.go
  tkg/tkgconfigproviders/vsphere.go
Labels: ok-to-merge, cla-not-required

#3988 Adding default fields check to avoid AntreaConfig creation
  providers/yttcb/clusterbootstrap.yaml
Labels: ok-to-merge, cla-not-required

#3962 Remove package installing when deleting cc mgmt cluster
  tkg/client/delete_region.go
Labels: ok-to-merge, cla-not-required

#3997 Change azure image selector
  providers/infrastructure-azure/v1.5.3/yttcc/overlay.yaml
Labels: ok-to-merge, cla-not-required

#3970 Remove kapp labels with patch verb
  tkg/client/init.go
  tkg/clusterclient/clusterclient.go
  tkg/clusterclient/clusterclient_test.go
  tkg/fakes/clusterclient.go
Labels: ok-to-merge, cla-not-required

#3960 Apply ClusterBootstrap objects from bootstrap cluster to management cluster
  providers/yttcb/clusterbootstrap.yaml
  tkg/client/client_suite_test.go
  tkg/client/init.go
  tkg/fakes/config/config_custom_clusterbootstrap.yaml
Labels: ok-to-merge, cla-not-required

#3998 Trim the version suffix from the default ClusterClass name
  tkg/yamlprocessor/ytt.go
  tkg/yamlprocessor/ytt_test.go
Labels: ok-to-merge, cla-not-required

#4005 Move bring your own image sub-command from cluster to kubernetes-release
  cmd/cli/plugin/cluster/README.md
  cmd/cli/plugin/cluster/go.mod
  cmd/cli/plugin/cluster/go.sum
  cmd/cli/plugin/cluster/main.go
  cmd/cli/plugin/tkr/README.md
  cmd/cli/plugin/tkr/main.go
  cmd/cli/plugin/tkr/osimage.go
  cmd/cli/plugin/tkr/osimage_oracle.go
  go.mod
  go.sum
Labels: ok-to-merge, cla-not-required

#4001 Use Cobra's bash completion V2
  cli/core/pkg/command/completion.go
  cli/core/pkg/command/completion_test.go
Labels: ok-to-merge, cla-not-required, area/core-cli

#3846 Add new flag to enable kubevip to be service type lb provider when enabled
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  providers/config_default.yaml
  providers/infrastructure-vsphere/v1.5.0/cconly/base.yaml
  providers/infrastructure-vsphere/v1.5.0/yttcc/overlay.yaml
  providers/tests/clustergen/param_models/cluster_optional.model
  providers/yttcb/clusterbootstrap.yaml
  providers/yttcc/lib/config_variable_association.star
  tkg/fakes/config/cluster_vsphere.yaml
Labels: ok-to-merge, cla-not-required

#3862 provider: Introduce Pod Security Standard for non-CC and CC based Clusters
  packages/cluster-api-provider-azure/bundle/config/overlay/add-pod-security-namespace-labels.yaml
  packages/cluster-api-provider-docker/bundle/config/overlay/add-pod-security-namespace-labels.yaml
  packages/tkg-clusterclass-docker/bundle/config/upstream/overlay.yaml
  packages/tkg-clusterclass-oci/bundle/config/upstream/overlay.yaml
  packages/tkg-clusterclass/bundle/config/packageinstalls/tkg-infra-clusterclass-pi.yaml
  providers/config_default.yaml
  providers/infrastructure-azure/v1.5.3/infrastructure-components.yaml
  providers/infrastructure-docker/v1.2.4/cconly/overlay.yaml
  providers/infrastructure-docker/v1.2.4/infrastructure-components.yaml
  providers/infrastructure-oci/v0.4.0/cconly/overlay.yaml
  providers/tests/clustergen/param_models/cluster_optional.model
  providers/ytt/03_customizations/pod_security_admission.yaml
  providers/ytt/lib/helpers.star
  tkg/client/admission_upgrade_helper.go
  tkg/client/admission_upgrade_helper_test.go
  tkg/client/upgrade_cluster.go
  tkg/constants/clusterclass_mapping.go
  tkg/constants/config_variables.go
Labels: ok-to-merge, cla-not-required

#4004 Enable tkg-windows template automatically CBT Windows
  providers/yttcb/clusterbootstrap.yaml
Labels: ok-to-merge, cla-not-required

#3911 Fix upgrade logic for additional packages in ClusterBoostrap but not in CBT
  addons/controllers/clusterbootstrap_controller.go
  addons/controllers/clusterbootstrap_controller_test.go
  addons/controllers/testdata/test-cluster-bootstrap-9.yaml
  addons/pkg/util/tkr_util.go
Labels: ok-to-merge, cla-not-required

#3905 Tanzu CLI Configuration - Replace Strategy
  cli/core/pkg/config/bom.go
  cli/core/pkg/config/defaults.go
  cli/runtime/apis/config/v1alpha1/clientconfig_metadata_types.go
  cli/runtime/apis/config/v1alpha1/zz_generated.deepcopy.go
  cli/runtime/config/cli_discovery_sources.go
  cli/runtime/config/cli_discovery_sources_it_test.go
  cli/runtime/config/cli_discovery_sources_test.go
  cli/runtime/config/cli_options.go
  cli/runtime/config/cli_options_test.go
  cli/runtime/config/cli_repositories.go
  cli/runtime/config/cli_repositories_it_test.go
  cli/runtime/config/cli_repositories_test.go
  cli/runtime/config/clientconfig_factory.go
  cli/runtime/config/clientconfig_filesystem.go
  cli/runtime/config/clientconfig_typemeta.go
  cli/runtime/config/collectionutils/arrayutils.go
  cli/runtime/config/collectionutils/arrayutils_test.go
  cli/runtime/config/config_factory.go
  cli/runtime/config/config_filesystem.go
  cli/runtime/config/contexts.go
  cli/runtime/config/contexts_it_test.go
  cli/runtime/config/contexts_test.go
  cli/runtime/config/conversion.go
  cli/runtime/config/discovery_sources_node.go
  cli/runtime/config/discovery_sources_node_test.go
  cli/runtime/config/envs.go
  cli/runtime/config/envs_test.go
  cli/runtime/config/features.go
  cli/runtime/config/legacy_clientconfig_factory.go
  cli/runtime/config/legacy_clientconfig_factory_test.go
  cli/runtime/config/legacy_clientconfig_filesystem.go
  cli/runtime/config/lock.go
  cli/runtime/config/metadata_api.go
  cli/runtime/config/metadata_api_test.go
  cli/runtime/config/metadata_factory.go
  cli/runtime/config/metadata_factory_test.go
  cli/runtime/config/metadata_filesystem.go
  cli/runtime/config/metadata_keys.go
  cli/runtime/config/metadata_lock.go
  cli/runtime/config/nodeutils/find_node.go
  cli/runtime/config/nodeutils/find_node_test.go
  cli/runtime/config/nodeutils/merge_nodes.go
  cli/runtime/config/nodeutils/merge_nodes_test.go
  cli/runtime/config/nodeutils/node_types.go
  cli/runtime/config/nodeutils/replace_nodes.go
  cli/runtime/config/nodeutils/replace_nodes_test.go
  cli/runtime/config/patchstrategy_it_test.go
  cli/runtime/config/servers.go
  cli/runtime/config/servers_it_test.go
Labels: ok-to-merge, cla-not-required

#4000 ci: refactor 'Main' github workflow
  .github/workflows/build.yaml
  .github/workflows/lint.yaml
  .github/workflows/unittests.yaml
  .github/workflows/verify.yaml
  Makefile
Labels: kind/refactor, area/testing, ok-to-merge, cla-not-required

#4037 Adding timestamps to the make release target for performance optimiza…
  cmd/cli/plugin-admin/builder/command/cli_compile.go
Labels: ok-to-merge, cla-not-required

#4008 Sync antrea package 1.7.1 fixes for kind overlay
  providers/vendir.lock.yml
  providers/vendir.yml
  providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.7.1/bundle/config/overlay/antrea-overlay.yaml
Labels: ok-to-merge, cla-not-required

#3899 Add Node IPAM support for vSphere
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  providers/config.yaml
  providers/config_default.yaml
  providers/infrastructure-ipam-in-cluster/v0.1.0/ipam-components.yaml
  providers/infrastructure-ipam-in-cluster/v0.1.0/metadata.yaml
  providers/infrastructure-vsphere/v1.5.0/cconly/base.yaml
  providers/ytt/lib/config_variable_association.star
  providers/yttcc/lib/config_variable_association.star
  tkg/client/client.go
  tkg/client/init.go
  tkg/clusterclient/clusterclient.go
  tkg/constants/clusterclass_mapping.go
  tkg/constants/config_variables.go
  tkg/constants/featureflags.go
  tkg/fakes/config/cluster_vsphere.yaml
  tkg/tkgctl/create_cluster_test.go
Labels: ok-to-merge, cla-not-required

#3989 make TLS cipher suite used by webhook servers configurable
  addons/go.mod
  addons/go.sum
  addons/main.go
  featuregates/controller/go.mod
  featuregates/controller/go.sum
  featuregates/controller/main.go
  packages/addons-manager/bundle/config/upstream/addons-manager.yaml
  packages/addons-manager/bundle/config/values.yaml
  packages/featuregates/bundle/config/upstream/tanzu-featuregates-manager.yaml
  packages/featuregates/bundle/config/values.yaml
  packages/tkr-service/bundle/config/upstream/tkr-conversion-webhook-deployment.yaml
  packages/tkr-service/bundle/config/upstream/tkr-resolver-cluster-webhook-deployment.yaml
  packages/tkr-service/bundle/config/values.yaml
  tkr/go.mod
  tkr/webhook/cluster/tkr-resolver/main.go
  tkr/webhook/tkr-conversion/main.go
Labels: ok-to-merge, cla-not-required
