Repository vmware-tanzu/tanzu-framework, pull requests merged in 2022-02, with the labels that each got.

#1566 Bump containerd and image-spec
  addons/go.sum
  go.mod
  go.sum
Labels: ok-to-merge, cla-not-required

#1537 fix kubeconfig used by feature plugin
  docs/cli/plugin_implementation_guide.md
  pkg/v1/config/clientconfig.go
  pkg/v1/sdk/features/client/client.go
Labels: ok-to-merge, cla-not-required

#1597 addons/pinniped/post-deploy: improve BUILDER_BASE_IMAGE support
  addons/pinniped/post-deploy/hack/scripts/build-images.sh
Labels: ok-to-merge, cla-not-required

#1606 Fix installing plugins with legacy directory structure on windows
  pkg/v1/cli/pluginmanager/manager.go
Labels: area/cli, kind/bug, ok-to-merge, cla-not-required

#1555 Convert CalicoConfig API to data values secret and add CalicoConfig c…
  addons/controllers/addon_controller.go
  addons/controllers/calico/calicoconfig_controller.go
  addons/controllers/calico/calicoconfig_utils.go
  addons/controllers/calico/suite_test.go
  addons/controllers/calicoconfig_controller_test.go
  addons/controllers/suite_test.go
  addons/controllers/testdata/test-calico.yaml
  addons/go.mod
  addons/pkg/constants/constants.go
  addons/pkg/util/addon_util.go
  addons/testutil/test_helpers.go
  apis/cni/v1alpha1/calicoconfig_types.go
  apis/cni/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/cni.tanzu.vmware.com_calicoconfigs.yaml
  config/samples/cni_v1alpha1_calicoconfig.yaml
Labels: area/addons, ok-to-merge, cla-not-required, area/packages

#1541 Add API types and controller for TanzuClusterBootstrap
  Makefile
  PROJECT
  addons/controllers/addon_controller.go
  addons/controllers/suite_test.go
  addons/controllers/tanzuclusterbootstrap_controller.go
  addons/controllers/tanzuclusterbootstrap_controller_test.go
  addons/controllers/tanzuclusterbootstrap_handlers.go
  addons/controllers/testdata/foobar_crd.yaml
  addons/controllers/testdata/test-cluster-tanzu-cluster-bootstrap.yaml
  addons/main.go
  addons/pkg/constants/constants.go
  addons/pkg/util/cluster_util.go
  apis/run/v1alpha3/tanzuclusterbootstrap_types.go
  apis/run/v1alpha3/tanzuclusterbootstraptemplate_types.go
  apis/run/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/config.tanzu.vmware.com_clientconfigs.yaml
  config/crd/bases/run.tanzu.vmware.com_tanzuclusterbootstraps.yaml
  config/crd/bases/run.tanzu.vmware.com_tanzuclusterbootstraptemplates.yaml
  hack/tools/Makefile
Labels: area/addons, ok-to-merge, cla-not-required, area/packages

#1539 Create AntreaConfig API and controller
  PROJECT
  addons/controllers/antrea/antreaconfig_controller.go
  addons/controllers/antrea/antreaconfig_util.go
  addons/controllers/antreaconfig_controller_test.go
  addons/controllers/suite_test.go
  addons/controllers/tanzuclusterbootstrap_controller_test.go
  addons/controllers/testdata/antrea-test-1.yaml
  addons/controllers/testdata/infrastructure_dockercluster.yaml
  addons/main.go
  addons/pkg/constants/constants.go
  addons/pkg/util/addon_util.go
  apis/cni/v1alpha1/antreaconfig_types.go
  apis/cni/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/cni.tanzu.vmware.com_antreaconfigs.yaml
  config/crd/kustomization.yaml
  config/rbac/antreaconfig_editor_role.yaml
  config/rbac/antreaconfig_viewer_role.yaml
  config/samples/cni_v1alpha1_antreaconfig.yaml
Labels: area/addons, ok-to-merge, cla-not-required, area/packages

#1553 Create KappControllerConfig API and controller
  PROJECT
  addons/controllers/addon_controller_test.go
  addons/controllers/antrea/antreaconfig_controller.go
  addons/controllers/calico/calicoconfig_controller.go
  addons/controllers/kapp-controller/kappcontrollerconfig_controller.go
  addons/controllers/kapp-controller/kappcontrollerconfig_types.go
  addons/controllers/kappcontrollerconfig_controller_test.go
  addons/controllers/suite_test.go
  addons/controllers/testdata/test-kapp-controller-1.yaml
  apis/run/v1alpha3/kappcontrollerconfig_types.go
  apis/run/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/run.tanzu.vmware.com_kappcontrollerconfigs.yaml
  config/crd/kustomization.yaml
  config/rbac/kappcontrollerconfig_editor_role.yaml
  config/rbac/kappcontrollerconfig_viewer_role.yaml
  config/samples/run_v1alpha3_kappcontrollerconfig.yaml
Labels: area/addons, ok-to-merge, cla-not-required, area/packages

#1615 Relax the type constraint on OSImage.Spec.Image.Ref values
  apis/run/v1alpha3/osimage_test.go
  apis/run/v1alpha3/osimage_types.go
  apis/run/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/run.tanzu.vmware.com_osimages.yaml
Labels: ok-to-merge, cla-not-required

#1609 Add base scaffolding directory structure for `tkg` and `tkg-clusterclass` management packages
  .gitignore
  packages/management/tkg-clusterclass-aws/Makefile
  packages/management/tkg-clusterclass-aws/README.md
  packages/management/tkg-clusterclass-aws/bundle/config/values.yaml
  packages/management/tkg-clusterclass-aws/metadata.yaml
  packages/management/tkg-clusterclass-aws/package.yaml
  packages/management/tkg-clusterclass-azure/Makefile
  packages/management/tkg-clusterclass-azure/README.md
  packages/management/tkg-clusterclass-azure/bundle/config/values.yaml
  packages/management/tkg-clusterclass-azure/metadata.yaml
  packages/management/tkg-clusterclass-azure/package.yaml
  packages/management/tkg-clusterclass-docker/Makefile
  packages/management/tkg-clusterclass-docker/README.md
  packages/management/tkg-clusterclass-docker/bundle/config/values.yaml
  packages/management/tkg-clusterclass-docker/metadata.yaml
  packages/management/tkg-clusterclass-docker/package.yaml
  packages/management/tkg-clusterclass-vsphere/Makefile
  packages/management/tkg-clusterclass-vsphere/README.md
  packages/management/tkg-clusterclass-vsphere/bundle/config/values.yaml
  packages/management/tkg-clusterclass-vsphere/metadata.yaml
  packages/management/tkg-clusterclass-vsphere/package.yaml
  packages/management/tkg-clusterclass/Makefile
  packages/management/tkg-clusterclass/README.md
  packages/management/tkg-clusterclass/bundle/config/values.yaml
  packages/management/tkg-clusterclass/metadata.yaml
  packages/management/tkg-clusterclass/package.yaml
  packages/management/tkg/Makefile
  packages/management/tkg/README.md
  packages/management/tkg/bundle/config/values.yaml
  packages/management/tkg/metadata.yaml
  packages/management/tkg/package.yaml
  packages/package-values.yaml
Labels: kind/other, ok-to-merge, cla-not-required, area/packages

#1629 List context server name in `plugin source list`
  pkg/v1/cli/command/core/discovery_source.go
Labels: ok-to-merge, cla-not-required

#1598 Configure Kind subnets for dualstack ipv6 primary
  pkg/v1/tkg/fakes/config/config_ipv6_ipv4_with_cidrs.yaml
  pkg/v1/tkg/kind/client.go
  pkg/v1/tkg/kind/client_test.go
Labels: ok-to-merge, cla-not-required

#1624 Make `tkg` and `tkg-clusterclass` composite management packages
  Makefile
  packages/management/tkg-clusterclass/bundle/config/packageinstalls/infra-clusterclass-pi.yaml
  packages/management/tkg-clusterclass/bundle/config/packageinstalls/service-account.yaml
  packages/management/tkg-clusterclass/bundle/config/values.yaml
  packages/management/tkg/bundle/config/packageinstalls/clusterclass-pi.yaml
  packages/management/tkg/bundle/config/packageinstalls/service-account.yaml
  packages/management/tkg/bundle/config/values.yaml
  packages/management/tkg/testdata/sample-values.yaml
Labels: ok-to-merge, cla-not-required, area/packages

#1605 Make compatibility file resolution happen via config
  Makefile
  apis/config/v1alpha1/clientconfig.go
  apis/config/v1alpha1/clientconfig_types.go
  pkg/v1/cli/command/core/config.go
  pkg/v1/config/clientconfig.go
  pkg/v1/tkg/fakes/tkgconfigbomclient.go
  pkg/v1/tkg/tkgconfigbom/bom.go
  pkg/v1/tkg/tkgconfigbom/bom_test.go
  pkg/v1/tkg/tkgconfigbom/client.go
  pkg/v1/tkg/tkgconfigupdater/ensure.go
Labels: area/cli, ok-to-merge, cla-not-required

#1507 Add note to use global gitignore for IDEs
  .gitignore
Labels: area/repo maintenance, ok-to-merge, cla-not-required

#1635 TanzuClusterBootstrap reconciler should add labels on cloned objects
  addons/controllers/tanzuclusterbootstrap_controller.go
  addons/controllers/tanzuclusterbootstrap_controller_test.go
  addons/pkg/types/addons.go
Labels: area/addons, ok-to-merge, cla-not-required

#1650 Drop redundant Tanzu from TanzuClusterBootstrapTemplate and TanzuClus…
  addons/controllers/clusterbootstrap_controller.go
  addons/controllers/clusterbootstrap_controller_test.go
  addons/controllers/clusterbootstrap_handlers.go
  addons/controllers/suite_test.go
  addons/controllers/testdata/test-cluster-bootstrap.yaml
  addons/pkg/constants/constants.go
  apis/cni/v1alpha1/antreaconfig_types.go
  apis/cni/v1alpha1/calicoconfig_types.go
  apis/run/v1alpha3/clusterbootstrap_types.go
  apis/run/v1alpha3/clusterbootstraptemplate_types.go
  apis/run/v1alpha3/kappcontrollerconfig_types.go
  apis/run/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/cni.tanzu.vmware.com_antreaconfigs.yaml
  config/crd/bases/cni.tanzu.vmware.com_calicoconfigs.yaml
  config/crd/bases/config.tanzu.vmware.com_clientconfigs.yaml
  config/crd/bases/run.tanzu.vmware.com_clusterbootstraps.yaml
  config/crd/bases/run.tanzu.vmware.com_clusterbootstraptemplates.yaml
  config/crd/bases/run.tanzu.vmware.com_kappcontrollerconfigs.yaml
Labels: ok-to-merge, cla-not-required

#1630 CLI: Add pre-download verification for HTTP plugin artifacts
  pkg/v1/cli/pluginmanager/manager.go
  pkg/v1/cli/pluginmanager/manager_test.go
  pkg/v1/config/defaults.go
Labels: area/cli, area/security, ok-to-merge, cla-not-required

#1656 increase qps & burst values to avoid throttling messages
  pkg/v1/tkg/clusterclient/clusterclient.go
  pkg/v1/tkg/constants/defaults.go
  pkg/v1/tkg/kappclient/client.go
Labels: ok-to-merge, cla-not-required

#1638 Add implmentation for tkr-infra-machine-webhook
  Makefile
  go.mod
  pkg/v2/tkr/webhook/infra-machine/Dockerfile
  pkg/v2/tkr/webhook/infra-machine/Makefile
  pkg/v2/tkr/webhook/infra-machine/fieldsetter/fieldsetter.go
  pkg/v2/tkr/webhook/infra-machine/fieldsetter/fieldsetter_test.go
  pkg/v2/tkr/webhook/infra-machine/main.go
Labels: kind/feature, kind/other, ok-to-merge, cla-not-required, area/tkr

#1668 Deploy management packages into bootstrap and management cluster when `package-based-lcm-beta` feature-flag is enabled
  packages/management/tkg-clusterclass-aws/bundle/config/upstream/aws-clusterclass.yaml
  packages/management/tkg-clusterclass-aws/bundle/config/values.yaml
  packages/management/tkg-clusterclass-azure/bundle/config/upstream/azure-clusterclass.yaml
  packages/management/tkg-clusterclass-docker/bundle/config/upstream/docker-clusterclass.yaml
  packages/management/tkg-clusterclass-vsphere/bundle/config/upstream/vsphere-clusterclass.yaml
  pkg/v1/config/clientconfig.go
  pkg/v1/tkg/client/init.go
  pkg/v1/tkg/client/management_components.go
  pkg/v1/tkg/client/management_components_test.go
  pkg/v1/tkg/constants/cluster_internal.go
  pkg/v1/tkg/constants/files.go
  pkg/v1/tkg/fakes/tkgconfigbomclient.go
  pkg/v1/tkg/fakes/tkgpackageclient.go
  pkg/v1/tkg/managementcomponents/helper.go
  pkg/v1/tkg/managementcomponents/management_component_install.go
  pkg/v1/tkg/managementcomponents/management_component_install_test.go
  pkg/v1/tkg/managementcomponents/types.go
  pkg/v1/tkg/tkgconfigbom/bom.go
  pkg/v1/tkg/tkgconfigbom/client.go
  pkg/v1/tkg/tkgconfigpaths/client.go
  pkg/v1/tkg/tkgconfigpaths/filepaths.go
  pkg/v1/tkg/tkgpackageclient/client.go
  pkg/v1/tkg/tkgpackageclient/image_utils.go
  pkg/v1/tkg/tkgpackageclient/image_utils_test.go
  pkg/v1/tkg/tkgpackageclient/interface.go
  pkg/v1/tkg/tkgpackageclient/package_get_test.go
  pkg/v1/tkg/tkgpackageclient/package_install.go
  pkg/v1/tkg/tkgpackageclient/package_install_test.go
  pkg/v1/tkg/tkgpackageclient/package_list_test.go
  pkg/v1/tkg/tkgpackageclient/package_uninstall_test.go
  pkg/v1/tkg/tkgpackageclient/package_update.go
  pkg/v1/tkg/tkgpackageclient/package_update_test.go
  pkg/v1/tkg/tkgpackageclient/registry_secret_add.go
  pkg/v1/tkg/tkgpackageclient/registry_secret_add_test.go
  pkg/v1/tkg/tkgpackageclient/registry_secret_delete.go
  pkg/v1/tkg/tkgpackageclient/registry_secret_delete_test.go
  pkg/v1/tkg/tkgpackageclient/registry_secret_list.go
  pkg/v1/tkg/tkgpackageclient/registry_secret_list_test.go
  pkg/v1/tkg/tkgpackageclient/registry_secret_update.go
  pkg/v1/tkg/tkgpackageclient/registry_secret_update_test.go
  pkg/v1/tkg/tkgpackageclient/repository_add.go
  pkg/v1/tkg/tkgpackageclient/repository_add_test.go
  pkg/v1/tkg/tkgpackageclient/repository_delete_test.go
  pkg/v1/tkg/tkgpackageclient/repository_get_test.go
  pkg/v1/tkg/tkgpackageclient/repository_list_test.go
  pkg/v1/tkg/tkgpackageclient/repository_update.go
  pkg/v1/tkg/tkgpackageclient/repository_update_test.go
Labels: ok-to-merge, cla-not-required, area/lcm

#1686 fix docker builds
  .dockerignore
Labels: kind/bug, ok-to-merge, cla-not-required

#1676 update airgap script in a physically airgapped environment
  hack/gen-publish-images-fromtar.sh
  hack/gen-publish-images-totar.sh
Labels: ok-to-merge, cla-not-required

#1681 CLI: Add post-download verification for plugins
  pkg/v1/cli/pluginmanager/manager.go
  pkg/v1/cli/pluginmanager/manager_test.go
  pkg/v1/cli/pluginmanager/test/local/discovery/context/cluster.yaml
  pkg/v1/cli/pluginmanager/test/local/discovery/default/management-cluster.yaml
  pkg/v1/cli/pluginmanager/test/local/discovery/standalone/login.yaml
Labels: ok-to-merge, cla-not-required

#1698 Update BOM retrieval version to v0.17.0
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: ok-to-merge, cla-not-required

#1701 Fix tkr-infra-machine-webhook dockerfile
  pkg/v2/tkr/webhook/infra-machine/Dockerfile
  pkg/v2/tkr/webhook/infra-machine/main.go
Labels: kind/bug, ok-to-merge, cla-not-required, area/tkr

#1699 Update BOM retrieval version to v0.18.0-dev
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: ok-to-merge, cla-not-required

#1573 generate capabilities imgpkg bundle
  Makefile
  packages/kbld-config.yaml
  packages/package-values.yaml
  packages/standalone/capabilities/Makefile
  packages/standalone/capabilities/README.md
  packages/standalone/capabilities/bundle/config/upstream/capabilities-crd.yaml
  packages/standalone/capabilities/bundle/config/upstream/rbac.yaml
  packages/standalone/capabilities/bundle/config/upstream/tanzu-capabilities-controller-manager.yaml
  packages/standalone/capabilities/bundle/config/values.yaml
  packages/standalone/capabilities/bundle/vendir.lock.yml
  packages/standalone/capabilities/bundle/vendir.yml
  packages/standalone/capabilities/metadata.yaml
  packages/standalone/capabilities/package.yaml
  pkg/v1/sdk/capabilities/Makefile
Labels: area/api, kind/feature, ok-to-merge, cla-not-required

#1627 Separate long and short CLI descriptions
  cmd/cli/plugin/cluster/delete_machinehealthcheck_control_plane.go
  cmd/cli/plugin/cluster/delete_machinehealthcheck_node.go
  cmd/cli/plugin/cluster/get_machinehealthcheck_control_plane.go
  cmd/cli/plugin/managementcluster/get_ceip.go
  cmd/cli/plugin/managementcluster/import.go
  cmd/cli/plugin/managementcluster/set_ceip.go
  cmd/cli/plugin/package/package_available_get.go
  cmd/cli/plugin/secret/registry_secret_add.go
  cmd/cli/plugin/secret/registry_secret_delete.go
  cmd/cli/plugin/secret/registry_secret_list.go
  cmd/cli/plugin/secret/registry_secret_update.go
  pkg/v1/builder/command/publish.go
  pkg/v1/cli/command/core/config.go
  pkg/v1/cli/command/core/discovery_source.go
  pkg/v1/tkg/cmd/add_region.go
  pkg/v1/tkg/cmd/config.go
  pkg/v1/tkg/cmd/get_ceip.go
  pkg/v1/tkg/cmd/get_kubernetes_versions.go
  pkg/v1/tkg/cmd/set_ceip.go
Labels: ok-to-merge, area/ux, cla-not-required

#1190 Implement automation to create dev tag retrieval PR as part release automation
  .github/workflows/dev_tag_retrieval_pr.yaml
Labels: area/release, ok-to-merge, cla-not-required, orange

#1712 TKR Service: Cluster webhook scaffolding
  pkg/v2/tkr/service/Dockerfile
  pkg/v2/tkr/service/Makefile
  pkg/v2/tkr/service/cluster/webhook.go
  pkg/v2/tkr/service/main.go
Labels: ok-to-merge, cla-not-required

#1649 New cni selection using cluster class variable
  addons/controllers/calico/calicoconfig_controller.go
  addons/controllers/calico/calicoconfig_utils.go
  addons/controllers/clusterbootstrap_controller.go
  addons/controllers/clusterbootstrap_controller_test.go
  addons/controllers/suite_test.go
  addons/controllers/testdata/test-cluster-bootstrap-1.yaml
  addons/controllers/testdata/test-cluster-bootstrap-2.yaml
  addons/controllers/testdata/test-cluster-bootstrap.yaml
  addons/main.go
  addons/pkg/util/cluster_variable_util.go
  addons/pkg/util/cluster_variable_util_test.go
  apis/run/v1alpha3/clusterbootstraptemplate_types.go
  apis/run/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/run.tanzu.vmware.com_clusterbootstraps.yaml
  config/crd/bases/run.tanzu.vmware.com_clusterbootstraptemplates.yaml
  pkg/v1/tkg/constants/defaults.go
Labels: area/addons, ok-to-merge, cla-not-required

#1715 Remove incorrect instructions for zsh completions
  docs/cli/commands/tanzu_completion.md
  pkg/v1/cli/command/core/completion.go
Labels: ok-to-merge, cla-not-required

#1379 Improve windows cluster
  pkg/v1/providers/ytt/03_customizations/03_windows/register_antrea_cleanup.yaml
Labels: ok-to-merge, cla-not-required, orange

#1667 add new CRDs and RBACs in addons-manager package
  packages/management/addons-manager/bundle/config/upstream/addons-manager.yaml
  packages/management/addons-manager/bundle/config/upstream/antreaconfigs.yaml
  packages/management/addons-manager/bundle/config/upstream/calicoconfigs.yaml
  packages/management/addons-manager/bundle/config/upstream/clusterbootstraps.yaml
  packages/management/addons-manager/bundle/config/upstream/clusterbootstraptemplates.yaml
  packages/management/addons-manager/bundle/config/upstream/kappcontrollerconfigs.yaml
  packages/management/addons-manager/bundle/vendir.lock.yml
  packages/management/addons-manager/bundle/vendir.yml
Labels: ok-to-merge, cla-not-required

#1639 Add proxy configuration in tanzuClusterBootstrap
  addons/controllers/addon_controller.go
  addons/controllers/app_reconciler.go
  addons/controllers/clusterbootstrap_controller.go
  addons/controllers/clusterbootstrap_controller_test.go
  addons/controllers/kapp-controller/kappcontrollerconfig_controller.go
  addons/controllers/kapp-controller/kappcontrollerconfig_handlers.go
  addons/controllers/kapp-controller/kappcontrollerconfig_types.go
  addons/controllers/kappcontrollerconfig_controller_test.go
  addons/controllers/package_reconciler.go
  addons/controllers/suite_test.go
  addons/controllers/testdata/test-cluster-bootstrap-1.yaml
  addons/controllers/testdata/test-kapp-controller-1.yaml
  addons/main.go
  addons/pkg/config/config.go
  addons/pkg/constants/constants.go
  addons/pkg/types/clusterbootstrap.go
  apis/run/v1alpha3/kappcontrollerconfig_types.go
  config/crd/bases/run.tanzu.vmware.com_kappcontrollerconfigs.yaml
  pkg/v1/tkg/constants/defaults.go
Labels: area/addons, ok-to-merge, cla-not-required

#1659 update ytt to 0.38.0
  go.mod
  go.sum
  pkg/v1/cli/carvelhelpers/ytt.go
  pkg/v1/tkg/yamlprocessor/ytt.go
Labels: ok-to-merge, cla-not-required

#1726 Golangci-lint should not check function length for tests
  .golangci.yaml
  addons/pinniped/post-deploy/pkg/configure/concierge/concierge_test.go
  addons/pinniped/post-deploy/pkg/configure/configure_test.go
  addons/pinniped/post-deploy/pkg/configure/helper_test.go
  addons/pinniped/post-deploy/pkg/configure/supervisor/supervisor_test.go
  apis/config/v1alpha1/featuregate_webhook_test.go
  cmd/cli/plugin/pinniped-auth/login_test.go
  pkg/v1/cli/catalog_test.go
  pkg/v1/sdk/features/featuregate/featuregate_test.go
Labels: area/testing, ok-to-merge, cla-not-required

#1734 Update ytt module to github.com/vmware-tanzu/carvel-ytt v0.40.0
  .github/workflows/providers.yaml
  addons/go.mod
  addons/go.sum
  go.mod
  go.sum
  hack/tools/Makefile
  pkg/v1/builder/template/plugintemplates/gomod.tmpl
  pkg/v1/cli/carvelhelpers/ytt.go
  pkg/v1/tkg/yamlprocessor/ytt.go
Labels: area/cli, area/api, kind/cleanup, ok-to-merge, cla-not-required

#1651 Expose Avi controller version in cluster config
  pkg/v1/providers/config_default.yaml
  pkg/v1/providers/ytt/02_addons/avi/ako_operator_secret.yaml
  pkg/v1/providers/ytt/03_customizations/02_avi/ako-operator-deployment.lib.yaml
Labels: ok-to-merge, cla-not-required

#1717 Cache refresh for the TKR Resolver webhook
  pkg/v2/tkr/resolver/internal/resolver_impl_test.go
  pkg/v2/tkr/util/testdata/gendata.go
  pkg/v2/tkr/webhook/cluster/tkr-resolver/Dockerfile
  pkg/v2/tkr/webhook/cluster/tkr-resolver/Makefile
  pkg/v2/tkr/webhook/cluster/tkr-resolver/cache/refresh.go
  pkg/v2/tkr/webhook/cluster/tkr-resolver/cache/refresh_test.go
  pkg/v2/tkr/webhook/cluster/tkr-resolver/cluster/cluster.go
  pkg/v2/tkr/webhook/cluster/tkr-resolver/main.go
Labels: ok-to-merge, cla-not-required
