Repository vmware-tanzu/tanzu-framework, pull requests merged in 2022-01, with the labels that each got.

#1443 Update generated files for updated headers
  apis/cli/v1alpha1/zz_generated.deepcopy.go
  apis/config/v1alpha1/zz_generated.deepcopy.go
  apis/run/v1alpha1/zz_generated.deepcopy.go
  apis/run/v1alpha2/zz_generated.deepcopy.go
Labels: ok-to-merge, cla-not-required

#1399 Run all lint checks as part of the lint Action
  .github/workflows/main.yaml
  Makefile
  hack/install.sh
  hack/test-release-artifacts.sh
Labels: CI, area/repo maintenance, ok-to-merge, cla-not-required

#1435 Refactor datacenter changed event
  pkg/v1/tkg/web/src/app/shared/service/Messenger.ts
  pkg/v1/tkg/web/src/app/shared/service/vsphere-wizard-form.service.ts
  pkg/v1/tkg/web/src/app/views/landing/vsphere-wizard/node-setting-step/node-setting-step.component.ts
  pkg/v1/tkg/web/src/app/views/landing/vsphere-wizard/os-image-step/vsphere-os-image-step.component.ts
  pkg/v1/tkg/web/src/app/views/landing/vsphere-wizard/provider-step/vsphere-provider-step.component.ts
  pkg/v1/tkg/web/src/app/views/landing/vsphere-wizard/resource-step/resource-step.component.ts
  pkg/v1/tkg/web/src/app/views/landing/vsphere-wizard/vsphere-network-step/vsphere-network-step.component.ts
  pkg/v1/tkg/web/src/app/views/landing/vsphere-wizard/vsphere-os-image-step/vsphere-os-image-step.component.ts
  pkg/v1/tkg/web/src/app/views/landing/vsphere-wizard/vsphere-wizard.component.ts
  pkg/v1/tkg/web/src/app/views/landing/wcp-redirect/wcp-redirect.component.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/components/steps/load-balancer/load-balancer-step.component.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/components/steps/network-step/network-step.component.html
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/components/steps/network-step/network-step.component.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/components/steps/os-image-step/os-image-step.component.spec.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/step-form/step-form.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/wizard-shared.module.ts
Labels: kind/bug, kind/cleanup, ok-to-merge, area/ux, area/ui

#1366 Update pinniped configuration warning
  pkg/v1/tkg/client/cluster.go
Labels: area/cli, ok-to-merge, area/ux, cla-not-required

#1300 Remove unnecessary credentials configuration step
  .github/workflows/main.yaml
  .github/workflows/plugin_tests.yaml
  .github/workflows/release.yaml
  .github/workflows/release_staging.yaml
  .github/workflows/tkg_integration_tests.yaml
  .github/workflows/tkgpackage_integration_test.yaml
Labels: area/repo maintenance, area/testing, ok-to-merge

#457 Add empty 04_user_customizations directory for end users
  pkg/v1/providers/ytt/04_user_customizations/README.md
Labels: area/addons, kind/documentation, ok-to-merge

#1413 Enable CSI topology feature for K8S 1.22 and above
  pkg/v1/providers/ytt/02_addons/csi/csi_addon_data.lib.yaml
Labels: area/addons, ok-to-merge, cla-not-required

#1451 Assert conditional SEG names for AVI configmap in bootstrap clusters.
  pkg/v1/providers/tests/unit/avi_test.go
  pkg/v1/providers/ytt/04_user_customizations/README.md
Labels: area/testing, ok-to-merge, cla-not-required

#1449 Updating version tag used for BOM retrieval to v0.15.0
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#1453 Updating version tag used for BOM retrieval to v0.16.0-dev
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#1447 Update docs to use/download smaller sized artifacts for cli installation which excludes plugin binaries
  docs/cli/getting-started.md
  docs/cli/plugin_implementation_guide.md
Labels: area/docs, ok-to-merge, cla-not-required

#1458 Add github workflow to welcome new contributors
  .github/workflows/welcome-contributors.yaml
Labels: ok-to-merge, cla-not-required

#1410 Add yaml linter in github workflow
  Makefile
  addons/manifests/samples/bom_configmap.yaml
  addons/manifests/samples/simple-app_addon_secret.yaml
  addons/packages/addons-manager/metadata.yaml
  cmd/cli/plugin/cluster/testdata/kubeconfig1.yaml
  cmd/cli/plugin/cluster/testdata/tanzuconfig/config2.yaml
  hack/check/.yamllintconfig.yaml
  hack/check/check-yaml.sh
  pkg/v1/cli/command/plugin/lint/cli-wordlist.yml
  pkg/v1/providers/infrastructure-aws/v1.2.0/ytt/base-template.yaml
  pkg/v1/providers/infrastructure-azure/v1.0.0/ytt/base-template.yaml
  pkg/v1/providers/infrastructure-azure/v1.0.0/ytt/overlay.yaml
  pkg/v1/providers/infrastructure-docker/ytt/docker-overlay.yaml
  pkg/v1/providers/infrastructure-tkg-service-vsphere/ytt/tkg-service-vsphere-overlay.yaml
  pkg/v1/providers/ytt/02_addons/auth/pinniped_addon_secret.lib.yaml
  pkg/v1/providers/ytt/02_addons/cni/antrea/antrea_addon_data.lib.yaml
  pkg/v1/providers/ytt/02_addons/metrics-server/metrics_server_secret.yaml
  pkg/v1/providers/ytt/02_addons/standard-repo/add_standard_repo.yaml
  pkg/v1/providers/ytt/02_addons/tanzu-addons-manager/tanzu-addons-manager_addon_data.lib.yaml
  pkg/v1/providers/ytt/03_customizations/01_tkr/tkr.lib.yaml
  pkg/v1/providers/ytt/03_customizations/01_tkr/tkr_overlay.lib.yaml
  pkg/v1/providers/ytt/03_customizations/02_avi/add_akoo.yaml
  pkg/v1/providers/ytt/03_customizations/02_avi/ako-deployment.lib.yaml
  pkg/v1/providers/ytt/03_customizations/add_mhc.yaml
  pkg/v1/providers/ytt/03_customizations/annotate_os_info.yaml
  pkg/v1/providers/ytt/03_customizations/capabilities/add_capabilities.yaml
  pkg/v1/providers/ytt/03_customizations/registry_skip_tls_verify.yaml
  pkg/v1/tkg/fakes/config/bom/tkg-bom-v1.3.1.yaml
  pkg/v1/tkg/fakes/config/bom/tkr-bom-v1.18.0+vmware.1-tkg.2.yaml
  pkg/v1/tkg/fakes/config/config2.yaml
  pkg/v1/tkg/fakes/config/config3.yaml
  pkg/v1/tkg/fakes/config/config4.yaml
  pkg/v1/tkg/fakes/config/config5.yaml
  pkg/v1/tkg/fakes/config/config6.yaml
  pkg/v1/tkg/fakes/config/config7.yaml
  pkg/v1/tkg/fakes/config/config_custom_registry_ca_cert.yaml
  pkg/v1/tkg/fakes/config/config_custom_registry_skip_tls_verify.yaml
  pkg/v1/tkg/fakes/config/configmap/kubeadm-config1.yaml
  pkg/v1/tkg/fakes/config/kubeconfig/config5.yaml
  pkg/v1/tkg/fakes/config/kubeconfig/config6.yaml
  pkg/v1/tkg/manifest/telemetry/config-aws.yaml
  pkg/v1/tkg/test/config/aws.yaml
  pkg/v1/tkg/test/config/azure.yaml
  pkg/v1/tkg/test/config/template.yaml
  pkg/v1/tkg/test/data/cert-manager-resources.yaml
  pkg/v1/tkg/test/data/nginx_autoscaler.yaml
  pkg/v1/tkr/config/default/kustomization.yaml
  pkg/v1/tkr/fakes/boms/bad-bom.yaml
  pkg/v1/tkr/fakes/boms/bom-v1.19.1+vmware.1.yaml
  pkg/v1/tkr/fakes/boms/metadata.yaml
Labels: ok-to-merge, cla-not-required

#1457 Fix the race condition in spinner caused by active() check
  cmd/cli/plugin/package/display_utils.go
Labels: area/cli, area/addons, ok-to-merge, cla-not-required

#1465 Remove bold formatting from table output
  pkg/v1/cli/component/output.go
Labels: area/cli, ok-to-merge, area/ux, cla-not-required

#1467 Address yamllint errors
  hack/check/.yamllintconfig.yaml
  pkg/v1/tkg/test/tkgpackageclient/config/assets/registry-namespace.yml
Labels: ok-to-merge

#1471 Fixes lint error by renaming from 'Component' to 'Directive'
  pkg/v1/tkg/web/src/app/views/landing/aws-wizard/os-image-step/aws-os-image-step.component.ts
  pkg/v1/tkg/web/src/app/views/landing/azure-wizard/os-image-step/azure-os-image-step.component.ts
  pkg/v1/tkg/web/src/app/views/landing/vsphere-wizard/vsphere-os-image-step/vsphere-os-image-step.component.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/components/steps/os-image-step/os-image-step.component.ts
Labels: ok-to-merge, area/ui

#1469 Configure TKG_HTTP_PROXY_ENABLED variable if proxy is set during upgrade
  pkg/v1/tkg/client/upgrade_addon.go
  pkg/v1/tkg/client/upgrade_addon_test.go
Labels: kind/bug, ok-to-merge, cla-not-required, area/lcm

#1477 align ako statefulset resource limit
  pkg/v1/providers/ytt/03_customizations/02_avi/ako-deployment.lib.yaml
Labels: ok-to-merge, cla-not-required

#1365 vSphere upgrade rely on moid instead of name
  pkg/v1/providers/config_default.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.0.2/ytt/base-template.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.0.2/ytt/overlay-windows.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.0.2/ytt/overlay.yaml
  pkg/v1/providers/infrastructure-vsphere/ytt/vsphere-overlay.yaml
  pkg/v1/providers/tests/clustergen/param_models/cluster_vsphere.model
  pkg/v1/tkg/client/upgrade_cluster.go
  pkg/v1/tkg/client/upgrade_cluster_test.go
  pkg/v1/tkg/client/validate.go
  pkg/v1/tkg/constants/config_variables.go
Labels: ok-to-merge, cla-not-required

#1370 Describes best practice for using feature flags for a beta period
  docs/cli/config-features.md
Labels: ok-to-merge, orange

#1478 Update ako owners in tanzu framework repo
  CODEOWNERS
Labels: kind/other, ok-to-merge, cla-not-required, area/networking, area/dx, orange

#1226 Refactors Kickstart UI's export service
  pkg/v1/tkg/web/src/app/shared/service/export.service.ts
  pkg/v1/tkg/web/src/app/views/landing/aws-wizard/aws-wizard.component.ts
  pkg/v1/tkg/web/src/app/views/landing/azure-wizard/azure-wizard.component.ts
  pkg/v1/tkg/web/src/app/views/landing/docker-wizard/docker-wizard.component.ts
  pkg/v1/tkg/web/src/app/views/landing/vsphere-wizard/vsphere-wizard.component.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/wizard-base/wizard-base.ts
Labels: kind/cleanup, ok-to-merge, area/ux, area/ui, orange

#1070 addded another example to the confirmation feedback section
  docs/cli/style_guide.md
Labels: documentation, kind/design, area/docs, ok-to-merge, cla-not-required, orange

#1358 Add Support for REST based Discovery and GCP URI artifacts for CLI plugin discovery
  Makefile
  go.mod
  pkg/v1/cli/artifact/gcp.go
  pkg/v1/cli/artifact/http.go
  pkg/v1/cli/artifact/interface.go
  pkg/v1/cli/artifact/local.go
  pkg/v1/cli/discovery/interface.go
  pkg/v1/cli/discovery/interface_test.go
  pkg/v1/cli/discovery/kubernetes.go
  pkg/v1/cli/discovery/local.go
  pkg/v1/cli/discovery/oci.go
  pkg/v1/cli/discovery/rest.go
  pkg/v1/cli/discovery/rest_test.go
  pkg/v1/cli/discovery/utils.go
  pkg/v1/cli/discovery/utils_test.go
  pkg/v1/cli/distribution/artifact.go
Labels: kind/enhancement, ok-to-merge, cla-not-required, orange

#1492 Revert "vSphere upgrade rely on moid instead of name"
  pkg/v1/providers/config_default.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.0.2/ytt/base-template.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.0.2/ytt/overlay-windows.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.0.2/ytt/overlay.yaml
  pkg/v1/providers/infrastructure-vsphere/ytt/vsphere-overlay.yaml
  pkg/v1/providers/tests/clustergen/param_models/cluster_vsphere.model
  pkg/v1/tkg/client/upgrade_cluster.go
  pkg/v1/tkg/client/upgrade_cluster_test.go
  pkg/v1/tkg/client/validate.go
  pkg/v1/tkg/constants/config_variables.go
Labels: ok-to-merge, cla-not-required

#1493 Fix the CLI plugin manager
  pkg/v1/cli/pluginmanager/manager.go
Labels: kind/failing-test, ok-to-merge, cla-not-required

#1495 vSphere upgrade rely on moid instead of name
  pkg/v1/providers/config_default.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.0.2/ytt/base-template.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.0.2/ytt/overlay-windows.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.0.2/ytt/overlay.yaml
  pkg/v1/providers/infrastructure-vsphere/ytt/vsphere-overlay.yaml
  pkg/v1/providers/tests/clustergen/param_models/cluster_vsphere.model
  pkg/v1/tkg/client/upgrade_cluster.go
  pkg/v1/tkg/client/upgrade_cluster_test.go
  pkg/v1/tkg/client/validate.go
  pkg/v1/tkg/constants/config_variables.go
Labels: ok-to-merge, cla-not-required

#1501 Remove patch version check from workload create
  pkg/v1/tkg/client/cluster.go
  pkg/v1/tkg/client/cluster_test.go
Labels: ok-to-merge, cla-not-required

#1498 Update from mirror.gcr.io to dockerhub
  Makefile
  addons/Dockerfile
  addons/pinniped/post-deploy/Dockerfile
  pkg/v1/sdk/capabilities/Dockerfile
  pkg/v1/sdk/features/Dockerfile
  pkg/v1/tkr/Dockerfile
Labels: ok-to-merge, cla-not-required

#1500 Allow only trusted registries and fix issue regarding installing plugins in internet restricted from OCI source
  go.mod
  pkg/v1/cli/carvelhelpers/package.go
  pkg/v1/cli/carvelhelpers/registry.go
  pkg/v1/cli/distribution/artifact.go
  pkg/v1/cli/distribution/interface.go
  pkg/v1/cli/pluginmanager/manager.go
  pkg/v1/cli/pluginmanager/manager_test.go
  pkg/v1/config/defaults.go
  pkg/v1/tkg/constants/env_variables.go
  pkg/v1/tkr/fakes/registy.go
  pkg/v1/tkr/pkg/registry/client.go
  pkg/v1/tkr/pkg/registry/interface.go
Labels: ok-to-merge, cla-not-required

#1506 Fix file count error returned by OCIArtifact.Fetch
  pkg/v1/cli/artifact/oci.go
  pkg/v1/cli/artifact/oci_test.go
Labels: ok-to-merge, cla-not-required

#1520 Fix TKR status not being updated after mgmt cluster upgrade
  pkg/v1/tkr/controllers/source/suite_test.go
  pkg/v1/tkr/controllers/source/tkr_source_controller.go
  pkg/v1/util/patchset/patchset.go
  pkg/v1/util/patchset/patchset_test.go
Labels: ok-to-merge, cla-not-required

#1522 Use log.Infof for formatted log string
  pkg/v1/tkg/client/utils.go
Labels: kind/cleanup, ok-to-merge, cla-not-required

#1523 Trivial grammatical fix for "does not exists"
  docs/cli/tkgctl/components.md
  pkg/v1/cli/command/core/discovery_source_test.go
  pkg/v1/test/cli/framework_test.go
  pkg/v1/tkg/client/client_suite_test.go
  pkg/v1/tkg/clusterclient/clusterclient.go
  pkg/v1/tkg/tkgctl/helpers.go
  pkg/v1/tkg/utils/capi_conditions.go
  pkg/v1/tkg/vc/client_test.go
Labels: kind/cleanup, ok-to-merge, cla-not-required

#1450 Fold misspell check in main workflow
  .github/workflows/misspell.yaml
  Makefile
Labels: area/repo maintenance, area/testing, ok-to-merge, cla-not-required, orange

#1251 Update cobra to support plugin flag completion
  addons/go.mod
  addons/go.sum
  go.mod
  go.sum
  pkg/v1/cli/command/core/completion_test.go
Labels: ok-to-merge, cla-not-required, orange

#1511 add calico config API spec
  PROJECT
  addons/controllers/calico/calicoconfig_controller.go
  addons/controllers/calico/suite_test.go
  apis/cni/v1alpha1/calicoconfig_types.go
  apis/cni/v1alpha1/groupversion_info.go
  apis/cni/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/cni.tanzu.vmware.com_calicoconfigs.yaml
  config/crd/kustomization.yaml
  config/rbac/calicoconfig_editor_role.yaml
  config/rbac/calicoconfig_viewer_role.yaml
  config/samples/cni_v1alpha1_calicoconfig.yaml
Labels: area/addons, ok-to-merge, cla-not-required

#1463 Fix issue with deploying clusters to Azure gov cloud
  addons/go.sum
  go.mod
  go.sum
  pkg/v1/providers/config.yaml
  pkg/v1/providers/infrastructure-azure/v1.0.1/cluster-template-definition-dev.yaml
  pkg/v1/providers/infrastructure-azure/v1.0.1/cluster-template-definition-prod.yaml
  pkg/v1/providers/infrastructure-azure/v1.0.1/infrastructure-components.yaml
  pkg/v1/providers/infrastructure-azure/v1.0.1/metadata.yaml
  pkg/v1/providers/infrastructure-azure/v1.0.1/ytt/base-template.yaml
  pkg/v1/providers/infrastructure-azure/v1.0.1/ytt/overlay.yaml
  pkg/v1/tkg/tkgconfigproviders/azure.go
Labels: kind/bug, ok-to-merge, cla-not-required

#1529 Update version for BOM retrieval to v0.10.1
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#1455 upgrade deprecated Issuer API resource in featuregates package
  packages/management/featuregates/bundle/config/upstream/certificates.yaml
Labels: area/api, ok-to-merge, cla-not-required, orange

#1494 Enable antrea endpointslice feature flag
  pkg/v1/providers/config_default.yaml
Labels: ok-to-merge, cla-not-required, area/networking

#1487 default to the correct cidrs for KinD for ipv6,ipv4
  pkg/v1/tkg/fakes/config/config_ipv6_ipv4.yaml
  pkg/v1/tkg/kind/client.go
  pkg/v1/tkg/kind/client_test.go
Labels: ok-to-merge, cla-not-required, area/networking

#1538 Add TKR API v1alpha3 types
  apis/run/v1alpha3/groupversion_info.go
  apis/run/v1alpha3/osimage_types.go
  apis/run/v1alpha3/tanzukubernetesrelease_types.go
  apis/run/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/run.tanzu.vmware.com_osimages.yaml
  config/crd/bases/run.tanzu.vmware.com_tanzukubernetesreleases.yaml
Labels: area/api, ok-to-merge, area/tkr

#1473 Disable the spinner if CLI is not attached to terminal
  addons/go.sum
  cmd/cli/plugin/package/display_utils.go
  go.mod
  go.sum
  pkg/v1/cli/component/output_spinner.go
Labels: area/cli, area/addons, ok-to-merge, cla-not-required, orange

#1530 Add unit tests to validate AVI providers for the network separation feature.
  pkg/v1/providers/tests/unit/avi_test.go
Labels: ok-to-merge, cla-not-required

#1527 Update plugin templates to support Go 1.17
  docs/cli/plugin_implementation_guide.md
  hack/check/.misspellignore
  pkg/v1/builder/template/plugintemplates/github_workflow_release.yaml.tmpl
  pkg/v1/builder/template/plugintemplates/gitlab-ci.yaml.tmpl
  pkg/v1/builder/template/plugintemplates/gomod.tmpl
  pkg/v1/builder/template/root.go
Labels: area/cli, kind/enhancement, ok-to-merge, cla-not-required

#1422 Add the ability to create defaults based on package schema
  .gitignore
  cmd/cli/plugin/package/README.md
  cmd/cli/plugin/package/package_available_get.go
  cmd/cli/plugin/package/package_available_get_test.go
  cmd/cli/plugin/package/testdata/test-default-values.yaml
  pkg/v1/openapischema/schema_default.go
  pkg/v1/openapischema/schema_default_test.go
  pkg/v1/openapischema/suite_test.go
  pkg/v1/openapischema/testdata/contour-data-values.yaml
  pkg/v1/openapischema/testdata/contourschema.yaml
  pkg/v1/openapischema/testdata/grafana-data-values.yaml
  pkg/v1/openapischema/testdata/grafanaschema.yaml
  pkg/v1/tkg/tkgpackagedatamodel/package_available.go
Labels: ok-to-merge, cla-not-required, orange

#1549 Updating version tag used for BOM retrieval to v0.16.0
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#1558 Updating version tag used for BOM retrieval to v0.17.0-dev
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#1552 Replace satori/go.uuid with existing dependency google/uuid
  go.mod
  go.sum
  pkg/v1/config/clientconfig_test.go
  pkg/v1/test/cli/framework.go
Labels: ok-to-merge, cla-not-required

#1557 Retract v1.4.0-pre-alpha-* tags in go.mod
  go.mod
Labels: area/repo maintenance, area/release, kind/bug, ok-to-merge, cla-not-required

#1474 Add addons manager package in management package
  Makefile
  addons/Makefile
  packages/kbld-config.yaml
  packages/management/addons-manager/Makefile
  packages/management/addons-manager/README.md
  packages/management/addons-manager/bundle/config/overlays/overlay-addons-manager.yaml
  packages/management/addons-manager/bundle/config/upstream/addons-manager.yaml
  packages/management/addons-manager/bundle/config/values.yaml
  packages/management/addons-manager/bundle/vendir.lock.yml
  packages/management/addons-manager/bundle/vendir.yml
  packages/management/addons-manager/metadata.yaml
  packages/management/addons-manager/package.yaml
  packages/package-values.yaml
Labels: ok-to-merge, cla-not-required, orange
