Repository vmware-tanzu/tanzu-framework, pull requests merged in 2022-12, with the labels that each got.

#4022 Validation of kubevip lb
  providers/tests/clustergen/param_models/cluster_optional.model
  providers/yttcb/clusterbootstrap.yaml
  providers/yttcc/lib/config_variable_association.star
  tkg/client/cluster.go
  tkg/client/validate.go
  tkg/client/validate_test.go
  tkg/constants/config_variables.go
Labels: ok-to-merge, cla-not-required

#4054 Fix the deletion of discovery sources by using DeleteCLIDiscoverySource API in tanzu plugin source delete command
  cli/core/pkg/command/discovery_source.go
  cli/runtime/config/cli_discovery_sources.go
  cli/runtime/config/cli_discovery_sources_test.go
  cli/runtime/config/legacy_clientconfig_factory.go
Labels: ok-to-merge, cla-not-required

#4059 Fix missing TKR repo key for the oracle provider.
  tkg/managementcomponents/helper.go
  tkg/tkgconfigbom/bom_types.go
Labels: ok-to-merge, cla-not-required

#4048 Get akoo package input from addon secret during cluster upgrade
  packages/tkg/bundle/config/packageinstalls/ako-operator-pi.yaml
  tkg/client/management_components.go
  tkg/client/management_components_test.go
  tkg/constants/cluster_internal.go
  tkg/managementcomponents/management_component_install.go
Labels: area/cli, area/addons, ok-to-merge, cla-not-required, area/lcm, area/cc

#4039 Fix featuregates package installation in Clusterclass based AWS clusters
  packages/featuregates/bundle/config/values.yaml
  packages/framework/bundle/config/values.yaml
  packages/tkg/bundle/config/values.yaml
Labels: ok-to-merge, cla-not-required

#3914 Add capabilities config back to ytt directory in providers module
  providers/ytt/03_customizations/capabilities/add_capabilities.yaml
  tkg/client/upgrade_addon.go
  tkg/client/upgrade_cluster.go
Labels: ok-to-merge, cla-not-required

#3990 Fix upgrade check to allow upgrades to 2.x.x
  tkg/client/upgrade_region.go
  tkg/client/upgrade_region_test.go
  tkg/fakes/config/bom/tkg-bom-v2.1.0.yaml
  tkg/fakes/config/bom/tkg-bom-v3.0.0.yaml
Labels: ok-to-merge, cla-not-required

#4067 Fix the KUBEVIP_LOADBALANCER_CIDRS typo
  providers/config_default.yaml
Labels: ok-to-merge, cla-not-required

#3954 Tanzu CLI Configuration - Multi file approach
  cli/core/pkg/command/config.go
  cli/core/pkg/pluginmanager/default_discoveries_test.go
  cli/core/pkg/pluginmanager/manager_helper_test.go
  cli/core/pkg/pluginmanager/test/config-ng.yaml
  cli/runtime/apis/config/v1alpha1/metadata_clientconfig_types.go
  cli/runtime/apis/config/v1alpha1/zz_generated.deepcopy.go
  cli/runtime/config/cli_discovery_sources_it_test.go
  cli/runtime/config/cli_discovery_sources_test.go
  cli/runtime/config/cli_options_test.go
  cli/runtime/config/cli_repositories.go
  cli/runtime/config/cli_repositories_it_test.go
  cli/runtime/config/cli_repositories_test.go
  cli/runtime/config/clientconfig_factory.go
  cli/runtime/config/clientconfig_factory_test.go
  cli/runtime/config/clientconfig_test.go
  cli/runtime/config/clientconfignextgen_factory.go
  cli/runtime/config/clientconfignextgen_factory_test.go
  cli/runtime/config/clientconfignextgen_filesystem.go
  cli/runtime/config/clientconfignextgen_lock.go
  cli/runtime/config/collectionutils/arrayutils.go
  cli/runtime/config/config_factory.go
  cli/runtime/config/config_factory_test.go
  cli/runtime/config/config_keys.go
  cli/runtime/config/config_types.go
  cli/runtime/config/contexts.go
  cli/runtime/config/contexts_it_test.go
  cli/runtime/config/contexts_test.go
  cli/runtime/config/discovery_sources_node.go
  cli/runtime/config/envs.go
  cli/runtime/config/helpers_test.go
  cli/runtime/config/legacy_clientconfig.go
  cli/runtime/config/legacy_clientconfig_factory.go
  cli/runtime/config/legacy_clientconfig_factory_test.go
  cli/runtime/config/legacy_clientconfig_filesystem.go
  cli/runtime/config/lock.go
  cli/runtime/config/metadata_api.go
  cli/runtime/config/metadata_api_test.go
  cli/runtime/config/metadata_factory.go
  cli/runtime/config/metadata_factory_test.go
  cli/runtime/config/metadata_filesystem.go
  cli/runtime/config/metadata_keys.go
  cli/runtime/config/metadata_lock.go
  cli/runtime/config/metadata_settings_api.go
  cli/runtime/config/metadata_settings_api_test.go
  cli/runtime/config/nodeutils/delete_nodes.go
  cli/runtime/config/nodeutils/delete_nodes_test.go
  cli/runtime/config/nodeutils/helpers.go
  cli/runtime/config/nodeutils/merge_nodes.go
  cli/runtime/config/patchstrategy_it_test.go
  cli/runtime/config/servers.go
  cli/runtime/config/servers_it_test.go
  cli/runtime/config/servers_test.go
Labels: ok-to-merge, cla-not-required

#3948 Fix cc json patches related to dualstack
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  providers/infrastructure-vsphere/v1.5.0/cconly/base.yaml
Labels: ok-to-merge, cla-not-required

#3850 Make feature plugin work for Feature and FeatureGate APIs in core.tanzu.vmware.com
  cmd/cli/plugin/feature/README.md
  cmd/cli/plugin/feature/activate.go
  cmd/cli/plugin/feature/deactivate.go
  cmd/cli/plugin/feature/go.mod
  cmd/cli/plugin/feature/list.go
  cmd/cli/plugin/feature/list_test.go
  cmd/cli/plugin/feature/main.go
  featuregates/client/pkg/featuregateclient/client.go
  featuregates/client/pkg/featuregateclient/client_test.go
  featuregates/client/pkg/featuregateclient/errors.go
  featuregates/client/pkg/featuregateclient/fake/objects.go
  featuregates/client/pkg/featuregateclient/validation.go
Labels: enhancement, area/cli, area/plugin, area/api, kind/feature, ok-to-merge, cla-not-required

#4033 Support configuring etcd flags
  packages/tkg-clusterclass-aws/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-azure/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  providers/config_default.yaml
  providers/infrastructure-aws/v2.0.1/cconly/base.yaml
  providers/infrastructure-aws/v2.0.1/yttcc/overlay.yaml
  providers/infrastructure-azure/v1.5.3/cconly/base.yaml
  providers/infrastructure-azure/v1.5.3/yttcc/overlay.yaml
  providers/infrastructure-vsphere/v1.5.0/cconly/base.yaml
  providers/infrastructure-vsphere/v1.5.0/yttcc/overlay.yaml
  providers/yttcc/lib/config_variable_association.star
  providers/yttcc/lib/helpers.star
Labels: ok-to-merge, cla-not-required

#3992 Change the certificate struct for clusterclass, combining all certs into one encoding
  addons/controllers/clusterbootstrap_controller_test.go
  addons/controllers/kapp-controller/kappcontrollerconfig_types.go
  addons/controllers/kappcontrollerconfig_controller_test.go
  addons/controllers/testdata/test-kapp-controller-1.yaml
  addons/pkg/util/cluster_variable_util.go
  addons/pkg/util/cluster_variable_util_test.go
  packages/tkg-clusterclass-aws/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-azure/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-oci/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  providers/infrastructure-aws/v2.0.1/cconly/base.yaml
  providers/infrastructure-azure/v1.5.3/cconly/base.yaml
  providers/infrastructure-oci/v0.4.0/cconly/base.yaml
  providers/infrastructure-vsphere/v1.5.0/cconly/base.yaml
  providers/yttcc/lib/config_variable_association.star
Labels: ok-to-merge, cla-not-required

#4058 Pass bootstrap cluster flag to AKOO-v2
  packages/ako-operator-v2/bundle/config/overlays/overlay-deployment.yaml
  packages/ako-operator-v2/bundle/config/values.yaml
  tkg/client/management_components.go
  tkg/managementcomponents/helper.go
  tkg/managementcomponents/helper_test.go
  tkg/managementcomponents/test/output_vsphere_with_avi_enabled_bootstrap_cluster.yaml
  tkg/managementcomponents/test/output_vsphere_with_avi_enabled_management_cluster.yaml
  tkg/managementcomponents/types.go
Labels: ok-to-merge, cla-not-required

#4066 [provider][Azure] Add extraVolumes as jsonpatch
  packages/tkg-clusterclass-azure/bundle/config/upstream/base.yaml
  providers/infrastructure-azure/v1.5.3/cconly/base.yaml
Labels: ok-to-merge, cla-not-required

#4078 remove redundant values from vsphere cc package
  packages/tkg-clusterclass-vsphere/bundle/config/values.yaml
Labels: ok-to-merge, cla-not-required

#4075 fix azure cc upgrade issue
  packages/tkg-clusterclass-azure/bundle/config/upstream/base.yaml
  providers/infrastructure-azure/v1.5.3/cconly/base.yaml
Labels: ok-to-merge, cla-not-required

#4079 Retry 3 times for WaitForClusterInitialized
  tkg/clusterclient/clusterclient.go
Labels: ok-to-merge, cla-not-required

#4088 Revert "Retry 3 times for WaitForClusterInitialized"
  tkg/clusterclient/clusterclient.go
Labels: ok-to-merge, cla-not-required

#4074 Rename ContextType to Target in ClientConfig
  apis/cli/v1alpha1/cliplugin_helper.go
  apis/cli/v1alpha1/cliplugin_types.go
  apis/config/config/crd/bases/config.tanzu.vmware.com_clientconfigs.yaml
  cli/core/docs/cli/plugin_implementation_guide.md
  cli/core/docs/design/context-aware-plugin-discovery-design.md
  cli/core/pkg/auth/csp/grpc_test.go
  cli/core/pkg/command/context.go
  cli/core/pkg/command/plugin_manager.go
  cli/core/pkg/command/root.go
  cli/core/pkg/discovery/rest.go
  cli/core/pkg/pluginmanager/default_discoveries.go
  cli/core/pkg/pluginmanager/default_discoveries_test.go
  cli/core/pkg/pluginmanager/manager.go
  cli/core/pkg/pluginmanager/test/config-ng.yaml
  cli/core/pkg/pluginmanager/test/config.yaml
  cli/runtime/apis/config/v1alpha1/clientconfig.go
  cli/runtime/apis/config/v1alpha1/clientconfig_test.go
  cli/runtime/apis/config/v1alpha1/clientconfig_types.go
  cli/runtime/apis/config/v1alpha1/zz_generated.deepcopy.go
  cli/runtime/config/cli_discovery_sources_it_test.go
  cli/runtime/config/cli_repositories_it_test.go
  cli/runtime/config/clientconfig_test.go
  cli/runtime/config/clientconfignextgen_factory_test.go
  cli/runtime/config/config_factory_test.go
  cli/runtime/config/contexts.go
  cli/runtime/config/contexts_it_test.go
  cli/runtime/config/contexts_test.go
  cli/runtime/config/conversion.go
  cli/runtime/config/conversion_test.go
  cli/runtime/config/helpers_test.go
  cli/runtime/config/legacy_clientconfig_factory_test.go
  cli/runtime/config/nodeutils/compare_nodes_test.go
  cli/runtime/config/nodeutils/delete_nodes_test.go
  cli/runtime/config/nodeutils/merge_nodes_test.go
  cli/runtime/config/patchstrategy_it_test.go
  cli/runtime/config/servers_it_test.go
  cli/runtime/generated/crd/bases/cli.tanzu.vmware.com_catalogs.yaml
  cli/runtime/generated/crd/bases/config.tanzu.vmware.com_clientconfigs.yaml
  featuregates/client/go.mod
Labels: ok-to-merge, cla-not-required, area/core-cli

#4053 Set clusterkind explicitly from constant instead of retrieving from o…
  addons/controllers/antrea/antreaconfig_util.go
  addons/controllers/calico/calicoconfig_utils.go
  addons/controllers/cpi/cpiconfig_util.go
  addons/controllers/csi/vspherecsiconfig_utils.go
  addons/controllers/kapp-controller/kappcontrollerconfig_handlers.go
  addons/controllers/kubevipcpi/kubevipcpiconfig_utils.go
Labels: ok-to-merge, cla-not-required

#4090 Fix `current` field getting set to tmc context in client config
  cli/runtime/config/contexts.go
  cli/runtime/config/servers.go
Labels: ok-to-merge, cla-not-required, area/core-cli

#4071 Discard contexts and currentContext nodes from config.yaml
  cli/runtime/config/cli_discovery_sources_it_test.go
  cli/runtime/config/cli_repositories_it_test.go
  cli/runtime/config/config_factory.go
  cli/runtime/config/config_factory_test.go
  cli/runtime/config/patchstrategy_it_test.go
Labels: ok-to-merge, cla-not-required, area/core-cli

#4081 Enable feature-flag for `context-target` by default
  cli/core/docs/cli/cli-architecture.md
  cli/core/pkg/config/featureflags.go
  cli/core/pkg/pluginmanager/manager_helper_test.go
  cli/core/pkg/pluginmanager/manager_test.go
Labels: ok-to-merge, cla-not-required, area/core-cli

#4089 Adding missing secret for kube-proxy token SA
  providers/infrastructure-vsphere/v1.5.1/ytt/overlay-windows.yaml
Labels: ok-to-merge, cla-not-required

#4060 Skip the same cluster name validation if dry-run
  tkg/client/client.go
  tkg/client/validate.go
  tkg/client/validate_test.go
  tkg/tkgctl/init.go
Labels: ok-to-merge, cla-not-required

#4034 fix #3817 use latest available k8s version if not specified when upgrading cluster
  cmd/cli/plugin/cluster/upgrade.go
  cmd/cli/plugin/cluster/upgrade_test.go
Labels: ok-to-merge, cla-not-required

#4052 Adds aws cni ingress rules
  tkg/clusterclient/clusterclient.go
  tkg/clusterclient/clusterclient_test.go
Labels: ok-to-merge, cla-not-required

#4094 Add provider type oracle cloud infrastructure in validate func
  tkg/client/cluster.go
  tkg/client/validate.go
Labels: ok-to-merge, cla-not-required

#3956 Decouple the feature gate of control management-cluster and workload-cluster mode
  .github/workflows/tkg_integration_tests.yaml
  addons/controllers/addon_controller.go
  cli/core/pkg/config/featureflags.go
  cmd/cli/plugin/cluster/available_upgrade.go
  cmd/cli/plugin/cluster/featureflags.go
  cmd/cli/plugin/cluster/upgrade.go
  providers/config_default.yaml
  tkg/client/cluster.go
  tkg/client/common.go
  tkg/client/common_test.go
  tkg/client/config.go
  tkg/client/init.go
  tkg/client/management_components.go
  tkg/client/upgrade_cluster.go
  tkg/client/upgrade_region.go
  tkg/client/utils.go
  tkg/client/utils_test.go
  tkg/client/validate.go
  tkg/constants/cluster_internal.go
  tkg/constants/config_variables.go
  tkg/constants/featureflags.go
  tkg/test/cc_setup.md
  tkg/test/scripts/cc_hack.sh
  tkg/test/scripts/legacy_hack.sh
  tkg/test/tkgctl/aws/aws_suite_test.go
  tkg/test/tkgctl/azure/azure_suite_test.go
  tkg/test/tkgctl/docker/docker_suite_test.go
  tkg/test/tkgctl/oracle_cc/oracle_cc_suite_test.go
  tkg/test/tkgctl/tkgs/tkgs_suite_test.go
  tkg/test/tkgctl/tkgs_cc/tkgs_cc_suite_test.go
  tkg/test/tkgctl/vsphere67/vsphere_suite_test.go
  tkg/tkgctl/create_cluster.go
  tkg/tkgctl/create_cluster_test.go
Labels: ok-to-merge, cla-not-required

#4099 Revert "Add cli plugin for airgapped image copy"
  .github/workflows/unittests.yaml
  Makefile
  apis/run/pkg/tkr/v1/bom.go
  cmd/cli/plugin/isolated-cluster/Makefile
  cmd/cli/plugin/isolated-cluster/README.md
  cmd/cli/plugin/isolated-cluster/fakes/client_imgpkg_fake.go
  cmd/cli/plugin/isolated-cluster/go.mod
  cmd/cli/plugin/isolated-cluster/go.sum
  cmd/cli/plugin/isolated-cluster/imageop/client_imgpkg.go
  cmd/cli/plugin/isolated-cluster/imageop/interface.go
  cmd/cli/plugin/isolated-cluster/imageop/publishimagesfromtar.go
  cmd/cli/plugin/isolated-cluster/imageop/publishimagestotar.go
  cmd/cli/plugin/isolated-cluster/imageop/util.go
  cmd/cli/plugin/isolated-cluster/main.go
  cmd/cli/plugin/isolated-cluster/test/main.go
  cmd/cli/plugin/isolated-cluster/test/publishimagesfromtar_test.go
  cmd/cli/plugin/isolated-cluster/test/publishimagestotar_test.go
  cmd/cli/plugin/isolated-cluster/test/testdata/publish-images-fromtar
  cmd/cli/plugin/isolated-cluster/test/testdata/publish-images-fromtar_with_error
  cmd/cli/plugin/isolated-cluster/test/testdata/tkg-bom-v1.3.0.yaml
  cmd/cli/plugin/isolated-cluster/test/testdata/tkr-bom-v1.17.16+vmware.2-tkg.1.yaml
  cmd/cli/plugin/isolated-cluster/test/testdata/tkr-compatibility.yaml
  common.mk
  packages/standalone-plugins/bundle/config/overlay/isolated-cluster.yaml
  packages/standalone-plugins/kbld-config.yaml
  packages/standalone-plugins/values.template.yaml
Labels: ok-to-merge, cla-not-required

#2806 Remove podcidr auto-fill when tkgs routable pod feature is enabled
  tkg/client/validate.go
  tkg/client/validate_test.go
  tkg/constants/config_variables.go
Labels: ok-to-merge, cla-not-required

#4106 Skip plugin sync when --dry-run flag is used with management-cluster create
  cmd/cli/plugin/managementcluster/create.go
Labels: kind/bug, ok-to-merge, cla-not-required

#4064 Translate FQDN ytt template to ClusterClass json patch
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  providers/config_default.yaml
  providers/infrastructure-vsphere/v1.5.1/cconly/base.yaml
  providers/infrastructure-vsphere/v1.5.1/yttcc/overlay.yaml
  providers/yttcc/lib/config_variable_association.star
Labels: ok-to-merge, cla-not-required

#4085 Move identity secret in front of Cluster
  providers/infrastructure-vsphere/v1.5.1/yttcc/base-template.yaml
  providers/infrastructure-vsphere/v1.5.1/yttcc/overlay.yaml
Labels: ok-to-merge, cla-not-required

#4117 fix applying additional manifest error
  cmd/cli/plugin/managementcluster/osimage_oracle.go
Labels: ok-to-merge, cla-not-required

#4103 WIP: Add new airgapped plugin as standalone plugin
  Makefile
  apis/run/pkg/tkr/v1/bom.go
  cmd/cli/plugin/isolated-cluster/Makefile
  cmd/cli/plugin/isolated-cluster/README.md
  cmd/cli/plugin/isolated-cluster/fakes/client_imgpkg_fake.go
  cmd/cli/plugin/isolated-cluster/go.mod
  cmd/cli/plugin/isolated-cluster/go.sum
  cmd/cli/plugin/isolated-cluster/imageop/client_imgpkg.go
  cmd/cli/plugin/isolated-cluster/imageop/interface.go
  cmd/cli/plugin/isolated-cluster/imageop/publishimagesfromtar.go
  cmd/cli/plugin/isolated-cluster/imageop/publishimagestotar.go
  cmd/cli/plugin/isolated-cluster/imageop/util.go
  cmd/cli/plugin/isolated-cluster/main.go
  cmd/cli/plugin/isolated-cluster/test/main.go
  cmd/cli/plugin/isolated-cluster/test/publishimagesfromtar_test.go
  cmd/cli/plugin/isolated-cluster/test/publishimagestotar_test.go
  cmd/cli/plugin/isolated-cluster/test/testdata/publish-images-fromtar
  cmd/cli/plugin/isolated-cluster/test/testdata/publish-images-fromtar_with_error
  cmd/cli/plugin/isolated-cluster/test/testdata/tkg-bom-v1.3.0.yaml
  cmd/cli/plugin/isolated-cluster/test/testdata/tkr-bom-v1.17.16+vmware.2-tkg.1.yaml
  cmd/cli/plugin/isolated-cluster/test/testdata/tkr-compatibility.yaml
  common.mk
  hack/test-release-artifacts.ps1
  hack/test-release-artifacts.sh
  packages/standalone-plugins/bundle/config/overlay/isolated-cluster.yaml
  packages/standalone-plugins/kbld-config.yaml
  packages/standalone-plugins/values.template.yaml
Labels: ok-to-merge, cla-not-required

#4101 Support specifying extraArgs for kubelet/scheduler/apiserver/controllermanager
  packages/tkg-clusterclass-aws/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-azure/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  providers/config_default.yaml
  providers/infrastructure-aws/v2.0.2/cconly/base.yaml
  providers/infrastructure-aws/v2.0.2/yttcc/overlay.yaml
  providers/infrastructure-azure/v1.5.3/cconly/base.yaml
  providers/infrastructure-azure/v1.5.3/yttcc/overlay.yaml
  providers/infrastructure-vsphere/v1.5.1/cconly/base.yaml
  providers/infrastructure-vsphere/v1.5.1/yttcc/overlay.yaml
  providers/yttcc/lib/config_variable_association.star
Labels: ok-to-merge, cla-not-required

#4121 ensure cluster's controlplane reference is set before accessing
  addons/controllers/csi/vspherecsiconfig_utils.go
Labels: ok-to-merge, cla-not-required

#3916 Plumb legacy PinnipedConfigs to ClusterBootstrap
  packages/tanzu-auth/metadata.yaml
  pinniped-components/post-deploy/pkg/configure/configure.go
  pinniped-components/post-deploy/pkg/configure/configure_test.go
  pinniped-components/post-deploy/pkg/configure/helper.go
  pinniped-components/post-deploy/pkg/configure/helper_test.go
  pinniped-components/tanzu-auth-controller-manager/controllers/v1_cascade_controller.go
  pinniped-components/tanzu-auth-controller-manager/controllers/v1_cascade_controller_test.go
  pinniped-components/tanzu-auth-controller-manager/controllers/v3_cascade_controller.go
  pinniped-components/tanzu-auth-controller-manager/controllers/v3_cascade_controller_test.go
  pinniped-components/tanzu-auth-controller-manager/hack/generate-package-secret.sh
  providers/yttcb/clusterbootstrap.yaml
  providers/yttcb/clusterbootstraphelpers.star
  providers/yttcb/pinniped_addon_secret.lib.yaml
  providers/yttcc/09_miscellaneous/09_filter.yaml
  tkg/client/get_cluster_pinniped_info.go
  tkg/client/get_cluster_pinniped_info_test.go
Labels: ok-to-merge, cla-not-required

#4086 Adds logic to handle ingress port for addons-manager on upgrade
  tkg/client/upgrade_cluster.go
  tkg/client/upgrade_cluster_test.go
  tkg/client/upgrade_region.go
  tkg/clusterclient/clusterclient.go
  tkg/clusterclient/clusterclient_test.go
  tkg/fakes/clusterclient.go
Labels: ok-to-merge, cla-not-required

#3993 fix azurefisk && azurefile replica
  addons/config/expected/csi.tanzu.vmware.com/v1alpha1/azurediskcsiconfig/default.yaml
  addons/config/templates/csi.tanzu.vmware.com/v1alpha1/azurediskcsiconfig.yaml
  addons/controllers/azurediskcsi/azurediskconfig_utils.go
  addons/controllers/azurediskcsi/azurediskcsiconfig_controller.go
  addons/controllers/azurefilecsi/azurefilecsiconfig_utils.go
  addons/pkg/constants/constants.go
  apis/addonconfigs/csi/v1alpha1/azurediskcsiconfig_types.go
  apis/addonconfigs/csi/v1alpha1/azurefilecsiconfig_types.go
  providers/yttcb/clusterbootstrap.yaml
Labels: ok-to-merge, cla-not-required

#4112 clusterclass: move overlays from tkg-clusterclass to provider specific directories
  packages/tkg-clusterclass-aws/bundle/config/upstream/overlay-pod-security-admission.yaml
  packages/tkg-clusterclass-aws/bundle/config/upstream/overlay.yaml
  packages/tkg-clusterclass-azure/bundle/config/upstream/overlay-pod-security-admission.yaml
  packages/tkg-clusterclass-azure/bundle/config/upstream/overlay.yaml
  packages/tkg-clusterclass-docker/bundle/config/upstream/overlay-pod-security-admission.yaml
  packages/tkg-clusterclass-docker/bundle/config/upstream/overlay.yaml
  packages/tkg-clusterclass-oci/bundle/config/upstream/overlay-pod-security-admission.yaml
  packages/tkg-clusterclass-oci/bundle/config/upstream/overlay.yaml
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/overlay-pod-security-admission.yaml
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/overlay.yaml
  packages/tkg-clusterclass-vsphere/vendir.lock.yml
  packages/tkg-clusterclass-vsphere/vendir.yml
  packages/tkg-clusterclass/bundle/config/packageinstalls/tkg-infra-clusterclass-pi.yaml
  providers/infrastructure-aws/v2.0.2/cconly/overlay-pod-security-admission.yaml
  providers/infrastructure-aws/v2.0.2/cconly/overlay.yaml
  providers/infrastructure-aws/v2.0.2/yttcc/overlay.yaml
  providers/infrastructure-azure/v1.5.3/cconly/overlay-pod-security-admission.yaml
  providers/infrastructure-azure/v1.5.3/cconly/overlay.yaml
  providers/infrastructure-azure/v1.5.3/yttcc/overlay.yaml
  providers/infrastructure-docker/v1.2.7/cconly/overlay-pod-security-admission.yaml
  providers/infrastructure-docker/v1.2.7/cconly/overlay.yaml
  providers/infrastructure-oci/v0.4.0/cconly/overlay-pod-security-admission.yaml
  providers/infrastructure-oci/v0.4.0/cconly/overlay.yaml
  providers/infrastructure-vsphere/v1.5.1/cconly/overlay-pod-security-admission.yaml
  providers/infrastructure-vsphere/v1.5.1/cconly/overlay.yaml
  providers/infrastructure-vsphere/v1.5.1/yttcc/overlay.yaml
  providers/yttcc/lib/config_variable_association.star
Labels: ok-to-merge, cla-not-required

#4132 Bump capz 1.4.5
  addons/go.mod
  addons/go.sum
  go.mod
  go.sum
  packages/cluster-api-provider-azure/bundle/config/upstream/infrastructure-components.yaml
  packages/cluster-api-provider-azure/vendir.lock.yml
  packages/cluster-api-provider-azure/vendir.yml
  pkg/v1/providers/config.yaml
  pkg/v1/providers/infrastructure-azure/v1.4.5/cconly/base.yaml
  pkg/v1/providers/infrastructure-azure/v1.4.5/cconly/overlay.yaml
  pkg/v1/providers/infrastructure-azure/v1.4.5/cluster-template-definition-dev.yaml
  pkg/v1/providers/infrastructure-azure/v1.4.5/cluster-template-definition-devcc.yaml
  pkg/v1/providers/infrastructure-azure/v1.4.5/cluster-template-definition-prod.yaml
  pkg/v1/providers/infrastructure-azure/v1.4.5/cluster-template-definition-prodcc.yaml
  pkg/v1/providers/infrastructure-azure/v1.4.5/clusterclass-tkg-azure-default.yaml
  pkg/v1/providers/infrastructure-azure/v1.4.5/infrastructure-components.yaml
  pkg/v1/providers/infrastructure-azure/v1.4.5/metadata.yaml
  pkg/v1/providers/infrastructure-azure/v1.4.5/ytt/base-template.yaml
  pkg/v1/providers/infrastructure-azure/v1.4.5/ytt/overlay.yaml
  pkg/v1/providers/infrastructure-azure/v1.4.5/yttcc/base-template.yaml
  pkg/v1/providers/infrastructure-azure/v1.4.5/yttcc/overlay.yaml
Labels: ok-to-merge, cla-not-required

#4113 Allowing spread of Windows MD across zones
  tkg/client/client_suite_test.go
  tkg/client/cluster.go
  tkg/client/config.go
  tkg/client/init.go
  tkg/client/validate.go
Labels: ok-to-merge, cla-not-required

#3968 CLI Core - base framework for end-to-end test cases implementation
  .github/workflows/cli_core_e2e_test.yaml
  cli/core/Makefile
  cli/core/test/e2e/cli_lifecycle/init_version_cmds.go
  cli/core/test/e2e/config/config_suite_test.go
  cli/core/test/e2e/config/config_test.go
  cli/core/test/e2e/framework/cli_lifecycle_operations.go
  cli/core/test/e2e/framework/cluster_container_runtime.go
  cli/core/test/e2e/framework/cluster_interface.go
  cli/core/test/e2e/framework/cluster_kind.go
  cli/core/test/e2e/framework/cmd_exec_operations.go
  cli/core/test/e2e/framework/config_operations.go
  cli/core/test/e2e/framework/framework.go
  cli/core/test/e2e/framework/util.go
Labels: area/testing, ok-to-merge, cla-not-required

#4152 Update dependabot.yaml to disable version checks correctly
  .github/dependabot.yml
Labels: area/repo maintenance, ok-to-merge, cla-not-required

#4102 add e2e case in azure cc test
  tkg/test/config/azure.yaml
  tkg/test/tkgctl/azure_cc/azure_cc_antrea_test.go
  tkg/test/tkgctl/shared/e2e_common_cc.go
  tkg/test/tkgctl/shared/package.go
Labels: ok-to-merge, cla-not-required

#4130 fix TKG-15754
  providers/yttcc/02_customizations/annotate_os_info.yaml
Labels: ok-to-merge, cla-not-required

#4159 Update BOM retrieval version to v0.25.4
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#4123 Support oci clusterclass customization for kubelet/scheduler/apiserver/controllermanager/etcd
  packages/tkg-clusterclass-oci/bundle/config/upstream/base.yaml
  providers/infrastructure-oci/v0.4.0/cconly/base.yaml
  providers/yttcc/lib/config_variable_association.star
Labels: ok-to-merge, cla-not-required

#4147 Add missing `TKG_DEFAULT_IMAGE_REPOSITORY` in CLI Makefile
  cli/core/Makefile
Labels: ok-to-merge, cla-not-required, area/core-cli

#4135 Adding support for cc packages in airgap cli
  .github/workflows/unittests.yaml
  apis/run/pkg/tkr/v1/tkgBom.go
  cmd/cli/plugin/isolated-cluster/go.mod
  cmd/cli/plugin/isolated-cluster/go.sum
  cmd/cli/plugin/isolated-cluster/imageop/client_imgpkg.go
  cmd/cli/plugin/isolated-cluster/imageop/publishimagestotar.go
  cmd/cli/plugin/isolated-cluster/test/publishimagestotar_test.go
  cmd/cli/plugin/isolated-cluster/test/testdata/tkg-bom-v1.3.0.yaml
Labels: ok-to-merge, cla-not-required

#4154 Update yttcb for pinniped defaults, disabling pinniped
  providers/yttcb/clusterbootstrap.yaml
  providers/yttcb/pinniped_addon_secret.lib.yaml
Labels: ok-to-merge, cla-not-required

#4116 Add ownerRef to nsx-t and vsphere secret referred by vspherecpiconfig
  addons/controllers/cpi/vspherecpiconfig_utils.go
  addons/controllers/testdata/test-vsphere-cpi-non-paravirtual-enqueue-cluster-event-cluster-spec.yaml
  addons/controllers/vspherecpiconfig_controller_test.go
  providers/yttcb/clusterbootstrap.yaml
Labels: ok-to-merge, cla-not-required

#4134 Supplement unit tests for pr 3956
  tkg/client/cluster.go
  tkg/client/cluster_test.go
  tkg/client/common.go
  tkg/client/common_test.go
Labels: ok-to-merge, cla-not-required

#4141 update tkr-controller-config cm namespace in upgrade_addon
  tkg/client/upgrade_addon.go
  tkg/client/upgrade_addon_test.go
Labels: ok-to-merge, cla-not-required

#4138 forbid calico mgmt cluster creation unless allowCalico env is set to true
  tkg/test/tkgctl/docker/docker_suite_test.go
  tkg/tkgctl/init.go
  tkg/tkgctl/init_test.go
Labels: ok-to-merge, cla-not-required

#3926 VSphere Cluster CC/Template: Use local_hostname instead of FQDN for node name
  cmd/cli/plugin-admin/builder/command/cli_compile.go
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  providers/infrastructure-vsphere/v1.5.1/cconly/base.yaml
  providers/infrastructure-vsphere/v1.5.1/ytt/base-template.yaml
  providers/tests/unit/ip_family_test.go
Labels: ok-to-merge, cla-not-required

#4151 Missing flag from isolated-cluster plugin
  cmd/cli/plugin/isolated-cluster/imageop/publishimagesfromtar.go
  cmd/cli/plugin/isolated-cluster/imageop/publishimagestotar.go
Labels: ok-to-merge, cla-not-required

#4122 Overwrite existing TKRs when installing TKRs from TKR packages
  tkr/controller/tkr-source/pkgcr/reconciler.go
  tkr/controller/tkr-source/pkgcr/reconciler_test.go
Labels: ok-to-merge, cla-not-required, area/tkr

#4167 Update CPI CVEs
  providers/vendir.lock.yml
  providers/vendir.yml
  providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.24.3/bundle/config/overlays/update-strategy-overlay.yaml
  providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.24.3/bundle/config/overlays/vsphere-cpi/add-secret.yaml
  providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.24.3/bundle/config/overlays/vsphere-cpi/update-config.yaml
  providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.24.3/bundle/config/overlays/vsphere-cpi/update-daemonset.yaml
  providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.24.3/bundle/config/overlays/vsphere-cpi/update-secret.yaml
  providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.24.3/bundle/config/overlays/vsphere-paravirtual-cpi/update-deployment.yaml
  providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.24.3/bundle/config/schema.yaml
  providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.24.3/bundle/config/upstream/vsphere-cpi/01-rbac.yaml
  providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.24.3/bundle/config/upstream/vsphere-cpi/02-config.yaml
  providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.24.3/bundle/config/upstream/vsphere-cpi/03-secret.yaml
  providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.24.3/bundle/config/upstream/vsphere-cpi/04-daemonset.yaml
  providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.24.3/bundle/config/upstream/vsphere-paravirtual-cpi/01-rbac.yaml
  providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.24.3/bundle/config/upstream/vsphere-paravirtual-cpi/02-config.yaml
  providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.24.3/bundle/config/upstream/vsphere-paravirtual-cpi/03-deployment.yaml
  providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.24.3/bundle/config/values.star
  providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.24.3/bundle/config/values.yaml
  providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.24.3/bundle/config/vsphereconf.lib.txt
  providers/ytt/vendir/vsphere_cpi/vsphere_cpi.lib.yaml
Labels: ok-to-merge, cla-not-required

#4155 Default deploy-in-cluster-ipam-provider to true
  cmd/cli/plugin/managementcluster/featureflags.go
  tkg/constants/featureflags.go
Labels: ok-to-merge, cla-not-required

#4170 add ALLOW_LEGACY_CLUSTER parameter into default config
  providers/config_default.yaml
Labels: ok-to-merge, cla-not-required

#4146 retry 3 times for WaitForClusterInitialized
  tkg/clusterclient/clusterclient.go
Labels: ok-to-merge, cla-not-required

#4120 Kickstart UI: Update packages to address critical and severe npm warnings
  tkg/web/package-lock.json
  tkg/web/package.json
Labels: area/security, ok-to-merge, cla-not-required

#4097 Bring Feature plugin, client unit tests to >70% coverage, upload to Codecov
  cmd/cli/plugin/feature/activate.go
  cmd/cli/plugin/feature/activate_test.go
  cmd/cli/plugin/feature/deactivate.go
  cmd/cli/plugin/feature/deactivate_test.go
  cmd/cli/plugin/feature/go.mod
  cmd/cli/plugin/feature/list_test.go
  cmd/cli/plugin/feature/testdata/k8s_config.kube
  featuregates/client/pkg/featuregateclient/client_test.go
  featuregates/client/pkg/featuregateclient/fake/objects.go
Labels: area/testing, area/plugin, ok-to-merge, cla-not-required

#4153 Fixing correct default values for AntreaConfig template
  addons/config/expected/cni.tanzu.vmware.com/v1alpha1/antreaconfig/default.yaml
  addons/config/templates/cni.tanzu.vmware.com/v1alpha1/antreaconfig.yaml
  addons/controllers/antreaconfig_controller_test.go
Labels: ok-to-merge, cla-not-required

#4189 Deploy IPAM Provider on bootstrap cluster
  tkg/client/delete_region.go
  tkg/client/init.go
Labels: ok-to-merge, cla-not-required

#4175 Bump kapp-controller to v0.41.5
  providers/vendir.lock.yml
  providers/vendir.yml
  providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.41.5/bundle/config/overlays/change-namespace.yaml
  providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.41.5/bundle/config/overlays/update-configmap.yaml
  providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.41.5/bundle/config/overlays/update-crds.yaml
  providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.41.5/bundle/config/overlays/update-deployment.yaml
  providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.41.5/bundle/config/overlays/update-strategy-overlay.yaml
  providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.41.5/bundle/config/upstream/kapp-controller.yaml
  providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.41.5/bundle/config/values.star
  providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.41.5/bundle/config/values.yaml
  providers/ytt/vendir/kapp-controller/kapp-controller.lib.yaml
Labels: ok-to-merge, cla-not-required

#4193 Fix clusterbootstrap continuous reconciliation
  addons/pkg/util/clusterbootstrapclone/clusterbootstrapclone.go
Labels: ok-to-merge, cla-not-required

#4199 isolated-cluster plugin writes incorrect image files
  cmd/cli/plugin/isolated-cluster/imagepullop/publishimagestotar.go
  cmd/cli/plugin/isolated-cluster/imagepushop/publishimagesfromtar.go
Labels: ok-to-merge, cla-not-required

#4143 fix CC vars for pod security standard
  providers/tests/unit/pod_security_standard_test.go
  providers/ytt/03_customizations/pod_security_standard/pod_security_standard.yaml
  providers/ytt/03_customizations/pod_security_standard/validation.yaml
  providers/ytt/lib/config_variable_association.star
  providers/yttcc/lib/config_variable_association.star
Labels: ok-to-merge, cla-not-required

#4194 check tkr creation in bootstrap cluster before creating cc-based mana…
  tkg/client/init.go
Labels: ok-to-merge, cla-not-required

#4198 Change audit policy api version to audit.k8s.io/v1 to adopt 1.24
  packages/tkg-clusterclass-aws/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-azure/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  providers/infrastructure-aws/v2.0.2/cconly/base.yaml
  providers/infrastructure-azure/v1.5.3/cconly/base.yaml
  providers/infrastructure-vsphere/v1.5.1/cconly/base.yaml
  providers/ytt/03_customizations/audit-logging/audit_logging.yaml
Labels: ok-to-merge, cla-not-required

#4197 fix TKG-13994
  packages/tkg-clusterclass/bundle/config/object-propagation/deployment.yaml
Labels: ok-to-merge, cla-not-required

#4192 Fix package plugin tests for classy clusters
  cmd/cli/plugin/package/test/package_plugin_integration_test.go
  cmd/cli/plugin/package/test/scripts/legacy_hack.sh
Labels: ok-to-merge, cla-not-required

#4201 Suppress provider update if developer needs
  tkg/client/common.go
  tkg/client/common_test.go
Labels: ok-to-merge, cla-not-required

#4205 fix aws cluster hardcode ubuntu
  providers/infrastructure-aws/v2.0.2/yttcc/overlay.yaml
Labels: ok-to-merge, cla-not-required

#4200 set the node-ip correctly for kube-vip IPv6-only
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  providers/infrastructure-vsphere/v1.5.1/cconly/base.yaml
Labels: ok-to-merge, cla-not-required

#4162 Rename kctrl-command-tree feature flag
  cli/runtime/config/config_factory_test.go
  cmd/cli/plugin/package/featureflags.go
  cmd/cli/plugin/package/test/package_plugin_integration_test.go
Labels: ok-to-merge, cla-not-required

#4065 Bump kapp-controller cli for package plugin
  cmd/cli/plugin/package/go.mod
  cmd/cli/plugin/package/go.sum
Labels: ok-to-merge, cla-not-required

#4206 Using jsonpatch to fix Windows MD class values for CloudBase-init
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  providers/infrastructure-vsphere/v1.5.1/cconly/base.yaml
  providers/infrastructure-vsphere/v1.5.1/ytt/overlay-windows.yaml
Labels: ok-to-merge, cla-not-required, area/lcm

#4202 Add retry for installing mgmt package repo and packages
  packageclients/pkg/packageclient/package_install.go
  tkg/clusterclient/clusterclient.go
  tkg/managementcomponents/helper.go
  tkg/managementcomponents/management_component_install.go
  tkg/managementcomponents/management_component_install_test.go
  tkg/managementcomponents/utils.go
  tkg/managementcomponents/utils_test.go
Labels: ok-to-merge, cla-not-required, area/lcm
