Repository vmware-tanzu/tanzu-framework, pull requests merged in 2022-06, with the labels that each got.

#2525 Update BOM retrieval version to v0.22.0
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#2247 Bump cluster-api-azure to v1.2.1
  addons/go.mod
  addons/go.sum
  go.mod
  go.sum
  packages/cluster-api-provider-azure/bundle/config/upstream/infrastructure-components.yaml
  packages/cluster-api-provider-azure/bundle/config/upstream/metadata.yaml
  packages/cluster-api-provider-azure/vendir.lock.yml
  packages/cluster-api-provider-azure/vendir.yml
  pkg/v1/providers/config.yaml
  pkg/v1/providers/infrastructure-azure/v1.2.1/cluster-template-definition-dev.yaml
  pkg/v1/providers/infrastructure-azure/v1.2.1/cluster-template-definition-prod.yaml
  pkg/v1/providers/infrastructure-azure/v1.2.1/infrastructure-components.yaml
  pkg/v1/providers/infrastructure-azure/v1.2.1/metadata.yaml
  pkg/v1/providers/infrastructure-azure/v1.2.1/ytt/base-template.yaml
  pkg/v1/providers/infrastructure-azure/v1.2.1/ytt/overlay.yaml
  pkg/v1/providers/tests/clustergen/param_models/cluster_azure.model
Labels: ok-to-merge, cla-not-required, area/lcm

#2218 Switch from strings.Title to cases.Title
  addons/controllers/packageinstallstatus_controller.go
Labels: ok-to-merge, cla-not-required

#2528 Fixes AWS existing VPC ID error, in which CIDR was being used instead of ID
  pkg/v1/tkg/web/src/app/views/landing/aws-wizard/aws-wizard.component.ts
Labels: ok-to-merge, cla-not-required

#2532 CODEOWNERS: packages/management -> packages
  CODEOWNERS
Labels: CI, ok-to-merge, cla-not-required

#2529 tanzu-auth: only run v1a3 controller
  addons/pinniped/tanzu-auth-controller-manager/main.go
  packages/tanzu-auth/bundle/config/deployment.yaml
Labels: CI, ok-to-merge, cla-not-required

#2534 Move azure cc-related files from 1.0.1 to 1.2.1
  pkg/v1/providers/infrastructure-azure/v1.2.1/cconly/base.yaml
  pkg/v1/providers/infrastructure-azure/v1.2.1/cconly/overlay.yaml
  pkg/v1/providers/infrastructure-azure/v1.2.1/cluster-template-definition-devcc.yaml
  pkg/v1/providers/infrastructure-azure/v1.2.1/cluster-template-definition-prodcc.yaml
  pkg/v1/providers/infrastructure-azure/v1.2.1/clusterclass-tkg-azure-default.yaml
  pkg/v1/providers/infrastructure-azure/v1.2.1/yttcc/base-template.yaml
  pkg/v1/providers/infrastructure-azure/v1.2.1/yttcc/overlay.yaml
Labels: ok-to-merge, cla-not-required, area/lcm

#2542 Update the azure template definition files with v1.2.1
  pkg/v1/providers/infrastructure-azure/v1.2.1/cluster-template-definition-devcc.yaml
  pkg/v1/providers/infrastructure-azure/v1.2.1/cluster-template-definition-prodcc.yaml
  pkg/v1/providers/infrastructure-azure/v1.2.1/clusterclass-tkg-azure-default.yaml
Labels: ok-to-merge, cla-not-required, area/lcm

#2545 Fix: TKR resolver blocks cluster deletion
  pkg/v2/tkr/webhook/cluster/tkr-resolver/cluster/cluster.go
  pkg/v2/tkr/webhook/cluster/tkr-resolver/cluster/cluster_test.go
Labels: ok-to-merge, cla-not-required

#2547 Update CC integration tests to use updated addon gist
  .github/workflows/tkg_integration_tests_clusterclass.yaml
Labels: ok-to-merge, cla-not-required, area/lcm

#2393 Adding scaffolding for the tkg-autoscaler package
  docs/packages/dev-workflow.md
  packages/package-values.yaml
  packages/tkg-autoscaler/Makefile
  packages/tkg-autoscaler/README.md
  packages/tkg-autoscaler/bundle/config/upstream/tkg-autoscaler.yaml
  packages/tkg-autoscaler/bundle/config/values.yaml
  packages/tkg-autoscaler/kbld-config.yaml
  packages/tkg-autoscaler/metadata.yaml
  packages/tkg-autoscaler/package.yaml
  packages/tkg-autoscaler/vendir.lock.yml
  packages/tkg-autoscaler/vendir.yml
Labels: ok-to-merge, cla-not-required

#2515 Refactors Labels Component to Shared TKG Labels
  .gitignore
  pkg/v1/tkg/web/package-lock.json
  pkg/v1/tkg/web/package.json
  pkg/v1/tkg/web/src/app/app.module.ts
  pkg/v1/tkg/web/src/app/shared/service/user-data-form.service.ts
  pkg/v1/tkg/web/src/app/views/landing/aws-wizard/aws-wizard.component.html
  pkg/v1/tkg/web/src/app/views/landing/aws-wizard/aws-wizard.component.spec.ts
  pkg/v1/tkg/web/src/app/views/landing/aws-wizard/aws-wizard.component.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/components/steps/load-balancer/load-balancer-step.component.html
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/components/steps/load-balancer/load-balancer-step.component.spec.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/components/steps/load-balancer/load-balancer-step.component.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/components/steps/load-balancer/load-balancer-step.fieldmapping.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/components/steps/metadata-step/metadata-step.component.html
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/components/steps/metadata-step/metadata-step.component.spec.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/components/steps/metadata-step/metadata-step.component.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/components/steps/metadata-step/metadata-step.fieldmapping.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/components/widgets/tkg-labels/interfaces/tkg-labels.interface.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/components/widgets/tkg-labels/tkg-labels.component.html
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/components/widgets/tkg-labels/tkg-labels.component.scss
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/components/widgets/tkg-labels/tkg-labels.component.spec.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/components/widgets/tkg-labels/tkg-labels.component.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/constants/validation.constants.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/field-mapping/FieldMapping.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/utils/form-utils.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/validation/validation.service.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/wizard-base/wizard-base.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/wizard-shared.module.ts
  pkg/v1/tkg/web/src/contextualHelpDocs/index.json
Labels: ok-to-merge, area/ui, cla-not-required

#2555 Fixing kbld failure for autoscaler
  packages/package-values.yaml
  packages/tkg-autoscaler/kbld-config.yaml
Labels: ok-to-merge, cla-not-required, area/packages

#2557 Add service account for tkr-conversion-webhook deployment
  packages/tkr-service/bundle/config/upstream/tkr-conversion-webhook-deployment.yaml
Labels: kind/bug, ok-to-merge, cla-not-required, area/tkr, area/packages

#2559 Fix YAML marshaling error introduced by #2524
  pkg/v1/tkr/controllers/source/suite_test.go
  pkg/v1/tkr/controllers/source/test_helper.go
  pkg/v1/tkr/pkg/types/bommetadata.go
Labels: ok-to-merge, cla-not-required

#2493 propagates csi feature states from supervisor cluster to workload clusters
  addons/controllers/csi/vspherecsiconfig_constants.go
  addons/controllers/csi/vspherecsiconfig_controller.go
  addons/controllers/csi/vspherecsiconfig_datavalues.go
  addons/controllers/csi/vspherecsiconfig_utils.go
  addons/controllers/testdata/test-vsphere-csi-paravirtual.yaml
  addons/controllers/testdata/vmware-csi-system-ns.yaml
  addons/controllers/vspherecsiconfig_controller_test.go
  addons/test/testutil/test_helpers.go
Labels: ok-to-merge, cla-not-required

#2553 Fix vsphereCSIConfig controller bug where multiple vsphereclusters are resolved for 1 capicluster
  addons/controllers/csi/vspherecsiconfig_controller.go
  addons/controllers/testdata/test-vsphere-csi-paravirtual.yaml
  addons/controllers/vspherecsiconfig_controller_test.go
Labels: ok-to-merge, cla-not-required

#2573 Fix status slashing by PatchSet
  pkg/v1/util/patchset/patchset.go
  pkg/v1/util/patchset/patchset_test.go
Labels: ok-to-merge, cla-not-required, area/tkr

#2566 Temporary hack to configure tkr-source-controller package values
  pkg/v1/tkg/managementcomponents/helper.go
  pkg/v1/tkg/managementcomponents/types.go
Labels: ok-to-merge, cla-not-required, area/tkr

#2587 Kickstart UI: fix build dependency issue
  Makefile
  pkg/v1/tkg/web/package-lock.json
Labels: ok-to-merge, area/ui

#2591 Install core-management-plugins-package as part of TKG meta package
  packages/core-management-plugins/bundle/config/cliplugin-crd.yaml
  packages/core-management-plugins/bundle/config/values.yaml
  packages/tkg/bundle/config/packageinstalls/core-management-plugins-pi.yaml
  packages/tkg/bundle/config/packageinstalls/core-management-plugins-service-account.yaml
  packages/tkg/bundle/config/values.yaml
  pkg/v1/tkg/managementcomponents/helper.go
  pkg/v1/tkg/managementcomponents/types.go
Labels: ok-to-merge, cla-not-required

#2575 Add permissions for CPI and CSI controller to create ClusterRole for CAPV to reconcile ProviderServiceAccount
  packages/addons-manager/bundle/config/upstream/addons-manager.yaml
Labels: ok-to-merge, cla-not-required

#2586 TKGS Validation changes for cluster class use case
  pkg/v1/tkg/client/cluster.go
  pkg/v1/tkg/client/get_kubernetes_versions_test.go
  pkg/v1/tkg/client/validate.go
  pkg/v1/tkg/constants/cluster_internal.go
  pkg/v1/tkg/tkgctl/create_cluster.go
  pkg/v1/tkg/tkgctl/create_cluster_test.go
Labels: ok-to-merge, cla-not-required, area/lcm

#2530 Use GVR based discovery when looking up CLIPlugins
  pkg/v1/tkg/clusterclient/clusterclient.go
  pkg/v1/tkg/clusterclient/clusterclient_test.go
Labels: area/cli, area/plugin, ok-to-merge, cla-not-required

#2522 Add feature flag to opt in for kctrl pkg cmd tree
  addons/go.mod
  addons/go.sum
  cmd/cli/plugin/package/kctrl/README.md
  cmd/cli/plugin/package/kctrl/kctrl.go
  cmd/cli/plugin/package/kctrl/ui.go
  cmd/cli/plugin/package/kctrl/ui_test.go
  cmd/cli/plugin/package/main.go
  go.mod
  go.sum
  pkg/v1/config/clientconfig.go
Labels: ok-to-merge, cla-not-required

#2601 Include uncommitted go mod tidy changes
  Makefile
  addons/go.mod
  addons/go.sum
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  pkg/v1/providers/tests/go.mod
Labels: ok-to-merge, cla-not-required

#2584 Do not update certificates on filesystem if content is identical.
  addons/pkg/constants/constants.go
  pkg/v1/webhooks/certificates.go
  pkg/v1/webhooks/certificates_test.go
Labels: ok-to-merge, cla-not-required

#2595 CAPV aggregated role patch appends rbac rules
  addons/controllers/clusterbootstrap_controller_test.go
  addons/controllers/cpi/vspherecpiconfig_controller.go
  addons/controllers/csi/vspherecsiconfig_controller.go
  addons/controllers/vspherecpiconfig_controller_test.go
  addons/controllers/vspherecsiconfig_controller_test.go
  addons/pkg/constants/constants.go
Labels: ok-to-merge, cla-not-required

#2412 Add docs for updated addons-manager
  addons/README.md
  addons/docs/images/supervisor-workload.jpg
Labels: area/docs, ok-to-merge, cla-not-required

#2620 Add object-propagation to the components to fix tkg-clusterclass buil…
  Makefile
Labels: ok-to-merge, cla-not-required

#2608 Mark additional TKRs as compatible
  pkg/v2/tkr/controller/tkr-source/compatibility/reconciler.go
  pkg/v2/tkr/controller/tkr-source/compatibility/reconciler_test.go
  pkg/v2/tkr/controller/tkr-source/main.go
  pkg/v2/tkr/util/sets/strings.go
Labels: ok-to-merge, cla-not-required

#2621 Add object-propagation to the components as part of CI to fix tkg-clusterclass build issue
  .github/workflows/tkg_integration_tests_clusterclass.yaml
Labels: CI, ok-to-merge, cla-not-required

#2596 Add Sync period bootstrap packages on the workload cluster on workload cluster
  addons/controllers/clusterbootstrap_controller.go
  addons/controllers/clusterbootstrap_controller_test.go
Labels: area/addons, kind/bug, ok-to-merge

#2628 Fix nil pointer panic in TKR resolver webhook
  pkg/v2/tkr/util/resolution/resolution.go
  pkg/v2/tkr/webhook/cluster/tkr-resolver/cluster/cluster.go
  pkg/v2/tkr/webhook/cluster/tkr-resolver/cluster/cluster_test.go
Labels: ok-to-merge, cla-not-required

#2627 Remove installing specific version of the plugin based on version in TKG bom file
  pkg/v1/tkg/client/management_components.go
Labels: ok-to-merge, cla-not-required, area/lcm

#1792 Clean up and organize `builder` command code
  Makefile
  cmd/cli/plugin-admin/builder/README.md
  cmd/cli/plugin-admin/builder/cli.go
  cmd/cli/plugin-admin/builder/command_test.go
  cmd/cli/plugin-admin/builder/init.go
  cmd/cli/plugin-admin/builder/main.go
  cmd/cli/plugin-admin/builder/publish.go
  pkg/v1/builder/command/cli_add.go
  pkg/v1/builder/command/cli_compile.go
  pkg/v1/builder/command/doc.go
  pkg/v1/builder/command/init.go
  pkg/v1/builder/command/publish.go
  pkg/v1/builder/template/plugintemplates/command_readme.md.tmpl
  pkg/v1/builder/template/plugintemplates/gomod.tmpl
  pkg/v1/builder/template/plugintemplates/plugin_readme.md.tmpl
  pkg/v1/builder/template/root.go
Labels: ok-to-merge, cla-not-required

#2578 Support building and publishing multiple versions of specific package as part of package repository and updated tkg-autoscaler package to use multiple versions
  hack/packages/package-tools/cmd/helpers.go
  hack/packages/package-tools/cmd/package-bundle-generate.go
  hack/packages/package-tools/cmd/package-bundle-push.go
  hack/packages/package-tools/cmd/packageValues.go
  hack/packages/package-tools/cmd/repo-bundle-generate.go
  hack/packages/package-tools/utils/utils.go
  hack/packages/templates/repo-utils/package-cr-overlay.yaml
  packages/package-values.yaml
  packages/tkg-autoscaler/Makefile
  packages/tkg-autoscaler/bundle/config/upstream/tkg-autoscaler.yaml
  packages/tkg-autoscaler/bundle/config/values.yaml
  packages/tkg-autoscaler/values.template.yaml
Labels: ok-to-merge, cla-not-required, area/packages

#2505 Support for ClusterClass based cluster upgrades
  pkg/v1/tkg/client/upgrade_cluster.go
  pkg/v1/tkg/client/upgrade_cluster_clusterclass.go
  pkg/v1/tkg/client/upgrade_cluster_test.go
  pkg/v1/tkg/clusterclient/clusterclient.go
  pkg/v1/tkg/clusterclient/clusterclient_test.go
  pkg/v1/tkg/fakes/clusterclient.go
  pkg/v1/tkg/fakes/helper/fakeobjectcreater.go
  pkg/v1/tkg/fakes/helper/types.go
Labels: ok-to-merge, cla-not-required, area/lcm, area/cc

#2640 Ensure a non-empty array is present for preKubeAdmCommands
  packages/tkg-clusterclass-aws/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-azure/bundle/config/upstream/base.yaml
  pkg/v1/providers/infrastructure-aws/v1.2.0/cconly/base.yaml
  pkg/v1/providers/infrastructure-azure/v1.2.1/cconly/base.yaml
Labels: ok-to-merge, cla-not-required

#2642 Fix reinvocation policy add logs to cluster pause webhook
  addons/webhooks/cluster_pause_webhook.go
  packages/addons-manager/bundle/config/upstream/webhook-manifests.lib.yaml
Labels: ok-to-merge, cla-not-required

#2624 CB controller should ignore clusters tied to a TKR with legacy-tkr label
  addons/controllers/clusterbootstrap_controller.go
  addons/controllers/clusterbootstrap_controller_test.go
  addons/controllers/testdata/test-cluster-legacy.yaml
  addons/controllers/testdata/test-tkg-system-ns-resources.yaml
  addons/pkg/constants/constants.go
Labels: ok-to-merge, cla-not-required

#2646 Update BOM retrieval version to v0.23.0
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#2657 Update BOM retrieval version to v0.24.0-dev
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#2653 Remove use of deprecated ioutil module
  Makefile
  pkg/v1/codegen/generators/feature/gen_integration_test.go
  pkg/v1/tkg/test/framework/e2e_config.go
  pkg/v1/tkg/test/framework/exec/command.go
  pkg/v1/tkg/test/framework/utils.go
  pkg/v1/tkg/test/tkgpackageclient/package_plugin_integration_test.go
  pkg/v1/tkg/tkgctl/client_test.go
Labels: ok-to-merge, cla-not-required

#2669 Fix temp dir creation in client_test.go
  pkg/v1/tkg/tkgctl/client_test.go
Labels: ok-to-merge, cla-not-required

#2678 default namespace in capabilities package values
  packages/capabilities/bundle/config/values.yaml
Labels: ok-to-merge, cla-not-required

#2576 remove enable tkgs upgrade flag
  addons/controllers/clusterbootstrap_controller.go
  addons/controllers/clusterbootstrap_controller_test.go
  addons/controllers/suite_test.go
  addons/controllers/testdata/test-cluster-bootstrap-2.yaml
  addons/main.go
  addons/pkg/config/config.go
  addons/pkg/constants/constants.go
  addons/pkg/util/addon_util.go
  addons/pkg/util/addon_util_test.go
Labels: ok-to-merge, cla-not-required

#2673 Remove redundant vet and fmt calls
  Makefile
Labels: ok-to-merge, cla-not-required

#2684 Package unit tests return non 0 on fail
  Makefile
Labels: CI, ok-to-merge, cla-not-required

#2666 monitor TKGS cluster class Cluster creation progress
  pkg/v1/tkg/client/cluster.go
Labels: ok-to-merge, cla-not-required, area/lcm, area/cc

#2539 Support vSphere Supervisor login using Pinniped
  cmd/cli/plugin/login/main.go
  pkg/v1/auth/tkg/kube_config.go
  pkg/v1/auth/tkg/kube_config_test.go
  pkg/v1/auth/wcp/discovery.go
  pkg/v1/auth/wcp/discovery_test.go
  pkg/v1/tkg/client/get_cluster_pinniped_info.go
  pkg/v1/tkg/fakes/helper/fakeobjectcreater.go
  pkg/v1/tkg/utils/kubeconfig.go
  pkg/v1/tkg/utils/kubeconfig_test.go
  pkg/v1/util/net/set_port.go
  pkg/v1/util/net/set_port_test.go
Labels: ok-to-merge, cla-not-required

#2665 enable TKGS featuregate validation check for TKGS classy cluster creation
  pkg/v1/tkg/constants/cluster_internal.go
  pkg/v1/tkg/fakes/config/cluster_tkgs.yaml
  pkg/v1/tkg/tkgctl/create_cluster.go
  pkg/v1/tkg/tkgctl/create_cluster_test.go
Labels: ok-to-merge, cla-not-required, area/lcm, area/cc

#2696 Conditionally use local registry for CC integration tests workflow
  .github/workflows/tkg_integration_tests_clusterclass.yaml
Labels: CI, ok-to-merge, cla-not-required

#2699 update TKGS featuregate validation check for TKGS cluster class based…
  pkg/v1/tkg/constants/cluster_internal.go
  pkg/v1/tkg/fakes/config/cluster_tkgs.yaml
  pkg/v1/tkg/tkgctl/create_cluster.go
  pkg/v1/tkg/tkgctl/create_cluster_test.go
Labels: ok-to-merge, cla-not-required, area/lcm, area/cc

#2648 Add config options for tanzu-auth controller deployment
  addons/pinniped/tanzu-auth-controller-manager/hack/run.sh
  addons/pinniped/tanzu-auth-controller-manager/main.go
  packages/framework/bundle/config/values.yaml
  packages/tanzu-auth/bundle/config/deployment.yaml
  packages/tanzu-auth/bundle/config/namespace.yaml
  packages/tanzu-auth/bundle/config/values.yaml
Labels: ok-to-merge, cla-not-required

#2716 Support ClusterClassBased Cluster upgrade
  pkg/v1/tkg/client/upgrade_cluster.go
  pkg/v1/tkg/client/upgrade_cluster_clusterclass.go
  pkg/v1/tkg/client/upgrade_cluster_test.go
  pkg/v1/tkg/clusterclient/clusterclient.go
  pkg/v1/tkg/clusterclient/clusterclient_test.go
  pkg/v1/tkg/fakes/clusterclient.go
  pkg/v1/tkg/fakes/helper/fakeobjectcreater.go
  pkg/v1/tkg/fakes/helper/types.go
Labels: ok-to-merge, cla-not-required, area/lcm, area/cc

#2707 Hide `package-based-lcm-beta` feature-flag from tanzu config file
  pkg/v1/config/clientconfig.go
Labels: ok-to-merge, cla-not-required

#2599 change to read cni version bump from TKR object as CNI can be user-cu…
  addons/controllers/addon_controller.go
  addons/controllers/addon_handlers.go
  addons/controllers/clusterbootstrap_controller.go
  addons/controllers/clusterbootstrap_controller_test.go
  addons/controllers/packageinstallstatus_controller.go
  addons/controllers/suite_test.go
  addons/controllers/testdata/dependency/crd/run.tanzu.vmware.com_tanzukubernetesreleases.yaml
  addons/controllers/testdata/test-cluster-bootstrap-1.yaml
  addons/controllers/testdata/test-tkg-system-ns-resources.yaml
  addons/pkg/util/cluster_util.go
  addons/pkg/util/tkr_util.go
  addons/pkg/util/tkr_util_test.go
Labels: ok-to-merge, cla-not-required

#2713 Fix AntreaConfig CRD generation
  apis/cni/v1alpha1/antreaconfig_types.go
  config/crd/bases/cni.tanzu.vmware.com_antreaconfigs.yaml
Labels: ok-to-merge, cla-not-required

#2672 Remove omitEmpty from boolean values to ensure all the bool values get displayed regardless of true or false
  addons/controllers/antrea/antreaconfig_util.go
Labels: area/addons, ok-to-merge

#2682 add prepare command to package tooling
  hack/packages/package-tools/cmd/carvelTools.go
  hack/packages/package-tools/cmd/config/carveltools-config.yaml
  hack/packages/package-tools/cmd/prepare.go
Labels: ok-to-merge, cla-not-required

#2671 Speed up CI builds by only building needed platform
  .github/workflows/main.yaml
Labels: CI, ok-to-merge, cla-not-required

#2753 fix carvel tools config file name
  hack/packages/package-tools/cmd/config/carvel-tools-config.yaml
  hack/packages/package-tools/cmd/prepare.go
Labels: CI, kind/bug, ok-to-merge, cla-not-required

#2717 Plumb legacy CLI Addon Configs to ClusterBootstrap and AddonConfig API
  pkg/v1/providers/infrastructure-aws/v1.2.0/cluster-template-definition-devcc.yaml
  pkg/v1/providers/infrastructure-aws/v1.2.0/cluster-template-definition-prodcc.yaml
  pkg/v1/providers/infrastructure-azure/v1.2.1/cluster-template-definition-devcc.yaml
  pkg/v1/providers/infrastructure-azure/v1.2.1/cluster-template-definition-prodcc.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/cluster-template-definition-devcc.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/cluster-template-definition-prodcc.yaml
  pkg/v1/providers/yttcb/clusterbootstrap.yaml
Labels: area/addons, ok-to-merge, cla-not-required

#2751 Full TKR version not always replaced in Cluster `topology.version`
  pkg/v2/tkr/webhook/cluster/tkr-resolver/cluster/cluster.go
  pkg/v2/tkr/webhook/cluster/tkr-resolver/cluster/cluster_test.go
Labels: kind/bug, ok-to-merge, cla-not-required, area/tkr, go

#2747 Fix exception while cluster upgrades when checking IsClusterClassBased
  pkg/v1/tkg/clusterclient/clusterclient.go
  pkg/v1/tkg/clusterclient/clusterclient_test.go
Labels: ok-to-merge, cla-not-required, area/lcm, area/cc

#2710 CPIController should list vSphereCluster within the same namespace as cluster.
  addons/controllers/cpi/vspherecpiconfig_controller.go
  addons/controllers/testdata/test-vsphere-cpi-paravirtual-clusters-same-name.yaml
  addons/controllers/vspherecpiconfig_controller_test.go
Labels: ok-to-merge, cla-not-required

#2754 Add antreaNSXPodRoutingEnabled field to the CPIConfig CR.
  addons/config/expected/cpi.tanzu.vmware.com/v1alpha1/vspherecpiconfig/tkgs.yaml
  addons/config/templates/cpi.tanzu.vmware.com/v1alpha1/vspherecpiconfig.yaml
  addons/controllers/cpi/vspherecpiconfig_datavalues.go
  addons/controllers/cpi/vspherecpiconfig_utils.go
  addons/controllers/testdata/test-vsphere-cpi-paravirtual.yaml
  addons/controllers/vspherecpiconfig_controller_test.go
  apis/cpi/v1alpha1/vspherecpiconfig_types.go
  config/crd/bases/cpi.tanzu.vmware.com_vspherecpiconfigs.yaml
Labels: ok-to-merge, cla-not-required

#2689 Enable metrics for addons-manager
  addons/main.go
  packages/addons-manager/bundle/config/upstream/addons-manager.yaml
  packages/addons-manager/bundle/config/values.yaml
  packages/framework/bundle/config/values.yaml
  packages/tkg/bundle/config/values.yaml
Labels: ok-to-merge, cla-not-required

#2734 Add PodSecurityPolicy support for Capabilities ClusterRole
  packages/capabilities/bundle/config/overlays/update-clusterrole-with-psp.yaml
  packages/capabilities/bundle/config/values.yaml
  packages/capabilities/vendir.lock.yml
  packages/capabilities/vendir.yml
Labels: area/sdk, kind/bug, ok-to-merge, cla-not-required, area/carvel

#2725 Skip reconcile delete for clusters already deleted.
  addons/controllers/clusterbootstrap_controller.go
  addons/controllers/clusterbootstrap_controller_test.go
  addons/controllers/machine_controller_test.go
Labels: ok-to-merge, cla-not-required

#2757 Add nodeselector, deployment and daemonset options to kapp-controller data-values
  pkg/v1/providers/kapp-controller-values/kapp-controller_data.lib.yaml
  pkg/v1/tkg/client/test/kapp-controller-values/testcase1/output.yaml
  pkg/v1/tkg/client/test/kapp-controller-values/testcase2/output.yaml
  pkg/v1/tkg/client/test/kapp-controller-values/testcase3/output.yaml
Labels: ok-to-merge, cla-not-required, area/packages

#2750 Fix GVR lookup errors seen in Kind cluster during mgmt cluster bootstrap
  addons/controllers/clusterbootstrap_controller.go
  addons/controllers/testdata/test-cluster-bootstrap-2.yaml
  addons/pkg/util/cluster_util.go
  addons/pkg/util/clusterbootstrapclone/clusterbootstrapclone.go
  addons/pkg/util/clusterbootstrapclone/clusterbootstrapclone_test.go
  addons/pkg/util/gvr_helper.go
  addons/pkg/util/gvr_helper_test.go
  addons/pkg/util/provider_util.go
  addons/test/testutil/test_fake_helpers.go
Labels: ok-to-merge, cla-not-required

#2732 Add go and node caching to all Github workflows
  .github/workflows/main.yaml
  .github/workflows/plugin_tests.yaml
  .github/workflows/providers.yaml
  .github/workflows/release.yaml
  .github/workflows/release_staging.yaml
  .github/workflows/security_codeql.yaml
  .github/workflows/tkg_integration_tests.yaml
  .github/workflows/tkg_integration_tests_clusterclass.yaml
  .github/workflows/tkgpackage_integration_test.yaml
Labels: CI, ok-to-merge, cla-not-required

#2735 Add featuregate check for TKGS TKC cluster creation and return proper error message for CCluster creation when cli feature flag disabled
  pkg/v1/tkg/constants/cluster_internal.go
  pkg/v1/tkg/fakes/config/cluster_tkgs_tkc.yaml
  pkg/v1/tkg/tkgctl/create_cluster.go
  pkg/v1/tkg/tkgctl/create_cluster_test.go
Labels: area/cli, ok-to-merge, cla-not-required

#2692 Add the missing logic to handle pre-created ClusterBootstrap
  addons/controllers/clusterbootstrap_controller.go
  addons/pkg/util/clusterbootstrapclone/clusterbootstrapclone.go
  addons/pkg/util/clusterbootstrapclone/clusterbootstrapclone_test.go
  addons/webhooks/clusterbootstrap_webhook.go
  addons/webhooks/clusterbootstrap_webhook_test.go
Labels: ok-to-merge, cla-not-required

#2733 Support clusterclass based TKGS workload cluster upgrade
  pkg/v1/tkg/client/upgrade_cluster.go
  pkg/v1/tkg/clusterclient/clusterclient.go
  pkg/v1/tkg/clusterclient/clusterclient_test.go
  pkg/v1/tkg/tkgctl/upgrade_cluster.go
Labels: area/cli, ok-to-merge, cla-not-required, area/lcm

#2800 Kickstart UI: CLUSTER_LABEL fix
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/components/steps/load-balancer/load-balancer-step.fieldmapping.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/components/steps/metadata-step/metadata-step.fieldmapping.ts
Labels: ok-to-merge, cla-not-required

#2791 TKR Ready status condition and additional print-column
  apis/run/v1alpha3/tanzukubernetesrelease_types.go
  config/crd/bases/run.tanzu.vmware.com_tanzukubernetesreleases.yaml
  packages/tkr-service/bundle/config/upstream/tkr-crd.yaml
  pkg/v2/tkr/resolver/internal/resolver_impl.go
  pkg/v2/tkr/resolver/internal/resolver_impl_test.go
Labels: priority/critical-urgent, area/api, kind/api-change, kind/cleanup, ok-to-merge, area/ux, cla-not-required, area/tkr, area/packages, go
