Repository vmware-tanzu/tanzu-framework, pull requests merged in 2022-04, with the labels that each got.

#1857 Add make target to generate addon config CRs
  Makefile
  addons/Makefile
  addons/config/README.md
  addons/config/expected/cni.tanzu.vmware.com/v1alpha1/antreaconfig.yaml
  addons/config/expected/cni.tanzu.vmware.com/v1alpha1/calicoconfig.yaml
  addons/config/expected/run.tanzu.vmware.com/v1alpha3/kappcontrollerconfig.yaml
  addons/config/hack/test.sh
  addons/config/templates/cni.tanzu.vmware.com/v1alpha1/antreaconfig.yaml
  addons/config/templates/cni.tanzu.vmware.com/v1alpha1/calicoconfig.yaml
  addons/config/templates/run.tanzu.vmware.com/v1alpha3/kappcontrollerconfig.yaml
  addons/controllers/kapp-controller/kappcontrollerconfig_types.go
Labels: ok-to-merge, cla-not-required

#1968 [release-0.11] Configure etcd `extraArgs` from TKR during cluster creation/upgrade
  pkg/v1/providers/infrastructure-aws/v1.2.0/ytt/overlay.yaml
  pkg/v1/providers/infrastructure-azure/v1.0.1/ytt/overlay.yaml
  pkg/v1/providers/infrastructure-docker/v1.0.1/ytt/overlay.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.0.3/ytt/overlay-windows.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.0.3/ytt/overlay.yaml
  pkg/v1/tkg/client/upgrade_cluster.go
  pkg/v1/tkg/client/upgrade_cluster_test.go
  pkg/v1/tkg/tkgconfigbom/bom_test.go
Labels: ok-to-merge, cla-not-required

#1987 [release-0.11] Use go 1.16 during linter checks
  .github/workflows/main.yaml
Labels: CI, ok-to-merge, cla-not-required

#1964 [release-0.11] Configure vSphere CPI to exclude kube-vip IP
  pkg/v1/providers/tests/unit/ip_family_test.go
  pkg/v1/providers/tests/unit/windows_test.go
  pkg/v1/providers/vendir.lock.yml
  pkg/v1/providers/vendir.yml
  pkg/v1/providers/ytt/02_addons/cpi/cpi_addon_data.lib.yaml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.6/bundle/config/overlays/add-secret.yaml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.6/bundle/config/overlays/update-config.yaml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.6/bundle/config/overlays/update-daemonset.yaml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.6/bundle/config/overlays/update-secret.yaml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.6/bundle/config/schema.yaml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.6/bundle/config/upstream/vsphere-cpi/01-rbac.yaml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.6/bundle/config/upstream/vsphere-cpi/02-config.yaml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.6/bundle/config/upstream/vsphere-cpi/03-secret.yaml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.6/bundle/config/upstream/vsphere-cpi/04-daemonset.yaml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.6/bundle/config/values.star
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.6/bundle/config/values.yaml
  pkg/v1/providers/ytt/vendir/vsphere_cpi/_ytt_lib/addons/packages/vsphere-cpi/1.22.6/bundle/config/vsphereconf.lib.txt
  pkg/v1/providers/ytt/vendir/vsphere_cpi/vsphere_cpi.lib.yaml
Labels: ok-to-merge, cla-not-required

#1867 Install kapp-controller to the bootstrap and management cluster
  pkg/v1/cli/carvelhelpers/package.go
  pkg/v1/cli/carvelhelpers/package_test.go
  pkg/v1/cli/carvelhelpers/registry.go
  pkg/v1/cli/carvelhelpers/test/package1/input/.imgpkg/images.yaml
  pkg/v1/cli/carvelhelpers/test/package1/input/config/overlay.yaml
  pkg/v1/cli/carvelhelpers/test/package1/input/config/pod.yaml
  pkg/v1/cli/carvelhelpers/test/package1/input/config/values.yaml
  pkg/v1/cli/carvelhelpers/test/package1/output.yaml
  pkg/v1/cli/carvelhelpers/test/package2/input/config/overlay.yaml
  pkg/v1/cli/carvelhelpers/test/package2/input/config/pod.yaml
  pkg/v1/cli/carvelhelpers/test/package2/input/config/values.yaml
  pkg/v1/cli/carvelhelpers/test/package2/output.yaml
  pkg/v1/cli/carvelhelpers/ytt.go
  pkg/v1/providers/kapp-controller-values/datavalues.yaml
  pkg/v1/providers/kapp-controller-values/helpers.star
  pkg/v1/providers/kapp-controller-values/kapp-controller_data.lib.yaml
  pkg/v1/providers/kapp-controller-values/values.yaml
  pkg/v1/providers/ytt/02_addons/kapp-controller/add_kapp-controller.yaml
  pkg/v1/providers/ytt/lib/helpers.star
  pkg/v1/tkg/client/management_components.go
  pkg/v1/tkg/client/management_components_test.go
  pkg/v1/tkg/client/test/kapp-controller-values/testcase1/output.yaml
  pkg/v1/tkg/client/test/kapp-controller-values/testcase1/uservalues.yaml
  pkg/v1/tkg/client/test/kapp-controller-values/testcase2/output.yaml
  pkg/v1/tkg/client/test/kapp-controller-values/testcase2/uservalues.yaml
  pkg/v1/tkg/client/test/kapp-controller-values/testcase3/output.yaml
  pkg/v1/tkg/client/test/kapp-controller-values/testcase3/uservalues.yaml
  pkg/v1/tkg/client/upgrade_region.go
  pkg/v1/tkg/fakes/tkgconfigbomclient.go
  pkg/v1/tkg/tkgconfigbom/bom.go
  pkg/v1/tkg/tkgconfigbom/client.go
  pkg/v1/tkg/tkgconfigbom/constants.go
  pkg/v1/tkg/utils/files.go
Labels: area/cli, kind/feature, ok-to-merge, cla-not-required

#1926 Add defaults for KappController CRD
  apis/run/v1alpha3/clusterbootstraptemplate_types.go
  apis/run/v1alpha3/kappcontrollerconfig_types.go
  config/crd/bases/run.tanzu.vmware.com_clusterbootstraps.yaml
  config/crd/bases/run.tanzu.vmware.com_clusterbootstraptemplates.yaml
  config/crd/bases/run.tanzu.vmware.com_kappcontrollerconfigs.yaml
Labels: ok-to-merge, cla-not-required

#1965 Add cluster pause webhook
  addons/controllers/cluster_pause_webhook_test.go
  addons/controllers/suite_test.go
  addons/controllers/testdata/webhooks/cluster-pause-webhook-manifests.yaml
  addons/testutil/test_helpers.go
  pkg/v1/tkg/constants/cluster_internal.go
  pkg/v1/webhooks/cluster_pause_webhook.go
Labels: ok-to-merge, cla-not-required

#1969 set vsphere tlsThumbprint for CSI
  pkg/v1/providers/ytt/02_addons/csi/csi_addon_data.lib.yaml
Labels: ok-to-merge, cla-not-required

#1967 Load proxy CA to TKG Management cluster and Workload cluster's node's CA trust store
  pkg/v1/providers/ytt/03_customizations/http_proxy_ca_cert.yaml
Labels: ok-to-merge, cla-not-required

#1991 [release-0.11] Load proxy ca TKG cluster's ca trust store
  pkg/v1/providers/ytt/03_customizations/http_proxy_ca_cert.yaml
Labels: ok-to-merge, cla-not-required

#1893 [release-0.11] Use log.Infof for formatted log string
  pkg/v1/tkg/client/utils.go
Labels: ok-to-merge, cla-not-required

#1977 [release-0.11] Supress output of spinner if not connected to terminal (#1111)
  .github/workflows/tkgpackage_integration_test.yaml
  cmd/cli/plugin/package/display_utils.go
  go.mod
  go.sum
Labels: ok-to-merge, cla-not-required

#1923 [release-0.11] Bump cluster-api-azure to v1.0.2
  addons/go.sum
  go.mod
  go.sum
  pkg/v1/providers/config.yaml
  pkg/v1/providers/infrastructure-azure/v1.0.2/cluster-template-definition-dev.yaml
  pkg/v1/providers/infrastructure-azure/v1.0.2/cluster-template-definition-prod.yaml
  pkg/v1/providers/infrastructure-azure/v1.0.2/infrastructure-components.yaml
  pkg/v1/providers/infrastructure-azure/v1.0.2/metadata.yaml
  pkg/v1/providers/infrastructure-azure/v1.0.2/ytt/base-template.yaml
  pkg/v1/providers/infrastructure-azure/v1.0.2/ytt/overlay.yaml
  pkg/v1/providers/tests/clustergen/param_models/cluster_azure.model
Labels: ok-to-merge, cla-not-required

#1939 Derive cluster information required by the paravirtual mode for CPIConfig
  addons/controllers/cpi/vspherecpiconfig_const.go
  addons/controllers/cpi/vspherecpiconfig_controller.go
  addons/controllers/cpi/vspherecpiconfig_utils.go
  addons/controllers/suite_test.go
  addons/controllers/testdata/test-vsphere-cpi-paravirtual.yaml
  addons/controllers/vspherecpiconfig_controller_test.go
  apis/cpi/v1alpha1/vspherecpiconfig_types.go
  config/crd/bases/cpi.tanzu.vmware.com_vspherecpiconfigs.yaml
Labels: ok-to-merge, cla-not-required

#1848 Add framework meta package
  packages/management/addons-manager-v2/README.md
  packages/management/featuregates/bundle/config/upstream/certificates.yaml
  packages/management/featuregates/bundle/config/upstream/rbac.yaml
  packages/management/featuregates/bundle/config/upstream/service.yaml
  packages/management/featuregates/bundle/config/upstream/tanzu-featuregates-manager.yaml
  packages/management/featuregates/bundle/config/upstream/webhook.yaml
  packages/management/featuregates/bundle/config/values.yaml
  packages/management/framework/Makefile
  packages/management/framework/README.md
  packages/management/framework/bundle/config/pacakgeinstalls/featuregates-pi.yaml
  packages/management/framework/bundle/config/pacakgeinstalls/featuregates-service-account.yaml
  packages/management/framework/bundle/config/values.yaml
  packages/management/framework/metadata.yaml
  packages/management/framework/package.yaml
  packages/management/framework/vendir.lock.yml
  packages/management/framework/vendir.yml
  packages/management/tkg/bundle/config/namespaces/featuregates-package-resources-namespace.yaml
  packages/management/tkg/bundle/config/packageinstalls/clusterclass-service-account.yaml
  packages/management/tkg/bundle/config/packageinstalls/framework-pi.yaml
  packages/management/tkg/bundle/config/packageinstalls/framework-service-account.yaml
  packages/management/tkg/bundle/config/values.yaml
  packages/package-values.yaml
Labels: kind/feature, ok-to-merge, cla-not-required, area/packages

#1707 Automate release note generation process for Tanzu Framework Release
  .github/workflows/release.yaml
Labels: area/release, ok-to-merge, cla-not-required

#1979 [release-0.11] Disable the spinner if CLI is not attached to terminal (#1473)
  addons/go.sum
  cmd/cli/plugin/package/display_utils.go
  go.mod
  go.sum
  pkg/v1/cli/component/output_spinner.go
Labels: ok-to-merge, cla-not-required

#1953 [release-0.11] Update version for BOM retrieval to v0.11.4
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#1998 Fix flaky test in TKR Resolver
  go.mod
  pkg/v2/tkr/resolver/internal/resolver_impl_test.go
  pkg/v2/tkr/util/testdata/gendata.go
Labels: area/testing, ok-to-merge, cla-not-required

#1997 Add `cliplugins` management package which contains CLIPlugin CRD
  packages/management/cliplugins/Makefile
  packages/management/cliplugins/README.md
  packages/management/cliplugins/bundle/config/cliplugin-crd.yaml
  packages/management/cliplugins/metadata.yaml
  packages/management/cliplugins/package.yaml
  packages/management/cliplugins/vendir.lock.yml
  packages/management/cliplugins/vendir.yml
  packages/package-values.yaml
Labels: kind/feature, ok-to-merge, cla-not-required, area/packages

#1992 addons/pinniped/post-deploy: create pinniped-info from package
  addons/pinniped/post-deploy/pkg/configure/configure.go
  addons/pinniped/post-deploy/pkg/configure/configure_test.go
Labels: ok-to-merge, cla-not-required

#2061 [release-0.11] Add missing Use Node 10.x action to release.yaml
  .github/workflows/release.yaml
Labels: area/release, ok-to-merge, area/ui, cla-not-required

#2062 Fixes vSphere network name issue
  pkg/v1/tkg/web/node-server/src/routes/api/mockService.js
  pkg/v1/tkg/web/src/app/views/landing/docker-wizard/docker-wizard.component.ts
  pkg/v1/tkg/web/src/app/views/landing/wizard/shared/wizard-base/wizard-base.ts
Labels: ok-to-merge, area/ux, cla-not-required

#2045 fix featuregates package installation on management cluster
  pkg/v1/providers/ytt/02_addons/management-packages/featuregates/add_featuregates_package.yaml
Labels: ok-to-merge, cla-not-required

#2046 adding vspherecsi api and controller
  addons/Makefile
  addons/controllers/cpi/vspherecpiconfig_const.go
  addons/controllers/cpi/vspherecpiconfig_utils.go
  addons/controllers/csi/vspherecsiconfig_constants.go
  addons/controllers/csi/vspherecsiconfig_controller.go
  addons/controllers/csi/vspherecsiconfig_datavalues.go
  addons/controllers/csi/vspherecsiconfig_utils.go
  addons/controllers/suite_test.go
  addons/controllers/testdata/test-vsphere-csi-non-paravirtual-minimal.yaml
  addons/controllers/testdata/test-vsphere-csi-non-paravirtual.yaml
  addons/controllers/testdata/test-vsphere-csi-paravirtual.yaml
  addons/controllers/utils/utils.go
  addons/controllers/vspherecsiconfig_controller_test.go
  addons/main.go
  addons/pkg/constants/constants.go
  apis/csi/v1alpha1/groupversion_info.go
  apis/csi/v1alpha1/vspherecsiconfig_types.go
  apis/csi/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/csi.tanzu.vmware.com_vspherecsiconfigs.yaml
  config/crd/kustomization.yaml
  config/rbac/vspherecsiconfig_editor_role.yaml
  config/rbac/vspherecsiconfig_viewer_role.yaml
  packages/management/addons-manager-v2/bundle/config/overlays/feature-gate-clusterbootstrap.yaml
  packages/management/addons-manager-v2/bundle/config/upstream/addons-manager.yaml
Labels: ok-to-merge, cla-not-required

#2090 adding vspherecsiconfig crd & running 'vendir sync'
  packages/management/addons-manager-v2/bundle/config/upstream/csi.tanzu.vmware.com_vspherecsiconfigs.yaml
  packages/management/addons-manager-v2/vendir.lock.yml
  packages/management/addons-manager-v2/vendir.yml
Labels: ok-to-merge, cla-not-required

#2047 Add TKR Service package to framework composite package
  Makefile
  packages/management/framework/README.md
  packages/management/framework/bundle/config/pacakgeinstalls/tkr-service-pi.yaml
  packages/management/framework/bundle/config/pacakgeinstalls/tkr-service-service-account.yaml
  packages/management/framework/bundle/config/values.yaml
  packages/management/tkg/bundle/config/namespaces/tkr-service-package-resources-namespace.yaml
  packages/management/tkg/bundle/config/packageinstalls/framework-pi.yaml
  packages/management/tkg/bundle/config/packageinstalls/framework-service-account.yaml
  packages/management/tkg/bundle/config/values.yaml
  packages/management/tkr-service/bundle/config/overlays/overlay-tkr-service.yaml
  packages/management/tkr-service/bundle/config/upstream/certificates.yaml
  packages/management/tkr-service/bundle/config/upstream/rbac.yaml
  packages/management/tkr-service/bundle/config/upstream/service.yaml
  packages/management/tkr-service/bundle/config/upstream/tkr-resolver-cluster-webhook-deployment.yaml
  packages/management/tkr-service/bundle/config/upstream/webhook.yaml
  packages/management/tkr-service/bundle/config/values.yaml
  packages/management/tkr-service/bundle/vendir.lock.yml
  packages/management/tkr-service/bundle/vendir.yml
Labels: kind/enhancement, ok-to-merge, cla-not-required, area/tkr

#2065 Add cliplugins to framework composite package and Make clusterclass package consistent with other packages
  packages/management/framework/bundle/config/pacakgeinstalls/cliplugins-pi.yaml
  packages/management/framework/bundle/config/pacakgeinstalls/cliplugins-service-account.yaml
  packages/management/tkg-clusterclass/bundle/config/packageinstalls/infra-clusterclass-pi.yaml
  packages/management/tkg-clusterclass/bundle/config/packageinstalls/tkg-infra-clusterclass-pi.yaml
  packages/management/tkg-clusterclass/bundle/config/packageinstalls/tkg-infra-clusterclass-service-account.yaml
  packages/management/tkg-clusterclass/bundle/config/values.yaml
  packages/management/tkg/bundle/config/packageinstalls/clusterclass-pi.yaml
  packages/management/tkg/bundle/config/packageinstalls/tkg-clusterclass-pi.yaml
  packages/management/tkg/bundle/config/packageinstalls/tkg-clusterclass-service-account.yaml
  packages/management/tkg/bundle/config/values.yaml
Labels: ok-to-merge, cla-not-required, area/packages

#2133 Fix issue of namespace being hardcoded in addons-manager webhook templates
  packages/management/addons-manager-v2/bundle/config/upstream/cni-webhook-manifests.lib.yaml
Labels: area/addons, ok-to-merge, cla-not-required

#2123 addons/pinniped/config-controller: add v1alpha1 compatibility
  addons/pinniped/config-controller/Dockerfile
  addons/pinniped/config-controller/constants/constants.go
  addons/pinniped/config-controller/controllers/constants.go
  addons/pinniped/config-controller/controllers/controllers.go
  addons/pinniped/config-controller/controllers/handlers.go
  addons/pinniped/config-controller/controllers/suite_test.go
  addons/pinniped/config-controller/controllers/utils.go
  addons/pinniped/config-controller/controllers/utils_test.go
  addons/pinniped/config-controller/controllers/v1_controller.go
  addons/pinniped/config-controller/controllers/v1_controller_test.go
  addons/pinniped/config-controller/controllers/v3_controller.go
  addons/pinniped/config-controller/controllers/v3_controller_test.go
  addons/pinniped/config-controller/main.go
  addons/pinniped/config-controller/manifests/role.yaml
  addons/pinniped/config-controller/utils/utils.go
Labels: ok-to-merge, cla-not-required

#2136 Pick new key for golangci-lint cache
  .github/workflows/main.yaml
Labels: area/testing, ok-to-merge, cla-not-required

#2066 Add addons manager package into TKG composite package
  packages/management/addons-manager-v2/bundle/config/upstream/addons-manager.yaml
  packages/management/addons-manager-v2/bundle/config/values.yaml
  packages/management/addons-manager-v2/package.yaml
  packages/management/framework/bundle/config/pacakgeinstalls/addons-manager-pi.yaml
  packages/management/framework/bundle/config/pacakgeinstalls/addons-manager-service-account.yaml
  packages/management/framework/bundle/config/values.yaml
  packages/management/tkg/bundle/config/packageinstalls/framework-service-account.yaml
  packages/management/tkg/bundle/config/values.yaml
Labels: ok-to-merge, cla-not-required

#2085 ensure TKG_NO_PROXY value is stored in sorted order
  pkg/v1/providers/ytt/09_miscellaneous/08_store_data_values.yaml
Labels: area/testing, ok-to-merge, cla-not-required

#2120 Enable CI on package-based-lcm branch
  .github/workflows/main.yaml
  .github/workflows/plugin_tests.yaml
  .github/workflows/providers.yaml
  .github/workflows/tkg_integration_tests.yaml
  .github/workflows/tkgpackage_integration_test.yaml
  pkg/v1/providers/infrastructure-aws/v1.2.0/cconly/base.yaml
  pkg/v1/providers/infrastructure-aws/v1.2.0/cconly/overlay.yaml
  pkg/v1/providers/infrastructure-aws/v1.2.0/yttcc/overlay.yaml
  pkg/v1/providers/infrastructure-azure/v1.0.1/cconly/base.yaml
  pkg/v1/providers/infrastructure-azure/v1.0.1/cconly/overlay.yaml
  pkg/v1/providers/infrastructure-azure/v1.0.1/yttcc/overlay.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/cconly/base.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/cconly/overlay-windows.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/cconly/overlay.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/yttcc/overlay-windows.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/yttcc/overlay.yaml
  pkg/v1/tkg/client/cluster.go
Labels: CI, ok-to-merge, cla-not-required

#1946 Parse cluster proxy & trust variables
  addons/controllers/clusterbootstrap_controller.go
  addons/controllers/clusterbootstrap_controller_test.go
  addons/controllers/kapp-controller/kappcontrollerconfig_types.go
  addons/controllers/kappcontrollerconfig_controller_test.go
  addons/controllers/suite_test.go
  addons/controllers/testdata/test-cluster-bootstrap-1.yaml
  addons/controllers/testdata/test-kapp-controller-1.yaml
  addons/main.go
  addons/pkg/config/config.go
  addons/pkg/constants/constants.go
  addons/pkg/types/clusterbootstrap.go
  addons/pkg/util/cluster_variable_util.go
  addons/pkg/util/cluster_variable_util_test.go
Labels: area/addons, ok-to-merge, cla-not-required

#2143 addons/pinniped/config-controller: update secret when wlc is created or updated
  addons/pinniped/config-controller/controllers/constants.go
  addons/pinniped/config-controller/controllers/handlers.go
  addons/pinniped/config-controller/controllers/utils.go
  addons/pinniped/config-controller/controllers/utils_test.go
  addons/pinniped/config-controller/controllers/v1_controller.go
  addons/pinniped/config-controller/controllers/v1_controller_test.go
  addons/pinniped/config-controller/controllers/v3_controller_test.go
Labels: ok-to-merge, cla-not-required

#2149 addons/pinniped/config-controller: delete secret when wlc deleted
  addons/pinniped/config-controller/controllers/utils.go
  addons/pinniped/config-controller/controllers/v1_controller.go
  addons/pinniped/config-controller/controllers/v1_controller_test.go
  addons/pinniped/config-controller/controllers/v3_controller.go
  addons/pinniped/config-controller/manifests/role.yaml
Labels: ok-to-merge, cla-not-required

#2138 Vendir latest CRDs and fixes from testing with supervisor cluster
  addons/controllers/addon_controller.go
  addons/controllers/clusterbootstrap_controller.go
  addons/controllers/packageinstallstatus_controller.go
  addons/main.go
  addons/pkg/util/cluster_util.go
  packages/management/addons-manager-v2/bundle/config/upstream/cni-webhook-manifests.lib.yaml
  packages/management/addons-manager-v2/bundle/config/upstream/cni.tanzu.vmware.com_antreaconfigs.yaml
  packages/management/addons-manager-v2/bundle/config/upstream/cni.tanzu.vmware.com_calicoconfigs.yaml
  packages/management/addons-manager-v2/bundle/config/upstream/cpi.tanzu.vmware.com_vspherecpiconfigs.yaml
  packages/management/addons-manager-v2/bundle/config/upstream/run.tanzu.vmware.com_clusterbootstraps.yaml
  packages/management/addons-manager-v2/bundle/config/upstream/run.tanzu.vmware.com_clusterbootstraptemplates.yaml
  packages/management/addons-manager-v2/bundle/config/upstream/run.tanzu.vmware.com_kappcontrollerconfigs.yaml
  packages/management/addons-manager-v2/vendir.lock.yml
  packages/management/addons-manager-v2/vendir.yml
Labels: ok-to-merge, cla-not-required

#1697 Add webhook for ClusterBootstrap and ClusterBootstrapTemplate
  .golangci.yaml
  addons/controllers/addon_controller_test.go
  addons/controllers/antreaconfig_controller_test.go
  addons/controllers/calicoconfig_controller_test.go
  addons/controllers/certificates_test.go
  addons/controllers/cluster_pause_webhook_test.go
  addons/controllers/clusterbootstrap_controller_test.go
  addons/controllers/kappcontrollerconfig_controller_test.go
  addons/controllers/packageinstallstatus_controller_test.go
  addons/controllers/suite_test.go
  addons/controllers/testdata/test-cluster-bootstrap-1.yaml
  addons/controllers/testdata/webhooks/cluster-pause-webhook-manifests.yaml
  addons/controllers/testdata/webhooks/clusterbootstrap-webhook-manifests.yaml
  addons/controllers/testdata/webhooks/test-antrea-calico-webhook-manifests.yaml
  addons/controllers/vspherecpiconfig_controller_test.go
  addons/controllers/vspherecsiconfig_controller_test.go
  addons/go.mod
  addons/go.sum
  addons/main.go
  addons/test/builder/builders.go
  addons/test/builder/doc.go
  addons/test/testutil/test_helpers.go
  addons/webhooks/clusterbootstrap_webhook.go
  addons/webhooks/clusterbootstraptemplate_webhook.go
  addons/webhooks/doc.go
  apis/run/v1alpha3/clusterbootstraptemplate_types.go
  config/crd/kustomization.yaml
  config/rbac/clusterbootstrap_editor_role.yaml
  config/rbac/clusterbootstrap_viewer_role.yaml
  config/rbac/clusterbootstraptemplate_editor_role.yaml
  config/rbac/clusterbootstraptemplate_viewer_role.yaml
  packages/management/addons-manager-v2/bundle/config/overlays/feature-gate-clusterbootstrap.yaml
  packages/management/addons-manager-v2/bundle/config/upstream/addons-manager.yaml
  packages/management/addons-manager-v2/bundle/config/upstream/cni-webhook-manifests.lib.yaml
  packages/management/addons-manager-v2/bundle/config/upstream/webhook-manifests.lib.yaml
Labels: area/addons, ok-to-merge, cla-not-required

#2084 Add generate-package-config Makefile target for VSphereCPIConfig.
  Makefile
  addons/config/expected/cni.tanzu.vmware.com/v1alpha1/antreaconfig/default.yaml
  addons/config/expected/cni.tanzu.vmware.com/v1alpha1/calicoconfig/default.yaml
  addons/config/expected/cpi.tanzu.vmware.com/v1alpha1/vspherecpiconfig/default.yaml
  addons/config/expected/cpi.tanzu.vmware.com/v1alpha1/vspherecpiconfig/tkgs.yaml
  addons/config/expected/run.tanzu.vmware.com/v1alpha3/kappcontrollerconfig/default.yaml
  addons/config/hack/test.sh
  addons/config/templates/cpi.tanzu.vmware.com/v1alpha1/vspherecpiconfig.yaml
  addons/config/testcases/cni.tanzu.vmware.com/v1alpha1/antreaconfig/default.yaml
  addons/config/testcases/cni.tanzu.vmware.com/v1alpha1/calicoconfig/default.yaml
  addons/config/testcases/cpi.tanzu.vmware.com/v1alpha1/vspherecpiconfig/default.yaml
  addons/config/testcases/cpi.tanzu.vmware.com/v1alpha1/vspherecpiconfig/tkgs.yaml
  addons/config/testcases/run.tanzu.vmware.com/v1alpha3/kappcontrollerconfig/default.yaml
Labels: ok-to-merge, cla-not-required

#2063 Rename fields for VSphereCPIConfig CR.
  addons/controllers/cpi/vspherecpiconfig_controller.go
  addons/controllers/cpi/vspherecpiconfig_utils.go
  addons/controllers/testdata/test-vsphere-cpi-non-paravirtual.yaml
  addons/controllers/vspherecpiconfig_controller_test.go
  apis/cpi/v1alpha1/vspherecpiconfig_types.go
  apis/cpi/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/cpi.tanzu.vmware.com_vspherecpiconfigs.yaml
Labels: ok-to-merge, cla-not-required

#2159 TKR Resolver: Use cluster variables
  apis/run/v1alpha3/tanzukubernetesrelease_types.go
  pkg/v2/tkr/util/topology/cluster.go
  pkg/v2/tkr/util/topology/cluster_test.go
  pkg/v2/tkr/webhook/cluster/tkr-resolver/cluster/cluster.go
  pkg/v2/tkr/webhook/cluster/tkr-resolver/cluster/cluster_test.go
  pkg/v2/tkr/webhook/cluster/tkr-resolver/cluster/tkrdata.go
Labels: ok-to-merge, cla-not-required

#2167 addons/pinniped/config-controller: restore wlc secret when modified or deleted
  addons/pinniped/config-controller/README.md
  addons/pinniped/config-controller/controllers/handlers.go
  addons/pinniped/config-controller/controllers/utils.go
  addons/pinniped/config-controller/controllers/v1_controller.go
  addons/pinniped/config-controller/controllers/v1_controller_test.go
  addons/pinniped/config-controller/controllers/v3_controller.go
  addons/pinniped/config-controller/controllers/v3_controller_test.go
Labels: ok-to-merge, cla-not-required

#2083 Clusterbootstrap controller needs to handle inline data value from ClusterBootstrapPackage
  addons/controllers/clusterbootstrap_controller.go
  addons/controllers/clusterbootstrap_controller_test.go
  addons/controllers/testdata/test-cluster-bootstrap-1.yaml
  addons/controllers/testdata/test-cluster-bootstrap-2.yaml
  addons/pkg/util/addon_util.go
  addons/test/builder/builders.go
  apis/run/v1alpha3/clusterbootstraptemplate_types.go
  apis/run/v1alpha3/zz_generated.deepcopy.go
  config/crd/bases/run.tanzu.vmware.com_clusterbootstraps.yaml
  config/crd/bases/run.tanzu.vmware.com_clusterbootstraptemplates.yaml
Labels: area/addons, ok-to-merge, cla-not-required

#2172 addons/pinniped/config-controller: propagate pinniped-info state to workload clusters
  addons/pinniped/config-controller/controllers/constants.go
  addons/pinniped/config-controller/controllers/v1_controller.go
  addons/pinniped/config-controller/controllers/v1_controller_test.go
  addons/pinniped/config-controller/controllers/v3_controller.go
  addons/pinniped/config-controller/main.go
Labels: ok-to-merge, cla-not-required

#2104 Add Makefile target for VSphereCSIConfig
  addons/config/expected/csi.tanzu.vmware.com/v1alpha1/vspherecsiconfig/default.yaml
  addons/config/expected/csi.tanzu.vmware.com/v1alpha1/vspherecsiconfig/tkgs.yaml
  addons/config/templates/csi.tanzu.vmware.com/v1alpha1/vspherecsiconfig.yaml
  addons/config/testcases/csi.tanzu.vmware.com/v1alpha1/vspherecsiconfig/default.yaml
  addons/config/testcases/csi.tanzu.vmware.com/v1alpha1/vspherecsiconfig/tkgs.yaml
Labels: ok-to-merge, cla-not-required

#2141 Support management package upgrades as part of `management-cluster` upgrade
  packages/management/framework/bundle/config/pacakgeinstalls/addons-manager-pi.yaml
  packages/management/framework/bundle/config/pacakgeinstalls/cliplugins-pi.yaml
  packages/management/framework/bundle/config/pacakgeinstalls/featuregates-pi.yaml
  packages/management/framework/bundle/config/pacakgeinstalls/tkr-service-pi.yaml
  packages/management/framework/bundle/config/values.yaml
  packages/management/tkg-clusterclass/bundle/config/packageinstalls/tkg-infra-clusterclass-pi.yaml
  packages/management/tkg-clusterclass/bundle/config/values.yaml
  packages/management/tkg/bundle/config/packageinstalls/framework-pi.yaml
  packages/management/tkg/bundle/config/packageinstalls/tkg-clusterclass-pi.yaml
  packages/management/tkg/bundle/config/values.yaml
  packages/management/tkg/testdata/sample-values.yaml
  pkg/v1/providers/ytt/02_addons/management-packages/core-management-plugins/add_core_management_plugins_package.yaml
  pkg/v1/providers/ytt/02_addons/management-packages/featuregates/add_featuregates_package.yaml
  pkg/v1/providers/ytt/02_addons/tanzu-addons-manager/add_tanzu-addons-manager.yaml
  pkg/v1/tkg/client/init.go
  pkg/v1/tkg/client/management_components.go
  pkg/v1/tkg/client/upgrade_cluster.go
  pkg/v1/tkg/client/upgrade_region.go
  pkg/v1/tkg/clusterclient/resource.go
  pkg/v1/tkg/constants/cluster_internal.go
  pkg/v1/tkg/constants/files.go
  pkg/v1/tkg/fakes/tkgconfigbomclient.go
  pkg/v1/tkg/managementcomponents/helper.go
  pkg/v1/tkg/managementcomponents/management_component_install.go
  pkg/v1/tkg/managementcomponents/management_component_install_test.go
  pkg/v1/tkg/managementcomponents/types.go
  pkg/v1/tkg/tkgconfigbom/bom.go
  pkg/v1/tkg/tkgconfigbom/client.go
  pkg/v1/tkg/tkgpackageclient/package_install.go
  pkg/v1/tkg/tkgpackagedatamodel/package.go
Labels: area/cli, kind/feature, ok-to-merge, cla-not-required, area/packages

#2184 add bootstrap-token-ttl flag to bootstrap controller
  pkg/v1/providers/bootstrap-kubeadm/v1.1.3/bootstrap-components.yaml
Labels: ok-to-merge, cla-not-required, area/lcm

#2215 addons/pinniped: controller, update constants.go
  addons/pinniped/config-controller/controllers/constants.go
Labels: ok-to-merge, cla-not-required

#2187 Add thick tarball option for package bundle generation
  Makefile
  docs/packages/definitions.md
  docs/packages/dev-workflow.md
  hack/packages/package-tools/cmd/package-bundle-generate.go
Labels: ok-to-merge, cla-not-required

#2216 Go modules for apis/cni and apis/cpi
  addons/go.mod
  apis/cni/go.mod
  apis/cni/go.sum
  apis/cpi/go.mod
  apis/cpi/go.sum
  go.mod
Labels: ok-to-merge, cla-not-required

#1786 Detect go modules for linting
  Makefile
  hack/tools/main.go
Labels: ok-to-merge, cla-not-required

#2103 Prevent host network pods from getting kube-vip address on clusters with IPv6 as the primary IP family
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/ytt/overlay.yaml
  pkg/v1/providers/tests/unit/ip_family_test.go
Labels: ok-to-merge, cla-not-required, area/networking

#2178 [1931] Add tkr conversion webhook to tkr service
  packages/kbld-config.yaml
  packages/management/framework/bundle/config/pacakgeinstalls/tkr-service-service-account.yaml
  packages/management/tkr-service/bundle/config/upstream/certificates.yaml
  packages/management/tkr-service/bundle/config/upstream/osimage-crd.yaml
  packages/management/tkr-service/bundle/config/upstream/service.yaml
  packages/management/tkr-service/bundle/config/upstream/tkr-conversion-webhook-deployment.yaml
  packages/management/tkr-service/bundle/config/upstream/tkr-crd.yaml
  packages/management/tkr-service/bundle/vendir.lock.yml
  packages/management/tkr-service/bundle/vendir.yml
Labels: kind/feature, ok-to-merge, cla-not-required, area/tkr

#2122 replace 'username' and 'password' fields with secret reference in vspherecsiconfig api
  addons/controllers/cluster_pause_webhook_test.go
  addons/controllers/clusterbootstrap_controller_test.go
  addons/controllers/csi/vspherecsiconfig_utils.go
  addons/controllers/testdata/test-cluster-bootstrap-1.yaml
  addons/controllers/testdata/test-cluster-bootstrap-2.yaml
  addons/controllers/testdata/test-vsphere-csi-non-paravirtual.yaml
  addons/controllers/testdata/webhooks/cluster-pause-webhook-manifests.yaml
  addons/controllers/vspherecsiconfig_controller_test.go
  apis/csi/v1alpha1/vspherecsiconfig_types.go
  apis/csi/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/csi.tanzu.vmware.com_vspherecsiconfigs.yaml
Labels: ok-to-merge, cla-not-required

#2199 Generate Package Custom Resource when Package Bundle is Created
  Makefile
  hack/packages/package-tools/cmd/helpers.go
  hack/packages/package-tools/cmd/package-bundle-generate.go
  hack/packages/package-tools/cmd/repo-bundle-generate.go
  hack/packages/templates/repo-utils/images-tmpl.yaml
  hack/packages/templates/repo-utils/package-cr-overlay.yaml
  hack/packages/templates/repo-utils/package-helpers.lib.yaml
  hack/packages/templates/repo-utils/package-metadata-cr-overlay.yaml
  hack/packages/templates/repo-utils/packagerepo-tmpl.yaml
Labels: ok-to-merge, cla-not-required

#2230 Remove extraneous log line
  pkg/v1/tkg/tkgctl/create_cluster.go
Labels: ok-to-merge, cla-not-required

#2248 Cleanup .cache and .kube directories on custom github runners
  .github/workflows/plugin_tests.yaml
  .github/workflows/tkg_integration_tests.yaml
  .github/workflows/tkgpackage_integration_test.yaml
Labels: CI, ok-to-merge, cla-not-required

#2251 Add ClusterPause webhook to addons manager package
  addons/main.go
  packages/management/addons-manager-v2/bundle/config/upstream/webhook-manifests.lib.yaml
Labels: ok-to-merge, cla-not-required

#2265 make webhook server port configurable in featuregates package
  packages/management/featuregates/bundle/config/upstream/service.yaml
  packages/management/featuregates/bundle/config/upstream/tanzu-featuregates-manager.yaml
  packages/management/featuregates/bundle/config/values.yaml
  packages/management/framework/bundle/config/values.yaml
  packages/management/tkg/bundle/config/values.yaml
Labels: ok-to-merge, cla-not-required, area/packages

#1920 Add TKR nodeselector and handle cluster upgrade pause in ClusterBootstrap controller
  addons/controllers/clusterbootstrap_controller.go
  addons/controllers/clusterbootstrap_controller_test.go
  addons/controllers/suite_test.go
  addons/controllers/testdata/dependency/crd/vmoperator.vmware.com_virtualmachines.yaml
  addons/controllers/testdata/test-cluster-bootstrap-2.yaml
  addons/go.mod
  addons/go.sum
  addons/main.go
  addons/pkg/config/config.go
  addons/pkg/constants/constants.go
  addons/pkg/types/addons.go
  addons/pkg/util/addon_util.go
  addons/pkg/util/cluster_util.go
  packages/management/addons-manager-v2/bundle/config/upstream/webhook-manifests.lib.yaml
  pkg/v1/tkg/constants/cluster_internal.go
  pkg/v1/webhooks/certificates.go
Labels: ok-to-merge, cla-not-required
