Repository vmware-tanzu/tanzu-framework, pull requests merged in 2022-10, with the labels that each got.

#3491 Add doc with details on BoM usage
  docs/cli/tkgctl/bom.md
  docs/cli/tkgctl/example-boms/tkg-bom.yaml
  docs/cli/tkgctl/example-boms/tkr-bom.yaml
Labels: area/docs, kind/documentation, ok-to-merge, cla-not-required

#3542 Nolinting linter errors to get the CI to pass
  hack/packages/package-tools/cmd/prepare.go
  hack/packages/package-tools/cmd/repo-bundle-push.go
Labels: ok-to-merge, cla-not-required

#3541 fix lint issues in capabilites and package-tools
  capabilities/client/pkg/discovery/tkg/clustermetadata.go
  capabilities/controller/pkg/capabilities/core/capability_controller.go
  capabilities/controller/pkg/capabilities/core/doc.go
  capabilities/controller/pkg/capabilities/run/capability_controller.go
  capabilities/controller/pkg/capabilities/run/doc.go
  capabilities/controller/pkg/config/doc.go
  capabilities/controller/pkg/constants/doc.go
  hack/packages/package-tools/cmd/prepare.go
Labels: ok-to-merge, cla-not-required

#3535 Fix plugin module name
  cmd/cli/plugin-admin/test/go.mod
  cmd/cli/plugin/secret/go.mod
Labels: kind/refactor, ok-to-merge, cla-not-required

#3532 Run Go tests for admin plugins
  .github/workflows/main.yaml
  .github/workflows/release_staging.yaml
  Makefile
Labels: kind/refactor, ok-to-merge, cla-not-required

#3516 Fix simple lint issues under addons and plugin/package directories
  addons/controllers/antrea/antreaconfig_util.go
  addons/controllers/calico/calicoconfig_utils.go
  addons/controllers/clusterbootstrap_controller.go
  addons/controllers/clusterbootstrap_controller_test.go
  addons/controllers/cpi/vspherecpiconfig_utils.go
  addons/controllers/csi/vspherecsiconfig_utils.go
  addons/controllers/kappcontrollerconfig_controller_test.go
  addons/controllers/packageinstallstatus_controller.go
  addons/controllers/suite_test.go
  addons/controllers/vspherecpiconfig_controller_test.go
  addons/controllers/vspherecsiconfig_controller_test.go
  addons/controllers/webhooks_test.go
  addons/fakegen/fakegen.go
  addons/main.go
  addons/pkg/util/clusterbootstrapclone/clusterbootstrapclone.go
  addons/pkg/util/clusterbootstrapclone/clusterbootstrapclone_test.go
  addons/pkg/util/gvr_helper.go
  addons/pkg/util/gvr_helper_test.go
  addons/webhooks/cluster_pause_webhook.go
  addons/webhooks/cluster_pause_webhook_test.go
  addons/webhooks/clusterbootstrap_webhook.go
  addons/webhooks/clusterbootstrap_webhook_test.go
  cmd/cli/plugin/package/test/package_plugin_integration_test.go
Labels: ok-to-merge, cla-not-required

#3510 AddonConfig controllers enqueue Cluster by ownerRef
  addons/controllers/antrea/antreaconfig_util.go
  addons/controllers/calico/calicoconfig_utils.go
  addons/controllers/cpi/vspherecpiconfig_utils.go
  addons/controllers/csi/vspherecsiconfig_utils.go
  addons/controllers/kapp-controller/kappcontrollerconfig_handlers.go
  addons/controllers/testdata/test-vsphere-cpi-non-paravirtual-enqueue-cluster-event-cluster-spec.yaml
  addons/controllers/vspherecpiconfig_controller_test.go
Labels: ok-to-merge, cla-not-required

#3552 Skipping CEIP Tests
  tkg/test/tkgctl/shared/ceip.go
Labels: kind/failing-test, ok-to-merge, cla-not-required

#3540 Bump kapp-controller package to 0.38.5 for release-0.25
  pkg/v1/providers/vendir.lock.yml
  pkg/v1/providers/vendir.yml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.38.5/bundle/config/overlays/change-namespace.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.38.5/bundle/config/overlays/update-configmap.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.38.5/bundle/config/overlays/update-crds.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.38.5/bundle/config/overlays/update-deployment.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.38.5/bundle/config/overlays/update-strategy-overlay.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.38.5/bundle/config/upstream/kapp-controller.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.38.5/bundle/config/values.star
  pkg/v1/providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.38.5/bundle/config/values.yaml
  pkg/v1/providers/ytt/vendir/kapp-controller/kapp-controller.lib.yaml
Labels: ok-to-merge, cla-not-required

#3376 Add BYOI subcommand to import public OS image.
  cmd/cli/plugin/cluster/README.md
  cmd/cli/plugin/cluster/main.go
  cmd/cli/plugin/cluster/osimage.go
  cmd/cli/plugin/cluster/osimage_oracle.go
  go.mod
  go.sum
  tkg/carvelhelpers/registry.go
  tkg/go.mod
  tkg/go.sum
  tkg/oracle/client.go
  tkg/oracle/interface.go
Labels: ok-to-merge, cla-not-required

#3534 Run Go tests for refactored plugins
  .github/workflows/main.yaml
  .github/workflows/release_staging.yaml
  Makefile
Labels: area/testing, ok-to-merge, cla-not-required

#3520 Add unit tests
  cli/core/pkg/discovery/gcp.go
  cli/core/pkg/discovery/gcp_test.go
  cli/core/pkg/discovery/local_test.go
  cli/core/pkg/distribution/artifact_test.go
  cli/core/pkg/utils/common_test.go
  cli/core/pkg/utils/files_test.go
  cli/runtime/command/deprecate_test.go
  cli/runtime/component/reader_test.go
  cli/runtime/go.mod
  cli/runtime/go.sum
Labels: area/testing, ok-to-merge, cla-not-required

#3521 Remove pinniped from Codecov yaml ignore list
  .codecov.yaml
Labels: area/testing, ok-to-merge, cla-not-required, github_actions

#3553 add default toleration in metrics-server secret
  pkg/v1/providers/ytt/02_addons/metrics-server/metrics_server_secret.yaml
Labels: ok-to-merge, cla-not-required

#3536 Update BOM retrieval version to v0.27.0
  tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#3566 Clean up runner space for release workflows
  .github/workflows/release.yaml
  .github/workflows/release_staging.yaml
Labels: CI, area/release, ok-to-merge, cla-not-required

#3564 Update BOM retrieval version to v0.28.0-dev
  tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#3537 Add control plane node selector and toleration to kappcontroller
  addons/config/expected/run.tanzu.vmware.com/v1alpha3/kappcontrollerconfig/default.yaml
  addons/config/templates/run.tanzu.vmware.com/v1alpha3/kappcontrollerconfig.yaml
  addons/controllers/kapp-controller/kappcontrollerconfig_types.go
  addons/controllers/kappcontrollerconfig_controller_test.go
  addons/controllers/testdata/test-cluster-bootstrap-2.yaml
  addons/controllers/testdata/test-kapp-controller-template-config-1.yaml
  addons/controllers/testdata/test-packageinstallstatus.yaml
  addons/controllers/testdata/test-tkg-system-ns-resources.yaml
  apis/run/config/crd/bases/run.tanzu.vmware.com_kappcontrollerconfigs.yaml
  apis/run/v1alpha3/kappcontrollerconfig_types.go
  packages/addons-manager/bundle/config/upstream/runcrds/run.tanzu.vmware.com_kappcontrollerconfigs.yaml
  pkg/v1/providers/kapp-controller-values/kapp-controller_data.lib.yaml
  tkg/client/test/kapp-controller-values/testcase1/output.yaml
  tkg/client/test/kapp-controller-values/testcase2/output.yaml
  tkg/client/test/kapp-controller-values/testcase3/output.yaml
  tkg/test/tkgctl/shared/constants.go
  tkg/test/tkgctl/shared/e2e_common_cc.go
Labels: ok-to-merge, cla-not-required

#3560 add default tolerations for addons-manager package
  packages/addons-manager/bundle/config/values.yaml
  packages/framework/bundle/config/values.yaml
  packages/tkg/bundle/config/values.yaml
Labels: ok-to-merge, cla-not-required

#3489 Add node-role.kubernetes.io/control-plane toleration for featuregates-manager
  packages/featuregates/bundle/config/upstream/tanzu-featuregates-manager.yaml
Labels: priority/important-soon, priority/critical-urgent, kind/other, ok-to-merge, cla-not-required, area/packages

#3587 Makefile: Ensure pinniped-components is treated as a true go module
  Makefile
  pinniped-components/hack/tools/go.sum
  pinniped-components/post-deploy/go.sum
  pinniped-components/tanzu-auth-controller-manager/go.sum
Labels: priority/critical-urgent, area/repo maintenance, ok-to-merge, cla-not-required

#3588 Makefile: Add "smoke-build" target to check everything can build
  Makefile
Labels: priority/important-soon, area/repo maintenance, ok-to-merge, cla-not-required

#3482 Unit test coverage - CLI core
  cli/core/pkg/artifact/http.go
  cli/core/pkg/artifact/http_test.go
  cli/core/pkg/artifact/interface_test.go
  cli/core/pkg/artifact/local_test.go
  cli/core/pkg/auth/csp/grpc_test.go
  cli/core/pkg/auth/csp/token.go
  cli/core/pkg/auth/csp/token_test.go
  cli/core/pkg/auth/tkg/kube_config_test.go
  cli/core/pkg/auth/utils/kubeconfig/kubeconfig_test.go
  cli/core/pkg/carvelhelpers/package_test.go
  cli/core/pkg/carvelhelpers/ytt_test.go
  cli/core/pkg/cluster/client.go
  cli/core/pkg/cluster/client_test.go
  cli/core/pkg/config/bom_test.go
  cli/core/pkg/config/config.go
  cli/core/pkg/config/config_test.go
  cli/core/pkg/config/defaults_test.go
  cli/core/pkg/fakes/CrtClient_fake.go
  cli/core/pkg/fakes/clusterclient_fake.go
  cli/core/pkg/fakes/clusterclientfactory_fake.go
  cli/core/pkg/fakes/config/kubeconfig1.yaml
  cli/core/pkg/fakes/config/kubeconfig2.yaml
  cli/core/pkg/fakes/config/kubeconfig_server_ver.yaml
  cli/core/pkg/fakes/config_client_fake.go
  cli/core/pkg/fakes/crtclientfactory.go
  cli/core/pkg/fakes/crtclusterclient.go
  cli/core/pkg/fakes/discoveryclientfactory_fake.go
  cli/core/pkg/fakes/discoveryclusterclient_fake.go
  cli/core/pkg/fakes/dynamicclientfactory_fake.go
  cli/core/pkg/fakes/http_client_fake.go
  cli/core/pkg/interfaces/config_client_interface.go
  cli/core/pkg/interfaces/http_client_interface.go
Labels: area/testing, ok-to-merge, cla-not-required

#3586 Use go mod instead of go deps
  .github/workflows/main.yaml
  .github/workflows/package_integration_test.yaml
  .github/workflows/plugin_tests.yaml
  .github/workflows/release.yaml
  .github/workflows/release_staging.yaml
  .github/workflows/security_codeql.yaml
  .github/workflows/tkg_integration_tests.yaml
Labels: priority/critical-urgent, area/repo maintenance, ok-to-merge, cla-not-required

#3590 Add control-plane tolerations to kapp-controller and addons-manager
  addons/controllers/testdata/test-kapp-controller-1.yaml
  pkg/v1/providers/ytt/02_addons/kapp-controller/kapp-controller_addon_data.lib.yaml
  pkg/v1/providers/ytt/02_addons/kapp-controller/kapp-controller_overlay.lib.yaml
  pkg/v1/providers/ytt/02_addons/tanzu-addons-manager/tanzu-addons-manager_addon_data.lib.yaml
Labels: ok-to-merge, cla-not-required

#3071 Update makefile to download arm64 version of vale
  hack/tools/Makefile
Labels: ok-to-merge, cla-not-required

#3608 Removing useExperimentalRetryJoin from Windows templates
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.1/cconly/base.yaml
Labels: ok-to-merge, cla-not-required

#3611 Ensure generators are in sync for all modules
  Makefile
  addons/manifests/tanzu-addons-manager.yaml
  apis/addonconfigs/Makefile
  apis/cli/Makefile
  apis/cli/config/crd/bases/cli.tanzu.vmware.com_cliplugins.yaml
  apis/config/Makefile
  apis/core/Makefile
  apis/run/Makefile
  apis/run/config/crd/bases/run.tanzu.vmware.com_tanzukubernetesclusters.yaml
  cli/runtime/generated/crd/bases/cli.tanzu.vmware.com_catalogs.yaml
  cli/runtime/generated/crd/bases/config.tanzu.vmware.com_clientconfigs.yaml
  common.mk
  hack/tools/Makefile
  tkg/vsphere-template-resolver/templateresolver/fakes/templateresolver.go
Labels: priority/critical-urgent, CI, area/repo maintenance, ok-to-merge, cla-not-required

#3610 Fix lint issue in tkg packge
  capabilities/client/pkg/discovery/tkg/clustermetadata.go
  cli/runtime/component/colorable-tty.go
  cli/runtime/component/colorable-tty_test.go
  cmd/cli/plugin-admin/test/main.go
  pkg/v1/providers/tests/unit/pci_passthrough_test.go
  tkg/auth/doc.go
  tkg/carvelhelpers/registry.go
  tkg/client/machine_deployment_cc_test.go
  tkg/client/package_helper_test.go
  tkg/tkgctl/create_cluster_test.go
  tkg/vsphere-template-resolver/template/resolver.go
  tkg/vsphere-template-resolver/templateresolver/resolver_impl.go
  tkr/resolver/internal/resolver_impl.go
Labels: ok-to-merge, cla-not-required

#3627 Fix some linter errors
  addons/test/testutil/test_fake_helpers.go
  apis/run/util/clusters/clusters.go
  capabilities/controller/pkg/capabilities/suite_test.go
  cli/core/pkg/pluginmanager/manager.go
  cli/runtime/component/colorable-tty_test.go
  cmd/cli/plugin/cluster/available_upgrade.go
  cmd/cli/plugin/cluster/osimage_oracle.go
  cmd/cli/plugin/package/test/lib/package_plugin.go
  cmd/cli/plugin/secret/test/lib/secret_plugin.go
  featuregates/controller/pkg/featuregate/suite_test.go
  tkg/client/package_helper_test.go
  tkg/oracle/client.go
  tkg/oracle/interface.go
  tkg/test/tkgctl/shared/node_pools.go
  tkg/test/tkgctl/shared/utils.go
  tkg/tkgctl/create_cluster_test.go
  tkg/vsphere-template-resolver/template/resolver.go
  tkg/vsphere-template-resolver/template/resolver_test.go
  tkg/vsphere-template-resolver/template/vcenter.go
  tkg/vsphere-template-resolver/templateresolver/fakes/templateresolver.go
  tkg/vsphere-template-resolver/templateresolver/interface.go
  tkg/vsphere-template-resolver/templateresolver/resolver_impl.go
  tkg/vsphere-template-resolver/templateresolver/resolver_impl_test.go
  tkg/vsphere-template-resolver/templateresolver/types_test.go
  tkr/go.mod
Labels: ok-to-merge, cla-not-required

#3570 [Tooling] Remove use of -compat flag for go mod
  Makefile
  common.mk
Labels: priority/critical-urgent, CI, ok-to-merge, cla-not-required

#3640 Bump TKR conversion webhook Dockerfile to golang:1.18
  tkr/webhook/tkr-conversion/Dockerfile
Labels: ok-to-merge, cla-not-required

#3631 Adds last-applied annotation to kapp-controller deployment before upgrade
  tkg/client/upgrade_addon.go
  tkg/client/upgrade_addon_test.go
  tkg/clusterclient/clusterclient.go
  tkg/fakes/clusterclient.go
Labels: ok-to-merge, cla-not-required

#3579 Update support matrix to handle the next TKG release.
  tkg/tkgconfighelper/tkgconfighelper_test.go
  tkg/tkgconfighelper/validate.go
Labels: ok-to-merge, cla-not-required, area/lcm

#3597 Fix linter issues in cli/core
  cli/core/pkg/artifact/http.go
  cli/core/pkg/artifact/http_test.go
  cli/core/pkg/artifact/interface_test.go
  cli/core/pkg/auth/csp/grpc_test.go
  cli/core/pkg/auth/csp/token_test.go
  cli/core/pkg/auth/tkg/cluster_pinniped_info.go
  cli/core/pkg/auth/utils/kubeconfig/kubeconfig_test.go
  cli/core/pkg/auth/wcp/discovery.go
  cli/core/pkg/cli/catalog.go
  cli/core/pkg/cli/catalog_test.go
  cli/core/pkg/cluster/client.go
  cli/core/pkg/cluster/client_test.go
  cli/core/pkg/command/config.go
  cli/core/pkg/command/doc.go
  cli/core/pkg/command/plugin_manager.go
  cli/core/pkg/command/plugin_manager_test.go
  cli/core/pkg/command/root.go
  cli/core/pkg/command/update.go
  cli/core/pkg/config/bom.go
  cli/core/pkg/config/bom_test.go
  cli/core/pkg/config/init.go
  cli/core/pkg/interfaces/config_client_interface.go
  cli/core/pkg/pluginmanager/manager.go
  cli/core/pkg/pluginmanager/manager_test.go
  cli/core/pkg/registry/client.go
  cli/runtime/apis/config/v1alpha1/clientconfig.go
  cli/runtime/apis/config/v1alpha1/clientconfig_types.go
  cli/runtime/component/reader.go
  cmd/cli/plugin/cluster/available_upgrade.go
  pkg/v1/auth/wcp/discovery.go
Labels: ok-to-merge, cla-not-required

#3664 Free up space in standard github runner
  .github/workflows/main.yaml
  .github/workflows/providers.yaml
  .github/workflows/tkg_integration_tests.yaml
  .github/workflows/tkg_integration_tests_clusterclass.yaml
Labels: CI, area/repo maintenance, ok-to-merge, cla-not-required

#3654 clusterclient: Add capi experimental to scheme to allow tanzu get cluster to work
  tkg/clusterclient/clusterclient.go
  tkg/clusterclient/clusterclient_test.go
Labels: ok-to-merge, cla-not-required

#3319 Add legacy 2 cc storageclass config
  packages/tkg-storageclass/bundle/config/upstream/base.yaml
  packages/tkg-storageclass/bundle/config/values.yaml
  providers/yttcb/clusterbootstrap.yaml
  tkg/test/tkgctl/shared/e2e_common_cc.go
  tkg/test/tkgctl/shared/package.go
Labels: ok-to-merge

#3617 Customization for nameserver/searchDomain/ntpServer for vSphere cc mode
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  providers/config_default.yaml
  providers/infrastructure-vsphere/v1.3.1/cconly/base.yaml
  providers/infrastructure-vsphere/v1.3.1/yttcc/overlay.yaml
  providers/yttcc/lib/config_variable_association.star
Labels: ok-to-merge, cla-not-required

#3675 Fix bastion host variable on AWS
  packages/tkg-clusterclass-aws/bundle/config/upstream/base.yaml
  providers/infrastructure-aws/v1.2.0/cconly/base.yaml
Labels: ok-to-merge, cla-not-required

#3499 Add control-plane toleration to capabilities manager
  capabilities/config/tanzu-capabilities-manager.yaml
  capabilities/hack/ytt/schema.yaml
  packages/capabilities/bundle/config/upstream/tanzu-capabilities-controller-manager.yaml
Labels: ok-to-merge, cla-not-required

#3684 Free up space in standard github runner for release-0.25
  .github/workflows/main.yaml
  .github/workflows/providers.yaml
  .github/workflows/tkg_integration_tests.yaml
  .github/workflows/tkg_integration_tests_clusterclass.yaml
Labels: priority/critical-urgent, CI, area/repo maintenance, ok-to-merge, cla-not-required

#3639 Remove `BOMRepo` and `CompatibilityFilePath` dependency from ClientConfig
  cli/runtime/apis/config/v1alpha1/clientconfig_types.go
  cmd/cli/plugin/cluster/create.go
  cmd/cli/plugin/cluster/upgrade.go
  cmd/cli/plugin/managementcluster/create.go
  cmd/cli/plugin/managementcluster/delete.go
  cmd/cli/plugin/managementcluster/upgrade.go
  tkg/go.mod
  tkg/go.sum
  tkg/tkgctl/compatibility_test.go
Labels: ok-to-merge, cla-not-required

#3687 fix RBAC in capabilities package
  featuregates/client/go.mod
  packages/capabilities/bundle/config/upstream/rbac.yaml
Labels: ok-to-merge, cla-not-required

#3686 Fix Capabilities schema definition.
  capabilities/hack/ytt/schema.yaml
Labels: ok-to-merge, cla-not-required

#3663 Skip adding last applied annotation to kapp-controller on workload cluster
  tkg/client/upgrade_addon.go
Labels: ok-to-merge, cla-not-required

#3424 Add aws ebs csi api and controller for classy cluster
  PROJECT
  addons/config/expected/csi.tanzu.vmware.com/v1alpha1/awsebscsiconfig/default.yaml
  addons/config/templates/csi.tanzu.vmware.com/v1alpha1/awsebscsiconfig.yaml
  addons/config/testcases/csi.tanzu.vmware.com/v1alpha1/awsebscsiconfig/default.yaml
  addons/controllers/awsebscsi/awsebscsiconfig_controller.go
  addons/controllers/awsebscsi/awsebscsiconfig_datavalues.go
  addons/controllers/awsebscsi/awsescsiconfig_utils.go
  addons/controllers/awsebscsiconfig_controller_test.go
  addons/controllers/suite_test.go
  addons/controllers/testdata/test-aws-ebs-csi-config.yaml
  addons/main.go
  addons/pkg/config/config.go
  addons/pkg/constants/constants.go
  apis/addonconfigs/config/crd/bases/csi.tanzu.vmware.com_awsebscsiconfigs.yaml
  apis/addonconfigs/csi/v1alpha1/awsebscsiconfig_types.go
  apis/addonconfigs/csi/v1alpha1/zz_generated.deepcopy.go
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_awsebscsiconfigs.yaml
  config/crd/patches/webhook_in_awsebscsiconfigs.yaml
  config/rbac/awsebscsiconfig_editor_role.yaml
  config/rbac/awsebscsiconfig_viewer_role.yaml
  config/samples/csi_v1alpha1_awsebscsiconfig.yaml
  packages/addons-manager/bundle/config/upstream/addonconfigscrds/csi.tanzu.vmware.com_awsebscsiconfigs.yaml
  packages/addons-manager/vendir.yml
  providers/yttcb/clusterbootstrap.yaml
  tkg/test/tkgctl/shared/constants.go
  tkg/test/tkgctl/shared/e2e_common_cc.go
  tkg/test/tkgctl/shared/package.go
Labels: ok-to-merge, cla-not-required, area/cc

#3682 Bump CAPV to v1.3.2
  addons/go.mod
  addons/go.sum
  go.mod
  go.sum
  packages/cluster-api-provider-vsphere/bundle/config/overlay/set-feature-gates.yaml
  packages/cluster-api-provider-vsphere/bundle/config/upstream/infrastructure-components-supervisor.yaml
  packages/cluster-api-provider-vsphere/bundle/config/upstream/infrastructure-components.yaml
  packages/cluster-api-provider-vsphere/vendir.yml
  pkg/v1/providers/config.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.2/cconly/base.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.2/cconly/overlay.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.2/cluster-template-definition-dev.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.2/cluster-template-definition-devcc.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.2/cluster-template-definition-prod.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.2/cluster-template-definition-prodcc.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.2/clusterclass-tkg-vsphere-default.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.2/infrastructure-components-supervisor.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.2/infrastructure-components.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.2/metadata.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.2/ytt/base-template.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.2/ytt/overlay-windows.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.2/ytt/overlay.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.2/yttcc/base-template.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.3.2/yttcc/overlay.yaml
  pkg/v1/providers/tests/clustergen/param_models/cluster_optional.model
  pkg/v1/providers/tests/clustergen/param_models/cluster_vsphere.model
  pkg/v1/providers/tests/unit/ip_family_test.go
Labels: ok-to-merge, cla-not-required

#3706 Correct go module paths
  hack/tools/go.mod
  pinniped-components/hack/tools/go.mod
Labels: ok-to-merge, cla-not-required

#3602 Fix NSX ALB service engine group & network validation failure when duplicate resource names in different clouds
  tkg/client/validate.go
Labels: ok-to-merge, cla-not-required

#3523 Handle capabilities component resources upgradation
  CODEOWNERS
  packages/capabilities/bundle/config/upstream/tanzu-capabilities-controller-manager.yaml
  providers/ytt/03_customizations/capabilities/add_capabilities.yaml
  tkg/client/upgrade_addon.go
  tkg/client/upgrade_cluster.go
Labels: ok-to-merge, cla-not-required

#3719 Revert "Adding missing Antrea 1.5.3 spec configurations"
  providers/yttcb/clusterbootstrap.yaml
Labels: ok-to-merge, cla-not-required

#3680 package-bundle-generate: Print ytt and kbld commands about to be run
  hack/packages/package-tools/cmd/package-bundle-generate.go
Labels: ok-to-merge, cla-not-required

#3721 [cherry-pick] Fix NSX ALB service engine group & network validation failure when duplicate resource names in different clouds
  pkg/v1/tkg/client/validate.go
Labels: ok-to-merge, cla-not-required

#3623 Bump calico v3.24.1
  providers/vendir.lock.yml
  providers/vendir.yml
  providers/ytt/02_addons/cni/calico/calico_overlay.lib.yaml
  providers/ytt/vendir/cni/_ytt_lib/addons/packages/calico/3.24.1/bundle/config/overlay/calico-overlay.yaml
  providers/ytt/vendir/cni/_ytt_lib/addons/packages/calico/3.24.1/bundle/config/overlay/update-strategy-overlay.yaml
  providers/ytt/vendir/cni/_ytt_lib/addons/packages/calico/3.24.1/bundle/config/schema.yaml
  providers/ytt/vendir/cni/_ytt_lib/addons/packages/calico/3.24.1/bundle/config/upstream/calico.yaml
  providers/ytt/vendir/cni/_ytt_lib/addons/packages/calico/3.24.1/bundle/config/values.star
  providers/ytt/vendir/cni/_ytt_lib/addons/packages/calico/3.24.1/bundle/config/values.yaml
  providers/ytt/vendir/cni/cni.lib.yaml
Labels: area/addons, ok-to-merge, cla-not-required, area/networking, area/lcm

#3717 Adding tkg-windows package
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  packages/tkg-windows/Makefile
  packages/tkg-windows/README.md
  packages/tkg-windows/bundle/config/upstream/rbac.yaml
  packages/tkg-windows/bundle/config/values.yaml
  packages/tkg-windows/metadata.yaml
  packages/tkg-windows/package.yaml
  packages/tkg-windows/vendir.lock.yml
  packages/tkg-windows/vendir.yml
  providers/infrastructure-vsphere/v1.3.1/cconly/base.yaml
Labels: ok-to-merge, cla-not-required

#3605 Support prodcc plan on vSphere classy cluster
  providers/infrastructure-vsphere/v1.3.1/yttcc/overlay.yaml
  providers/infrastructure-vsphere/yttcc/vsphere-overlay.yaml
  tkg/client/client_suite_test.go
  tkg/client/cluster.go
  tkg/client/init.go
  tkg/client/utils.go
  tkg/client/validate.go
  tkg/client/validate_test.go
  tkg/clusterclient/clusterclient.go
  tkg/clusterclient/clusterclient_test.go
  tkg/fakes/clusterclient.go
  tkg/test/tkgctl/shared/node_pools.go
  tkg/tkgctl/create_cluster.go
Labels: ok-to-merge, cla-not-required

#3724 TKR webhook should not reject a paused cluster.
  tkr/webhook/cluster/tkr-resolver/cluster/cluster.go
  tkr/webhook/cluster/tkr-resolver/cluster/cluster_test.go
Labels: ok-to-merge, cla-not-required

#3709 Remove kube-rbac-proxy in akoo manifest in Bootstrap Cluster
  providers/tests/unit/avi_test.go
  providers/ytt/03_customizations/02_avi/add_akoo.yaml
  providers/ytt/03_customizations/02_avi/ako-operator-deployment.lib.yaml
  providers/ytt/03_customizations/02_avi/static.lib.yaml
Labels: ok-to-merge, cla-not-required

#3700 Ensures kapp-controller deployment has last-applied annotation before upgrade
  tkg/client/delete_region.go
  tkg/client/init.go
  tkg/client/management_components.go
  tkg/client/upgrade_region.go
  tkg/clusterclient/clusterclient.go
  tkg/constants/cluster_internal.go
  tkg/managementcomponents/management_component_install.go
  tkg/managementcomponents/management_component_install_test.go
Labels: ok-to-merge, cla-not-required

#3629 Add unit tests for capabilities to increase test coverage
  capabilities/client/go.mod
  capabilities/client/pkg/discovery/cluster_test.go
  capabilities/client/pkg/discovery/fake.go
  capabilities/client/pkg/discovery/generate.go
  capabilities/client/pkg/discovery/generate_test.go
Labels: area/testing, ok-to-merge, cla-not-required, area/framework

#3615 Kickstart UI: Remove trailing comma when converting a string map to string
  tkg/tkgconfigproviders/helper.go
  tkg/tkgconfigproviders/helper_test.go
  tkg/tkgconfigproviders/tkgconfig_test.go
Labels: ok-to-merge, area/ui, cla-not-required

#3741 Set sizeGiB for AWS classy cluster overlay
  providers/infrastructure-aws/v1.2.0/yttcc/overlay.yaml
Labels: ok-to-merge, cla-not-required

#3713 cluster_bootstrap: Short requeue if CRD not found on remote cluster
  addons/controllers/clusterbootstrap_controller.go
Labels: ok-to-merge, cla-not-required

#3550 Add support for completions in fish and powershell
  cli/core/pkg/command/completion.go
  cli/core/pkg/command/completion_test.go
Labels: ok-to-merge, area/ux, cla-not-required, docs-triage-needed, area/core-cli

#3327 Add documentation for build and make variables and targets
  Makefile
Labels: area/repo maintenance, ok-to-merge, cla-not-required, area/dx

#3751 Add proxy configuration to tkrSourceControllerPackage when creating MC
  tkg/managementcomponents/helper.go
  tkg/managementcomponents/helper_test.go
  tkg/managementcomponents/test/output_vsphere_with_proxy.yaml
  tkg/managementcomponents/types.go
Labels: ok-to-merge, cla-not-required

#3756 Fix makefile comments
  .github/workflows/plugin_tests.yaml
  Makefile
Labels: CI, ok-to-merge, cla-not-required

#3758 Update kctrl Invoke in package plugin
  cmd/cli/plugin/package/kctrl/kctrl.go
  cmd/cli/plugin/package/kctrl/kctrl_test.go
  cmd/cli/plugin/package/main.go
Labels: ok-to-merge, cla-not-required

#3683 [TKG-13275] package tkr-vsphere-template webhook for vsphere-cc
  .github/workflows/tkg_integration_tests_clusterclass.yaml
  Makefile
  packages/tkg-clusterclass-vsphere/README.md
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/certificates.yaml
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/rbac.yaml
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/service.yaml
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/vsphere-template-resolver-cluster-webhook-deployment.yaml
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/webhook.yaml
  packages/tkg-clusterclass-vsphere/bundle/config/values.yaml
  packages/tkg-clusterclass-vsphere/kbld-config.yaml
  packages/tkg-clusterclass-vsphere/vendir.lock.yml
  packages/tkg-clusterclass-vsphere/vendir.yml
  packages/tkg-clusterclass/bundle/config/packageinstalls/tkg-infra-clusterclass-service-account.yaml
  providers/infrastructure-vsphere/v1.3.1/cconly/base.yaml
  providers/infrastructure-vsphere/v1.3.1/cconly/certificates.yaml
  providers/infrastructure-vsphere/v1.3.1/cconly/rbac.yaml
  providers/infrastructure-vsphere/v1.3.1/cconly/service.yaml
  providers/infrastructure-vsphere/v1.3.1/cconly/vsphere-template-resolver-cluster-webhook-deployment.yaml
  providers/infrastructure-vsphere/v1.3.1/cconly/webhook.yaml
  providers/infrastructure-vsphere/v1.3.1/yttcc/overlay.yaml
  tkg/vsphere-template-resolver/Makefile
Labels: ok-to-merge, cla-not-required

#3753 Add BOM ConfigMaps to tkr-system if configured
  packages/tkg/bundle/config/values.yaml
  packages/tkr-source-controller/bundle/config/upstream/tkr-source-controller-deployment.yaml
  packages/tkr-source-controller/bundle/config/values.yaml
  tkg/test/tkgctl/aws_cc/aws_cc_suite_test.go
  tkr/controller/tkr-source/fetcher/fetcher.go
  tkr/controller/tkr-source/main.go
Labels: ok-to-merge, cla-not-required, area/tkr

#3750 Update nodepool cc to default top level variable
  cmd/cli/plugin/managementcluster/go.mod
  cmd/cli/plugin/package/go.mod
  go.mod
  tkg/client/machine_deployment_cc.go
  tkg/client/machine_deployment_cc_test.go
Labels: ok-to-merge, cla-not-required

#3747 Bump kapp-controller cli in package plugin
  cmd/cli/plugin/package/go.mod
  cmd/cli/plugin/package/go.sum
  cmd/cli/plugin/package/kctrl/README.md
Labels: ok-to-merge, cla-not-required

#3775 set minimum tls version to 1.2 for webhook servers
  addons/main.go
  featuregates/controller/main.go
  tkr/webhook/cluster/tkr-resolver/main.go
  tkr/webhook/tkr-conversion/main.go
Labels: ok-to-merge, cla-not-required

#3783 set minimum tls version to 1.2 for webhook servers (#3775)
  addons/main.go
  cmd/managers/featuregate/main.go
  pkg/v2/tkr/webhook/cluster/tkr-resolver/main.go
  pkg/v2/tkr/webhook/tkr-conversion/main.go
Labels: ok-to-merge, cla-not-required

#3641 Adding 'pluginRuntimeVersion' to `tanzu <plugin> info` command output
  .github/workflows/dev_tag_retrieval_pr.yaml
  Makefile
  cli/runtime/Makefile
  cli/runtime/hack/update-bundled-plugin-runtime-version/update-bundled-plugin-runtime-version.txt
  cli/runtime/plugin/info.go
  cli/runtime/plugin/info_test.go
  cli/runtime/version/zz_generated_plugin_runtime_version.go
  hack/verify-dirty.sh
Labels: ok-to-merge, cla-not-required, area/core-cli
