Repository vmware-tanzu/tanzu-framework, pull requests merged in 2022-05, with the labels that each got.

#2267 Fix clustergen comment post workflow
  .github/workflows/recv_providers.yaml
Labels: CI, ok-to-merge

#2269 Update upload-cloud-storage to use v0.10.2
  .github/workflows/recv_providers.yaml
  .github/workflows/release.yaml
  .github/workflows/release_staging.yaml
Labels: CI, ok-to-merge, cla-not-required

#2270 upload clustergen diffs via glob pattern
  .github/workflows/recv_providers.yaml
Labels: CI, ok-to-merge

#2276 Updating version tag used for BOM retrieval to v0.21.0
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#2277 Updating version tag used for BOM retrieval to v0.22.0-dev
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: ok-to-merge, cla-not-required

#2242 Update the KR plugin to implement the new TKR API v1alpha3
  cmd/cli/plugin/tkr/main.go
  cmd/cli/plugin/tkr/utils/helpers.go
  cmd/cli/plugin/tkr/v1alpha1/activate_deactivate.go
  cmd/cli/plugin/tkr/v1alpha1/available_upgrade.go
  cmd/cli/plugin/tkr/v1alpha1/available_upgrade_test.go
  cmd/cli/plugin/tkr/v1alpha1/doc.go
  cmd/cli/plugin/tkr/v1alpha1/get_tkr.go
  cmd/cli/plugin/tkr/v1alpha1/get_tkr_test.go
  cmd/cli/plugin/tkr/v1alpha1/os.go
  cmd/cli/plugin/tkr/v1alpha3/activate_deactivate.go
  cmd/cli/plugin/tkr/v1alpha3/activate_deactivate_test.go
  cmd/cli/plugin/tkr/v1alpha3/doc.go
  cmd/cli/plugin/tkr/v1alpha3/get_tkr.go
  cmd/cli/plugin/tkr/v1alpha3/get_tkr_test.go
  cmd/cli/plugin/tkr/v1alpha3/os.go
  cmd/cli/plugin/tkr/v1alpha3/os_test.go
  pkg/v1/config/clientconfig.go
  pkg/v1/tkg/client/client.go
  pkg/v1/tkg/clusterclient/clusterclient.go
  pkg/v1/tkg/tkgctl/interface.go
Labels: ok-to-merge, cla-not-required

#2249 packges/management/tanzu-auth: remove backup file
  packages/management/tanzu-auth/bundle/.imgpkg__BACKUP/README.md
  packages/management/tanzu-auth/bundle/.imgpkg__BACKUP/bundle.yml
  packages/management/tanzu-auth/bundle/.imgpkg__BACKUP/images.yml
Labels: ok-to-merge, cla-not-required

#2198 Update data values for vsphere cpi to contain paravirt or non-paravirt and fix ProviderServiceAccount for cpi and csi
  addons/Makefile
  addons/controllers/cpi/vspherecpiconfig_controller.go
  addons/controllers/cpi/vspherecpiconfig_datavalues.go
  addons/controllers/cpi/vspherecpiconfig_utils.go
  addons/controllers/csi/vspherecsiconfig_controller.go
  addons/controllers/csi/vspherecsiconfig_utils.go
  addons/controllers/testdata/test-vsphere-cpi-paravirtual.yaml
  addons/controllers/testdata/test-vsphere-csi-paravirtual.yaml
  addons/controllers/vspherecpiconfig_controller_test.go
  addons/controllers/vspherecsiconfig_controller_test.go
Labels: ok-to-merge, cla-not-required

#2283 Embed PEM of root certificates in Mozilla's root store
  pkg/v1/cli/clientconfighelpers/windows_trusted_ca.go
Labels: ok-to-merge, cla-not-required

#2196 Fix VSphereCPIConfig data values type inconsistency and directly use endpoint IP.
  addons/controllers/cpi/vspherecpiconfig_const.go
  addons/controllers/cpi/vspherecpiconfig_datavalues.go
  addons/controllers/cpi/vspherecpiconfig_utils.go
  addons/controllers/testdata/test-vsphere-cpi-paravirtual.yaml
  addons/controllers/vspherecpiconfig_controller_test.go
Labels: ok-to-merge, cla-not-required

#2289 Consider additional metadata as part of kubernetes build version during version comparison
  pkg/v1/tkg/utils/common.go
  pkg/v1/tkg/utils/common_test.go
Labels: ok-to-merge, cla-not-required, area/lcm

#2161 Update clusterclasses to use TKR_DATA variable values to populate image data
  pkg/v1/providers/infrastructure-aws/v1.2.0/cconly/base.yaml
  pkg/v1/providers/infrastructure-aws/v1.2.0/yttcc/overlay.yaml
  pkg/v1/providers/infrastructure-azure/v1.0.1/cconly/base.yaml
  pkg/v1/providers/infrastructure-azure/v1.0.1/yttcc/overlay.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/cconly/base.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/yttcc/base-template.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/yttcc/overlay-windows.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/yttcc/overlay.yaml
Labels: ok-to-merge, cla-not-required, area/lcm

#2287 Fix context-scoped plugins not getting installed after creating management-cluster f…
  pkg/v1/tkg/web/server/handlers/init.go
Labels: ok-to-merge, cla-not-required

#2290 Opted out of CEIP when ENABLE_CEIP_PARTICIPATION is set to false
  cmd/cli/plugin/managementcluster/common.go
  cmd/cli/plugin/managementcluster/create.go
  pkg/v1/tkg/test/config/azure.yaml
  pkg/v1/tkg/test/config/docker.yaml
  pkg/v1/tkg/test/tkgctl/azure/azure_suite_test.go
  pkg/v1/tkg/test/tkgctl/docker/docker_suite_test.go
  pkg/v1/tkg/tkgctl/helper_constants.go
  pkg/v1/tkg/tkgctl/init.go
  pkg/v1/tkg/tkgctl/utils.go
  pkg/v1/tkg/tkgctl/utils_test.go
Labels: ok-to-merge, cla-not-required

#2291 clustergen: generate CC-based output for base commit as well
  hack/clustergen/ci-validate-clustergen.sh
  hack/clustergen/cluster-check.sh
  pkg/v1/providers/tests/clustergen/run_tests.sh
Labels: ok-to-merge, cla-not-required

#2284 [release-0.11] Embed PEM of root certificates in Mozilla's root store
  pkg/v1/cli/clientconfighelpers/windows_trusted_ca.go
Labels: ok-to-merge, cla-not-required

#2312 Add 'required' field to TKR_DATA patch
  pkg/v1/providers/infrastructure-aws/v1.2.0/cconly/base.yaml
  pkg/v1/providers/infrastructure-azure/v1.0.1/cconly/base.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/cconly/base.yaml
Labels: ok-to-merge, cla-not-required

#2313 addons/pinniped/tanzu-auth-controller-manager: Remove pinniped block if id type none
  addons/pinniped/tanzu-auth-controller-manager/controllers/utils.go
  addons/pinniped/tanzu-auth-controller-manager/controllers/utils_test.go
  addons/pinniped/tanzu-auth-controller-manager/controllers/v1_cascade_controller.go
  addons/pinniped/tanzu-auth-controller-manager/controllers/v1_cascade_controller_test.go
Labels: ok-to-merge, cla-not-required

#2296 [release-0.11] Consider additional metadata as part of kubernetes build version during version comparison
  pkg/v1/tkg/utils/common.go
  pkg/v1/tkg/utils/common_test.go
Labels: ok-to-merge, cla-not-required

#2204 Create workload cluster with Cluster class input file for TKGS
  pkg/v1/tkg/client/cluster.go
  pkg/v1/tkg/tkgctl/helpers.go
Labels: ok-to-merge, cla-not-required

#2308 [release-0.11] Opted out of CEIP when ENABLE_CEIP_PARTICIPATION is set to false (#2290)
  cmd/cli/plugin/managementcluster/common.go
  cmd/cli/plugin/managementcluster/create.go
  pkg/v1/tkg/test/config/azure.yaml
  pkg/v1/tkg/test/config/docker.yaml
  pkg/v1/tkg/test/tkgctl/azure/azure_suite_test.go
  pkg/v1/tkg/test/tkgctl/docker/docker_suite_test.go
  pkg/v1/tkg/tkgctl/helper_constants.go
  pkg/v1/tkg/tkgctl/init.go
  pkg/v1/tkg/tkgctl/utils.go
  pkg/v1/tkg/tkgctl/utils_test.go
Labels: ok-to-merge, cla-not-required

#2311 setting vsphere csi replica count based on controlplane node count
  addons/controllers/csi/vspherecsiconfig_constants.go
  addons/controllers/csi/vspherecsiconfig_controller.go
  addons/controllers/csi/vspherecsiconfig_utils.go
  addons/controllers/testdata/test-cluster-bootstrap-1.yaml
  addons/controllers/testdata/test-vsphere-csi-non-paravirtual-minimal.yaml
  addons/controllers/testdata/test-vsphere-csi-non-paravirtual.yaml
  addons/controllers/vspherecsiconfig_controller_test.go
Labels: ok-to-merge, cla-not-required

#2314 Update version for BOM retrieval to v0.11.5
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge

#2299 Customize deployment of tkr-service package
  packages/management/framework/bundle/config/packageinstalls/addons-manager-pi.yaml
  packages/management/framework/bundle/config/packageinstalls/addons-manager-service-account.yaml
  packages/management/framework/bundle/config/packageinstalls/cliplugins-pi.yaml
  packages/management/framework/bundle/config/packageinstalls/cliplugins-service-account.yaml
  packages/management/framework/bundle/config/packageinstalls/featuregates-pi.yaml
  packages/management/framework/bundle/config/packageinstalls/featuregates-service-account.yaml
  packages/management/framework/bundle/config/packageinstalls/tkr-service-pi.yaml
  packages/management/framework/bundle/config/packageinstalls/tkr-service-service-account.yaml
  packages/management/framework/bundle/config/values.yaml
  packages/management/tkg/bundle/config/values.yaml
  packages/management/tkr-service/bundle/config/upstream/service.yaml
  packages/management/tkr-service/bundle/config/upstream/tkr-conversion-webhook-deployment.yaml
  packages/management/tkr-service/bundle/config/upstream/tkr-resolver-cluster-webhook-deployment.yaml
  packages/management/tkr-service/bundle/config/values.yaml
  pkg/v2/tkr/webhook/cluster/tkr-resolver/main.go
  pkg/v2/tkr/webhook/tkr-conversion/main.go
Labels: kind/feature, ok-to-merge, cla-not-required, area/tkr, area/packages

#2319 Fixed the indentation for Issuer resource in tkr-service package
  packages/management/tkr-service/bundle/config/upstream/certificates.yaml
Labels: kind/bug, ok-to-merge, cla-not-required, area/tkr, area/packages

#2315 Change addons-manager-v2 package name to addons-manager
  packages/kbld-config.yaml
  packages/management/addons-manager/Makefile
  packages/management/addons-manager/README.md
  packages/management/addons-manager/bundle/config/overlays/feature-gate-clusterbootstrap.yaml
  packages/management/addons-manager/bundle/config/upstream/addons-manager.yaml
  packages/management/addons-manager/bundle/config/upstream/cni.tanzu.vmware.com_antreaconfigs.yaml
  packages/management/addons-manager/bundle/config/upstream/cni.tanzu.vmware.com_calicoconfigs.yaml
  packages/management/addons-manager/bundle/config/upstream/cpi.tanzu.vmware.com_vspherecpiconfigs.yaml
  packages/management/addons-manager/bundle/config/upstream/csi.tanzu.vmware.com_vspherecsiconfigs.yaml
  packages/management/addons-manager/bundle/config/upstream/run.tanzu.vmware.com_clusterbootstraps.yaml
  packages/management/addons-manager/bundle/config/upstream/run.tanzu.vmware.com_clusterbootstraptemplates.yaml
  packages/management/addons-manager/bundle/config/upstream/run.tanzu.vmware.com_kappcontrollerconfigs.yaml
  packages/management/addons-manager/bundle/config/upstream/webhook-manifests.lib.yaml
  packages/management/addons-manager/bundle/config/values.yaml
  packages/management/addons-manager/metadata.yaml
  packages/management/addons-manager/package.yaml
  packages/management/addons-manager/vendir.lock.yml
  packages/management/addons-manager/vendir.yml
  packages/management/framework/bundle/config/packageinstalls/addons-manager-pi.yaml
  packages/package-values.yaml
Labels: ok-to-merge, cla-not-required

#2325 Remove API Machinery team as code owner to every package
  CODEOWNERS
Labels: ok-to-merge, cla-not-required

#2173 TKR Source Controller implementation
  packages/management/tkr-service/bundle/config/upstream/rbac.yaml
  pkg/v2/tkr/controller/tkr-source/Dockerfile
  pkg/v2/tkr/controller/tkr-source/Makefile
  pkg/v2/tkr/controller/tkr-source/compatibility/reconciler.go
  pkg/v2/tkr/controller/tkr-source/fetcher/configurer.go
  pkg/v2/tkr/controller/tkr-source/fetcher/fetcher.go
  pkg/v2/tkr/controller/tkr-source/fetcher/helper.go
  pkg/v2/tkr/controller/tkr-source/main.go
  pkg/v2/tkr/controller/tkr-source/pkgcr/reconciler.go
  pkg/v2/tkr/controller/tkr-source/pkgcr/reconciler_test.go
  pkg/v2/tkr/util/testdata/testhelpers.go
Labels: ok-to-merge, cla-not-required

#2333 [release-0.11] Fix provider version mismatch when talking with old management cluster using TKG client library
  pkg/v1/providers/infrastructure-azure/v1.0.1/cluster-template-definition-dev.yaml
  pkg/v1/providers/infrastructure-azure/v1.0.1/cluster-template-definition-prod.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.0.2/cluster-template-definition-dev-windows.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.0.2/cluster-template-definition-dev.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.0.2/cluster-template-definition-prod.yaml
Labels: ok-to-merge, cla-not-required

#2317 add tanzu-auth pkg to management pkg
  packages/kbld-config.yaml
  packages/package-values.yaml
Labels: area/auth, ok-to-merge, cla-not-required, area/packages

#2343 TKR Source Controller: Add Cluster API to client scheme
  pkg/v2/tkr/controller/tkr-source/main.go
Labels: ok-to-merge, cla-not-required

#2297 Fix PackageInstall secret name for kapp-controller
  CODEOWNERS
  addons/controllers/antrea/antreaconfig_controller.go
  addons/controllers/clusterbootstrap_controller.go
  addons/controllers/clusterbootstrap_controller_test.go
  addons/controllers/kapp-controller/kappcontrollerconfig_controller.go
  addons/controllers/kappcontrollerconfig_controller_test.go
  addons/controllers/testdata/test-cluster-bootstrap-3.yaml
  addons/pkg/types/addons.go
  addons/pkg/util/addon_util.go
  packages/management/addons-manager/bundle/config/upstream/addons-manager.yaml
  packages/management/addons-manager/bundle/config/values.yaml
  packages/management/framework/bundle/config/values.yaml
  packages/management/tkg/bundle/config/values.yaml
Labels: ok-to-merge, cla-not-required

#2351 Remove owner reference from PackageInstall on workload cluster
  addons/controllers/clusterbootstrap_controller.go
  addons/controllers/clusterbootstrap_controller_test.go
Labels: ok-to-merge, cla-not-required

#2164 Remove namespace in CalicoConfig and change the output format of vethMTU to string
  addons/controllers/calico/calicoconfig_utils.go
  addons/controllers/calicoconfig_controller_test.go
  addons/controllers/testdata/test-calico.yaml
  apis/cni/v1alpha1/calicoconfig_types.go
  apis/cni/v1alpha1/calicoconfig_webhook.go
  config/crd/bases/cni.tanzu.vmware.com_calicoconfigs.yaml
Labels: area/addons, ok-to-merge, cla-not-required

#2229 Bump calico to 3.22.1
  pkg/v1/providers/vendir.lock.yml
  pkg/v1/providers/vendir.yml
  pkg/v1/providers/ytt/02_addons/cni/calico/calico_addon_data.lib.yaml
  pkg/v1/providers/ytt/vendir/cni/_ytt_lib/addons/packages/calico/3.19.1/bundle/config/values.yaml
  pkg/v1/providers/ytt/vendir/cni/_ytt_lib/addons/packages/calico/3.22.1/bundle/config/overlay/calico-overlay.yaml
  pkg/v1/providers/ytt/vendir/cni/_ytt_lib/addons/packages/calico/3.22.1/bundle/config/overlay/update-strategy-overlay.yaml
  pkg/v1/providers/ytt/vendir/cni/_ytt_lib/addons/packages/calico/3.22.1/bundle/config/schema.yaml
  pkg/v1/providers/ytt/vendir/cni/_ytt_lib/addons/packages/calico/3.22.1/bundle/config/upstream/calico.yaml
  pkg/v1/providers/ytt/vendir/cni/_ytt_lib/addons/packages/calico/3.22.1/bundle/config/values.star
  pkg/v1/providers/ytt/vendir/cni/_ytt_lib/addons/packages/calico/3.22.1/bundle/config/values.yaml
  pkg/v1/providers/ytt/vendir/cni/cni.lib.yaml
Labels: ok-to-merge, cla-not-required

#2342 Validate workload cluster service CIDR size
  pkg/v1/tkg/client/cluster.go
  pkg/v1/tkg/client/validate_test.go
Labels: ok-to-merge, cla-not-required

#2179 Update cc vars to organize/simplify data values
  pkg/v1/providers/infrastructure-aws/v1.2.0/cconly/base.yaml
  pkg/v1/providers/infrastructure-aws/v1.2.0/yttcc/overlay.yaml
  pkg/v1/providers/infrastructure-azure/v1.0.1/cconly/base.yaml
  pkg/v1/providers/infrastructure-azure/v1.0.1/yttcc/overlay.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/cconly/base.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/yttcc/overlay-windows.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/yttcc/overlay.yaml
  pkg/v1/providers/yttcc/lib/config_variable_association.star
Labels: ok-to-merge, cla-not-required

#2349 allow to customize featuregates webhook server port
  cmd/managers/featuregate/main.go
  hack/packages/package-tools/cmd/package-bundle-generate.go
  packages/management/featuregates/bundle/config/upstream/helpers.star
  packages/management/featuregates/bundle/config/upstream/tanzu-featuregates-manager.yaml
  packages/management/featuregates/bundle/config/values.yaml
Labels: ok-to-merge, cla-not-required

#2239 packages/management/framework: add tanzu-auth package
  packages/management/framework/bundle/config/packageinstalls/tanzu-auth-pi.yaml
  packages/management/framework/bundle/config/packageinstalls/tanzu-auth-service-account.yaml
  packages/management/framework/bundle/config/values.yaml
  packages/management/tkg/bundle/config/values.yaml
  packages/management/tkg/testdata/sample-values.yaml
  pkg/v1/tkg/managementcomponents/helper.go
  pkg/v1/tkg/managementcomponents/types.go
Labels: ok-to-merge, cla-not-required

#2379 Apply overlays based on pblcm flag and Remove unneccesary overlays fr…
  pkg/v1/providers/ytt/02_addons/cni/add_cni.yaml
  pkg/v1/providers/ytt/03_customizations/01_tkr/add_tkr.yaml
  pkg/v1/providers/ytt/03_customizations/add_mhc.yaml
  pkg/v1/providers/ytt/03_customizations/capabilities/add_capabilities.yaml
  pkg/v1/providers/yttcc/02_addons/auth/pinniped_addon_secret.lib.yaml
  pkg/v1/providers/yttcc/02_addons/auth/pinniped_addon_secret.yaml
  pkg/v1/providers/yttcc/02_addons/avi/ako_operator_secret.yaml
  pkg/v1/providers/yttcc/02_addons/cni/add_cni.yaml
  pkg/v1/providers/yttcc/02_addons/cni/antrea/antrea_addon_data.lib.yaml
  pkg/v1/providers/yttcc/02_addons/cni/antrea/antrea_overlay.lib.yaml
  pkg/v1/providers/yttcc/02_addons/cni/calico/calico_addon_data.lib.yaml
  pkg/v1/providers/yttcc/02_addons/cni/calico/calico_overlay.lib.yaml
  pkg/v1/providers/yttcc/02_addons/cpi/cpi_addon_data.lib.yaml
  pkg/v1/providers/yttcc/02_addons/cpi/cpi_app.lib.yaml
  pkg/v1/providers/yttcc/02_addons/cpi/cpi_overlay.lib.yaml
  pkg/v1/providers/yttcc/02_addons/cpi/cpi_secret.yaml
  pkg/v1/providers/yttcc/02_addons/cpi/cpi_secret_crs.yaml
  pkg/v1/providers/yttcc/02_addons/csi/csi_addon_data.lib.yaml
  pkg/v1/providers/yttcc/02_addons/csi/csi_secret.yaml
  pkg/v1/providers/yttcc/02_addons/kapp-controller/add_kapp-controller.yaml
  pkg/v1/providers/yttcc/02_addons/kapp-controller/kapp-controller_addon_data.lib.yaml
  pkg/v1/providers/yttcc/02_addons/kapp-controller/kapp-controller_overlay.lib.yaml
  pkg/v1/providers/yttcc/02_addons/management-packages/add_management_package_repo.yaml
  pkg/v1/providers/yttcc/02_addons/management-packages/core-management-plugins/add_core_management_plugins_package.yaml
  pkg/v1/providers/yttcc/02_addons/management-packages/featuregates/add_default_featuregate_cr.yaml
  pkg/v1/providers/yttcc/02_addons/management-packages/featuregates/add_featuregates_package.yaml
  pkg/v1/providers/yttcc/02_addons/metadata/add_cluster_metadata.yaml
  pkg/v1/providers/yttcc/02_addons/metrics-server/metrics_server_secret.yaml
  pkg/v1/providers/yttcc/02_addons/package-repos/add_package-repos.yaml
  pkg/v1/providers/yttcc/02_addons/secretgen-controller/add_secretgen-controller.yaml
  pkg/v1/providers/yttcc/02_addons/secretgen-controller/secretgen-controller_addon_data.lib.yaml
  pkg/v1/providers/yttcc/02_addons/standard-repo/add_standard_repo.yaml
  pkg/v1/providers/yttcc/02_addons/tanzu-addons-manager/add_tanzu-addons-manager.yaml
  pkg/v1/providers/yttcc/02_addons/tanzu-addons-manager/tanzu-addons-manager_addon_data.lib.yaml
  pkg/v1/providers/yttcc/02_addons/tanzu-addons-manager/tanzu-addons-manager_overlay.lib.yaml
  pkg/v1/providers/yttcc/02_addons/tanzu-addons-manager/tanzu-addons-manager_package.lib.yaml
  pkg/v1/providers/yttcc/03_customizations/01_tkr/add_tkr.yaml
  pkg/v1/providers/yttcc/03_customizations/01_tkr/tkr.lib.yaml
  pkg/v1/providers/yttcc/03_customizations/01_tkr/tkr_overlay.lib.yaml
  pkg/v1/providers/yttcc/03_customizations/02_avi/add-ako.yaml
  pkg/v1/providers/yttcc/03_customizations/02_avi/add_akoo.yaml
  pkg/v1/providers/yttcc/03_customizations/02_avi/ako-deployment.lib.yaml
  pkg/v1/providers/yttcc/03_customizations/02_avi/ako-operator-deployment.lib.yaml
  pkg/v1/providers/yttcc/03_customizations/02_avi/rbac.lib.yaml
  pkg/v1/providers/yttcc/03_customizations/02_avi/static.lib.yaml
  pkg/v1/providers/yttcc/03_customizations/add_mhc.yaml
  pkg/v1/providers/yttcc/03_customizations/add_sc.yaml
  pkg/v1/providers/yttcc/03_customizations/annotate_os_info.yaml
  pkg/v1/providers/yttcc/03_customizations/audit-logging/audit_logging.yaml
  pkg/v1/providers/yttcc/03_customizations/autoscaler/autoscaler_overlay.yaml
  pkg/v1/providers/yttcc/03_customizations/autoscaler/enable_autoscaler.yaml
  pkg/v1/providers/yttcc/03_customizations/capabilities/add_capabilities.yaml
  pkg/v1/providers/yttcc/03_customizations/http_proxy.lib.txt
  pkg/v1/providers/yttcc/03_customizations/http_proxy.yaml
  pkg/v1/providers/yttcc/03_customizations/ip_family.yaml
  pkg/v1/providers/yttcc/03_customizations/nameservers.yaml
  pkg/v1/providers/yttcc/04_user_customizations/README.md
  pkg/v1/providers/yttcc/09_miscellaneous/08_store_data_values.yaml
  pkg/v1/providers/yttcc/09_miscellaneous/09_filter.yaml
Labels: ok-to-merge, cla-not-required, area/lcm

#2186 Refactor clusterbootstrap_controller
  addons/controllers/clusterbootstrap_controller.go
  addons/go.mod
  addons/go.sum
  addons/pkg/util/clusterbootstrapclone/clusterbootstrapclone.go
  addons/pkg/util/clusterbootstrapclone/clusterbootstrapclone_suite_test.go
  addons/pkg/util/clusterbootstrapclone/clusterbootstrapclone_test.go
  addons/pkg/util/clusterbootstrapclone/doc.go
  addons/pkg/util/provider_util.go
Labels: ok-to-merge, cla-not-required

#2362 enhancing 'generate-package-config' Makefile target to specify infra
  Makefile
Labels: ok-to-merge, cla-not-required

#2383 package/management: tanzu-auth package fixes for build
  addons/pinniped/tanzu-auth-controller-manager/hack/run.sh
  packages/management/tanzu-auth/bundle/config/values.yaml
  packages/management/tanzu-auth/bundle/values.yaml
Labels: ok-to-merge, cla-not-required

#2381 [release-0.11] Conditonally set --node-ip on kubelet for TKR 1.22+ IPv6 workload clusters
  pkg/v1/providers/infrastructure-vsphere/v1.0.3/ytt/overlay.yaml
  pkg/v1/providers/tests/unit/custom_nameservers_test.go
  pkg/v1/providers/tests/unit/fixtures/yttmocks/lib/helpers.star
  pkg/v1/providers/tests/unit/ip_family_test.go
  pkg/v1/providers/tests/unit/matchers/yaml_path_matchers.go
Labels: ok-to-merge, cla-not-required

#2397 Updating version tag used for BOM retrieval to v0.11.6
  pkg/v1/tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: ok-to-merge, cla-not-required

#2380 Conditonally set --node-ip on kubelet for TKR 1.22+ IPv6 workload clusters
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/ytt/overlay.yaml
  pkg/v1/providers/tests/unit/custom_nameservers_test.go
  pkg/v1/providers/tests/unit/fixtures/yttmocks/lib/helpers.star
  pkg/v1/providers/tests/unit/ip_family_test.go
Labels: ok-to-merge, cla-not-required

#2348 derive all service and pod cidrs from cluster config
  pkg/v1/tkg/client/upgrade_addon.go
  pkg/v1/tkg/client/upgrade_addon_test.go
Labels: ok-to-merge, cla-not-required, area/networking

#2382 Fix a potential TKR Resolver index corruption
  pkg/v2/tkr/resolver/data/types.go
  pkg/v2/tkr/resolver/internal/resolver_impl.go
  pkg/v2/tkr/resolver/internal/resolver_impl_test.go
Labels: priority/critical-urgent, kind/bug, ok-to-merge, area/tkr, go

#2355 Packaging tkr-source-controller
  Makefile
  packages/kbld-config.yaml
  packages/management/tkg/bundle/config/packageinstalls/framework-pi.yaml
  packages/management/tkg/bundle/config/packageinstalls/tkr-source-controller-pi.yaml
  packages/management/tkg/bundle/config/packageinstalls/tkr-source-controller-service-account.yaml
  packages/management/tkg/bundle/config/values.yaml
  packages/management/tkr-service/bundle/config/upstream/rbac.yaml
  packages/management/tkr-source-controller/Makefile
  packages/management/tkr-source-controller/README.md
  packages/management/tkr-source-controller/bundle/config/overlays/overlay-tkr-source-controller.yaml
  packages/management/tkr-source-controller/bundle/config/upstream/rbac.yaml
  packages/management/tkr-source-controller/bundle/config/upstream/tkr-source-controller-deployment.yaml
  packages/management/tkr-source-controller/bundle/config/values.yaml
  packages/management/tkr-source-controller/metadata.yaml
  packages/management/tkr-source-controller/package.yaml
  packages/management/tkr-source-controller/vendir.lock.yml
  packages/management/tkr-source-controller/vendir.yml
  packages/package-values.yaml
  pkg/v2/tkr/controller/tkr-source/main.go
Labels: ok-to-merge, cla-not-required

#2378 Hide TKR_DATA when not running yaml tests
  pkg/v1/providers/config_default.yaml
  pkg/v1/providers/infrastructure-aws/v1.2.0/yttcc/overlay.yaml
  pkg/v1/providers/infrastructure-azure/v1.0.1/yttcc/overlay.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/yttcc/overlay.yaml
  pkg/v1/providers/tests/clustergen/run_tests.sh
  pkg/v1/providers/yttcc/lib/config_variable_association.star
Labels: ok-to-merge, cla-not-required

#2391 Show TKR name in cluster list and cluster get commands
  cmd/cli/plugin/cluster/get.go
  cmd/cli/plugin/cluster/list.go
  cmd/cli/plugin/managementcluster/get.go
  pkg/v1/tkg/client/get_cluster.go
  pkg/v1/tkg/client/get_cluster_helper.go
  pkg/v1/tkg/client/get_cluster_test.go
Labels: area/cli, kind/enhancement, ok-to-merge, cla-not-required

#2402 postpone connecting to remote cluster until when needed
  addons/controllers/clusterbootstrap_controller.go
Labels: ok-to-merge, cla-not-required

#2253 disable printing usage info for management-cluster and cluster commands if they fail even for correct command
  addons/go.mod
  addons/go.sum
  cmd/cli/plugin/cluster/available_upgrade.go
  cmd/cli/plugin/cluster/create.go
  cmd/cli/plugin/cluster/credentials.go
  cmd/cli/plugin/cluster/credentials_update.go
  cmd/cli/plugin/cluster/delete.go
  cmd/cli/plugin/cluster/delete_machinehealthcheck.go
  cmd/cli/plugin/cluster/delete_machinehealthcheck_control_plane.go
  cmd/cli/plugin/cluster/delete_machinehealthcheck_node.go
  cmd/cli/plugin/cluster/delete_node_pool.go
  cmd/cli/plugin/cluster/get.go
  cmd/cli/plugin/cluster/get_machinehealthcheck.go
  cmd/cli/plugin/cluster/get_machinehealthcheck_control_plane.go
  cmd/cli/plugin/cluster/get_machinehealthcheck_node.go
  cmd/cli/plugin/cluster/get_node_pools.go
  cmd/cli/plugin/cluster/kubeconfig.go
  cmd/cli/plugin/cluster/kubeconfig_get.go
  cmd/cli/plugin/cluster/list.go
  cmd/cli/plugin/cluster/machinehealthcheck.go
  cmd/cli/plugin/cluster/machinehealthcheck_control_plane.go
  cmd/cli/plugin/cluster/machinehealthcheck_node.go
  cmd/cli/plugin/cluster/main.go
  cmd/cli/plugin/cluster/node_pool.go
  cmd/cli/plugin/cluster/scale.go
  cmd/cli/plugin/cluster/set_machinehealthcheck.go
  cmd/cli/plugin/cluster/set_machinehealthcheck_control_plane.go
  cmd/cli/plugin/cluster/set_machinehealthcheck_node.go
  cmd/cli/plugin/cluster/set_node_pool.go
  cmd/cli/plugin/cluster/test/cluster_silentmode.go
  cmd/cli/plugin/cluster/test/create.go
  cmd/cli/plugin/cluster/test/delete.go
  cmd/cli/plugin/cluster/test/main.go
  cmd/cli/plugin/cluster/test/management_cluster.go
  cmd/cli/plugin/cluster/upgrade.go
  cmd/cli/plugin/managementcluster/ceip.go
  cmd/cli/plugin/managementcluster/create.go
  cmd/cli/plugin/managementcluster/credentials.go
  cmd/cli/plugin/managementcluster/credentials_update.go
  cmd/cli/plugin/managementcluster/delete.go
  cmd/cli/plugin/managementcluster/get.go
  cmd/cli/plugin/managementcluster/get_ceip.go
  cmd/cli/plugin/managementcluster/import.go
  cmd/cli/plugin/managementcluster/kubeconfig.go
  cmd/cli/plugin/managementcluster/kubeconfig_get.go
  cmd/cli/plugin/managementcluster/permissions.go
  cmd/cli/plugin/managementcluster/permissions_aws_generate.go
  cmd/cli/plugin/managementcluster/permissions_aws_set.go
  cmd/cli/plugin/managementcluster/set_ceip.go
  cmd/cli/plugin/managementcluster/upgrade.go
  go.mod
  go.sum
  pkg/v1/test/cli/framework.go
  pkg/v1/tkg/cmd/set_ceip.go
Labels: area/cli, ok-to-merge, area/ux, cla-not-required

#2354 allow to customize healthz & webhook-server port
  addons/main.go
  packages/management/addons-manager/bundle/config/upstream/addons-manager.yaml
  packages/management/addons-manager/bundle/config/values.yaml
  packages/management/framework/bundle/config/values.yaml
  packages/management/tkg/bundle/config/values.yaml
Labels: ok-to-merge, cla-not-required

#2280 Add codecov to github workflow
  .codecov.yaml
  .github/workflows/main.yaml
  Makefile
  addons/Makefile
  addons/pinniped/post-deploy/Makefile
  addons/pinniped/tanzu-auth-controller-manager/controllers/utils_test.go
  addons/pinniped/tanzu-auth-controller-manager/hack/test.sh
  hack/tools/Makefile
Labels: CI, ok-to-merge, cla-not-required

#2400 Fix `cliplugins` package deletion issue
  packages/management/framework/bundle/config/packageinstalls/cliplugins-pi.yaml
Labels: ok-to-merge, cla-not-required

#2427 Fix kubebuilder binaries installation
  hack/tools/Makefile
Labels: area/testing, ok-to-merge, cla-not-required

#2418 Makefile: add tanzu-auth-controller-manager as a COMPONENT
  Makefile
  addons/pinniped/tanzu-auth-controller-manager/Makefile
Labels: ok-to-merge, cla-not-required, area/packages

#2428 Fix post-merge tests involving get_pr_num
  .github/workflows/main.yaml
  .github/workflows/plugin_tests.yaml
  .github/workflows/tkg_integration_tests.yaml
  .github/workflows/tkgpackage_integration_test.yaml
Labels: CI, ok-to-merge, cla-not-required

#2361 Add Windows-related ClusterClass Template changes
  packages/management/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  packages/management/tkg-clusterclass-vsphere/bundle/config/upstream/overlay-windows.yaml
  packages/management/tkg-clusterclass-vsphere/bundle/config/upstream/overlay.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/cconly/base.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/cconly/overlay-windows.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/cconly/overlay.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/cluster-template-definition-dev-windows.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/cluster-template-definition-dev-windowscc.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/yttcc/overlay-windows.yaml
  pkg/v1/providers/infrastructure-vsphere/v1.1.0/yttcc/overlay.yaml
Labels: ok-to-merge, cla-not-required, area/lcm

#2435 TKR CRD v1alpha2: fix divergence with TKGS
  packages/management/tkr-service/bundle/config/upstream/tkr-crd.yaml
Labels: area/api, kind/cleanup, ok-to-merge, cla-not-required, area/tkr

#2442 Upload coverage reports on push to main
  .github/workflows/release_staging.yaml
Labels: ok-to-merge, cla-not-required

#1940 Separate kbld configs
  Makefile
  addons/Makefile
  addons/pinniped/tanzu-auth-controller-manager/Makefile
  cliplugins/Makefile
  hack/packages/kbld-image-replace/main.go
  hack/packages/package-tools/cmd/package-bundle-generate.go
  hack/packages/package-tools/constants/constants.go
  packages/addons-manager/kbld-config.yaml
  packages/capabilities/kbld-config.yaml
  packages/core-management-plugins/kbld-config.yaml
  packages/featuregates/kbld-config.yaml
  packages/kbld-config.yaml
  packages/standalone-plugins/kbld-config.yaml
  packages/tanzu-auth/bundle/config/values.yaml
  packages/tanzu-auth/kbld-config.yaml
  packages/tkr-aws-machine-webhook/kbld-config.yaml
  packages/tkr-azure-machine-webhook/kbld-config.yaml
  packages/tkr-docker-machine-webhook/kbld-config.yaml
  packages/tkr-service/kbld-config.yaml
  packages/tkr-source-controller/kbld-config.yaml
  packages/tkr-vsphere-machine-webhook/kbld-config.yaml
  pkg/v1/sdk/capabilities/Makefile
  pkg/v1/sdk/features/Makefile
  pkg/v2/tkr/controller/tkr-source/Makefile
  pkg/v2/tkr/controller/tkr-status/Makefile
  pkg/v2/tkr/webhook/cluster/tkr-resolver/Makefile
  pkg/v2/tkr/webhook/infra-machine/Makefile
  pkg/v2/tkr/webhook/tkr-conversion/Makefile
Labels: ok-to-merge, cla-not-required, area/packages

#2491 Updating AWS VPC to use different AWS account for CI tests
  pkg/v1/tkg/test/config/aws.yaml
Labels: CI, ok-to-merge, cla-not-required

#2337 Expose `AVI_LABELS` in workload cluster config file when performing `tanzu cluster create`
  pkg/v1/providers/config_default.yaml
  pkg/v1/providers/tests/clustergen/gencluster_params.py
  pkg/v1/providers/tests/clustergen/param_models/cluster_vsphere.model
  pkg/v1/providers/tests/unit/avi_test.go
  pkg/v1/providers/tests/unit/custom_nameservers_test.go
  pkg/v1/providers/tests/unit/ip_family_test.go
  pkg/v1/providers/tests/unit/windows_test.go
  pkg/v1/providers/ytt/03_customizations/02_avi/add-avi-labels.yaml
Labels: ok-to-merge, cla-not-required, area/networking, area/lcm

#2416 Update SkipCNIBinaries param to CalicoConfig
  addons/config/expected/cni.tanzu.vmware.com/v1alpha1/calicoconfig/default.yaml
  addons/config/templates/cni.tanzu.vmware.com/v1alpha1/calicoconfig.yaml
  addons/controllers/calico/calicoconfig_utils.go
  addons/controllers/calicoconfig_controller_test.go
  addons/controllers/testdata/test-calico-1.yaml
  addons/controllers/testdata/test-calico-2.yaml
  apis/cni/v1alpha1/calicoconfig_types.go
  config/crd/bases/cni.tanzu.vmware.com_calicoconfigs.yaml
Labels: area/addons, ok-to-merge, cla-not-required

#2403 defaulting webhook for clusterbootstrap cr
  addons/go.sum
  addons/pkg/constants/constants.go
  addons/pkg/util/clusterbootstrapclone/clusterbootstrapclone.go
  addons/pkg/util/clusterbootstrapclone/clusterbootstrapclone_test.go
  addons/webhooks/clusterbootstrap_webhook.go
  addons/webhooks/clusterbootstrap_webhook_test.go
  addons/webhooks/testdata/README.md
  addons/webhooks/testdata/crds/fake-carvel-package.yaml
  addons/webhooks/testdata/crds/run.tanzu.vmware.com_tanzukubernetesreleases.yaml
  addons/webhooks/webhooks_suite_test.go
Labels: ok-to-merge, cla-not-required

#2425 Prevent finalizer from being added to management cluster
  addons/controllers/clusterbootstrap_controller.go
Labels: ok-to-merge, cla-not-required

#2494 Create aggregate cluster role for CAPV
  addons/controllers/cpi/vspherecpiconfig_controller.go
  addons/controllers/cpi/vspherecpiconfig_utils.go
  addons/controllers/csi/vspherecsiconfig_controller.go
  addons/controllers/csi/vspherecsiconfig_utils.go
  addons/controllers/vspherecpiconfig_controller_test.go
  addons/controllers/vspherecsiconfig_controller_test.go
  addons/pkg/constants/constants.go
Labels: ok-to-merge, cla-not-required

#2331 Removes superfluous logging of machine-controller
  addons/controllers/clusterbootstrap_controller.go
  addons/controllers/machine_controller.go
Labels: ok-to-merge, cla-not-required

#2507 Sync CRDs in addons-manager
  packages/addons-manager/bundle/config/upstream/cni.tanzu.vmware.com_calicoconfigs.yaml
  packages/addons-manager/bundle/config/upstream/cpi.tanzu.vmware.com_vspherecpiconfigs.yaml
  packages/addons-manager/bundle/config/upstream/csi.tanzu.vmware.com_vspherecsiconfigs.yaml
  packages/addons-manager/bundle/config/upstream/run.tanzu.vmware.com_clusterbootstraps.yaml
  packages/addons-manager/bundle/config/upstream/run.tanzu.vmware.com_clusterbootstraptemplates.yaml
  packages/addons-manager/vendir.lock.yml
  packages/addons-manager/vendir.yml
Labels: area/addons, ok-to-merge, cla-not-required

#2417 Enable webhook tls tertificate management
  addons/controllers/certificates_test.go
  addons/controllers/suite_test.go
  addons/main.go
  addons/pkg/constants/constants.go
  pkg/v1/webhooks/certificates.go
  pkg/v1/webhooks/certificates_test.go
  pkg/v1/webhooks/webhooks.go
Labels: ok-to-merge, cla-not-required

#2423 Update Azure TKR image data processing
  packages/tkg-clusterclass-azure/bundle/config/upstream/base.yaml
  pkg/v1/providers/infrastructure-azure/v1.0.1/cconly/base.yaml
  pkg/v1/providers/tests/clustergen/run_tests.sh
Labels: ok-to-merge, cla-not-required
