Repository vmware-tanzu/tanzu-framework, pull requests merged in 2023-03, with the labels that each got.

#4415 error out when getting virtual machine images fails for context related error
  tkg/vc/client.go
  tkg/vsphere-template-resolver/templateresolver/resolver_impl.go
Labels: ok-to-merge, cla-not-required, backports/release-0.28

#4382 Support Image build from custom build args
  addons/Dockerfile
  addons/Makefile
  capabilities/Makefile
  capabilities/controller/Dockerfile
  common.mk
  featuregates/Makefile
  featuregates/controller/Dockerfile
  object-propagation/Dockerfile
  object-propagation/Makefile
  pinniped-components/post-deploy/Dockerfile
  pinniped-components/post-deploy/Makefile
  pinniped-components/post-deploy/hack/scripts/build-images.sh
  pinniped-components/tanzu-auth-controller-manager/Dockerfile
  pinniped-components/tanzu-auth-controller-manager/Makefile
  pkg/v1/tkr/Dockerfile
  pkg/v1/tkr/Makefile
  tkg/vsphere-template-resolver/Dockerfile
  tkg/vsphere-template-resolver/Makefile
  tkr/controller/tkr-source/Dockerfile
  tkr/controller/tkr-source/Makefile
  tkr/controller/tkr-status/Dockerfile
  tkr/controller/tkr-status/Makefile
  tkr/webhook/cluster/tkr-resolver/Dockerfile
  tkr/webhook/cluster/tkr-resolver/Makefile
  tkr/webhook/tkr-conversion/Dockerfile
  tkr/webhook/tkr-conversion/Makefile
Labels: ok-to-merge, cla-not-required

#4444 [release-0.28] cherry-pick #4415: return error if context canceled during getting virtual machine image…
  tkg/vc/client.go
  tkg/vsphere-template-resolver/templateresolver/resolver_impl.go
Labels: ok-to-merge, cla-not-required, backports/release-0.28

#4448 Omits PCI related params from tkg vsphere config
  providers/yttcc/lib/config_variable_association.star
  tkg/tkgconfigproviders/vsphere.go
Labels: ok-to-merge, cla-not-required

#4451 packages/tanzu-auth: support PSA
  packages/tanzu-auth/bundle/config/deployment.yaml
Labels: ok-to-merge, cla-not-required

#4446 Update BOM retrieval version to v0.28.1
  tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#4374 Bump kapp-controller to v0.41.6
  providers/vendir.lock.yml
  providers/vendir.yml
  providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.41.6/bundle/config/overlays/change-namespace.yaml
  providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.41.6/bundle/config/overlays/update-configmap.yaml
  providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.41.6/bundle/config/overlays/update-crds.yaml
  providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.41.6/bundle/config/overlays/update-deployment.yaml
  providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.41.6/bundle/config/overlays/update-strategy-overlay.yaml
  providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.41.6/bundle/config/upstream/kapp-controller.yaml
  providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.41.6/bundle/config/values.star
  providers/ytt/vendir/kapp-controller/_ytt_lib/addons/packages/kapp-controller/0.41.6/bundle/config/values.yaml
  providers/ytt/vendir/kapp-controller/kapp-controller.lib.yaml
Labels: ok-to-merge, cla-not-required

#4416 check cluster name length when ako needs to be deployed in the cluster
  tkg/client/cluster.go
  tkg/client/management_components.go
  tkg/client/management_components_test.go
  tkg/client/upgrade_region.go
  tkg/client/validate.go
  tkg/client/validate_test.go
  tkg/constants/cluster_internal.go
  tkg/managementcomponents/helper.go
  tkg/utils/common.go
  tkg/utils/common_test.go
Labels: ok-to-merge, cla-not-required

#4430 Change default namesapce for vsphere-csi
  addons/controllers/csi/vspherecsiconfig_constants.go
  addons/controllers/vspherecsiconfig_controller_test.go
Labels: ok-to-merge, cla-not-required

#4458 Fix tanzu-auth-controller user to refer by id instead of name and fix psa profile
  packages/tanzu-auth/bundle/config/namespace.yaml
  pinniped-components/tanzu-auth-controller-manager/Dockerfile
Labels: ok-to-merge, cla-not-required

#4445 Fix issue when a custom image repository uses a public cert
  packages/tkg-clusterclass-aws/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-aws/bundle/config/upstream/overlay.yaml
  packages/tkg-clusterclass-azure/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-azure/bundle/config/upstream/overlay.yaml
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/overlay.yaml
  providers/infrastructure-aws/v2.0.2/cconly/base.yaml
  providers/infrastructure-aws/v2.0.2/cconly/overlay.yaml
  providers/infrastructure-azure/v1.6.1/cconly/base.yaml
  providers/infrastructure-azure/v1.6.1/cconly/overlay.yaml
  providers/infrastructure-vsphere/v1.5.3/cconly/base.yaml
  providers/infrastructure-vsphere/v1.5.3/cconly/overlay.yaml
Labels: ok-to-merge, cla-not-required, cherry-pick/release-0.28

#4462 Fix docker cache invalidation due to missing build argument
  build-tooling.mk
Labels: cla-not-required

#4419 Support retrieve azure credentials from AzureClusterIdentity
  providers/ytt/lib/validate.star
  providers/yttcc/lib/validate.star
  tkg/client/cluster.go
  tkg/client/validate.go
  tkg/client/validate_test.go
  tkg/clusterclient/clusterclient.go
  tkg/clusterclient/clusterclient_test.go
  tkg/clusterclient/credentials.go
  tkg/fakes/clusterclient.go
  tkg/tkgctl/create_cluster.go
Labels: ok-to-merge, cla-not-required

#4456 remove default Featuregate resource in featuregates package
  packages/featuregates/bundle/config/upstream/crds/config/config.tanzu.vmware.com_featuregates.yaml
  packages/featuregates/bundle/config/upstream/crds/config/config.tanzu.vmware.com_features.yaml
  packages/featuregates/bundle/config/upstream/default-featuregate-cr.yaml
  packages/featuregates/vendir.lock.yml
  packages/featuregates/vendir.yml
Labels: ok-to-merge, cla-not-required

#4386 Update AWS network resources to be used by CI
  .github/workflows/tkg_integration_tests_clusterclass.yaml
  tkg/client/config_permission_test.go
  tkg/test/config/aws.yaml
  tkg/test/config/cc/aws/aws_cc_wc_config.yaml
  tkg/test/scripts/aws_cleanup.sh
  tkg/test/scripts/aws_setup.sh
  tkg/tkgconfigupdater/ensure.go
Labels: ok-to-merge, cla-not-required, provider/aws

#4455 Set improved pod security configuration for CAPI components in MC to comply with restricted policy
  hack/providers-sync-tools/cluster-api-bootstrap-kubeadm/overlay/update-pod-security-admission.yaml
  hack/providers-sync-tools/cluster-api-control-plane-kubeadm/overlay/update-pod-security-admission.yaml
  hack/providers-sync-tools/cluster-api-provider-aws/overlay/update-pod-security-admission.yaml
  hack/providers-sync-tools/cluster-api-provider-azure/overlay/update-pod-security-admission.yaml
  hack/providers-sync-tools/cluster-api-provider-vsphere/overlay/update-pod-security-admission.yaml
  hack/providers-sync-tools/cluster-api/overlay/update-pod-security-admission.yaml
  providers/bootstrap-kubeadm/v1.2.8/bootstrap-components.yaml
  providers/cluster-api/v1.2.8/core-components.yaml
  providers/control-plane-kubeadm/v1.2.8/control-plane-components.yaml
  providers/infrastructure-aws/v2.0.2/infrastructure-components.yaml
  providers/infrastructure-azure/v1.6.1/infrastructure-components.yaml
  providers/infrastructure-ipam-in-cluster/v0.1.0/ipam-components.yaml
  providers/infrastructure-vsphere/v1.5.3/infrastructure-components-supervisor.yaml
  providers/infrastructure-vsphere/v1.5.3/infrastructure-components.yaml
Labels: ok-to-merge, cla-not-required

#4457 Omits PCI related params from tkg vsphere config
  providers/yttcc/lib/config_variable_association.star
  tkg/tkgconfigproviders/vsphere.go
Labels: ok-to-merge, cla-not-required

#4467 Support additional image registries with self-signed CA certificates
  packages/tkg-clusterclass-aws/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-aws/bundle/config/upstream/overlay.yaml
  packages/tkg-clusterclass-azure/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-azure/bundle/config/upstream/overlay.yaml
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/overlay.yaml
  providers/config_default.yaml
  providers/infrastructure-aws/v2.0.2/cconly/base.yaml
  providers/infrastructure-aws/v2.0.2/cconly/overlay.yaml
  providers/infrastructure-aws/v2.0.2/yttcc/overlay.yaml
  providers/infrastructure-azure/v1.6.1/cconly/base.yaml
  providers/infrastructure-azure/v1.6.1/cconly/overlay.yaml
  providers/infrastructure-azure/v1.6.1/yttcc/overlay.yaml
  providers/infrastructure-vsphere/v1.5.3/cconly/base.yaml
  providers/infrastructure-vsphere/v1.5.3/cconly/overlay.yaml
  providers/infrastructure-vsphere/v1.5.3/yttcc/overlay.yaml
  providers/yttcc/lib/config_variable_association.star
  providers/yttcc/lib/helpers.star
Labels: ok-to-merge, cla-not-required, cherry-pick/release-0.28

#4478 Add PSA support & bump ako operator new changes into ako operator v2 package
  packages/ako-operator-v2/bundle/config/overlays/overlay-deployment.yaml
  packages/ako-operator-v2/bundle/config/upstream/akooperator/deployment.yaml
  packages/ako-operator-v2/bundle/config/upstream/akooperator/static.yaml
  packages/ako-operator-v2/metadata.yaml
Labels: ok-to-merge, cla-not-required

#4480 Change capz pipeline to create cc mc and legacy wc
  tkg/client/upgrade_region.go
  tkg/clusterclient/clusterclient.go
  tkg/constants/cluster_internal.go
  tkg/manifest/telemetry/config-aws.yaml
  tkg/manifest/telemetry/config-azure.yaml
  tkg/manifest/telemetry/config-docker.yaml
  tkg/manifest/telemetry/config-vsphere.yaml
  tkg/test/framework/schemes.go
  tkg/test/scripts/legacy_hack.sh
  tkg/test/tkgctl/shared/ceip.go
Labels: ok-to-merge, cla-not-required

#4459 getGVR should only fail if no GroupVersionResource is found
  addons/go.mod
  addons/go.sum
  addons/webhooks/clusterbootstrap_webhook.go
  addons/webhooks/clusterbootstrap_webhook_test.go
  addons/webhooks/webhooks_suite_test.go
Labels: ok-to-merge, cla-not-required

#4486 Installer UI - Update npm packages to fix critical dependabot alert
  tkg/web/package-lock.json
  tkg/web/package.json
Labels: ok-to-merge, cla-not-required

#4490 Add cert-manager provider manifest for v1.10.2
  providers/cert-manager/v1.10.2/cert-manager.yaml
  providers/config.yaml
Labels: ok-to-merge, cla-not-required, area/packages

#4504 update avi controller min support version
  tkg/avi/client.go
Labels: ok-to-merge, cla-not-required

#4505 Update telemetry bindata
  tkg/manifest/telemetry/zz_generated.bindata.go
Labels: ok-to-merge, cla-not-required

#4317 Adds required minimum graceperiod for addons manager certificates
  addons/controllers/webhooks_test.go
  addons/pkg/webhooks/webhooks.go
Labels: ok-to-merge, cla-not-required

#4474 Fix deadlock for mgmt cluster upgrade and tkr fetch
  packages/tkr-source-controller/bundle/config/upstream/default-compatible-tkr.yaml
  packages/tkr-source-controller/bundle/config/upstream/tkr-source-controller-deployment.yaml
  tkg/client/upgrade_cluster_clusterclass.go
  tkg/client/upgrade_cluster_test.go
  tkg/client/upgrade_region.go
Labels: ok-to-merge, cla-not-required

#4453 Adding env test to featuregate controller
  apis/core/v1alpha2/featuregate_webhook.go
  featuregates/Makefile
  featuregates/controller/Dockerfile
  featuregates/controller/go.mod
  featuregates/controller/go.sum
  featuregates/controller/pkg/feature/feature_suite_test.go
  featuregates/controller/pkg/feature/testdata/webhook.yaml
  featuregates/controller/pkg/featuregate/suite_test.go
  featuregates/controller/pkg/test/cert.go
  featuregates/controller/pkg/test/kube.go
Labels: ok-to-merge, cla-not-required

#4302 Fix addons controller crd waiter bug (#4247)
  addons/controllers/addon_controller.go
  addons/controllers/suite_test.go
  addons/main.go
  addons/pkg/crdwait/crd_wait.go
  addons/pkg/crdwait/crd_wait_test.go
Labels: ok-to-merge, cla-not-required

#4499 Changes for upgrade for packages with inline valuesFrom which change from nil to not nil
  addons/controllers/clusterbootstrap_controller.go
  addons/controllers/clusterbootstrap_controller_test.go
  addons/controllers/testdata/test-cluster-bootstrap-10.yaml
Labels: ok-to-merge, cla-not-required

#4506 Update autoscaler related annotations and Add filter to node-group-auto-discovery arg
  providers/ytt/03_customizations/autoscaler/autoscaler_overlay.yaml
  providers/ytt/03_customizations/autoscaler/enable_autoscaler.yaml
  providers/yttcc/02_customizations/autoscaler/enable_autoscaler.yaml
Labels: ok-to-merge, cla-not-required

#4511 enhance output instuction when creating cc cluster with legacy config
  tkg/client/cluster.go
  tkg/client/cluster_test.go
Labels: ok-to-merge, cla-not-required

#4450 Use build-tooling to build FeatureGates component
  .dockerignore
  Dockerfile
  build-tooling.mk
  capabilities/client/go.mod
  capabilities/client/go.sum
  capabilities/controller/go.mod
  capabilities/controller/go.sum
Labels: cla-not-required

#4491 Add VolumeSnapshot related RBACs to provider service account for TKC/GC
  addons/controllers/csi/vspherecsiconfig_controller.go
  addons/controllers/vspherecsiconfig_controller_test.go
Labels: ok-to-merge, cla-not-required

#4517 TKG-18468 Add UI export e2e test payload and control yaml for vsphere, aws and azure
  tkg/test/ui/data/aws/aws-test-1-input.json
  tkg/test/ui/data/aws/aws-test-1-output-config.yaml
  tkg/test/ui/data/azure/azure-test-1-input.json
  tkg/test/ui/data/azure/azure-test-1-output-config.yaml
  tkg/test/ui/data/vsphere/vsphere-test-1-input.json
  tkg/test/ui/data/vsphere/vsphere-test-1-output-config.yaml
Labels: ok-to-merge, cla-not-required

#4514 Extract common PinnipedInfo struct so that it can be used everywhere
  cli/core/go.mod
  cli/core/pkg/auth/tkg/cluster_pinniped_info.go
  cli/core/pkg/auth/tkg/cluster_pinniped_info_test.go
  cli/core/pkg/auth/tkg/kube_config.go
  cli/core/pkg/auth/tkg/kube_config_test.go
  cli/core/pkg/fakes/helper/fakeobjectcreater.go
  cmd/cli/plugin-admin/builder/go.mod
  cmd/cli/plugin-admin/test/go.mod
  cmd/cli/plugin/cluster/go.mod
  cmd/cli/plugin/isolated-cluster/go.mod
  cmd/cli/plugin/login/go.mod
  cmd/cli/plugin/managementcluster/go.mod
  cmd/cli/plugin/managementcluster/kubeconfig_get.go
  cmd/cli/plugin/package/go.mod
  go.mod
  pinniped-components/common/doc.go
  pinniped-components/common/go.mod
  pinniped-components/common/go.sum
  pinniped-components/common/pkg/pinnipedinfo/doc.go
  pinniped-components/common/pkg/pinnipedinfo/pinnipedinfo.go
  pinniped-components/post-deploy/go.mod
  pinniped-components/post-deploy/pkg/configure/configure.go
  pinniped-components/post-deploy/pkg/configure/helper.go
  pinniped-components/post-deploy/pkg/configure/helper_test.go
  pinniped-components/post-deploy/pkg/configure/supervisor/supervisor.go
  tkg/auth/kube_config.go
  tkg/auth/kube_config_test.go
  tkg/client/get_cluster_pinniped_info.go
  tkg/client/get_cluster_pinniped_info_test.go
  tkg/fakes/helper/fakeobjectcreater.go
  tkg/go.mod
  tkg/utils/kubeconfig.go
  tkg/utils/kubeconfig_test.go
  tkg/vsphere-template-resolver/Dockerfile
Labels: ok-to-merge, cla-not-required

#4477 Upgrades CAPZ version to v1.6.3
  packages/cluster-api-provider-azure/bundle/config/upstream/infrastructure-components.yaml
  packages/cluster-api-provider-azure/vendir.lock.yml
  packages/cluster-api-provider-azure/vendir.yml
  providers/config.yaml
  providers/infrastructure-azure/v1.6.3/cconly/base.yaml
  providers/infrastructure-azure/v1.6.3/cconly/overlay-kube-apiserver-admission.yaml
  providers/infrastructure-azure/v1.6.3/cconly/overlay.yaml
  providers/infrastructure-azure/v1.6.3/cluster-template-definition-dev.yaml
  providers/infrastructure-azure/v1.6.3/cluster-template-definition-devcc.yaml
  providers/infrastructure-azure/v1.6.3/cluster-template-definition-prod.yaml
  providers/infrastructure-azure/v1.6.3/cluster-template-definition-prodcc.yaml
  providers/infrastructure-azure/v1.6.3/clusterclass-tkg-azure-default.yaml
  providers/infrastructure-azure/v1.6.3/infrastructure-components.yaml
  providers/infrastructure-azure/v1.6.3/metadata.yaml
  providers/infrastructure-azure/v1.6.3/ytt/base-template.yaml
  providers/infrastructure-azure/v1.6.3/ytt/overlay.yaml
  providers/infrastructure-azure/v1.6.3/yttcc/base-template.yaml
  providers/infrastructure-azure/v1.6.3/yttcc/overlay.yaml
Labels: ok-to-merge, cla-not-required

#4502 Configure Dex to issue refresh tokens with an expiry of 9h
  pinniped-components/post-deploy/pkg/schemas/schemas.go
  providers/ytt/02_addons/auth/pinniped_addon_secret.lib.yaml
  providers/yttcb/pinniped_addon_secret.lib.yaml
Labels: area/auth, ok-to-merge, cla-not-required

#4520 remove an invalid credential
  tkg/test/ui/data/aws/aws-test-1-output-config.yaml
Labels: ok-to-merge, cla-not-required

#4529 Ensure cluster-api-ipam-provider-in-cluster respects the imagePath field in the BOM
  tkg/fakes/config/bom/tkg-bom-v1.3.0.yaml
  tkg/fakes/config/bom/tkg-bom-v1.3.1.yaml
  tkg/fakes/config/bom/tkg-bom-v2.1.0.yaml
  tkg/fakes/config/bom/tkg-bom-v3.0.0.yaml
  tkg/tkgconfigupdater/images.go
Labels: ok-to-merge, cla-not-required

#4501 Add generate-fakes to /tkg/Makefile
  tkg/Makefile
  tkg/go.mod
  tkg/go.sum
  tkg/tools/tools.go
Labels: ok-to-merge, cla-not-required

#4531 Combine the zeroes-out AWS credential action for both legacy and cc
  tkg/client/upgrade_cluster.go
  tkg/client/upgrade_cluster_clusterclass.go
  tkg/client/upgrade_region.go
Labels: ok-to-merge, cla-not-required

#4518 Pinniped | Remove embedded Pinniped 0.4.4 CLI
  Makefile
  cli/core/pkg/auth/tkg/cluster_pinniped_info_test.go
  cli/core/pkg/auth/tkg/kube_config.go
  cli/core/pkg/auth/tkg/kube_config_test.go
  cmd/cli/plugin/pinniped-auth/asset/pinniped-v0.4.4
  cmd/cli/plugin/pinniped-auth/login.go
  cmd/cli/plugin/pinniped-auth/login_test.go
  docs/cli/commands/tanzu_pinniped-auth_login.md
  pinniped-components/common/pkg/pinnipedinfo/pinnipedinfo.go
  pinniped-components/post-deploy/cmd/job/main.go
  pinniped-components/post-deploy/pkg/configure/configure.go
  pinniped-components/post-deploy/pkg/configure/configure_test.go
  pinniped-components/post-deploy/pkg/configure/helper_test.go
  pinniped-components/post-deploy/pkg/vars/vars.go
  tkg/auth/kube_config.go
  tkg/auth/kube_config_test.go
  tkg/client/get_cluster_pinniped_info.go
  tkg/client/get_cluster_pinniped_info_test.go
  tkg/utils/kubeconfig_test.go
Labels: ok-to-merge, cla-not-required

#4530 Add CVE scan workflow
  .github/workflows/cve_scan.yaml
  .trivy.yaml
  apis/addonconfigs/go.mod
  apis/addonconfigs/go.sum
  cli/runtime/hack/tools/go.mod
  cli/runtime/hack/tools/go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  packages/cluster-api-bootstrap-kubeadm/test/go.mod
  packages/cluster-api-bootstrap-kubeadm/test/go.sum
  packages/cluster-api-provider-aws/test/go.mod
  packages/cluster-api-provider-aws/test/go.sum
  packages/cluster-api-provider-azure/test/go.mod
  packages/cluster-api-provider-azure/test/go.sum
  packages/cluster-api-provider-docker/test/go.mod
  packages/cluster-api-provider-docker/test/go.sum
  packages/cluster-api-provider-vsphere/test/go.mod
  packages/cluster-api-provider-vsphere/test/go.sum
  packages/cluster-api/test/go.mod
  packages/cluster-api/test/go.sum
  pinniped-components/hack/tools/go.mod
  pinniped-components/hack/tools/go.sum
  test/pkg/go.mod
  test/pkg/go.sum
Labels: area/security, ok-to-merge, cla-not-required, area/dx
