Repository vmware-tanzu/tanzu-framework, pull requests merged in 2023-01, with the labels that each got.

#4225 Fix copyright headers in generated files
  apis/addonconfigs/cni/v1alpha1/zz_generated.deepcopy.go
  apis/addonconfigs/cpi/v1alpha1/zz_generated.deepcopy.go
  apis/addonconfigs/csi/v1alpha1/zz_generated.deepcopy.go
  apis/cli/v1alpha1/zz_generated.deepcopy.go
  apis/config/v1alpha1/zz_generated.deepcopy.go
  apis/core/v1alpha1/zz_generated.deepcopy.go
  apis/core/v1alpha2/zz_generated.deepcopy.go
  apis/run/v1alpha1/zz_generated.deepcopy.go
  apis/run/v1alpha2/zz_generated.deepcopy.go
  apis/run/v1alpha3/zz_generated.deepcopy.go
  cli/runtime/apis/cli/v1alpha1/zz_generated.deepcopy.go
  cli/runtime/apis/config/v1alpha1/zz_generated.deepcopy.go
  util/patchset/internal/apis/run/v1alpha3/zz_generated.deepcopy.go
Labels: ok-to-merge, cla-not-required

#4213 Add antrea 1.7.2 package
  providers/vendir.lock.yml
  providers/vendir.yml
  providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.7.2/bundle/config/kapp-config.yaml
  providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.7.2/bundle/config/overlay/antrea-overlay.yaml
  providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.7.2/bundle/config/overlay/update-strategy-overlay.yaml
  providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.7.2/bundle/config/schema.yaml
  providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.7.2/bundle/config/upstream/antrea.yaml
  providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.7.2/bundle/config/values.star
  providers/ytt/vendir/cni/_ytt_lib/addons/packages/antrea/1.7.2/bundle/config/values.yaml
  providers/ytt/vendir/cni/cni.lib.yaml
Labels: ok-to-merge, cla-not-required

#4223 Package Plugin Tests: Wait for App to be paused before updating kapp-controller configmap
  cmd/cli/plugin/package/test/package_plugin_integration_test.go
Labels: ok-to-merge, cla-not-required

#4186 Enable MHC by default for vsphere/azure providers
  packages/tkg-clusterclass-azure/bundle/config/values.yaml
  packages/tkg-clusterclass-vsphere/bundle/config/values.yaml
Labels: ok-to-merge, cla-not-required

#4176 use ALLOW_LEGACY_CLUSTER to judge create legacy or classy cluster
  tkg/client/cluster.go
  tkg/client/cluster_test.go
  tkg/client/common.go
Labels: ok-to-merge, cla-not-required

#4226 Add proxy to tkrservice package
  packages/framework/bundle/config/values.yaml
  packages/tkg/bundle/config/values.yaml
  packages/tkr-vsphere-resolver/bundle/config/overlays/overlay-tkr-vsphere-resolver-cluster-webhook-deployment.yaml
  packages/tkr-vsphere-resolver/bundle/config/upstream/tkr-vsphere-resolver-cluster-webhook-deployment.yaml
  packages/tkr-vsphere-resolver/bundle/config/values.yaml
  tkg/managementcomponents/helper.go
  tkg/managementcomponents/test/output_vsphere_with_custom_repo_ca.yaml
  tkg/managementcomponents/test/output_vsphere_with_custom_repo_ca_rw.yaml
  tkg/managementcomponents/test/output_vsphere_with_proxy.yaml
  tkg/managementcomponents/types.go
Labels: ok-to-merge, cla-not-required

#4230 drop ligatures from various manifests
  packages/tkg-clusterclass-aws/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-azure/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-docker/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-oci/bundle/config/upstream/base.yaml
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  providers/infrastructure-aws/v2.0.2/cconly/base.yaml
  providers/infrastructure-azure/v1.5.3/cconly/base.yaml
  providers/infrastructure-docker/v1.2.8/cconly/base.yaml
  providers/infrastructure-oci/v0.4.0/cconly/base.yaml
  providers/infrastructure-vsphere/v1.5.1/cconly/base.yaml
Labels: ok-to-merge, cla-not-required

#4220 delete in-tree sc && infraProvider is empty package will not raise error
  packages/tkg-storageclass/bundle/config/upstream/base.yaml
  packages/tkg-storageclass/bundle/config/values.yaml
  packages/tkg-storageclass/package.yaml
  providers/yttcb/clusterbootstrap.yaml
Labels: ok-to-merge, cla-not-required

#4236 remove legacy tkr label from yttcc overlay
  providers/infrastructure-azure/v1.5.3/yttcc/overlay.yaml
  providers/infrastructure-oci/v0.4.0/yttcc/overlay.yaml
Labels: ok-to-merge, cla-not-required

#4232 Skip CLIPlugin CRD installation as part of core-management-plugins package
  tkg/managementcomponents/helper.go
Labels: ok-to-merge, cla-not-required

#4234 Parse insecure flag from cluster.tlsThumbprint
  tkg/constants/clusterclass_mapping.go
  tkg/fakes/config/cluster_vsphere_insecure.yaml
  tkg/tkgctl/create_cluster_test.go
  tkg/tkgctl/helpers.go
Labels: ok-to-merge, cla-not-required

#4228 Fix the certificate processing for clusterclass
  tkg/constants/clusterclass_mapping.go
  tkg/fakes/config/cluster_aws.yaml
  tkg/fakes/config/cluster_aws_incorrectClass.yaml
  tkg/fakes/config/cluster_aws_multipleObjects.yaml
  tkg/fakes/config/cluster_azure.yaml
  tkg/fakes/config/cluster_vsphere.yaml
  tkg/tkgctl/helpers.go
Labels: ok-to-merge, cla-not-required

#4246 Fix upgrade version check to allow 1.6.x to 2.x.x
  tkg/client/upgrade_region.go
  tkg/client/upgrade_region_test.go
Labels: area/cli, kind/bug, ok-to-merge, cla-not-required, area/lcm

#4248 Fix the trust format in cluster_vsphere_insecure
  tkg/fakes/config/cluster_vsphere_insecure.yaml
Labels: ok-to-merge, cla-not-required

#4243 refactor retrying code on azure upgrade and create
  tkg/clusterclient/clusterclient.go
  tkg/clusterclient/clusterclient_test.go
Labels: ok-to-merge, cla-not-required

#4235 Fix ako addon secret name when deleting cc management cluster
  tkg/client/delete_region.go
Labels: ok-to-merge, cla-not-required

#4247 Fix addons controller crd waiter bug
  addons/controllers/addon_controller.go
  addons/controllers/suite_test.go
  addons/main.go
  addons/pkg/crdwait/crd_wait.go
  addons/pkg/crdwait/crd_wait_test.go
Labels: ok-to-merge, cla-not-required

#4256 tanzu isolated cluster plugin was pushing the images with different f…
  cmd/cli/plugin/isolated-cluster/imagepullop/publishimagestotar.go
Labels: ok-to-merge, cla-not-required

#4249 bump kctrl in package plugin
  cmd/cli/plugin/package/go.mod
  cmd/cli/plugin/package/go.sum
Labels: ok-to-merge, cla-not-required

#4253 Install CLIPlugin CRD through core-management-plugins package
  packages/cliplugins/bundle/config/cliplugin-crd.yaml
  packages/cliplugins/bundle/config/values.yaml
  packages/cliplugins/package.yaml
  packages/core-management-plugins/bundle/config/cliplugin-crd.yaml
  packages/framework/bundle/config/packageinstalls/cliplugins-pi.yaml
  packages/tkg/bundle/config/packageinstalls/core-management-plugins-pi.yaml
  packages/tkg/bundle/config/values.yaml
  tkg/managementcomponents/helper.go
  tkg/managementcomponents/types.go
Labels: kind/bug, ok-to-merge, cla-not-required

#4245 Trim input values for `tanzu context create`
  cli/core/pkg/command/context.go
  cli/runtime/component/prompt.go
  cmd/cli/plugin/login/main.go
Labels: ok-to-merge, cla-not-required

#4261 Add avi related namespace to skipping list of installing CC
  packages/tkg-clusterclass/bundle/config/object-propagation/deployment.yaml
Labels: ok-to-merge, cla-not-required

#4240 Topic/m1zzx2/storageclass 3
  packages/tkg-storageclass/bundle/config/upstream/base.yaml
  packages/tkg-storageclass/bundle/config/values.yaml
  packages/tkg-storageclass/metadata.yaml
  providers/yttcb/clusterbootstrap.yaml
  tkg/test/tkgctl/shared/e2e_common_cc.go
  tkg/test/tkgctl/shared/package.go
Labels: ok-to-merge, cla-not-required

#4267 TKR Source Controller: Resolve images in TKR package repo bundle
  tkr/controller/tkr-source/fetcher/fetcher.go
  tkr/controller/tkr-source/imgpkgutil/imgpkgutil.go
  tkr/controller/tkr-source/imgpkgutil/imgpkgutil_test.go
  tkr/controller/tkr-source/pkgcr/reconciler.go
Labels: ok-to-merge, cla-not-required, area/tkr

#4255 Bump CAPZ version to v1.6.1
  addons/controllers/testdata/test-cluster-metadata.yaml
  addons/go.mod
  addons/go.sum
  cmd/cli/plugin/cluster/go.mod
  cmd/cli/plugin/cluster/go.sum
  cmd/cli/plugin/isolated-cluster/go.sum
  cmd/cli/plugin/managementcluster/go.mod
  cmd/cli/plugin/managementcluster/go.sum
  cmd/cli/plugin/package/go.mod
  cmd/cli/plugin/package/go.sum
  go.mod
  go.sum
  hack/providers-sync-tools/cluster-api-provider-azure/overlay/add-tolerations.yaml
  packages/cluster-api-provider-azure/bundle/config/upstream/infrastructure-components.yaml
  packages/cluster-api-provider-azure/bundle/config/upstream/metadata.yaml
  packages/cluster-api-provider-azure/vendir.lock.yml
  packages/cluster-api-provider-azure/vendir.yml
  packages/tkg-clusterclass-docker/bundle/config/upstream/overlay-pod-security-admission.yaml
  providers/config.yaml
  providers/infrastructure-azure/v1.6.1/cconly/base.yaml
  providers/infrastructure-azure/v1.6.1/cconly/overlay-kube-apiserver-admission.yaml
  providers/infrastructure-azure/v1.6.1/cconly/overlay.yaml
  providers/infrastructure-azure/v1.6.1/cluster-template-definition-dev.yaml
  providers/infrastructure-azure/v1.6.1/cluster-template-definition-devcc.yaml
  providers/infrastructure-azure/v1.6.1/cluster-template-definition-prod.yaml
  providers/infrastructure-azure/v1.6.1/cluster-template-definition-prodcc.yaml
  providers/infrastructure-azure/v1.6.1/clusterclass-tkg-azure-default.yaml
  providers/infrastructure-azure/v1.6.1/infrastructure-components.yaml
  providers/infrastructure-azure/v1.6.1/metadata.yaml
  providers/infrastructure-azure/v1.6.1/ytt/base-template.yaml
  providers/infrastructure-azure/v1.6.1/ytt/overlay.yaml
  providers/infrastructure-azure/v1.6.1/yttcc/base-template.yaml
  providers/infrastructure-azure/v1.6.1/yttcc/overlay.yaml
  tkg/go.mod
  tkg/go.sum
Labels: ok-to-merge, cla-not-required

#4271 TKR Resolver: exact TKR version match (if exists) should be the only result
  tkr/resolver/internal/resolver_impl.go
  tkr/resolver/internal/resolver_impl_test.go
Labels: ok-to-merge, cla-not-required, area/tkr

#4272 fix issue with querying for GVR in capabilities discovery package
  capabilities/client/pkg/discovery/cluster_gvr.go
Labels: ok-to-merge, cla-not-required

#4274 Adds apiextension rules to tanzu-addons-manager-clusterrole
  packages/addons-manager/bundle/config/upstream/addons-manager.yaml
Labels: ok-to-merge, cla-not-required

#4277 Revert "Fix addons controller crd waiter bug (#4247)"
  addons/controllers/addon_controller.go
  addons/controllers/suite_test.go
  addons/main.go
  addons/pkg/crdwait/crd_wait.go
  addons/pkg/crdwait/crd_wait_test.go
Labels: ok-to-merge, cla-not-required

#4276 Revert "VSphere Cluster CC/Template: Use local_hostname instead of FQDN for node name (#3926)
  cmd/cli/plugin-admin/builder/command/cli_compile.go
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  providers/infrastructure-vsphere/v1.5.1/cconly/base.yaml
  providers/infrastructure-vsphere/v1.5.1/ytt/base-template.yaml
  providers/tests/unit/ip_family_test.go
Labels: cla-not-required

#4275 remove secretgen-controller namespace to the skipping list of installing CC
  packages/tkg-clusterclass/bundle/config/object-propagation/deployment.yaml
Labels: ok-to-merge, cla-not-required

#4278 TKR Source Controller: Airgap Image Resolution Fix
  tkr/controller/tkr-source/fetcher/fetcher.go
  tkr/controller/tkr-source/imgpkgutil/imgpkgutil.go
  tkr/controller/tkr-source/imgpkgutil/imgpkgutil_test.go
  tkr/controller/tkr-source/pkgcr/reconciler.go
Labels: ok-to-merge, cla-not-required, area/tkr

#4280 fix azure credential updating
  tkg/client/update_credentials.go
  tkg/clusterclient/clusterclient.go
  tkg/clusterclient/clusterclient_test.go
  tkg/clusterclient/credentials.go
  tkg/fakes/clusterclient.go
Labels: ok-to-merge, cla-not-required

#4282 Fix vSphere OSImage labeling
  tkr/util/osimage/osimage.go
  tkr/webhook/cluster/tkr-resolver/cluster/cluster_test.go
Labels: ok-to-merge, cla-not-required, area/tkr

#4283 Handle TKR package bundleImage being a `@sha:<hash>` image itself
  tkr/controller/tkr-source/imgpkgutil/imgpkgutil.go
  tkr/controller/tkr-source/imgpkgutil/imgpkgutil_test.go
Labels: ok-to-merge, cla-not-required, area/tkr

#4279 Fix issue that upgrading legacy cluster by latest cli will fail if audit is enabled
  tkg/client/audit_upgrade_helper.go
  tkg/client/audit_upgrade_helper_test.go
  tkg/client/upgrade_cluster.go
Labels: ok-to-merge, cla-not-required

#4263 Update BOM retrieval version to v0.28.0
  tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#4294 Update BOM retrieval version to v0.29.0-dev
  tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#4269 Adding cni from vars on vsphere template
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  providers/infrastructure-vsphere/v1.5.1/cconly/base.yaml
  providers/infrastructure-vsphere/v1.5.1/yttcc/overlay.yaml
Labels: ok-to-merge, cla-not-required

#4160 Adds/removes finalizer from legacy cluster
  addons/controllers/addon_controller.go
  addons/controllers/addon_controller_test.go
  addons/controllers/testdata/test-management-finalizer.yaml
  addons/controllers/testdata/test-workload-finalizer.yaml
Labels: ok-to-merge, cla-not-required

#4296 Update the image path of kube-vip
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  providers/infrastructure-vsphere/v1.5.1/cconly/base.yaml
Labels: ok-to-merge, cla-not-required

#4297 Cherry pick #4296 into G.0 release-0.28 branch
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  providers/infrastructure-vsphere/v1.5.1/cconly/base.yaml
Labels: ok-to-merge, cla-not-required

#4023 ignore dns servers from dhcp when providing nameservers
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  providers/infrastructure-vsphere/v1.5.1/cconly/base.yaml
Labels: ok-to-merge, cla-not-required

#4264 Enable custom cni provider support for classy clusters
  addons/controllers/clusterbootstrap_controller.go
  addons/pkg/constants/constants.go
  addons/pkg/util/clusterbootstrapclone/clusterbootstrapclone.go
  addons/webhooks/clusterbootstrap_webhook.go
  addons/webhooks/clusterbootstrap_webhook_test.go
  addons/webhooks/webhooks_suite_test.go
  providers/yttcb/clusterbootstrap.yaml
Labels: ok-to-merge, cla-not-required

#4288 Installer UI - Fix Dependabot alert #150 JSON5 prototype pollution
  tkg/web/package-lock.json
Labels: ok-to-merge, cla-not-required

#4300 Cherry pick #4264 into G.0 release-0.28 branch
  addons/controllers/clusterbootstrap_controller.go
  addons/pkg/constants/constants.go
  addons/pkg/util/clusterbootstrapclone/clusterbootstrapclone.go
  addons/webhooks/clusterbootstrap_webhook.go
  addons/webhooks/clusterbootstrap_webhook_test.go
  addons/webhooks/webhooks_suite_test.go
  providers/yttcb/clusterbootstrap.yaml
Labels: ok-to-merge, cla-not-required

#4309 Cherry pick #4269 - Adding cni from vars on vSphere template
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  providers/infrastructure-vsphere/v1.5.1/cconly/base.yaml
  providers/infrastructure-vsphere/v1.5.1/yttcc/overlay.yaml
Labels: ok-to-merge, cla-not-required

#4301 Cherry pick #4160 into G.0 release-0.28 branch
  addons/controllers/addon_controller.go
  addons/controllers/addon_controller_test.go
  addons/controllers/testdata/test-management-finalizer.yaml
  addons/controllers/testdata/test-workload-finalizer.yaml
Labels: ok-to-merge, cla-not-required

#4308 Installer UI - Fix dependabot alert #155
  tkg/web/package-lock.json
  tkg/web/package.json
Labels: ok-to-merge, cla-not-required
