Repository vmware-tanzu/tanzu-framework, pull requests merged in 2023-04, with the labels that each got.

#4538 Change image path in ako-operator-v2 package
  packages/ako-operator-v2/kbld-config.yaml
Labels: ok-to-merge, cla-not-required

#4535 add infrastructure-ipam-in-cluster parts to include it during management cluster upgrades
  tkg/tkgconfigbom/bom.go
  tkg/tkgconfigbom/bom_test.go
  tkg/tkgconfigupdater/images.go
Labels: ok-to-merge, cla-not-required

#4537 syntax tag should be at beginning of dockerfile
  addons/Dockerfile
  addons/manifests/samples/simple-app/Dockerfile
  capabilities/controller/Dockerfile
  featuregates/controller/Dockerfile
  object-propagation/Dockerfile
  pinniped-components/post-deploy/Dockerfile
  pinniped-components/tanzu-auth-controller-manager/Dockerfile
  pkg/v1/tkr/Dockerfile
  tkg/vsphere-template-resolver/Dockerfile
  tkr/controller/tkr-source/Dockerfile
  tkr/controller/tkr-status/Dockerfile
  tkr/webhook/cluster/tkr-resolver/Dockerfile
  tkr/webhook/tkr-conversion/Dockerfile
Labels: ok-to-merge, cla-not-required

#4547 Fix apigroups for volumesnapshots psa RBAC
  addons/controllers/csi/vspherecsiconfig_controller.go
  packages/addons-manager/bundle/config/upstream/addons-manager.yaml
Labels: ok-to-merge, cla-not-required

#4550 update antreaConfig crd as some new members are added to CRD
  addons/controllers/antrea/antreaconfig_util.go
  addons/controllers/antreaconfig_controller_test.go
  addons/controllers/testdata/antrea-custom-cb-2-resources.yaml
  addons/controllers/testdata/antrea-custom-tkg-system.yaml
  addons/controllers/testdata/antrea-test-1.yaml
  addons/controllers/testdata/antrea-test-template-config-1.yaml
  addons/controllers/testdata/test-cluster-bootstrap-10.yaml
  addons/controllers/testdata/test-cluster-bootstrap-2.yaml
  addons/controllers/testdata/test-cluster-bootstrap-3.yaml
  addons/controllers/testdata/test-cluster-bootstrap-7.yaml
  addons/controllers/testdata/test-cluster-bootstrap-8.yaml
  addons/controllers/testdata/test-cluster-bootstrap-9.yaml
  addons/controllers/testdata/test-packageinstallstatus.yaml
  addons/controllers/testdata/test-tkg-system-ns-resources.yaml
  apis/addonconfigs/config/crd/bases/cni.tanzu.vmware.com_antreaconfigs.yaml
  packages/addons-manager/bundle/config/upstream/addonconfigscrds/cni.tanzu.vmware.com_antreaconfigs.yaml
Labels: ok-to-merge, cla-not-required

#4555 Add missing labels for antreaconfig from clusterbootstrap
  addons/controllers/calicoconfig_controller_test.go
  addons/controllers/clusterbootstrap_controller.go
  addons/pkg/util/clusterbootstrapclone/clusterbootstrapclone.go
Labels: ok-to-merge, cla-not-required

#4549 Fix Docker related CVEs
  cli/core/go.mod
  cli/core/go.sum
  cmd/cli/plugin-admin/builder/go.mod
  cmd/cli/plugin-admin/builder/go.sum
  cmd/cli/plugin-admin/test/go.mod
  cmd/cli/plugin-admin/test/go.sum
  cmd/cli/plugin/cluster/go.mod
  cmd/cli/plugin/cluster/go.sum
  cmd/cli/plugin/isolated-cluster/go.mod
  cmd/cli/plugin/isolated-cluster/go.sum
  cmd/cli/plugin/login/go.mod
  cmd/cli/plugin/login/go.sum
  cmd/cli/plugin/managementcluster/go.mod
  cmd/cli/plugin/managementcluster/go.sum
  cmd/cli/plugin/package/go.mod
  cmd/cli/plugin/package/go.sum
  go.mod
  go.sum
  pkg/v1/tkr/go.mod
  pkg/v1/tkr/go.sum
  tkg/go.mod
  tkg/go.sum
  tkr/go.mod
  tkr/go.sum
Labels: ok-to-merge, cla-not-required

#4566 pinniped-components: fix make target and Dockerfile
  pinniped-components/post-deploy/Dockerfile
  pinniped-components/post-deploy/Makefile
Labels: ok-to-merge, cla-not-required

#4564 Add project structure for readiness APIs
  PROJECT
  apis/core/config/crd/bases/core.tanzu.vmware.com_readinesses.yaml
  apis/core/v1alpha2/readiness_types.go
  apis/core/v1alpha2/zz_generated.deepcopy.go
  build-tooling.mk
  go.mod
  readiness/client/go.mod
  readiness/client/pkg/readinessclient/doc.go
  readiness/controller/go.mod
  readiness/controller/go.sum
  readiness/controller/main.go
  readiness/controller/pkg/readiness/doc.go
  readiness/controller/pkg/readiness/readiness_controller.go
  readiness/controller/pkg/readiness/suite_test.go
Labels: area/api, kind/feature, kind/api-change, cla-not-required

#4573 fixed dependabot issue for xml2js
  tkg/web/package-lock.json
  tkg/web/package.json
Labels: ok-to-merge, cla-not-required

#4567 Adding readiness and readiness provider types
  PROJECT
  apis/core/config/crd/bases/core.tanzu.vmware.com_readinesses.yaml
  apis/core/config/crd/bases/core.tanzu.vmware.com_readinessproviders.yaml
  apis/core/v1alpha2/readiness_types.go
  apis/core/v1alpha2/readinessprovider_types.go
  apis/core/v1alpha2/zz_generated.deepcopy.go
Labels: cla-not-required

#4577 Adjust telemetry manifests to comply with restricted PSA policy
  tkg/manifest/telemetry/config-aws.yaml
  tkg/manifest/telemetry/config-azure.yaml
  tkg/manifest/telemetry/config-docker.yaml
  tkg/manifest/telemetry/config-vsphere.yaml
Labels: ok-to-merge, cla-not-required

#4552 Replace references to deprecated autoscaling APIs in Capabilities tests
  capabilities/client/pkg/discovery/cluster_test.go
Labels: ok-to-merge, cla-not-required

#4569 Add webhook certificate manager package to utils and use it for Featuregates controller
  capabilities/controller/go.mod
  capabilities/controller/go.sum
  featuregates/client/go.mod
  featuregates/client/go.sum
  featuregates/controller/go.mod
  featuregates/controller/go.sum
  featuregates/controller/main.go
  packages/featuregates/bundle/config/upstream/certificates.yaml
  packages/featuregates/bundle/config/upstream/rbac.yaml
  packages/featuregates/bundle/config/upstream/tanzu-featuregates-manager.yaml
  packages/featuregates/bundle/config/upstream/webhook-secret.yaml
  packages/featuregates/bundle/config/upstream/webhooks/config/webhook.yaml
  packages/featuregates/bundle/config/upstream/webhooks/core/webhook.yaml
  packages/featuregates/vendir.lock.yml
  packages/featuregates/vendir.yml
  util/go.mod
  util/go.sum
  util/webhook/certs/README.md
  util/webhook/certs/certmanager.go
  util/webhook/certs/certmanager_suite_test.go
  util/webhook/certs/certmanager_test.go
  util/webhook/certs/constants.go
  util/webhook/certs/doc.go
  util/webhook/certs/options.go
Labels: ok-to-merge, cla-not-required

#4579 change antreaConfig APIversion back to v1alpha1
  addons/controllers/antrea/antreaconfig_controller.go
  addons/controllers/antrea/antreaconfig_util.go
  addons/controllers/antreaconfig_controller_test.go
  addons/controllers/clusterbootstrap_controller_test.go
  addons/controllers/suite_test.go
  addons/controllers/testdata/antrea-custom-cb-2-resources.yaml
  addons/controllers/testdata/antrea-custom-tkg-system.yaml
  addons/controllers/testdata/antrea-test-2.yaml
  addons/controllers/testdata/antrea-test-template-config-1.yaml
  addons/controllers/testdata/test-cluster-bootstrap-10.yaml
  addons/controllers/testdata/test-cluster-bootstrap-2.yaml
  addons/controllers/testdata/test-cluster-bootstrap-3.yaml
  addons/controllers/testdata/test-cluster-bootstrap-7.yaml
  addons/controllers/testdata/test-cluster-bootstrap-8.yaml
  addons/controllers/testdata/test-cluster-bootstrap-9.yaml
  addons/controllers/testdata/test-packageinstallstatus.yaml
  addons/controllers/testdata/test-tkg-system-ns-resources.yaml
  addons/main.go
  addons/pkg/constants/constants.go
  addons/pkg/util/clusterbootstrapclone/clusterbootstrapclone_test.go
  addons/predicates/addon_config_test.go
  apis/addonconfigs/cni/v1alpha1/antreaconfig_types.go
  apis/addonconfigs/cni/v1alpha1/antreaconfig_webhook.go
  apis/addonconfigs/cni/v1alpha1/zz_generated.deepcopy.go
  apis/addonconfigs/cni/v1alpha2/antreaconfig_types.go
  apis/addonconfigs/cni/v1alpha2/antreaconfig_webhook.go
  apis/addonconfigs/cni/v1alpha2/groupversion_info.go
  apis/addonconfigs/cni/v1alpha2/zz_generated.deepcopy.go
  apis/addonconfigs/config/crd/bases/cni.tanzu.vmware.com_antreaconfigs.yaml
  packages/addons-manager/bundle/config/upstream/addonconfigscrds/cni.tanzu.vmware.com_antreaconfigs.yaml
  tkg/manifest/telemetry/zz_generated.bindata.go
Labels: ok-to-merge, cla-not-required

#4576 Initialize readiness package
  docs/packages/dev-workflow.md
  packages/package-values.yaml
  packages/readiness/Makefile
  packages/readiness/README.md
  packages/readiness/bundle/config/upstream/crds/core/core.tanzu.vmware.com_readinesses.yaml
  packages/readiness/bundle/config/upstream/crds/core/core.tanzu.vmware.com_readinessproviders.yaml
  packages/readiness/bundle/config/upstream/rbac.yaml
  packages/readiness/bundle/config/upstream/tanzu-readiness-manager.yaml
  packages/readiness/bundle/config/values.yaml
  packages/readiness/kbld-config.yaml
  packages/readiness/metadata.yaml
  packages/readiness/package.yaml
  packages/readiness/vendir.lock.yml
  packages/readiness/vendir.yml
Labels: area/docs, kind/feature, kind/documentation, ok-to-merge, cla-not-required, area/packages

#4582 Readiness controller re-conciliation
  apis/core/config/crd/bases/core.tanzu.vmware.com_readinesses.yaml
  apis/core/v1alpha2/readiness_types.go
  apis/core/v1alpha2/zz_generated.deepcopy.go
  readiness/controller/Makefile
  readiness/controller/go.mod
  readiness/controller/go.sum
  readiness/controller/main.go
  readiness/controller/pkg/readiness/readiness_controller.go
  readiness/controller/pkg/readiness/suite_test.go
Labels: cla-not-required

#4589 isolated-cluster plugin FIPS build support
  cmd/cli/plugin/isolated-cluster/imagepullop/publishimagestotar.go
Labels: ok-to-merge, cla-not-required

#4585 isolated-cluster plugin FIPS build support
  cmd/cli/plugin/isolated-cluster/imagepullop/publishimagestotar.go
Labels: ok-to-merge, cla-not-required

#4591 isolated-cluster plugin FIPS build support
  cmd/cli/plugin/isolated-cluster/imagepullop/publishimagestotar.go
Labels: ok-to-merge, cla-not-required

#4593 generate telemetry bindata
  tkg/manifest/telemetry/zz_generated.bindata.go
Labels: ok-to-merge, cla-not-required

#4592 ReadinessProvider reconcilitation implementation
  apis/core/config/crd/bases/core.tanzu.vmware.com_readinessproviders.yaml
  apis/core/v1alpha2/readinessprovider_types.go
  apis/core/v1alpha2/zz_generated.deepcopy.go
  packages/readiness/bundle/config/upstream/crds/core/core.tanzu.vmware.com_readinesses.yaml
  packages/readiness/bundle/config/upstream/crds/core/core.tanzu.vmware.com_readinessproviders.yaml
  readiness/controller/main.go
  readiness/controller/pkg/conditions/doc.go
  readiness/controller/pkg/conditions/resourceexistencecondition.go
  readiness/controller/pkg/conditions/resourceexistencecondition_test.go
  readiness/controller/pkg/constants/constants.go
  readiness/controller/pkg/readiness/suite_test.go
  readiness/controller/pkg/readinessprovider/doc.go
  readiness/controller/pkg/readinessprovider/readinessprovider_controller.go
  readiness/controller/pkg/readinessprovider/suite_test.go
Labels: cla-not-required

#4605 Update BOM retrieval version to v0.29.0
  tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: ok-to-merge, cla-not-required
