Repository vmware-tanzu/tanzu-framework, pull requests merged in 2023-02, with the labels that each got.

#4306 raise error for tkr controller if image path is empty
  tkr/controller/tkr-source/main.go
Labels: ok-to-merge, cla-not-required

#4298 Populate all imageRepository fields in TKR_DATA values
  tkr/webhook/cluster/tkr-resolver/cluster/cluster.go
  tkr/webhook/cluster/tkr-resolver/cluster/cluster_test.go
Labels: ok-to-merge, cla-not-required, area/tkr

#4321 raise error for tkr controller if image path is empty (cherry-pick #4306)
  tkr/controller/tkr-source/main.go
Labels: ok-to-merge, cla-not-required

#4316 [tanzu cli] use tkrVersion in topology.version for cc clusters
  providers/infrastructure-aws/v2.0.2/yttcc/overlay.yaml
  providers/infrastructure-azure/v1.6.1/yttcc/overlay.yaml
  providers/infrastructure-oci/v0.4.0/yttcc/overlay.yaml
  providers/infrastructure-vsphere/v1.5.1/yttcc/overlay.yaml
  tkg/client/upgrade_cluster_clusterclass.go
  tkg/client/upgrade_cluster_test.go
  tkg/tkgctl/upgrade_cluster.go
Labels: ok-to-merge, cla-not-required

#4323 Set node-ip in /etc/hosts instead of node-ip flag
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  providers/infrastructure-vsphere/v1.5.1/cconly/base.yaml
  providers/infrastructure-vsphere/v1.5.1/ytt/overlay.yaml
  providers/tests/unit/ip_family_test.go
Labels: ok-to-merge, cla-not-required

#4332 Update BOM retrieval BOM version to v0.28.1-dev
  tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: area/release, ok-to-merge, cla-not-required

#4313 enable delete of cluster when tkr is not present on supervisor
  addons/controllers/cluster_metadata_controller.go
  addons/controllers/clusterbootstrap_controller.go
  addons/controllers/packageinstallstatus_controller.go
  addons/pkg/constants/constants.go
  addons/pkg/util/tkr_util.go
  addons/pkg/util/tkr_util_test.go
Labels: ok-to-merge, cla-not-required

#4331 [tanzu cli] use tkrVersion in topology.version for cc clusters (#4316) (cherry-pick #4316 from main)
  providers/infrastructure-aws/v2.0.2/yttcc/overlay.yaml
  providers/infrastructure-azure/v1.6.1/yttcc/overlay.yaml
  providers/infrastructure-oci/v0.4.0/yttcc/overlay.yaml
  providers/infrastructure-vsphere/v1.5.1/yttcc/overlay.yaml
  tkg/client/upgrade_cluster_clusterclass.go
  tkg/client/upgrade_cluster_test.go
  tkg/tkgctl/upgrade_cluster.go
Labels: ok-to-merge, cla-not-required

#4273 Azure Omnibus Bug Fixes
  packages/tkg-clusterclass-azure/bundle/config/upstream/base.yaml
  providers/infrastructure-azure/v1.6.1/cconly/base.yaml
  providers/infrastructure-azure/v1.6.1/ytt/base-template.yaml
  providers/infrastructure-azure/v1.6.1/ytt/overlay.yaml
  providers/infrastructure-azure/v1.6.1/yttcc/overlay.yaml
Labels: ok-to-merge, cla-not-required

#4335 [cherry-pick: release-0.28] adds code to fetch TKR from annotation on cluster when TKR is no longer available on supervisor
  addons/controllers/cluster_metadata_controller.go
  addons/controllers/clusterbootstrap_controller.go
  addons/controllers/packageinstallstatus_controller.go
  addons/pkg/constants/constants.go
  addons/pkg/util/tkr_util.go
  addons/pkg/util/tkr_util_test.go
Labels: ok-to-merge, cla-not-required

#4325 Support specify maxUnhealthy of MachineHealthCheck
  packages/tkg-clusterclass-aws/bundle/config/upstream/overlay.yaml
  packages/tkg-clusterclass-aws/bundle/config/values.yaml
  packages/tkg-clusterclass-azure/bundle/config/upstream/overlay.yaml
  packages/tkg-clusterclass-azure/bundle/config/values.yaml
  packages/tkg-clusterclass-docker/bundle/config/upstream/overlay.yaml
  packages/tkg-clusterclass-docker/bundle/config/values.yaml
  packages/tkg-clusterclass-oci/bundle/config/upstream/overlay.yaml
  packages/tkg-clusterclass-oci/bundle/config/values.yaml
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/overlay.yaml
  packages/tkg-clusterclass-vsphere/bundle/config/values.yaml
  providers/config_default.yaml
  providers/infrastructure-aws/v2.0.2/cconly/overlay.yaml
  providers/infrastructure-azure/v1.6.1/cconly/overlay.yaml
  providers/infrastructure-docker/v1.2.8/cconly/overlay.yaml
  providers/infrastructure-oci/v0.4.0/cconly/overlay.yaml
  providers/infrastructure-vsphere/v1.5.1/cconly/overlay.yaml
  providers/yttcc/lib/config_variable_association.star
Labels: ok-to-merge, cla-not-required

#4291 Ensure legacy cluster upgrade does not overwrite kube-apiserver admission-control-config-file flag
  tkg/client/admission_upgrade_helper.go
  tkg/client/admission_upgrade_helper_test.go
Labels: ok-to-merge, cla-not-required, area/lcm

#4347 Cherry-pick Azure Omnibus Bug Fixes (#4273)
  packages/tkg-clusterclass-azure/bundle/config/upstream/base.yaml
  providers/infrastructure-azure/v1.6.1/cconly/base.yaml
  providers/infrastructure-azure/v1.6.1/ytt/base-template.yaml
  providers/infrastructure-azure/v1.6.1/ytt/overlay.yaml
  providers/infrastructure-azure/v1.6.1/yttcc/overlay.yaml
Labels: ok-to-merge, cla-not-required

#4319 Cherry-Pick #4291 - Ensure legacy cluster upgrade does not overwrite kube-apiserver admission-control-config-file flag
  tkg/client/admission_upgrade_helper.go
  tkg/client/admission_upgrade_helper_test.go
Labels: ok-to-merge, cla-not-required, area/lcm

#4334 Fix avi resources clean up issue when management cluster creation fails
  tkg/client/delete_region.go
Labels: ok-to-merge, cla-not-required

#4338 Check AVI controller version is supported or not before management cluster creation or upgrade
  tkg/avi/client.go
  tkg/client/upgrade_region.go
  tkg/utils/common.go
  tkg/utils/common_test.go
Labels: ok-to-merge, cla-not-required, cherry-pick/release-0.28

#4314 Fix the logic to upgrade kube-vip image during cluster upgrade
  tkg/client/client_suite_test.go
  tkg/client/kubevip_update_helper.go
  tkg/client/upgrade_cluster.go
  tkg/client/upgrade_cluster_test.go
Labels: ok-to-merge, cla-not-required, cherry-pick/release-0.28

#4333 change the capabilities deployment update strategy to fallback-on-replace
  packages/capabilities/bundle/config/upstream/tanzu-capabilities-controller-manager.yaml
Labels: ok-to-merge, cla-not-required, cherry-pick/release-0.28

#4353 [0.28 Cherrypick] validate avi controller version before management cluster creation an…
  tkg/avi/client.go
  tkg/client/upgrade_region.go
  tkg/utils/common.go
  tkg/utils/common_test.go
Labels: ok-to-merge, cla-not-required

#4352 [0.28 cherrypick] cleanup avi
  tkg/client/delete_region.go
Labels: ok-to-merge, cla-not-required

#4354 [0.28 cherrypick] fix upgrade kube vip
  tkg/client/client_suite_test.go
  tkg/client/kubevip_update_helper.go
  tkg/client/upgrade_cluster.go
  tkg/client/upgrade_cluster_test.go
Labels: ok-to-merge, cla-not-required

#4345 support configuring system wide proxy for vsphere
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  providers/config_default.yaml
  providers/infrastructure-vsphere/v1.5.1/cconly/base.yaml
  providers/tests/clustergen/param_models/cluster_optional.model
  providers/yttcc/lib/config_variable_association.star
  tkg/constants/clusterclass_mapping.go
  tkg/constants/config_variables.go
Labels: ok-to-merge, cla-not-required, cherry-pick/release-0.28

#4357 [0.28 Cherry pick] Add option to trust custom tdnf repository's cert (#4344)
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  providers/config_default.yaml
  providers/infrastructure-vsphere/v1.5.1/cconly/base.yaml
  providers/infrastructure-vsphere/v1.5.1/yttcc/overlay.yaml
  providers/tests/clustergen/param_models/cluster_optional.model
  providers/yttcc/lib/config_variable_association.star
  tkg/constants/clusterclass_mapping.go
  tkg/constants/config_variables.go
Labels: ok-to-merge, cla-not-required

#4360 Revert "validate avi controller version before management cluster creation and upgrade (#4353)" on release-0.28
  tkg/avi/client.go
  tkg/client/upgrade_region.go
  tkg/utils/common.go
  tkg/utils/common_test.go
Labels: ok-to-merge, cla-not-required

#4336 Add version check for antrea config fields marshal
  addons/controllers/antrea/antreaconfig_controller.go
  addons/controllers/antrea/antreaconfig_util.go
  addons/controllers/antreaconfig_controller_test.go
  addons/controllers/testdata/antrea-test-1.yaml
  addons/controllers/testdata/test-cluster-1.yaml
  addons/controllers/testdata/test-cluster-2.yaml
  addons/controllers/testdata/test-cluster-3.yaml
  addons/go.mod
Labels: ok-to-merge, cla-not-required

#4348 Support specify maxUnhealthy of MachineHealthCheck (#4325)
  packages/tkg-clusterclass-aws/bundle/config/upstream/overlay.yaml
  packages/tkg-clusterclass-aws/bundle/config/values.yaml
  packages/tkg-clusterclass-azure/bundle/config/upstream/overlay.yaml
  packages/tkg-clusterclass-azure/bundle/config/values.yaml
  packages/tkg-clusterclass-docker/bundle/config/upstream/overlay.yaml
  packages/tkg-clusterclass-docker/bundle/config/values.yaml
  packages/tkg-clusterclass-oci/bundle/config/upstream/overlay.yaml
  packages/tkg-clusterclass-oci/bundle/config/values.yaml
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/overlay.yaml
  packages/tkg-clusterclass-vsphere/bundle/config/values.yaml
  providers/config_default.yaml
  providers/infrastructure-aws/v2.0.2/cconly/overlay.yaml
  providers/infrastructure-azure/v1.6.1/cconly/overlay.yaml
  providers/infrastructure-docker/v1.2.8/cconly/overlay.yaml
  providers/infrastructure-oci/v0.4.0/cconly/overlay.yaml
  providers/infrastructure-vsphere/v1.5.1/cconly/overlay.yaml
  providers/yttcc/lib/config_variable_association.star
Labels: ok-to-merge, cla-not-required

#4359 [Cherry Pick] system wide proxy configure
  packages/tkg-clusterclass-vsphere/bundle/config/upstream/base.yaml
  providers/config_default.yaml
  providers/infrastructure-vsphere/v1.5.1/cconly/base.yaml
  providers/tests/clustergen/param_models/cluster_optional.model
  providers/yttcc/lib/config_variable_association.star
  tkg/constants/clusterclass_mapping.go
  tkg/constants/config_variables.go
Labels: ok-to-merge, cla-not-required

#4365 raise timeout for tkr-vsphere-resolver webhook
  packages/tkr-vsphere-resolver/bundle/config/upstream/webhook.yaml
Labels: ok-to-merge, cla-not-required, cherry-pick/release-0.28

#4367 [cherry-pick ] fix antrea version comp
  addons/controllers/antrea/antreaconfig_controller.go
  addons/controllers/antrea/antreaconfig_util.go
  addons/controllers/antreaconfig_controller_test.go
  addons/controllers/testdata/antrea-test-1.yaml
  addons/controllers/testdata/test-cluster-1.yaml
  addons/controllers/testdata/test-cluster-2.yaml
  addons/controllers/testdata/test-cluster-3.yaml
  addons/go.mod
Labels: ok-to-merge, cla-not-required, backports/release-0.28

#4375 Add comment notifications for cherry-pick workflow result
  .github/workflows/cherry-pick.yaml
  docs/release/cherry-pick.md
Labels: ok-to-merge, cla-not-required

#4346 truncate osimage label if overlength
  tkr/util/osimage/osimage.go
  tkr/webhook/cluster/tkr-resolver/cluster/cluster_test.go
Labels: ok-to-merge, cla-not-required, cherry-pick/release-0.28

#4361 Fix getting AWSCluster through Cluster name
  tkg/client/upgrade_cluster.go
  tkg/client/upgrade_cluster_test.go
Labels: ok-to-merge, cla-not-required

#4377 fix cluster upgrade error when node network list is empty
  tkg/managementcomponents/helper.go
  tkg/managementcomponents/helper_test.go
  tkg/managementcomponents/test/output_vsphere_with_avi_enabled_empty_node_network_list.yaml
Labels: ok-to-merge, cla-not-required, cherry-pick/release-0.28

#4387 [TKG-15207] Failed to refresh the Token while upgrading mgmt cluster in Azure
  tkg/clusterclient/clusterclient.go
Labels: ok-to-merge, cla-not-required

#4355 [0.28 cherrypick] change the deployment resource update strategy to fallback-on-replace in capabilities package
  packages/capabilities/bundle/config/upstream/tanzu-capabilities-controller-manager.yaml
Labels: ok-to-merge, cla-not-required, backports/release-0.28

#4391 [Cherry Pick] backport upgrade error when node network list is empty fix (#4377)
  tkg/managementcomponents/helper.go
  tkg/managementcomponents/helper_test.go
  tkg/managementcomponents/test/output_vsphere_with_avi_enabled_empty_node_network_list.yaml
Labels: ok-to-merge, cla-not-required

#4362 Handle equal sign in Extra Args
  providers/yttcc/lib/config_variable_association.star
  providers/yttcc/lib/helpers.star
  tkg/client/cluster.go
  tkg/client/cluster_test.go
  tkg/client/validate.go
  tkg/client/validate_test.go
  tkg/constants/config_variables.go
Labels: ok-to-merge, cla-not-required

#4376 [release-0.28] cherry-pick 4365 : raise timeout for tkr-vsphere-resolver webhook
  packages/tkr-vsphere-resolver/bundle/config/upstream/webhook.yaml
Labels: ok-to-merge, cla-not-required, cherry-pick/release-0.28, backports/release-0.28

#4384 [release-0.28] cherry-pick 4346 : truncate osimage label if overlength
  tkr/util/osimage/osimage.go
  tkr/webhook/cluster/tkr-resolver/cluster/cluster_test.go
Labels: ok-to-merge, cla-not-required, cherry-pick/release-0.28, backports/release-0.28

#4392 [TKG-15207][release-0.28] Failed to refresh the Token while upgrading mgmt cluster in Azure
  tkg/clusterclient/clusterclient.go
Labels: ok-to-merge, cla-not-required

#4389 [release-0.28] cherry-pick 4361: Fix getting AWSCluster through Cluster name
  tkg/client/upgrade_cluster.go
  tkg/client/upgrade_cluster_test.go
Labels: ok-to-merge, cla-not-required

#4388 Fetch vSphere credentials from vSphereClusterIdentity, instead of secret directly, in case of TMC based CSI deployment
  addons/controllers/csi/vspherecsiconfig_utils.go
Labels: ok-to-merge, cla-not-required, cherry-pick/release-0.28

#4394 Fix the kube-vip image parsing, and unit test
  tkg/client/kubevip_update_helper.go
  tkg/client/kubevip_update_helper_test.go
Labels: ok-to-merge, cla-not-required

#4401 [release-0.28] cherry-pick 4362 : Handle equal sign in Extra Args
  providers/yttcc/lib/config_variable_association.star
  providers/yttcc/lib/helpers.star
  tkg/client/cluster.go
  tkg/client/cluster_test.go
  tkg/client/validate.go
  tkg/client/validate_test.go
  tkg/constants/config_variables.go
Labels: ok-to-merge, cla-not-required

#4406 [cherry pick 0.28]kube vip image path processing cherrypick
  tkg/client/kubevip_update_helper.go
  tkg/client/kubevip_update_helper_test.go
Labels: ok-to-merge, cla-not-required

#4402 [release-0.28] cherry-pick 4388 : Fetch vSphere credentials from vSphereClusterIdentity, instead of secret directly, in case of TMC based CSI deployment
  addons/controllers/csi/vspherecsiconfig_utils.go
Labels: ok-to-merge, cla-not-required, cherry-pick/release-0.28, backports/release-0.28

#4383 Fix TKG_CUSTOM_IMAGE_REPOSITORY_SKIP_TLS_VERIFY user env setting
  tkg/managementcomponents/helper.go
  tkg/managementcomponents/helper_test.go
  tkg/managementcomponents/test/config.yaml
  tkg/managementcomponents/test/output_vsphere_with_custom_repo_ca_rw.yaml
  tkg/managementcomponents/types.go
Labels: ok-to-merge, cla-not-required, area/tkr, cherry-pick/release-0.28

#4404 Improve the error message for cherry-pick workflow
  .github/workflows/cherry-pick.yaml
Labels: ok-to-merge, cla-not-required

#4396 Populate all imageRepository fields in TKR_DATA values (#4298)
  tkr/webhook/cluster/tkr-resolver/cluster/cluster.go
  tkr/webhook/cluster/tkr-resolver/cluster/cluster_test.go
Labels: ok-to-merge, cla-not-required

#4407 [release-0.28] cherry-pick 4383 : Fix TKG_CUSTOM_IMAGE_REPOSITORY_SKIP_TLS_VERIFY user env setting
  tkg/managementcomponents/helper.go
  tkg/managementcomponents/helper_test.go
  tkg/managementcomponents/test/config.yaml
  tkg/managementcomponents/test/output_vsphere_with_custom_repo_ca_rw.yaml
  tkg/managementcomponents/types.go
Labels: ok-to-merge, cla-not-required, area/tkr, cherry-pick/release-0.28, backports/release-0.28

#4424 disable package plugin and TKG CAPD integration tests
  .github/workflows/package_integration_test.yaml
  .github/workflows/tkg_integration_tests.yaml
Labels: ok-to-merge, cla-not-required

#4422 Upgrade CAPZ version to v1.6.3
  packages/cluster-api-provider-azure/bundle/config/upstream/infrastructure-components.yaml
  packages/cluster-api-provider-azure/vendir.lock.yml
  packages/cluster-api-provider-azure/vendir.yml
  providers/config.yaml
  providers/infrastructure-azure/v1.6.3/cconly/base.yaml
  providers/infrastructure-azure/v1.6.3/cconly/overlay-kube-apiserver-admission.yaml
  providers/infrastructure-azure/v1.6.3/cconly/overlay.yaml
  providers/infrastructure-azure/v1.6.3/cluster-template-definition-dev.yaml
  providers/infrastructure-azure/v1.6.3/cluster-template-definition-devcc.yaml
  providers/infrastructure-azure/v1.6.3/cluster-template-definition-prod.yaml
  providers/infrastructure-azure/v1.6.3/cluster-template-definition-prodcc.yaml
  providers/infrastructure-azure/v1.6.3/clusterclass-tkg-azure-default.yaml
  providers/infrastructure-azure/v1.6.3/infrastructure-components.yaml
  providers/infrastructure-azure/v1.6.3/metadata.yaml
  providers/infrastructure-azure/v1.6.3/ytt/base-template.yaml
  providers/infrastructure-azure/v1.6.3/ytt/overlay.yaml
  providers/infrastructure-azure/v1.6.3/yttcc/base-template.yaml
  providers/infrastructure-azure/v1.6.3/yttcc/overlay.yaml
Labels: ok-to-merge, cla-not-required

#4425 Add logic to not to extract kube-vip manifest when kube-vip manifest is not presented in KCP, assume AVI
  tkg/client/kubevip_update_helper.go
  tkg/client/kubevip_update_helper_test.go
  tkg/client/upgrade_cluster.go
  tkg/client/upgrade_cluster_test.go
Labels: ok-to-merge, cla-not-required

#4426 Update v2.2 management cluster to support k8s v1.25
  tkg/tkgconfighelper/tkgconfighelper_test.go
  tkg/tkgconfighelper/validate.go
Labels: ok-to-merge, cla-not-required

#4427 [0.28 cherrypick]Add logic to not to extract kube-vip manifest when kube-vip manifest …
  tkg/client/kubevip_update_helper.go
  tkg/client/kubevip_update_helper_test.go
  tkg/client/upgrade_cluster.go
  tkg/client/upgrade_cluster_test.go
Labels: ok-to-merge, cla-not-required

#4428 workflow: Update condition for notification on PR
  .github/workflows/cherry-pick.yaml
Labels: ok-to-merge, cla-not-required

#4307 use build tooling for building capabilities component
  .github/workflows/experimental-build-using-buildtooling.yaml
  Dockerfile
  build-tooling.mk
  capabilities/client/go.mod
  capabilities/client/go.sum
  capabilities/client/pkg/discovery/fake.go
  capabilities/controller/go.mod
  capabilities/controller/go.sum
  cli/core/go.mod
  cmd/cli/plugin-admin/builder/go.mod
  cmd/cli/plugin-admin/test/go.mod
  cmd/cli/plugin/cluster/go.mod
  cmd/cli/plugin/isolated-cluster/go.mod
  cmd/cli/plugin/login/go.mod
  cmd/cli/plugin/managementcluster/go.mod
  cmd/cli/plugin/package/go.mod
  cmd/cli/plugin/secret/go.mod
  go.mod
  tkg/go.mod
Labels: ok-to-merge, cla-not-required

#3972 redo of BUILDKIT caching PR
  addons/Dockerfile
  addons/manifests/samples/simple-app/Dockerfile
  capabilities/controller/Dockerfile
  common.mk
  featuregates/controller/Dockerfile
  object-propagation/Dockerfile
  pinniped-components/post-deploy/Dockerfile
  pinniped-components/tanzu-auth-controller-manager/Dockerfile
  pkg/v1/tkr/Dockerfile
  tkg/vsphere-template-resolver/Dockerfile
  tkr/controller/tkr-source/Dockerfile
  tkr/controller/tkr-status/Dockerfile
  tkr/webhook/cluster/tkr-resolver/Dockerfile
  tkr/webhook/tkr-conversion/Dockerfile
Labels: ok-to-merge, cla-not-required

#4417 Fix security alerts related to addons, package and secret plugin
  addons/go.mod
  addons/go.sum
  addons/hack/tools/go.mod
  addons/hack/tools/go.sum
  cmd/cli/plugin/package/go.mod
  cmd/cli/plugin/package/go.sum
  cmd/cli/plugin/secret/go.mod
  cmd/cli/plugin/secret/go.sum
Labels: area/addons, ok-to-merge, cla-not-required, area/framework
