Repository vmware-tanzu/tanzu-framework, pull requests merged in 2023-06, with the labels that each got.

#4626 Fix local certificate manager startup issue in featuregates controller
  featuregates/controller/main.go
Labels: ok-to-merge, cla-not-required

#4635 Update code coverage on push to main
  .github/workflows/build.yaml
Labels: area/testing, ok-to-merge, cla-not-required, area/dx, github_actions

#4627 Adding webhook for readiness provider
  apis/core/v1alpha2/readinessprovider_webhook.go
  featuregates/controller/pkg/feature/feature_suite_test.go
  featuregates/controller/pkg/test/cert.go
  packages/readiness/README.md
  packages/readiness/bundle/config/upstream/helpers.star
  packages/readiness/bundle/config/upstream/rbac.yaml
  packages/readiness/bundle/config/upstream/service.yaml
  packages/readiness/bundle/config/upstream/tanzu-readiness-manager.yaml
  packages/readiness/bundle/config/upstream/webhook-secret.yaml
  packages/readiness/bundle/config/upstream/webhooks/core/webhook.yaml
  packages/readiness/bundle/config/values.yaml
  packages/readiness/vendir.lock.yml
  packages/readiness/vendir.yml
  readiness/controller/go.mod
  readiness/controller/go.sum
  readiness/controller/main.go
  readiness/controller/pkg/readinessprovider/suite_test.go
  readiness/controller/pkg/readinessprovider/testdata/webhook.yaml
  util/test/doc.go
  util/test/kube.go
Labels: ok-to-merge, cla-not-required

#4629 Copy over BTI changes, including caching Tanzu CLI and builder in build stages, and updating Tanzu CLI version
  .dockerignore
  Dockerfile
Labels: ok-to-merge, cla-not-required

#4636 Documentation to readiness framework
  docs/runtime-core/readiness-framework/deploy-local-changes.md
  docs/runtime-core/readiness-framework/guide-with-examples.md
Labels: ok-to-merge, cla-not-required

#4637 Add serviceAccount to ReadinessProvider spec
  apis/core/config/crd/bases/core.tanzu.vmware.com_readinessproviders.yaml
  apis/core/v1alpha2/readinessprovider_types.go
  apis/core/v1alpha2/readinessprovider_webhook.go
  apis/core/v1alpha2/zz_generated.deepcopy.go
  docs/runtime-core/readiness-framework.md
  docs/runtime-core/readiness-framework/guide-with-examples.md
  packages/readiness/bundle/config/upstream/crds/core.tanzu.vmware.com_readinessproviders.yaml
  packages/readiness/bundle/config/upstream/rbac.yaml
  readiness/controller/main.go
  readiness/controller/pkg/conditions/resourceexistence.go
  readiness/controller/pkg/conditions/resourceexistence_test.go
  readiness/controller/pkg/conditions/testdata/rbac.yaml
  readiness/controller/pkg/readinessprovider/readinessprovider_controller.go
  readiness/controller/pkg/readinessprovider/suite_test.go
  readiness/controller/pkg/readinessprovider/testdata/rbac.yaml
  util/kubeclient/doc.go
  util/kubeclient/kubeclient.go
Labels: area/api, kind/api-change, ok-to-merge, cla-not-required

#4638 Adding e2e tests for readiness framework
  Makefile
  docs/runtime-core/readiness-framework/deploy-local-changes.md
  e2e.mk
  readiness/e2e/e2e_test.go
  readiness/e2e/go.mod
  readiness/e2e/go.sum
  readiness/e2e/suite_test.go
Labels: ok-to-merge, cla-not-required

#4639 Extending readiess e2e tests with custom service account scenario
  readiness/e2e/doc.go
  readiness/e2e/e2e_test.go
  readiness/e2e/suite_test.go
Labels: ok-to-merge, cla-not-required
