Repository vmware-tanzu/tanzu-framework, pull requests merged in 2023-05, with the labels that each got.

#4610 Update BOM retrieval version to v0.28.2-dev
  tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: ok-to-merge, cla-not-required

#4612 Add welcome-contributors workflow
  .github/workflows/welcome-contributors.yaml
Labels: ok-to-merge, cla-not-required, area/dx, github_actions

#4613 Add printable columns for readiness resources
  Dockerfile
  apis/core/config/crd/bases/core.tanzu.vmware.com_readinesses.yaml
  apis/core/config/crd/bases/core.tanzu.vmware.com_readinessproviders.yaml
  apis/core/v1alpha2/readiness_types.go
  apis/core/v1alpha2/readinessprovider_types.go
  packages/readiness/bundle/config/upstream/crds/core/core.tanzu.vmware.com_readinesses.yaml
  packages/readiness/bundle/config/upstream/crds/core/core.tanzu.vmware.com_readinessproviders.yaml
Labels: ok-to-merge, cla-not-required

#4614 Enable verify action
  .github/workflows/verify.yaml
  Makefile
  hack/verify-dirty.sh
Labels: ok-to-merge, cla-not-required, github_actions

#4615 Update BOM retrieval version to v0.28.2
  tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: cla-not-required

#4617 Fix dependabot Docker security alert
  capabilities/client/go.mod
  capabilities/client/go.sum
Labels: ok-to-merge, cla-not-required

#4620 Run make test and upload coverage files to CodeCov
  .github/workflows/build.yaml
Labels: ok-to-merge, cla-not-required

#4604 Readiness Framework changes
  PROJECT
  apis/core/config/crd/bases/core.tanzu.vmware.com_readinesses.yaml
  apis/core/config/crd/bases/core.tanzu.vmware.com_readinessproviders.yaml
  apis/core/v1alpha2/readiness_types.go
  apis/core/v1alpha2/readinessprovider_types.go
  apis/core/v1alpha2/zz_generated.deepcopy.go
  build.mk
  docs/packages/dev-workflow.md
  docs/runtime-core/readiness-framework.md
  packages/package-values.yaml
  packages/readiness/Makefile
  packages/readiness/README.md
  packages/readiness/bundle/config/upstream/crds/core.tanzu.vmware.com_readinesses.yaml
  packages/readiness/bundle/config/upstream/crds/core.tanzu.vmware.com_readinessproviders.yaml
  packages/readiness/bundle/config/upstream/rbac.yaml
  packages/readiness/bundle/config/upstream/tanzu-readiness-manager.yaml
  packages/readiness/bundle/config/values.yaml
  packages/readiness/kbld-config.yaml
  packages/readiness/metadata.yaml
  packages/readiness/package.yaml
  packages/readiness/vendir.lock.yml
  packages/readiness/vendir.yml
  readiness/controller/go.mod
  readiness/controller/go.sum
  readiness/controller/main.go
  readiness/controller/pkg/conditions/doc.go
  readiness/controller/pkg/conditions/resourceexistence.go
  readiness/controller/pkg/conditions/resourceexistence_test.go
  readiness/controller/pkg/readiness/doc.go
  readiness/controller/pkg/readiness/readiness_controller.go
  readiness/controller/pkg/readiness/suite_test.go
  readiness/controller/pkg/readinessprovider/doc.go
  readiness/controller/pkg/readinessprovider/readinessprovider_controller.go
  readiness/controller/pkg/readinessprovider/suite_test.go
Labels: ok-to-merge, cla-not-required

#4624 Update BOM retrieval version to v0.28.3
  tkg/tkgconfigpaths/zz_bundled_default_bom_files_configdata.go
Labels: ok-to-merge, cla-not-required

#4625 Use apt-get to install Tanzu CLI plugin builder
  .dockerignore
  Dockerfile
Labels: ok-to-merge, cla-not-required
